:SWITCHBOARD~SWITCHBOARD






if (($SWITCHBOARD~MESSAGE = 0) or ($SWITCHBOARD~MESSAGE = ""))
  return
end
setvar $SWITCHBOARD~DISCORD_IGNORE "-- "

setvar $SWITCHBOARD~DISCORD_IGNORE_LENGTH 3

loadvar $BOT~BOTISDEAF
loadvar $BOT~MODE
loadvar $SWITCHBOARD~NODISCORD
loadvar $SWITCHBOARD~FEDSPACE_OUTPUT

if ($SWITCHBOARD~NODISCORD <> TRUE)
  getwordpos " "&$BOT~USER_COMMAND_LINE&" " $SWITCHBOARD~POS " nodiscord "
  if ($SWITCHBOARD~POS > 0)
    setvar $SWITCHBOARD~NODISCORD TRUE
  end
end

if ($SWITCHBOARD~FEDSPACE_OUTPUT <> TRUE)
  getwordpos " "&$BOT~USER_COMMAND_LINE&" " $SWITCHBOARD~POS " fed "
  if ($SWITCHBOARD~POS > 0)
    setvar $SWITCHBOARD~FEDSPACE_OUTPUT TRUE
  end
end

if ($SWITCHBOARD~FEDSPACE_OUTPUT)
  setvar $SWITCHBOARD~COMMUNICATION_STARTER "`"
  if ($SWITCHBOARD~NODISCORD)
    setvar $SWITCHBOARD~MSG_HEADER_SS_1 $SWITCHBOARD~COMMUNICATION_STARTER&$SWITCHBOARD~DISCORD_IGNORE&"Fedspace output - "
    setvar $SWITCHBOARD~MSG_HEADER_SS_2 $SWITCHBOARD~COMMUNICATION_STARTER&"*"&$SWITCHBOARD~DISCORD_IGNORE&"Fedspace output - * "
  else
    setvar $SWITCHBOARD~MSG_HEADER_SS_1 $SWITCHBOARD~COMMUNICATION_STARTER&"Fedspace output - "
    setvar $SWITCHBOARD~MSG_HEADER_SS_2 $SWITCHBOARD~COMMUNICATION_STARTER&"*Fedspace output - * "
  end
else
  setvar $SWITCHBOARD~COMMUNICATION_STARTER "'"
  if ($SWITCHBOARD~NODISCORD)
    setvar $SWITCHBOARD~MSG_HEADER_SS_1 $SWITCHBOARD~COMMUNICATION_STARTER&$SWITCHBOARD~DISCORD_IGNORE&"["&$BOT~MODE&"] {"&$SWITCHBOARD~BOT_NAME&"} - "
    setvar $SWITCHBOARD~MSG_HEADER_SS_2 $SWITCHBOARD~COMMUNICATION_STARTER&"*"&$SWITCHBOARD~DISCORD_IGNORE&"["&$BOT~MODE&"] {"&$SWITCHBOARD~BOT_NAME&"} - * "
  else
    setvar $SWITCHBOARD~MSG_HEADER_SS_1 $SWITCHBOARD~COMMUNICATION_STARTER&"["&$BOT~MODE&"] {"&$SWITCHBOARD~BOT_NAME&"} - "
    setvar $SWITCHBOARD~MSG_HEADER_SS_2 $SWITCHBOARD~COMMUNICATION_STARTER&"*["&$BOT~MODE&"] {"&$SWITCHBOARD~BOT_NAME&"} - * "
  end
end
setvar $SWITCHBOARD~MSG_HEADER_ECHO ANSI_9&"{"&ANSI_14&$SWITCHBOARD~BOT_NAME&ANSI_9&"} "&ANSI_15
if ($SWITCHBOARD~MESSAGE <> "")

  if ($SWITCHBOARD~SELF_COMMAND > 0)
    setvar $SWITCHBOARD~LENGTH 0
  else
    getlength $SWITCHBOARD~BOT_NAME $SWITCHBOARD~LENGTH
  end
  setvar $SWITCHBOARD~I 1
  setvar $SWITCHBOARD~SPACING ""
  getwordpos " "&$BOT~USER_COMMAND_LINE&" " $SWITCHBOARD~ISBROADCAST " ss "
  getwordpos " "&$BOT~USER_COMMAND_LINE&" " $SWITCHBOARD~ISSILENT " silent "

  if ($SWITCHBOARD~SELF_COMMAND <> 0)

    if (($BOT~COMMAND <> "help") and ($BOT~ONLY_HELP <> TRUE))
      if ($SWITCHBOARD~SELF_COMMAND > 1) or (($SWITCHBOARD~SELF_COMMAND = 1) and (($BOT~SILENT_RUNNING <> TRUE) and ($SWITCHBOARD~ISSILENT <= 0)))
        gosub :STRIPANSI
        if ($SWITCHBOARD~HELPLIST <> TRUE)
        end
      end
    end

    while ($SWITCHBOARD~I <= $SWITCHBOARD~LENGTH)
      setvar $SWITCHBOARD~SPACING $SWITCHBOARD~SPACING&" "
      add $SWITCHBOARD~I 1
    end
    setvar $SWITCHBOARD~NEW_MESSAGE ""
    setvar $SWITCHBOARD~MESSAGE_LINE ""
    gosub :FORMAT_RAW_MESSAGE
  else
    gosub :FORMAT_RAW_MESSAGE
  end

  getwordpos " "&$SWITCHBOARD~NEW_MESSAGE&" " $SWITCHBOARD~POS "*"
  getlength $SWITCHBOARD~NEW_MESSAGE $SWITCHBOARD~LENGTH
  if ($SWITCHBOARD~NODISCORD)
    setvar $SWITCHBOARD~NEW_MESSAGE $SWITCHBOARD~DISCORD_IGNORE&$SWITCHBOARD~NEW_MESSAGE
    add $SWITCHBOARD~LENGTH $SWITCHBOARD~DISCORD_IGNORE_LENGTH
  end

  if ($SWITCHBOARD~SELF_COMMAND > 1)
    setvar $SWITCHBOARD~SELF_COMMAND FALSE
  end
  if ($SWITCHBOARD~POS < $SWITCHBOARD~LENGTH)
    setvar $SWITCHBOARD~MULTIPLE_LINES TRUE
  else
    setvar $SWITCHBOARD~MULTIPLE_LINES FALSE
  end


  if ($SWITCHBOARD~ISSILENT > 0) or (($BOT~SILENT_RUNNING = TRUE) and ($SWITCHBOARD~SELF_COMMAND = TRUE)) or (((($SWITCHBOARD~SELF_COMMAND = TRUE) and (($BOT~COMMAND = "help") or ($BOT~ONLY_HELP = TRUE)))) and ($SWITCHBOARD~ISBROADCAST <= 0))
    if ($BOT~BOTISDEAF <> TRUE)
      echo "*"&$SWITCHBOARD~MSG_HEADER_ECHO&$SWITCHBOARD~NEW_MESSAGE
      send #145
    else
      setvar $SWITCHBOARD~WINDOW_CONTENT $SWITCHBOARD~NEW_MESSAGE
      replacetext $SWITCHBOARD~WINDOW_CONTENT "*" "[][]"
      savevar $SWITCHBOARD~WINDOW_CONTENT
    end
  elseif ($SWITCHBOARD~MULTIPLE_LINES = FALSE)
    setvar $SWITCHBOARD~MESSAGE $SWITCHBOARD~NEW_MESSAGE
    gosub :STRIPANSI
    send $SWITCHBOARD~MSG_HEADER_SS_1&$SWITCHBOARD~MESSAGE
  else
    setvar $SWITCHBOARD~MESSAGE $SWITCHBOARD~NEW_MESSAGE
    gosub :STRIPANSI
    send $SWITCHBOARD~MSG_HEADER_SS_2&$SWITCHBOARD~MESSAGE&"*"
  end
  setvar $SWITCHBOARD~MESSAGE ""
end
setvar $SWITCHBOARD~HELPLIST FALSE
return
:SWITCHBOARD~FORMAT_RAW_MESSAGE




getwordpos " "&$SWITCHBOARD~MESSAGE&" " $SWITCHBOARD~POS "*"

getlength $SWITCHBOARD~MESSAGE $SWITCHBOARD~MESSAGE_LENGTH

if ($SWITCHBOARD~POS < $SWITCHBOARD~MESSAGE_LENGTH)
  setvar $SWITCHBOARD~MULTIPLE_LINES TRUE
else
  setvar $SWITCHBOARD~MULTIPLE_LINES FALSE
end
if (($BOT~COMMAND <> "help") and ($BOT~ONLY_HELP <> TRUE))
  if ($SWITCHBOARD~SELF_COMMAND = 0) or ($SWITCHBOARD~SELF_COMMAND > 1) or (($SWITCHBOARD~SELF_COMMAND = 1) and (($BOT~SILENT_RUNNING <> TRUE) and ($SWITCHBOARD~ISSILENT <= 0)))

    setvar $SWITCHBOARD~NEXT_LENGTH 60
    setvar $SWITCHBOARD~I 1
    setvar $SWITCHBOARD~LENGTH 1
    while ($SWITCHBOARD~I <= $SWITCHBOARD~MESSAGE_LENGTH)
      cuttext $SWITCHBOARD~MESSAGE $SWITCHBOARD~CHARACTER $SWITCHBOARD~I 1
      if (($SWITCHBOARD~CHARACTER = " ") and ($SWITCHBOARD~LENGTH >= $SWITCHBOARD~NEXT_LENGTH)) or (($SWITCHBOARD~CHARACTER = "*") and ($SWITCHBOARD~LENGTH > 1))
        if ($SWITCHBOARD~I < $SWITCHBOARD~MESSAGE_LENGTH)
          cuttext $SWITCHBOARD~MESSAGE $SWITCHBOARD~FIRST_HALF 1 ($SWITCHBOARD~I - 1)
          cuttext $SWITCHBOARD~MESSAGE $SWITCHBOARD~SECOND_HALF ($SWITCHBOARD~I + 1) 999999999

          if ($SWITCHBOARD~NODISCORD)
            setvar $SWITCHBOARD~FIRST_HALF $SWITCHBOARD~FIRST_HALF&"*"&$SWITCHBOARD~DISCORD_IGNORE
            add $SWITCHBOARD~I $SWITCHBOARD~DISCORD_IGNORE_LENGTH
            add $SWITCHBOARD~MESSAGE_LENGTH $SWITCHBOARD~DISCORD_IGNORE_LENGTH
          else
            setvar $SWITCHBOARD~FIRST_HALF $SWITCHBOARD~FIRST_HALF&"* "
            add $SWITCHBOARD~I 1
            add $SWITCHBOARD~MESSAGE_LENGTH 1
          end
          setvar $SWITCHBOARD~MESSAGE $SWITCHBOARD~FIRST_HALF&$SWITCHBOARD~SECOND_HALF
          setvar $SWITCHBOARD~LENGTH 0
        end
      end
      add $SWITCHBOARD~LENGTH 1
      add $SWITCHBOARD~I 1
    end
  end
end
setvar $SWITCHBOARD~NEW_MESSAGE $SWITCHBOARD~MESSAGE
return
:SWITCHBOARD~STRIPANSI

striptext $SWITCHBOARD~MESSAGE ANSI_1
striptext $SWITCHBOARD~MESSAGE ANSI_2
striptext $SWITCHBOARD~MESSAGE ANSI_3
striptext $SWITCHBOARD~MESSAGE ANSI_4
striptext $SWITCHBOARD~MESSAGE ANSI_5
striptext $SWITCHBOARD~MESSAGE ANSI_6
striptext $SWITCHBOARD~MESSAGE ANSI_7
striptext $SWITCHBOARD~MESSAGE ANSI_8
striptext $SWITCHBOARD~MESSAGE ANSI_9
striptext $SWITCHBOARD~MESSAGE ANSI_10
striptext $SWITCHBOARD~MESSAGE ANSI_11
striptext $SWITCHBOARD~MESSAGE ANSI_12
striptext $SWITCHBOARD~MESSAGE ANSI_13
striptext $SWITCHBOARD~MESSAGE ANSI_14
striptext $SWITCHBOARD~MESSAGE ANSI_15
return
