:PLAYERINFO~INFOQUICK























































send "/"
setvar $PLAYERINFO~LINE ""
settextlinetrigger LINE :LINE
pause
:PLAYERINFO~LINE

getwordpos CURRENTLINE $PLAYERINFO~POS #179
getword CURRENTLINE $PLAYERINFO~TEST 1

if (($PLAYERINFO~POS = 0) and ($PLAYERINFO~TEST <> "Ship"))
  if ($PLAYERINFO~LINE <> "")

    return
  end
  settextlinetrigger LINE :LINE
  pause
end

setvar $PLAYERINFO~LINE CURRENTLINE
striptext $PLAYERINFO~LINE ","
replacetext $PLAYERINFO~LINE #179 " "

setvar $PLAYERINFO~PARAM 1
:PLAYERINFO~NEXT
getword $PLAYERINFO~LINE $PLAYERINFO~WORD $PLAYERINFO~PARAM
getword $PLAYERINFO~LINE $PLAYERINFO~VALUE ($PLAYERINFO~PARAM + 1)

if ($PLAYERINFO~WORD = 0)
  settextlinetrigger LINE :LINE
  pause
end

if ($PLAYERINFO~WORD = "Sect")
  setvar $PLAYERINFO~SECTOR $PLAYERINFO~VALUE
elseif ($PLAYERINFO~WORD = "Turns")
  setvar $PLAYERINFO~TURNS $PLAYERINFO~VALUE
elseif ($PLAYERINFO~WORD = "Creds")
  setvar $PLAYERINFO~CREDITS $PLAYERINFO~VALUE
elseif ($PLAYERINFO~WORD = "Figs")
  setvar $PLAYERINFO~FIGHTERS $PLAYERINFO~VALUE
elseif ($PLAYERINFO~WORD = "Shlds")
  setvar $PLAYERINFO~SHIELDS $PLAYERINFO~VALUE
elseif ($PLAYERINFO~WORD = "Hlds")
  setvar $PLAYERINFO~HOLDS $PLAYERINFO~VALUE
elseif ($PLAYERINFO~WORD = "Ore")
  setvar $PLAYERINFO~ORE $PLAYERINFO~VALUE
elseif ($PLAYERINFO~WORD = "Org")
  setvar $PLAYERINFO~ORG $PLAYERINFO~VALUE
elseif ($PLAYERINFO~WORD = "Equ")
  setvar $PLAYERINFO~EQUIP $PLAYERINFO~VALUE
elseif ($PLAYERINFO~WORD = "Col")
  setvar $PLAYERINFO~COLONISTS $PLAYERINFO~VALUE
elseif ($PLAYERINFO~WORD = "Phot")
  setvar $PLAYERINFO~PHOTONS $PLAYERINFO~VALUE
elseif ($PLAYERINFO~WORD = "Armd")
  setvar $PLAYERINFO~MINES $PLAYERINFO~VALUE
elseif ($PLAYERINFO~WORD = "Lmpt")
  setvar $PLAYERINFO~LIMPETS $PLAYERINFO~VALUE
elseif ($PLAYERINFO~WORD = "GTorp")
  setvar $PLAYERINFO~GENTORPS $PLAYERINFO~VALUE
elseif ($PLAYERINFO~WORD = "TWarp")
  if ($PLAYERINFO~VALUE = "No")
    setvar $PLAYERINFO~TWARP 0
  else
    setvar $PLAYERINFO~TWARP $PLAYERINFO~VALUE
  end
elseif ($PLAYERINFO~WORD = "Clks")
  setvar $PLAYERINFO~CLOAKS $PLAYERINFO~VALUE
elseif ($PLAYERINFO~WORD = "Beacns")
  setvar $PLAYERINFO~BEACONS $PLAYERINFO~VALUE
elseif ($PLAYERINFO~WORD = "AtmDt")
  setvar $PLAYERINFO~DETS $PLAYERINFO~VALUE
elseif ($PLAYERINFO~WORD = "Crbo")
  setvar $PLAYERINFO~CORBO $PLAYERINFO~VALUE
elseif ($PLAYERINFO~WORD = "EPrb")
  setvar $PLAYERINFO~PROBES $PLAYERINFO~VALUE
elseif ($PLAYERINFO~WORD = "MDis")
  setvar $PLAYERINFO~DISRUPTORS $PLAYERINFO~VALUE
elseif ($PLAYERINFO~WORD = "PsPrb")
  if ($PLAYERINFO~VALUE = "Yes")
    setvar $PLAYERINFO~PSIPROBE 1
  else
    setvar $PLAYERINFO~PSIPROBE 0
  end
elseif ($PLAYERINFO~WORD = "PlScn")
  if ($PLAYERINFO~VALUE = "Yes")
    setvar $PLAYERINFO~PLANETSCANNER 1
  else
    setvar $PLAYERINFO~PLANETSCANNER 0
  end
elseif ($PLAYERINFO~WORD = "LRS")
  if ($PLAYERINFO~VALUE = "None")
    setvar $PLAYERINFO~SCANNER 0
  elseif ($PLAYERINFO~VALUE = "Holo")
    setvar $PLAYERINFO~SCANNER 2
  else
    setvar $PLAYERINFO~SCANNER 1
  end
elseif ($PLAYERINFO~WORD = "Aln")
  setvar $PLAYERINFO~ALIGN $PLAYERINFO~VALUE
elseif ($PLAYERINFO~WORD = "Exp")
  setvar $PLAYERINFO~EXPERIENCE $PLAYERINFO~VALUE
elseif ($PLAYERINFO~WORD = "Corp")
  setvar $PLAYERINFO~CORP $PLAYERINFO~VALUE
elseif ($PLAYERINFO~WORD = "Ship")
  setvar $PLAYERINFO~SHIP $PLAYERINFO~VALUE

end
add $PLAYERINFO~PARAM 2
goto :NEXT
