:PLANET~GETPLANETINFO



setvar $PLANET~PLANET 0
setvar $PLANET~PLANET_FUEL 0
setvar $PLANET~PLANET_FUEL_MAX 0
setvar $PLANET~PLANET_ORGANICS 0
setvar $PLANET~PLANET_ORGANICS_MAX 0
setvar $PLANET~PLANET_EQUIPMENT 0
setvar $PLANET~PLANET_EQUIPMENT_MAX 0
setvar $PLANET~PLANET_FIGHTERS 0
setvar $PLANET~PLANET_TRANSPORT 0
setvar $PLANET~PLANET_FIGHTERS_MAX 0
setvar $PLANET~CITADEL 0
setvar $PLANET~CITADEL_CREDITS 0
setvar $PLANET~ATMOSPHERE_CANNON 0
setvar $PLANET~SECTOR_CANNON 0
setvar $PLANET~PLANET_CLASS_NAME "undefined"
setvar $PLANET~PLANET_NAME "undefined"
setvar $PLANET~UNDER_CONSTRUCTION FALSE
setvar $PLANET~MAXED_LEVEL FALSE



send "*"
killtrigger PLANETINFO2
settextlinetrigger PLANETINFO2 :PLANETINFO2 "Planet #"
pause
:PLANET~PLANETINFO2

setvar $PLANET~CITADEL 0
setvar $PLANET~SECTOR_CANNON 0
setvar $PLANET~ATMOSPHERE_CANNON 0
setvar $PLANET~CITADEL_CREDITS 0
getword CURRENTLINE $PLANET~PLANET 2
striptext $PLANET~PLANET "#"
getword CURRENTLINE $PLAYER~CURRENT_SECTOR 5
striptext $PLAYER~CURRENT_SECTOR ":"
getwordpos CURRENTLINE $PLANET~POS ": "
cuttext CURRENTLINE $PLANET~PLANET_NAME ($PLANET~POS + 2) 999
savevar $PLANET~PLANET
savevar $PLAYER~CURRENT_SECTOR
setsectorparameter $PLANET~PLANET "PSECTOR" $PLAYER~CURRENT_SECTOR

settextlinetrigger CLASS :GETCLASS "Class "
pause
:PLANET~GETCLASS
setvar $PLANET~PLANET_CLASS_NAME CURRENTLINE
waitfor "2 Build 1   Product    Amount     Amount     Maximum"

gosub :KILLPLANETTRIGGERS
:PLANET~GETPLANETSTUFF

settextlinetrigger FUELSTART :FUELSTART "Fuel Ore"
settextlinetrigger ORGSTART :ORGSTART "Organics"
settextlinetrigger EQUIPSTART :EQUIPSTART "Equipment"
settextlinetrigger FIGSTART :FIGSTART "Fighters        N/A"
settextlinetrigger TPORT :PLANETTPORT "-=-=-=-=-=- TransPort power ="
settextlinetrigger SHIELDS :PLANETSHIELDS "Planetary Defense Shielding Power Level ="
settextlinetrigger CITADELSTART :CITADELSTART "Planet has a level"
settextlinetrigger CANNON :CANNONSTART ", AtmosLvl="

settexttrigger MAXEDIG :MAXEDIG "Planetary Interdictor Generator ="
settexttrigger UNDERCONST :UNDERCONST "under construction,"
settexttrigger PLANETINFODONE :PLANETINFODONE "Planet command (?=help)"
pause
:PLANET~UNDERCONST

setvar $PLANET~UNDER_CONSTRUCTION TRUE
pause
:PLANET~MAXEDIG

setvar $PLANET~MAXED_LEVEL TRUE
pause
:PLANET~PLANETTPORT

gettext CURRENTLINE $PLANET~PLANET_TPAD "power =" "hops -"
striptext $PLANET~PLANET_TPAD ","
striptext $PLANET~PLANET_TPAD " "
isnumber $PLANET~TST $PLANET~PLANET_TPAD
if ($PLANET~TST = 0)
  setvar $PLANET~PLANET_TPAD 0
end
setvar $PLANET~PLANET_TRANSPORT $PLANET~PLANET_TPAD
pause
:PLANET~PLANETSHIELDS

getword CURRENTLINE $PLANET~PLANET_SHIELDS 8
striptext $PLANET~PLANET_SHIELDS ","
isnumber $PLANET~TST $PLANET~PLANET_SHIELDS
if ($PLANET~TST = 0)
  setvar $PLANET~PLANET_SHIELDS 0
end
pause
:PLANET~FUELSTART

getword CURRENTLINE $PLANET~PLANET_FUEL_COLONISTS 3
getword CURRENTLINE $PLANET~PLANET_FUEL 6
getword CURRENTLINE $PLANET~PLANET_FUEL_MAX 8
getword CURRENTLINE $PLANET~PLANETFUEL 6
getword CURRENTLINE $PLANET~PLANETFUELMAX 8
striptext $PLANET~PLANETFUEL ","
striptext $PLANET~PLANETFUELMAX ","
striptext $PLANET~PLANET_FUEL ","
striptext $PLANET~PLANET_FUEL_MAX ","
striptext $PLANET~PLANET_FUEL_COLONISTS ","
pause
:PLANET~ORGSTART

getword CURRENTLINE $PLANET~PLANET_ORGANICS_COLONISTS 2
getword CURRENTLINE $PLANET~PLANET_ORGANICS 5
getword CURRENTLINE $PLANET~PLANET_ORGANICS_MAX 7
getword CURRENTLINE $PLANET~PLANETORG 5
getword CURRENTLINE $PLANET~PLANETORGMAX 7
striptext $PLANET~PLANETORG ","
striptext $PLANET~PLANETORGMAX ","
striptext $PLANET~PLANET_ORGANICS ","
striptext $PLANET~PLANET_ORGANICS_MAX ","
striptext $PLANET~PLANET_ORGANICS_COLONISTS ","
pause
:PLANET~EQUIPSTART

getword CURRENTLINE $PLANET~PLANET_EQUIPMENT_COLONISTS 2
getword CURRENTLINE $PLANET~PLANET_EQUIPMENT 5
getword CURRENTLINE $PLANET~PLANET_EQUIPMENT_MAX 7
getword CURRENTLINE $PLANET~PLANETEQUIP 5
getword CURRENTLINE $PLANET~PLANETEQUIPMAX 7
striptext $PLANET~PLANETEQUIP ","
striptext $PLANET~PLANETEQUIPMAX ","
striptext $PLANET~PLANET_EQUIPMENT ","
striptext $PLANET~PLANET_EQUIPMENT_MAX ","
striptext $PLANET~PLANET_EQUIPMENT_COLONISTS ","
pause
:PLANET~FIGSTART

getword CURRENTLINE $PLANET~PLANET_FIGHTERS 5
getword CURRENTLINE $PLANET~PLANET_FIGHTERS_MAX 7
striptext $PLANET~PLANET_FIGHTERS ","
striptext $PLANET~PLANET_FIGHTERS_MAX ","
pause
:PLANET~CITADELSTART

getword CURRENTLINE $PLANET~CITADEL 5
getword CURRENTLINE $PLANET~CITADEL_CREDITS 9
striptext $PLANET~CITADEL_CREDITS ","
pause
:PLANET~CANNONSTART

getword CURRENTLINE $PLANET~MILITARYREACTION 2
getword CURRENTLINE $PLANET~ATMOSPHERE_CANNON 5
getword CURRENTLINE $PLANET~SECTOR_CANNON 6
striptext $PLANET~MILITARYREACTION "reaction="
striptext $PLANET~MILITARYREACTION "%"
striptext $PLANET~SECTOR_CANNON "SectLvl="
striptext $PLANET~SECTOR_CANNON "%"
striptext $PLANET~ATMOSPHERE_CANNON "AtmosLvl="
striptext $PLANET~ATMOSPHERE_CANNON "%"
striptext $PLANET~ATMOSPHERE_CANNON ","
pause
:PLANET~PLANETINFODONE
gosub :KILLPLANETTRIGGERS

setvar $PLANET~CURRENTBOTPLANET $PLANET~PLANET
savevar $PLANET~CURRENTBOTPLANET
savevar $PLANET~PLANET_FIGHTERS
savevar $PLAYER~CURRENT_SECTOR
savevar $PLANET~PLANET
savevar $PLANET~PLANET_FUEL
savevar $PLANET~PLANET_FUEL_MAX
savevar $PLANET~PLANET_ORGANICS
savevar $PLANET~PLANET_ORGANICS_MAX
savevar $PLANET~PLANET_EQUIPMENT
savevar $PLANET~PLANET_EQUIPMENT_MAX
savevar $PLANET~PLANET_FIGHTERS
savevar $PLANET~PLANET_TRANSPORT
savevar $PLANET~PLANET_FIGHTERS_MAX
savevar $PLANET~CITADEL
savevar $PLANET~CITADEL_CREDITS
savevar $PLANET~ATMOSPHERE_CANNON
savevar $PLANET~SECTOR_CANNON
savevar $PLANET~PLANET_CLASS_NAME
savevar $PLANET~PLANET_NAME
savevar $PLANET~UNDER_CONSTRUCTION
savevar $PLANET~MAXED_LEVEL


return
:PLANET~KILLPLANETTRIGGERS



killtrigger FUELSTART
killtrigger ORGSTART
killtrigger EQUIPSTART
killtrigger FIGSTART
killtrigger TPORT
killtrigger SHIELDS
killtrigger CITADELSTART
killtrigger CANNON
killtrigger CITEXISTS
killtrigger MAXEDIG
killtrigger UNDERCONST
killtrigger PLANETINFODONE
return
