:PLAYER~CURRENTPROMPT
settexttrigger PROMPT :ALLPROMPTSCATCH #145&#8
setdelaytrigger PROMPT_DELAY :CURRENT_PROMPT_DELAY 5000
send #145
pause
:PLAYER~CURRENT_PROMPT_DELAY
settextouttrigger ATKEYS :CURRENT_PROMPT_AT_KEYS
setdelaytrigger PROMPT_DELAY :VERIFYDELAY 30000
pause
:PLAYER~CURRENT_PROMPT_AT_KEYS
getouttext $PLAYER~OUT
send $PLAYER~OUT
killtrigger PROMPT_DELAY
return
:PLAYER~ALLPROMPTSCATCH
setvar $PLAYER~ANSILINE CURRENTANSILINE
setvar $PLAYER~SELF_DESTRUCT_PROMPT FALSE
getwordpos $PLAYER~ANSILINE $PLAYER~POS "ARE YOU SURE CAPTAIN? (Y/N) [N]"
if ($PLAYER~POS > 0)
  setvar $PLAYER~SELF_DESTRUCT_PROMPT TRUE
end
killtrigger PROMPT_DELAY
getword CURRENTLINE $PLAYER~CURRENT_PROMPT 1
if ($PLAYER~CURRENT_PROMPT = 0)
  getword CURRENTANSILINE $PLAYER~CURRENT_PROMPT 1
end
striptext $PLAYER~CURRENT_PROMPT #145
striptext $PLAYER~CURRENT_PROMPT #8
setvar $PLAYER~STARTINGLOCATION $PLAYER~CURRENT_PROMPT
return
:PLAYER~VERIFYDELAY


killalltriggers
disconnect
