:PLAYER~MOVEINTOSECTOR
setvar $PLAYER~RESULT ""
setvar $PLAYER~DROPFIGS TRUE
setvar $PLAYER~RESULT $PLAYER~RESULT&"m "&$PLAYER~MOVEINTOSECTOR&"*"
if (($PLAYER~MOVEINTOSECTOR > 10) and ($PLAYER~MOVEINTOSECTOR <> $MAP~STARDOCK))
  if ($PLAYER~FIGHTERS > $SHIP~SHIP_MAX_ATTACK)
    setvar $PLAYER~RESULT $PLAYER~RESULT&"za"&$SHIP~SHIP_MAX_ATTACK&"* * "
  else
    setvar $PLAYER~RESULT $PLAYER~RESULT&"za"&$PLAYER~FIGHTERS&"* * "
  end
end
if ($PLAYER~SURROUNDFIGS <= 0)
  setvar $PLAYER~SURROUNDFIGS 1
end
if (($PLAYER~MOVEINTOSECTOR > 10) and ($PLAYER~MOVEINTOSECTOR <> $MAP~STARDOCK))
  if ($PLAYER~SURROUNDFIGS > 0)
    setvar $PLAYER~RESULT $PLAYER~RESULT&"f  z  "&$PLAYER~SURROUNDFIGS&"* z  c  d  *  "
  end
  if ($PLAYER~SURROUNDLIMP > 0)
    setvar $PLAYER~RESULT $PLAYER~RESULT&"  H  2  Z  "&$PLAYER~SURROUNDLIMP&"*  Z C  *  "
  end
  if ($PLAYER~SURROUNDMINE > 0)
    setvar $PLAYER~RESULT $PLAYER~RESULT&"  H  1  Z  "&$PLAYER~SURROUNDMINE&"*  Z C  *  "
  end
end
send $PLAYER~RESULT
return
