:TARGETING~FASTCITADELATTACK







setvar $TARGETING~REFURBSTRING "l "&$TARGETING~PLANET&"* m * * * "
setvar $TARGETING~ATTACKSTRING ""
setvar $TARGETING~TARGETSTRING "a z "
setvar $TARGETING~TARGETSHOTGUNSTRING "a z z y z"&$SHIP~SHIP_MAX_ATTACK&"* a z z * y z"&$SHIP~SHIP_MAX_ATTACK&"* a z z * * y z"&$SHIP~SHIP_MAX_ATTACK&"* "
setvar $TARGETING~ISFOUND FALSE
getwordpos $TARGETING~SECTORDATA $TARGETING~BEACONPOS "[0m[35mBeacon  [1;33m:"
if ($PLAYER~FIGHTERS > 0)
  if ((($PLAYER~CURRENT_SECTOR > 10) and ($PLAYER~CURRENT_SECTOR <> STARDOCK)) and ($TARGETING~BEACONPOS > 0))
    setvar $TARGETING~TARGETSTRING $TARGETING~TARGETSTRING&"* "
  end
else
  echo ANSI_12 "*You have no fighters.*" ANSI_7
  return
end
if (($TARGETING~EMPTYSHIPCOUNT + ($TARGETING~FAKETRADERCOUNT + $TARGETING~REALTRADERCOUNT)) > 0)
  setvar $TARGETING~I 0
  while ($TARGETING~I < ($TARGETING~EMPTYSHIPCOUNT + $TARGETING~FAKETRADERCOUNT))
    setvar $TARGETING~TARGETSTRING $TARGETING~TARGETSTRING&"* "
    add $TARGETING~I 1
  end
  setvar $TARGETING~C 1
  if (($TARGETING~C <= $TARGETING~REALTRADERCOUNT) and ($TARGETING~ISFOUND = FALSE))
    if ((($PLAYER~CURRENT_SECTOR <= 10) or ($PLAYER~CURRENT_SECTOR = STARDOCK)) and ($TARGETING~TRADERS[$TARGETING~C][2] = TRUE))
      setvar $TARGETING~TARGETSTRING $TARGETING~TARGETSTRING&"* "
    elseif ($TARGETING~TRADERS[$TARGETING~C][1] = $PLAYER~CORP)
      setvar $TARGETING~TARGETSTRING $TARGETING~TARGETSTRING&"* "
    elseif (($TARGETING~TARGETINGCORP = TRUE) and ($TARGETING~TRADERS[$TARGETING~C][1] <> $TARGETING~TARGET))
      setvar $TARGETING~TARGETSTRING $TARGETING~TARGETSTRING&"* "
    elseif (($TARGETING~TARGETINGPERSON = TRUE) and ($TARGETING~TRADERS[$TARGETING~C] <> $TARGETING~TARGET))
      setvar $TARGETING~TARGETSTRING $TARGETING~TARGETSTRING&"* "
    else
      setvar $TARGETING~ISFOUND TRUE
      setvar $TARGETING~TARGETSTRING $TARGETING~TARGETSTRING&"z y z"

    end
    add $TARGETING~C 1

  end
else
  echo ANSI_12 "*You have no targets.*" ANSI_7
  return
end
if ($TARGETING~ISFOUND = TRUE)
  setvar $TARGETING~ATTACKSTRING ""
  setvar $TARGETING~COUNT 8
  while ($TARGETING~COUNT > 0)
    if ($TARGETING~SHOTGUN)
      setvar $TARGETING~ATTACKSTRING $TARGETING~ATTACKSTRING&"q "&$TARGETING~TARGETSHOTGUN&$TARGETING~REFURBSTRING
    else
      if ($TARGETING~DOUBLETAP)
        setvar $TARGETING~ATTACKSTRING $TARGETING~ATTACKSTRING&"q "&$TARGETING~TARGETSTRING&$SHIP~SHIP_MAX_ATTACK&"* "&$TARGETING~TARGETSTRING&$SHIP~SHIP_MAX_ATTACK&"* "&$TARGETING~REFURBSTRING
      else
        setvar $TARGETING~ATTACKSTRING $TARGETING~ATTACKSTRING&"q "&$TARGETING~TARGETSTRING&$SHIP~SHIP_MAX_ATTACK&"* "&$TARGETING~REFURBSTRING
      end
    end
    subtract $TARGETING~COUNT 1
  end
else
  echo ANSI_12 "*You have no valid targets.*" ANSI_7
  return
end
send "q "&$TARGETING~ATTACKSTRING&" c "
return
:TARGETING~INITIALIZETARGETING


setvar $TARGETING~REALTRADERCOUNT 0
setvar $TARGETING~FAKETRADERCOUNT 0
setvar $TARGETING~CORPIECOUNT 0
setvar $TARGETING~EMPTYSHIPCOUNT 0
setvar $TARGETING~CONTAINSBEACON FALSE
setarray $TARGETING~TRADERS 200
setarray $TARGETING~TRADERS 50
setarray $TARGETING~FAKETRADERS 50
setarray $TARGETING~EMPTYSHIPS 100
setvar $TARGETING~RANKSLENGTH 46


setarray $TARGETING~RANKS $TARGETING~RANKSLENGTH
setvar $TARGETING~RANKS[1] "36mCivilian"
setvar $TARGETING~RANKS[2] "36mPrivate 1st Class"
setvar $TARGETING~RANKS[3] "36mPrivate"
setvar $TARGETING~RANKS[4] "36mLance Corporal"
setvar $TARGETING~RANKS[5] "36mCorporal"
setvar $TARGETING~RANKS[6] "36mStaff Sergeant"
setvar $TARGETING~RANKS[7] "36mGunnery Sergeant"
setvar $TARGETING~RANKS[8] "36m1st Sergeant"
setvar $TARGETING~RANKS[9] "36mSergeant Major"
setvar $TARGETING~RANKS[10] "36mSergeant"
setvar $TARGETING~RANKS[11] "31mAnnoyance"
setvar $TARGETING~RANKS[12] "31mNuisance 3rd Class"
setvar $TARGETING~RANKS[13] "31mNuisance 2nd Class"
setvar $TARGETING~RANKS[14] "31mNuisance 1st Class"
setvar $TARGETING~RANKS[15] "31mMenace 3rd Class"
setvar $TARGETING~RANKS[16] "31mMenace 2nd Class"
setvar $TARGETING~RANKS[17] "31mMenace 1st Class"
setvar $TARGETING~RANKS[18] "31mSmuggler 3rd Class"
setvar $TARGETING~RANKS[19] "31mSmuggler 2nd Class"
setvar $TARGETING~RANKS[20] "31mSmuggler 1st Class"
setvar $TARGETING~RANKS[21] "31mSmuggler Savant"
setvar $TARGETING~RANKS[22] "31mRobber"
setvar $TARGETING~RANKS[23] "31mTerrorist"
setvar $TARGETING~RANKS[24] "31mInfamous Pirate"
setvar $TARGETING~RANKS[25] "31mNotorious Pirate"
setvar $TARGETING~RANKS[26] "31mDread Pirate"
setvar $TARGETING~RANKS[27] "31mPirate"
setvar $TARGETING~RANKS[28] "31mGalactic Scourge"
setvar $TARGETING~RANKS[29] "31mEnemy of the State"
setvar $TARGETING~RANKS[30] "31mEnemy of the People"
setvar $TARGETING~RANKS[31] "31mEnemy of Humankind"
setvar $TARGETING~RANKS[32] "31mHeinous Overlord"
setvar $TARGETING~RANKS[33] "31mPrime Evil"
setvar $TARGETING~RANKS[34] "36mChief Warrant Officer"
setvar $TARGETING~RANKS[35] "36mWarrant Officer"
setvar $TARGETING~RANKS[36] "36mEnsign"
setvar $TARGETING~RANKS[37] "36mLieutenant J.G."
setvar $TARGETING~RANKS[38] "36mLieutenant Commander"
setvar $TARGETING~RANKS[39] "36mLieutenant"
setvar $TARGETING~RANKS[40] "36mCommander"
setvar $TARGETING~RANKS[41] "36mCaptain"
setvar $TARGETING~RANKS[42] "36mCommodore"
setvar $TARGETING~RANKS[43] "36mRear Admiral"
setvar $TARGETING~RANKS[44] "36mVice Admiral"
setvar $TARGETING~RANKS[45] "36mFleet Admiral"
setvar $TARGETING~RANKS[46] "36mAdmiral"
setvar $TARGETING~ENDLINE "_ENDLINE_"
setvar $TARGETING~STARTLINE "_STARTLINE_"
setvar $TARGETING~LASTTARGET ""
return
:TARGETING~SCANITCITKILL


gosub :CHECKFORVICTIMSFROMCITADEL
echo ANSI_12 "*NO Targets*"
return
:TARGETING~CHECKFORVICTIMSFROMCITADEL

gosub :PLAYER~QUIKSTATS
setvar $PLAYER~STARTINGLOCATION $PLAYER~CURRENT_PROMPT
gosub :SECTOR~GETSECTORDATA
if ($SECTOR~CORPIECOUNT < $SECTOR~REALTRADERCOUNT)
  gosub :COMBAT~FASTCITADELATTACK
  goto :CHECKFORVICTIMSFROMCITADEL
end
return
