:INTERNAL_COMMANDS~LOGINMEMO

getword CURRENTLINE $INTERNAL_COMMANDS~WORD 1
if ($INTERNAL_COMMANDS~WORD <> "You")
  killtrigger LOGINMEMO
  settextlinetrigger LOGINMEMO :LOGINMEMO "You have a corporate memo from "
  pause
end
gettext CURRENTLINE $INTERNAL_COMMANDS~USER_NAME "You have a corporate memo from " "."

setvar $INTERNAL_COMMANDS~I 1
setvar $INTERNAL_COMMANDS~TEMPUSERNAME $INTERNAL_COMMANDS~USER_NAME
lowercase $INTERNAL_COMMANDS~TEMPUSERNAME
lowercase $INTERNAL_COMMANDS~USER_NAME
while ($INTERNAL_COMMANDS~I <= $BOT~CORPYCOUNT)
  setvar $INTERNAL_COMMANDS~TEMPCORPY $BOT~CORPY[$INTERNAL_COMMANDS~I]
  lowercase $INTERNAL_COMMANDS~TEMPCORPY
  if ($INTERNAL_COMMANDS~TEMPCORPY = $INTERNAL_COMMANDS~TEMPUSERNAME)
    goto :BOT~WAIT_FOR_COMMAND
  end
  add $INTERNAL_COMMANDS~I 1
end
add $BOT~CORPYCOUNT 1
setvar $BOT~CORPY[$BOT~CORPYCOUNT] $INTERNAL_COMMANDS~USER_NAME
cuttext $INTERNAL_COMMANDS~USER_NAME $INTERNAL_COMMANDS~CUT_USER_NAME 1 6
striptext $INTERNAL_COMMANDS~CUT_USER_NAME " "
setvar $INTERNAL_COMMANDS~LOGGEDIN[$INTERNAL_COMMANDS~CUT_USER_NAME] 1
send "'["&$BOT~MODE&"]{"&$SWITCHBOARD~BOT_NAME&"} - User Verified - "&$INTERNAL_COMMANDS~USER_NAME&"*"
goto :BOT~WAIT_FOR_COMMAND
:INTERNAL_COMMANDS~STOP


gosub :BOT~KILLTHETRIGGERS
listactivescripts $INTERNAL_COMMANDS~SCRIPTS
setvar $INTERNAL_COMMANDS~I 1
setvar $INTERNAL_COMMANDS~FOUND FALSE
while ($INTERNAL_COMMANDS~I <= $INTERNAL_COMMANDS~SCRIPTS)
  lowercase $INTERNAL_COMMANDS~SCRIPTS[$INTERNAL_COMMANDS~I]
  getwordpos "<><><>"&$INTERNAL_COMMANDS~SCRIPTS[$INTERNAL_COMMANDS~I] $INTERNAL_COMMANDS~POS "<><><>"&$BOT~PARM1
  getwordpos "<><><>"&$INTERNAL_COMMANDS~SCRIPTS[$INTERNAL_COMMANDS~I] $INTERNAL_COMMANDS~POS2 "<><><>mombot"
  if (($INTERNAL_COMMANDS~POS > 0) and ($INTERNAL_COMMANDS~POS2 <= 0))
    stop $INTERNAL_COMMANDS~SCRIPTS[$INTERNAL_COMMANDS~I]
    setvar $INTERNAL_COMMANDS~FOUND TRUE
    setvar $SWITCHBOARD~MESSAGE "Script ["&$INTERNAL_COMMANDS~SCRIPTS[$INTERNAL_COMMANDS~I]&"] killed.*"
    gosub :SWITCHBOARD~SWITCHBOARD
  end
  add $INTERNAL_COMMANDS~I 1
end
if ($INTERNAL_COMMANDS~FOUND = FALSE)
  setvar $SWITCHBOARD~MESSAGE "No script starting with "&$BOT~PARM1&" was found to kill.*"
  gosub :SWITCHBOARD~SWITCHBOARD
end
goto :BOT~WAIT_FOR_COMMAND
:INTERNAL_COMMANDS~STOPALL


gosub :BOT~KILLTHETRIGGERS
gosub :BOT~ENTER_MENU_DEAF
openmenu TWX_STOPALLFAST FALSE
gosub :BOT~EXIT_MENU_DEAF
setvar $BOT~MODE "General"
savevar $BOT~MODE
gosub :MSGS_ON

if ($INTERNAL_COMMANDS~WAS_SILENT)
  setvar $SWITCHBOARD~MESSAGE "All non-system scripts and modules killed, and modes reset. Also, turned messages back on.*"
else
  setvar $SWITCHBOARD~MESSAGE "All non-system scripts and modules killed, and modes reset.*"
end
gosub :SWITCHBOARD~SWITCHBOARD
goto :BOT~WAIT_FOR_COMMAND
:INTERNAL_COMMANDS~MSGS_ON

setvar $INTERNAL_COMMANDS~WAS_SILENT TRUE
:INTERNAL_COMMANDS~MSGS_ON_AGAIN
settexttrigger ONMSGS_ON :ONMSGS_ON "Displaying all messages."
settexttrigger ONMSGS_OFF :ONMSGS_OFF "Silencing all messages."
send "|"
pause
:INTERNAL_COMMANDS~ONMSGS_OFF
killtrigger ONMSGS_ON
setvar $INTERNAL_COMMANDS~WAS_SILENT FALSE
goto :MSGS_ON_AGAIN
:INTERNAL_COMMANDS~ONMSGS_ON
killtrigger ONMSGS_OFF
loadvar $BOT~BOTISDEAF
if ($BOT~BOTISDEAF = TRUE)
  gosub :MENUS~DONEPREFER
end
return
:INTERNAL_COMMANDS~LISTALL


listactivescripts $INTERNAL_COMMANDS~SCRIPTS
setvar $INTERNAL_COMMANDS~A 1
setvar $SWITCHBOARD~MESSAGE " Current script(s) loaded*"
setvar $SWITCHBOARD~MESSAGE $SWITCHBOARD~MESSAGE&"--------------------------*"
while ($INTERNAL_COMMANDS~A <= $INTERNAL_COMMANDS~SCRIPTS)
  setvar $SWITCHBOARD~MESSAGE $SWITCHBOARD~MESSAGE&"   "&$INTERNAL_COMMANDS~SCRIPTS[$INTERNAL_COMMANDS~A]&"*"
  add $INTERNAL_COMMANDS~A 1
end
if (($SWITCHBOARD~SELF_COMMAND <> TRUE) or ($BOT~SILENT_RUNNING <> TRUE))
  setvar $SWITCHBOARD~SELF_COMMAND 2
end
gosub :SWITCHBOARD~SWITCHBOARD
goto :BOT~WAIT_FOR_COMMAND
:INTERNAL_COMMANDS~STOPMODULES

gosub :BOT~ENTER_MENU_DEAF
openmenu TWX_STOPALLFAST FALSE
gosub :BOT~EXIT_MENU_DEAF
stop $BOT~LAST_LOADED_MODULE
echo ANSI_14 "*<<" ANSI_15 "General Mode Reset" ANSI_14 ">>*" ANSI_7
setvar $BOT~MODE "General"
savevar $BOT~MODE
setvar $BOT~LAST_LOADED_MODULE ""
savevar $BOT~LAST_LOADED_MODULE
gosub :MSGS_ON
goto :BOT~WAIT_FOR_COMMAND
:INTERNAL_COMMANDS~CALLIN


setvar $INTERNAL_COMMANDS~NEW_BOT_TEAM_NAME $BOT~PARM1
striptext $INTERNAL_COMMANDS~NEW_BOT_TEAM_NAME "^"
striptext $INTERNAL_COMMANDS~NEW_BOT_TEAM_NAME " "
lowercase $INTERNAL_COMMANDS~NEW_BOT_TEAM_NAME
getlength $INTERNAL_COMMANDS~NEW_BOT_TEAM_NAME $INTERNAL_COMMANDS~TARGETLENGTH
if (($INTERNAL_COMMANDS~NEW_BOT_TEAM_NAME = "") or ($INTERNAL_COMMANDS~TARGETLENGTH < 3))
  setvar $SWITCHBOARD~MESSAGE "Invalid team name entered, cannot join that one.  Must be more than 2 letters long.*"
  gosub :SWITCHBOARD~SWITCHBOARD
  goto :BOT~WAIT_FOR_COMMAND
else
  if (($INTERNAL_COMMANDS~NEW_BOT_TEAM_NAME = "all") or ($INTERNAL_COMMANDS~NEW_BOT_TEAM_NAME = 0))
    setvar $SWITCHBOARD~MESSAGE "Invalid team name*"
    gosub :SWITCHBOARD~SWITCHBOARD
    goto :BOT~WAIT_FOR_COMMAND
  else
    setvar $BOT~BOT_TEAM_NAME $INTERNAL_COMMANDS~NEW_BOT_TEAM_NAME
    savevar $BOT~BOT_TEAM_NAME
    setvar $SWITCHBOARD~MESSAGE "I am now part of team: "&$BOT~BOT_TEAM_NAME&"*"
    gosub :SWITCHBOARD~SWITCHBOARD
  end
end
goto :BOT~WAIT_FOR_COMMAND
:INTERNAL_COMMANDS~TWARPSWITCH


getinput $BOT~PARM1 "Twarp To:"
getword $BOT~PARM1 $BOT~PARM1 1
striptext $BOT~PARM1 " "
if ($BOT~PARM1 = "")
  goto :BOT~WAIT_FOR_COMMAND
end
setvar $BOT~USER_COMMAND_LINE "twarp "&$BOT~PARM1&" "
goto :USER_INTERFACE~RUNUSERCOMMANDLINE
:INTERNAL_COMMANDS~MOWSWITCH



getinput $BOT~PARM1 "Mow To:"
getword $BOT~PARM1 $BOT~PARM1 1
striptext $BOT~PARM1 " "
if ($BOT~PARM1 = "")
  goto :BOT~WAIT_FOR_COMMAND
end
setvar $BOT~USER_COMMAND_LINE "mow "&$BOT~PARM1&" 1"
goto :USER_INTERFACE~RUNUSERCOMMANDLINE
:INTERNAL_COMMANDS~FOTONSWITCH


if ($BOT~MODE = "Foton")
  setvar $BOT~USER_COMMAND_LINE "foton off"
  goto :USER_INTERFACE~RUNUSERCOMMANDLINE
else
  setvar $BOT~USER_COMMAND_LINE "foton on p"
  goto :USER_INTERFACE~RUNUSERCOMMANDLINE
end
goto :BOT~WAIT_FOR_COMMAND
:INTERNAL_COMMANDS~KIT


setvar $BOT~USER_COMMAND_LINE "macro_kit"
goto :USER_INTERFACE~RUNUSERCOMMANDLINE
:INTERNAL_COMMANDS~DOCK_SHOPPER

setvar $BOT~USER_COMMAND_LINE "dock_shopper"
goto :USER_INTERFACE~RUNUSERCOMMANDLINE
:INTERNAL_COMMANDS~HELP

setvar $BOT~USER_COMMAND_LINE "help "&$BOT~PARM1&" "&$BOT~PARM2&" "&$BOT~PARM3&" "&$BOT~PARM4&" "&$BOT~PARM5&" "&$BOT~PARM6&" "&$BOT~PARM7&" "&$BOT~PARM8
goto :USER_INTERFACE~RUNUSERCOMMANDLINE
:INTERNAL_COMMANDS~SECTOR
:INTERNAL_COMMANDS~SECTO
:INTERNAL_COMMANDS~SECT
:INTERNAL_COMMANDS~SEC


setvar $BOT~USER_COMMAND_LINE "sector "&$BOT~PARM1&" "&$BOT~PARM2&" "&$BOT~PARM3&" "&$BOT~PARM4
goto :USER_INTERFACE~RUNUSERCOMMANDLINE
:INTERNAL_COMMANDS~PARM
:INTERNAL_COMMANDS~PARMS
:INTERNAL_COMMANDS~PARAMS

setvar $BOT~USER_COMMAND_LINE "param "&$BOT~PARM1&" "&$BOT~PARM2&" "&$BOT~PARM3&" "&$BOT~PARM4
goto :USER_INTERFACE~RUNUSERCOMMANDLINE
:INTERNAL_COMMANDS~HOLOTORP
:INTERNAL_COMMANDS~HTORP

setvar $BOT~USER_COMMAND_LINE "htorp "&$BOT~PARM1&" "&$BOT~PARM2&" "&$BOT~PARM3&" "&$BOT~PARM4

gosub :BOT~KILLTHETRIGGERS

gosub :PLAYER~QUIKSTATS
if ($PLAYER~SCAN_TYPE <> "Holo")
  setvar $SWITCHBOARD~MESSAGE "You can not run htorp without a holographic scanner.*"
  gosub :SWITCHBOARD~SWITCHBOARD
  goto :BOT~WAIT_FOR_COMMAND
end
setvar $PLAYER~STARTINGLOCATION $PLAYER~CURRENT_PROMPT
if ($PLAYER~STARTINGLOCATION = "Command")

elseif ($PLAYER~STARTINGLOCATION = "Citadel")
  send "q "
  gosub :PLANET~GETPLANETINFO
else
  echo "*Wrong prompt for htorp.*"
  goto :BOT~WAIT_FOR_COMMAND
end
if ($PLAYER~STARTINGLOCATION = "Citadel")
  send "q szh* l "&$PLANET~PLANET&"* c "
else
  send "szh* "
end
settextlinetrigger CHECKFORHOLO :CONTINUECHECKHOLO "Select (H)olo Scan or (D)ensity Scan or (Q)uit?"
settextlinetrigger CHECKFORDENS :PHOTONEDHTORP "Relative Density Scan"
pause
:INTERNAL_COMMANDS~CONTINUECHECKHOLO
settexttrigger HTORPSECTOR :CONTINUEHTORPSECTOR "["&$PLAYER~CURRENT_SECTOR&"]"
pause
:INTERNAL_COMMANDS~CONTINUEHTORPSECTOR
if ($PLAYER~PHOTONS <= 0)
  echo ANSI_14&"*No Photons on hand.**"&ANSI_7
  goto :BOT~WAIT_FOR_COMMAND
end
setvar $INTERNAL_COMMANDS~I 1
while (SECTOR.WARPS[$PLAYER~CURRENT_SECTOR][$INTERNAL_COMMANDS~I] > 0)
  setvar $INTERNAL_COMMANDS~ADJ_SEC SECTOR.WARPS[$PLAYER~CURRENT_SECTOR][$INTERNAL_COMMANDS~I]
  if (SECTOR.TRADERCOUNT[$INTERNAL_COMMANDS~ADJ_SEC] > 0)
    setvar $INTERNAL_COMMANDS~TARGETINSECTOR FALSE
    setvar $INTERNAL_COMMANDS~CORPMEMBERINSECTOR FALSE
    setvar $INTERNAL_COMMANDS~J 1
    while (SECTOR.TRADERS[$INTERNAL_COMMANDS~ADJ_SEC][$INTERNAL_COMMANDS~J] <> 0)
      setvar $INTERNAL_COMMANDS~TEMPTARGET SECTOR.TRADERS[$INTERNAL_COMMANDS~ADJ_SEC][$INTERNAL_COMMANDS~J]
      getlength $INTERNAL_COMMANDS~TEMPTARGET $INTERNAL_COMMANDS~TARGETLENGTH
      if ($INTERNAL_COMMANDS~TARGETLENGTH >= 4)
        cuttext $INTERNAL_COMMANDS~TEMPTARGET $INTERNAL_COMMANDS~TARGETCORP ($INTERNAL_COMMANDS~TARGETLENGTH - 4) 999
        gettext $INTERNAL_COMMANDS~TARGETCORP $INTERNAL_COMMANDS~TARGETCORP "[" "]"
        if ($INTERNAL_COMMANDS~TARGETCORP <> $PLAYER~CORP)
          setvar $INTERNAL_COMMANDS~TARGETINSECTOR TRUE
        end
        if ($INTERNAL_COMMANDS~TARGETCORP = $PLAYER~CORP)
          setvar $INTERNAL_COMMANDS~CORPMEMBERINSECTOR TRUE
        end
      end
      add $INTERNAL_COMMANDS~J 1
    end
    if (($INTERNAL_COMMANDS~TARGETINSECTOR = TRUE) and ($INTERNAL_COMMANDS~CORPMEMBERINSECTOR = FALSE))
      send "c p y " $INTERNAL_COMMANDS~ADJ_SEC "* *q"
      setvar $SWITCHBOARD~MESSAGE "Photon fired into sector "&$INTERNAL_COMMANDS~ADJ_SEC&"!*"
      gosub :SWITCHBOARD~SWITCHBOARD
      goto :BOT~WAIT_FOR_COMMAND
    end
  end
  add $INTERNAL_COMMANDS~I 1
end
if ($PLAYER~STARTINGLOCATION = "Citadel")
  settexttrigger WAITFORCIT :CONTINUEWAITFORCIT "Citadel command (?=help)"
  pause
  :INTERNAL_COMMANDS~CONTINUEWAITFORCIT
end
echo ANSI_14&"*No valid targets**"&ANSI_7
goto :BOT~WAIT_FOR_COMMAND
:INTERNAL_COMMANDS~PHOTONEDHTORP
setvar $SWITCHBOARD~MESSAGE "You have no holographic scanner, perhaps you were photoned?*"
gosub :SWITCHBOARD~SWITCHBOARD
goto :BOT~WAIT_FOR_COMMAND
:INTERNAL_COMMANDS~LOGOFF
:INTERNAL_COMMANDS~LOGOUT


killalltriggers
gosub :PLAYER~QUIKSTATS
setvar $INTERNAL_COMMANDS~STARTINGLOCATION $PLAYER~CURRENT_PROMPT
setvar $INTERNAL_COMMANDS~QUITTINGWITHNOTIMER FALSE
isnumber $INTERNAL_COMMANDS~TEST $BOT~PARM1

if ($INTERNAL_COMMANDS~STARTINGLOCATION = "Citadel")
  send "q "
  gosub :PLANET~GETPLANETINFO
  send "c "
end
if ($INTERNAL_COMMANDS~TEST = FALSE)
  setvar $INTERNAL_COMMANDS~QUITTINGWITHNOTIMER TRUE
elseif (($BOT~PARM1 <= 0) or ($BOT~PARM1 = "cloak"))
  setvar $INTERNAL_COMMANDS~QUITTINGWITHNOTIMER TRUE
else
  setvar $INTERNAL_COMMANDS~TIMETOLOGBACKIN ($BOT~PARM1 * 60)
  gosub :CALCTIME
end
setvar $INTERNAL_COMMANDS~CLOAKINGOUT FALSE
getwordpos " "&$BOT~USER_COMMAND_LINE&" " $INTERNAL_COMMANDS~POS " cloak "
if ($INTERNAL_COMMANDS~POS > 0)
  setvar $INTERNAL_COMMANDS~CLOAKINGOUT TRUE
end
if (($INTERNAL_COMMANDS~CLOAKINGOUT = TRUE) and ($PLAYER~CLOAKS > 0))
  if ($INTERNAL_COMMANDS~QUITTINGWITHNOTIMER)
    send "'{" $SWITCHBOARD~BOT_NAME "} - Logging and cloaking out until I am at keys to login again.*"
  else
    send "'{" $SWITCHBOARD~BOT_NAME "} - Logging and cloaking out for "&$INTERNAL_COMMANDS~HOURS&" hours, "&$INTERNAL_COMMANDS~MINUTES&" minutes, and "&$INTERNAL_COMMANDS~SECONDS&" seconds.*"
  end
  send "q q q q  * * * * q q q q y y x *"
  waiton "==-- Trade Wars 2002 --=="
else
  if ($INTERNAL_COMMANDS~QUITTINGWITHNOTIMER)
    send "'{" $SWITCHBOARD~BOT_NAME "} - Logging out until I am at keys to login again.*"
  else
    send "'{" $SWITCHBOARD~BOT_NAME "} - Logging out for "&$INTERNAL_COMMANDS~HOURS&" hours, "&$INTERNAL_COMMANDS~MINUTES&" minutes, and "&$INTERNAL_COMMANDS~SECONDS&" seconds.*"
  end
  if ($INTERNAL_COMMANDS~STARTINGLOCATION = "Citadel")
    send "ryy* x *##"
    waiton "Game Server"
  else
    send "q q q q  * * * * q q q q y*"
    waiton "==-- Trade Wars 2002 --=="
  end
end
disconnect
setvar $INTERNAL_COMMANDS~TIMER 0
if ($INTERNAL_COMMANDS~QUITTINGWITHNOTIMER)
  setvar $BOT~DO_NOT_RESUSCITATE TRUE
  savevar $BOT~DO_NOT_RESUSCITATE
  halt
end
settextouttrigger LOGEARLY :ENDLOGOFFGAME #32
while ($INTERNAL_COMMANDS~TIMETOLOGBACKIN > 0)
  gosub :CALCTIME
  echo ANSI_10 #27&"[1A"&#27&"[K"&$INTERNAL_COMMANDS~HOURS ":" $INTERNAL_COMMANDS~MINUTES ":" $INTERNAL_COMMANDS~SECONDS " left before entering game " GAME " (" GAMENAME ") "&ANSI_15&" ["&ANSI_14&"Spacebar to relog"&ANSI_15&"]*"
  setdelaytrigger TIMEBEFORERELOG :RELOGTIMER 1000
  pause
  :INTERNAL_COMMANDS~RELOGTIMER
  setvar $INTERNAL_COMMANDS~TIMETOLOGBACKIN ($INTERNAL_COMMANDS~TIMETOLOGBACKIN - 1)
end
:INTERNAL_COMMANDS~ENDLOGOFFGAME
killtrigger LOGEARLY
killtrigger TIMEBEFORERELOG
goto :RELOG_ATTEMPT
:INTERNAL_COMMANDS~CALCTIME


setvar $INTERNAL_COMMANDS~HOURS 0
setvar $INTERNAL_COMMANDS~MINUTES 0
setvar $INTERNAL_COMMANDS~SECONDS 0
setvar $INTERNAL_COMMANDS~TESTTIME $INTERNAL_COMMANDS~TIMETOLOGBACKIN
if ($INTERNAL_COMMANDS~TESTTIME >= 3600)
  setvar $INTERNAL_COMMANDS~HOURS ($INTERNAL_COMMANDS~TESTTIME / 3600)
  setvar $INTERNAL_COMMANDS~TESTTIME ($INTERNAL_COMMANDS~TESTTIME - ($INTERNAL_COMMANDS~HOURS * 3600))
end
if ($INTERNAL_COMMANDS~TESTTIME >= 60)
  setvar $INTERNAL_COMMANDS~MINUTES ($INTERNAL_COMMANDS~TESTTIME / 60)
  setvar $INTERNAL_COMMANDS~TESTTIME ($INTERNAL_COMMANDS~TESTTIME - ($INTERNAL_COMMANDS~MINUTES * 60))
end
if ($INTERNAL_COMMANDS~TESTTIME >= 1)
  setvar $INTERNAL_COMMANDS~SECONDS $INTERNAL_COMMANDS~TESTTIME
end
if ($INTERNAL_COMMANDS~HOURS < 10)
  setvar $INTERNAL_COMMANDS~HOURS 0&$INTERNAL_COMMANDS~HOURS
end
if ($INTERNAL_COMMANDS~MINUTES < 10)
  setvar $INTERNAL_COMMANDS~MINUTES 0&$INTERNAL_COMMANDS~MINUTES
end
if ($INTERNAL_COMMANDS~SECONDS < 10)
  setvar $INTERNAL_COMMANDS~SECONDS 0&$INTERNAL_COMMANDS~SECONDS
end
return
:INTERNAL_COMMANDS~SURROUND



setvar $BOT~USER_COMMAND_LINE "surround "&$BOT~PARM1&" "&$BOT~PARM2&" "&$BOT~PARM3&" "&$BOT~PARM4&" "&$BOT~PARM5&" "&$BOT~PARM6&" "&$BOT~PARM7&" "&$BOT~PARM8
goto :USER_INTERFACE~RUNUSERCOMMANDLINE
:INTERNAL_COMMANDS~CLEAR





setvar $BOT~USER_COMMAND_LINE "clear "&$BOT~PARM1&" "&$BOT~PARM2&" "&$BOT~PARM3&" "&$BOT~PARM4&" "&$BOT~PARM5&" "&$BOT~PARM6&" "&$BOT~PARM7&" "&$BOT~PARM8
goto :USER_INTERFACE~RUNUSERCOMMANDLINE
:INTERNAL_COMMANDS~EXIT
:INTERNAL_COMMANDS~XENTER

setvar $BOT~USER_COMMAND_LINE "xenter "&$BOT~PARM1&" "&$BOT~PARM2&" "&$BOT~PARM3&" "&$BOT~PARM4&" "&$BOT~PARM5&" "&$BOT~PARM6&" "&$BOT~PARM7&" "&$BOT~PARM8
goto :USER_INTERFACE~RUNUSERCOMMANDLINE
:INTERNAL_COMMANDS~SHUTDOWN


setvar $BOT~MODE "General"
savevar $BOT~MODE
goto :BOT~WAIT_FOR_COMMAND
:INTERNAL_COMMANDS~ABOUT




gosub :MENUS~DOSPLASHSCREEN
echo "*" CURRENTANSILINE
goto :BOT~WAIT_FOR_COMMAND
:INTERNAL_COMMANDS~BOT

setvar $SWITCHBOARD~MESSAGE ""
if ($BOT~PARM1 = "on")
  setvar $BOT~BOTISOFF FALSE
  savevar $BOT~BOTISOFF
  setvar $SWITCHBOARD~MESSAGE "Bot Active*"
end
if ($BOT~PARM1 = "off")
  setvar $BOT~BOTISOFF TRUE
  savevar $BOT~BOTISOFF
  setvar $SWITCHBOARD~MESSAGE "Bot Deactivated*"
end
if (($BOT~PARM1 <> "off") and ($BOT~PARM1 <> "on"))
  setvar $SWITCHBOARD~MESSAGE "That status option is unknown..*"
end
gosub :SWITCHBOARD~SWITCHBOARD
goto :BOT~WAIT_FOR_COMMAND
:INTERNAL_COMMANDS~REFRESH


gosub :BOT~KILLTHETRIGGERS
gosub :PLAYER~QUIKSTATS
setvar $BOT~VALIDPROMPTS "Citadel Command"
gosub :BOT~CHECKSTARTINGPROMPT
if ($PLAYER~CURRENT_PROMPT = "Citadel")
  send "q"
  gosub :PLANET~GETPLANETINFO
  send "q"
end

gosub :PLAYER~GETINFO
gosub :GAME~GAMESTATS

gosub :SHIP~GETSHIPSTATS

gosub :PLAYER~QUIKSTATS
gosub :SHIP~GETSHIPCAPSTATS
gosub :SHIP~LOADSHIPINFO

gosub :PLANET~GETPLANETSTATS
gosub :PLANET~LOADPLANETINFO

if ($PLAYER~CURRENT_PROMPT = "Citadel")
  gosub :PLANET~LANDINGSUB
end
setvar $SWITCHBOARD~MESSAGE "Bot data refresh completed.*"
gosub :SWITCHBOARD~SWITCHBOARD
goto :BOT~WAIT_FOR_COMMAND
:INTERNAL_COMMANDS~HOLO_KILL
:INTERNAL_COMMANDS~HKILL



setvar $BOT~USER_COMMAND_LINE "hkill "&$BOT~PARM1&" "&$BOT~PARM2&" "&$BOT~PARM3&" "&$BOT~PARM4&" "&$BOT~PARM5&" "&$BOT~PARM6&" "&$BOT~PARM7&" "&$BOT~PARM8

gosub :BOT~KILLTHETRIGGERS

loadvar $PLAYER~SURROUND_BEFORE_HKILL
getwordpos $BOT~USER_COMMAND_LINE $INTERNAL_COMMANDS~POS "surround"
if ($INTERNAL_COMMANDS~POS > 0)
  setvar $PLAYER~SURROUND_BEFORE_HKILL TRUE
else
  if ($PLAYER~SURROUND_BEFORE_HKILL <> TRUE)
    setvar $PLAYER~SURROUND_BEFORE_HKILL FALSE
  end
end

setvar $PLAYER~CIT FALSE
gosub :PLAYER~QUIKSTATS
setvar $INTERNAL_COMMANDS~STARTINGLOCATION $PLAYER~CURRENT_PROMPT
setvar $BOT~VALIDPROMPTS "Citadel Command"
gosub :BOT~CHECKSTARTINGPROMPT
gosub :COMBAT~HOLOKILL
if ($SWITCHBOARD~MESSAGE <> "")
  gosub :SWITCHBOARD~SWITCHBOARD
end

goto :BOT~WAIT_FOR_COMMAND
:INTERNAL_COMMANDS~AUTOKILL




setvar $BOT~PARM1 "furb"
setvar $BOT~PARM2 "silent"
:INTERNAL_COMMANDS~KILL
gosub :BOT~KILLTHETRIGGERS
if ($BOT~PARM1 = "furb")
  setvar $INTERNAL_COMMANDS~FURB TRUE
end

gosub :PLAYER~CURRENTPROMPT
setvar $PLAYER~STARTINGLOCATION $PLAYER~CURRENT_PROMPT

if ($PLAYER~STARTINGLOCATION <> "Command")
  if ($PLAYER~STARTINGLOCATION = "Citadel")
    loadvar $BOT~MODE
    if ($BOT~MODE <> "Citkill")
      setvar $BOT~USER_COMMAND_LINE "citkill on override"
      setvar $BOT~AUTOATTACK FALSE
      savevar $BOT~AUTOATTACK
      goto :USER_INTERFACE~RUNUSERCOMMANDLINE
    else
      setvar $BOT~USER_COMMAND_LINE "citkill off"
      goto :USER_INTERFACE~RUNUSERCOMMANDLINE
    end
  end
  setvar $SWITCHBOARD~MESSAGE "Wrong prompt for auto kill.*"
  gosub :SWITCHBOARD~SWITCHBOARD
  if ($BOT~AUTOATTACK)
    setvar $BOT~AUTOATTACK FALSE
    savevar $BOT~AUTOATTACK
    setvar $SWITCHBOARD~MESSAGE "Since in wrong prompt, shutting down autokill option in bot.  Restart in options.*"
    gosub :SWITCHBOARD~SWITCHBOARD
  end
  goto :BOT~WAIT_FOR_COMMAND
end
loadvar $SHIP~SHIP_MAX_ATTACK
loadvar $SHIP~SHIP_FIGHTERS_MAX
loadvar $SHIP~SHIP_OFFENSIVE_ODDS
if ($SHIP~SHIP_MAX_ATTACK <= 0)
  gosub :SHIP~GETSHIPSTATS
end
setvar $PLAYER~ISFOUND FALSE
gosub :SECTOR~GETSECTORDATA
gosub :COMBAT~FASTATTACK
if ((($PLAYER~CURRENT_SECTOR = 1) or ($PLAYER~CURRENT_SECTOR = $MAP~STARDOCK)) and ($INTERNAL_COMMANDS~FURB = TRUE))
  if ($PLAYER~ISFOUND)
    load "scripts\"&$BOT~MOMBOT_DIRECTORY&"\commands\resource\refurb.cts"
    seteventtrigger 1 :REFURBENDED "SCRIPT STOPPED" "scripts\"&$BOT~MOMBOT_DIRECTORY&"\commands\resource\refurb.cts"
    pause
    :INTERNAL_COMMANDS~REFURBENDED
    gosub :SECTOR~GETSECTORDATA
    gosub :COMBAT~FASTATTACK
  end
end
goto :BOT~WAIT_FOR_COMMAND
:INTERNAL_COMMANDS~AUTOCAPTURE
:INTERNAL_COMMANDS~AUTOCAP
:INTERNAL_COMMANDS~CAP


setvar $BOT~USER_COMMAND_LINE "cap "&$BOT~PARM1&" "&$BOT~PARM2&" "&$BOT~PARM3&" "&$BOT~PARM4&" "&$BOT~PARM5&" "&$BOT~PARM6&" "&$BOT~PARM7&" "&$BOT~PARM8

gosub :BOT~KILLTHETRIGGERS
gosub :PLAYER~QUIKSTATS
setvar $PLAYER~STARTINGLOCATION $PLAYER~CURRENT_PROMPT
if ($PLAYER~STARTINGLOCATION <> "Command")
  if ($PLAYER~STARTINGLOCATION = "Citadel")
    loadvar $BOT~MODE
    if ($BOT~MODE <> "Citcap")
      setvar $BOT~COMMAND "citcap"
      setvar $BOT~USER_COMMAND_LINE " citcap on "
      setvar $BOT~PARM1 "on"
      goto :USER_INTERFACE~RUNUSERCOMMANDLINE
    else
      setvar $BOT~COMMAND "citcap"
      setvar $BOT~USER_COMMAND_LINE " citcap off "
      setvar $BOT~PARM1 "off"
      goto :USER_INTERFACE~RUNUSERCOMMANDLINE
    end
    goto :BOT~WAIT_FOR_COMMAND
  end
  setvar $SWITCHBOARD~MESSAGE "Wrong prompt for auto capture.*"
  gosub :SWITCHBOARD~SWITCHBOARD
  goto :BOT~WAIT_FOR_COMMAND
end
getwordpos $BOT~USER_COMMAND_LINE $INTERNAL_COMMANDS~POS "alien"
if ($INTERNAL_COMMANDS~POS > 0)
  setvar $PLAYER~ONLYALIENS TRUE
else
  setvar $PLAYER~ONLYALIENS FALSE
end
fileexists $SHIP~CAP_FILE_CHK $SHIP~CAP_FILE
if ($SHIP~CAP_FILE_CHK <> TRUE)
  gosub :SHIP~GETSHIPCAPSTATS
end
loadvar $SHIP~SHIP_MAX_ATTACK
loadvar $SHIP~SHIP_FIGHTERS_MAX
loadvar $SHIP~SHIP_OFFENSIVE_ODDS
if ($SHIP~SHIP_OFFENSIVE_ODDS <= 0)
  gosub :SHIP~GETSHIPSTATS
end
setvar $INTERNAL_COMMANDS~LASTTARGET ""
setvar $INTERNAL_COMMANDS~THISTARGET ""
gosub :SECTOR~GETSECTORDATA
gosub :COMBAT~FASTCAPTURE

goto :BOT~WAIT_FOR_COMMAND
:INTERNAL_COMMANDS~DO_RELOG


setvar $BOT~PARM1 "do_relog"
:INTERNAL_COMMANDS~RELOG_ATTEMPT
setvar $BOT~USER_COMMAND_LINE "relog "&$BOT~PARM1&" "&$BOT~PARM2&" "&$BOT~PARM3&" "&$BOT~PARM4&" "&$BOT~PARM5&" "&$BOT~PARM6&" "&$BOT~PARM7&" "&$BOT~PARM8
goto :USER_INTERFACE~RUNUSERCOMMANDLINE
:INTERNAL_COMMANDS~SCRUB


setvar $BOT~USER_COMMAND_LINE "scrub "&$BOT~PARM1&" "&$BOT~PARM2&" "&$BOT~PARM3&" "&$BOT~PARM4&" "&$BOT~PARM5&" "&$BOT~PARM6&" "&$BOT~PARM7&" "&$BOT~PARM8
goto :USER_INTERFACE~RUNUSERCOMMANDLINE
:INTERNAL_COMMANDS~AUTOREFURB
:INTERNAL_COMMANDS~REFURB

setvar $BOT~USER_COMMAND_LINE "refurb "&$BOT~PARM1&" "&$BOT~PARM2&" "&$BOT~PARM3&" "&$BOT~PARM4&" "&$BOT~PARM5&" "&$BOT~PARM6&" "&$BOT~PARM7&" "&$BOT~PARM8
goto :USER_INTERFACE~RUNUSERCOMMANDLINE
:INTERNAL_COMMANDS~SWITCHBOT

switchbot $BOT~PARM1
halt
