:MOVEPRODUCT~MOVEPRODUCT
gosub :PLAYERINFO~INFOQUICK

setvar $MOVEPRODUCT~PSCAN $PLAYERINFO~PLANETSCANNER
setvar $MOVEPRODUCT~CREDITS $PLAYERINFO~CREDITS
setvar $MOVEPRODUCT~MOVED 0
setvar $MOVEPRODUCT~RESTORE_HAGGLE 0

if (($MOVEPRODUCT~SOURCE = "P") and HAGGLE)
  setvar $MOVEPRODUCT~RESTORE_HAGGLE 1
  autohaggle off
end

if ($MOVEPRODUCT~PRODUCT = 4)
  send "qc;ql " $MOVEPRODUCT~SOURCE "* "

  settextlinetrigger GETMAXFIGS :GETMAXFIGS "Max Fighters:"
  pause
  :MOVEPRODUCT~GETMAXFIGS
  cuttext CURRENTLINE $MOVEPRODUCT~HOLDS 48 7
  striptext $MOVEPRODUCT~HOLDS ","
  striptext $MOVEPRODUCT~HOLDS " "
else
  setvar $MOVEPRODUCT~HOLDS $PLAYERINFO~HOLDS
end

if ($MOVEPRODUCT~SOURCESECTOR <> $MOVEPRODUCT~DESTSECTOR)
  setvar $MOVEPRODUCT~SAFE 1
end

if ($MOVEPRODUCT~PRODUCT = "C")
  setvar $MOVEPRODUCT~PICKUPTEXT "snt"&$MOVEPRODUCT~SOURCECATEGORY
  setvar $MOVEPRODUCT~DROPOFFTEXT "snl"&$MOVEPRODUCT~DESTCATEGORY
  setvar $MOVEPRODUCT~WAITTEXT "Which production group are you changing?"
elseif ($MOVEPRODUCT~PRODUCT = 4)
  setvar $MOVEPRODUCT~PICKUPTEXT "mnt"
  setvar $MOVEPRODUCT~DROPOFFTEXT "mnl"
  setvar $MOVEPRODUCT~WAITTEXT "There are currently "
else
  setvar $MOVEPRODUCT~PICKUPTEXT "tnt"&$MOVEPRODUCT~PRODUCT
  setvar $MOVEPRODUCT~DROPOFFTEXT "tnl"&$MOVEPRODUCT~PRODUCT
  setvar $MOVEPRODUCT~WAITTEXT "Which product are you leaving?"

end
if (($MOVEPRODUCT~SOURCE = "P") and ($MOVEPRODUCT~PORTQUANTITY = 0))

  send "cr*q"

  waiton "Commerce report for "

  if ($MOVEPRODUCT~PRODUCT = 1)
    settextlinetrigger GETPRODUCT :GETPRODUCT "Fuel Ore   "
  elseif ($MOVEPRODUCT~PRODUCT = 2)
    settextlinetrigger GETPRODUCT :GETPRODUCT "Organics   "
  else
    settextlinetrigger GETPRODUCT :GETPRODUCT "Equipment  "
  end
  pause
  :MOVEPRODUCT~GETPRODUCT

  if ($MOVEPRODUCT~PRODUCT = 1)
    getword CURRENTLINE $MOVEPRODUCT~PORTQUANTITY 4
  else
    getword CURRENTLINE $MOVEPRODUCT~PORTQUANTITY 3
  end


end
if ($MOVEPRODUCT~SOURCE = "P")
  if ($MOVEPRODUCT~PORTQUANTITY < $MOVEPRODUCT~QUANTITY)
    setvar $MOVEPRODUCT~QUANTITY $MOVEPRODUCT~PORTQUANTITY
  end
else
  send "d"
  gosub :PLANETINFO~PLANETINFO

  if ($MOVEPRODUCT~PRODUCT = "C")
    if ($PLANETINFO~COLO[$MOVEPRODUCT~SOURCECATEGORY] < $MOVEPRODUCT~QUANTITY)
      setvar $MOVEPRODUCT~QUANTITY $PLANETINFO~COLO[$MOVEPRODUCT~SOURCECATEGORY]
    end
  else
    if ($PLANETINFO~AMOUNT[$MOVEPRODUCT~PRODUCT] < $MOVEPRODUCT~QUANTITY)
      setvar $MOVEPRODUCT~QUANTITY $PLANETINFO~AMOUNT[$MOVEPRODUCT~PRODUCT]
    end
  end
end

if ($MOVEPRODUCT~SAFE)
  setvar $MOVEPRODUCT~FIRSTRUN 1
  setvar $MOVEPRODUCT~FINISHED 0

  if ($MOVEPRODUCT~PRODUCT = "C")
    setvar $MOVEPRODUCT~PLANETAMOUNT $PLANETINFO~COLO[$MOVEPRODUCT~SOURCECATEGORY]
  else
    setvar $MOVEPRODUCT~PLANETAMOUNT $PLANETINFO~AMOUNT[$MOVEPRODUCT~PRODUCT]
  end
  :MOVEPRODUCT~SAFECYCLE

  if ($MOVEPRODUCT~QUANTITY < $MOVEPRODUCT~HOLDS)
    setvar $MOVEPRODUCT~PICKUP $MOVEPRODUCT~QUANTITY
  else
    setvar $MOVEPRODUCT~PICKUP $MOVEPRODUCT~HOLDS
  end

  if ($MOVEPRODUCT~SOURCE = "P")
    if ($MOVEPRODUCT~PICKUP = 0)

      gosub :SUB_LANDDEST
      waiton "Planet #"&$MOVEPRODUCT~DEST
      waiton "Planet command (?=help)"
      gosub :MOVEPRODUCT~RESTOREHAGGLE
      return
    end


    if ($MOVEPRODUCT~PRODUCT = 1)
      setvar $MOVEPRODUCT~BUYPROD "Fuel"
    elseif ($MOVEPRODUCT~PRODUCT = 2)
      setvar $MOVEPRODUCT~BUYPROD "Organics"
    else
      setvar $MOVEPRODUCT~BUYPROD "Equipment"
    end
    :MOVEPRODUCT~RETRYHAGGLE

    send "pt"
    setvar $MOVEPRODUCT~SECTOR $MOVEPRODUCT~SOURCESECTOR

    if ($MOVEPRODUCT~PICKUP < $MOVEPRODUCT~HOLDS)
      setvar $MOVEPRODUCT~QUANTITY $MOVEPRODUCT~PICKUP
    end

waiton "Docking..."

settextlinetrigger BUY :BUY "We are selling up to "
settextlinetrigger SELL :SELL "We are buying up to "
pause

:MOVEPRODUCT~BUY
killtrigger GETCREDITS
killtrigger DONE
settexttrigger ONHAND :BUYONHAND "]?"
pause

:MOVEPRODUCT~BUYONHAND
getword CURRENTLINE $MOVEPRODUCT~PRODUCT 5
if ($MOVEPRODUCT~PRODUCT <> $MOVEPRODUCT~BUYPROD)
  send "0*"
  settexttrigger GETCREDITS :GETCREDITS "empty cargo holds."
  pause
end
send "*"

settexttrigger GETCREDITS :GETCREDITS "empty cargo holds."
pause
:MOVEPRODUCT~GETCREDITS
killtrigger CLASS0
killtrigger BUY
killtrigger SELL
getword CURRENTLINE $MOVEPRODUCT~CREDITS 3
striptext $MOVEPRODUCT~CREDITS ","
settextlinetrigger BUY :BUY "We are selling up to "
settextlinetrigger SELL :SELL "We are buying up to "
settexttrigger HAGGLEDONE :HAGGLEDONE "Command [TL="
pause
:MOVEPRODUCT~HAGGLEDONE
killtrigger BUY
killtrigger SELL


    if ($MOVEPRODUCT~ABORT)
      goto :RETRYHAGGLE
    end

    if ($MOVEPRODUCT~CREDITS < 10000)
      setvar $MOVEPRODUCT~FINISHED 1
    end
  else
    if ($MOVEPRODUCT~FIRSTRUN = 0)

      gosub :PLANETINFO~PLANETINFO

      if ($MOVEPRODUCT~PRODUCT = "C")
        setvar $MOVEPRODUCT~PLANETAMOUNT $PLANETINFO~COLO[$MOVEPRODUCT~SOURCECATEGORY]
      else
        setvar $MOVEPRODUCT~PLANETAMOUNT $PLANETINFO~AMOUNT[$MOVEPRODUCT~PRODUCT]
      end
    end

    if ($MOVEPRODUCT~PLANETAMOUNT < $MOVEPRODUCT~PICKUP)
      setvar $MOVEPRODUCT~PICKUP $MOVEPRODUCT~PLANETAMOUNT
    end

    if ($MOVEPRODUCT~PICKUP = 0)

      setvar $MOVEPRODUCT~FINISHED 1
      send "q"
    else
      if ($MOVEPRODUCT~PICKUP = $MOVEPRODUCT~HOLDS)
        send $MOVEPRODUCT~PICKUPTEXT "*q"
      else
        send $MOVEPRODUCT~PICKUPTEXT $MOVEPRODUCT~PICKUP "*q"
      end
    end
  end


  if ($MOVEPRODUCT~SOURCESECTOR <> $MOVEPRODUCT~DESTSECTOR)
    setvar $WARP~DEST $MOVEPRODUCT~DESTSECTOR
    setvar $WARP~MODE "E"
    gosub :WARP~WARP
  end


  if ($MOVEPRODUCT~FINISHED)
    gosub :SUB_LANDDEST
    waiton "<Preparing ship to land"
  else
    if ($MOVEPRODUCT~PSCAN or (SECTOR.PLANETCOUNT[$MOVEPRODUCT~DESTSECTOR] > 1))
      send "l " $MOVEPRODUCT~DEST "*" $MOVEPRODUCT~DROPOFFTEXT "*"
    else
      send "l " $MOVEPRODUCT~DROPOFFTEXT "*"
    end
    waiton $MOVEPRODUCT~WAITTEXT
  end

  waiton "Planet command (?=help)"
  subtract $MOVEPRODUCT~QUANTITY $MOVEPRODUCT~PICKUP
  add $MOVEPRODUCT~MOVED $MOVEPRODUCT~PICKUP

  if (($MOVEPRODUCT~QUANTITY <= 0) or $MOVEPRODUCT~FINISHED)

    gosub :MOVEPRODUCT~RESTOREHAGGLE
    return
  end

  send "q"

  if ($MOVEPRODUCT~SOURCESECTOR <> $MOVEPRODUCT~DESTSECTOR)
    setvar $WARP~DEST $MOVEPRODUCT~SOURCESECTOR
    setvar $WARP~MODE "E"
    gosub :WARP~WARP
  end

  if ($MOVEPRODUCT~SOURCE <> "P")

    gosub :SUB_LANDSOURCE
  end

  setvar $MOVEPRODUCT~FIRSTRUN 0
  goto :SAFECYCLE

else

  setvar $MOVEPRODUCT~CYCLES ($MOVEPRODUCT~QUANTITY / $MOVEPRODUCT~HOLDS)
  setvar $MOVEPRODUCT~REMAINDER ($MOVEPRODUCT~QUANTITY - ($MOVEPRODUCT~CYCLES * $MOVEPRODUCT~HOLDS))

  if ($MOVEPRODUCT~REMAINDER > 0)
    add $MOVEPRODUCT~CYCLES 1
  end

  if ($MOVEPRODUCT~SOURCE <> "P")
    send "q"
  end



  if ($MOVEPRODUCT~CYCLES <= 0)

    gosub :SUB_LANDDEST
    gosub :MOVEPRODUCT~RESTOREHAGGLE
    return
  end

  setvar $GAMEPREFS~BANK "MOVEPRODUCT"
  setvar $GAMEPREFS~ABORTDISPLAYALL[$GAMEPREFS~BANK] "ON"
  setvar $GAMEPREFS~ANSI[$GAMEPREFS~BANK] "ON"
  gosub :GAMEPREFS~SETGAMEPREFS

  setvar $MOVEPRODUCT~CLOCK 3
  :MOVEPRODUCT~CYCLE


  setvar $MOVEPRODUCT~SEND ""

  if ($MOVEPRODUCT~SOURCE = "P")


    setvar $MOVEPRODUCT~SEND "pt"

    if ((($MOVEPRODUCT~PRODUCT = 2) or ($MOVEPRODUCT~PRODUCT = 3)) and (PORT.BUYFUEL[$MOVEPRODUCT~SOURCESECTOR] = 0))
      setvar $MOVEPRODUCT~SEND $MOVEPRODUCT~SEND&"0*"
    end
    if (($MOVEPRODUCT~PRODUCT = 3) and (PORT.BUYORG[$MOVEPRODUCT~SOURCESECTOR] = 0))
      setvar $MOVEPRODUCT~SEND $MOVEPRODUCT~SEND&"0*"
    end

    if (($MOVEPRODUCT~CYCLES = 1) and ($MOVEPRODUCT~REMAINDER > 0))
      setvar $MOVEPRODUCT~SEND $MOVEPRODUCT~SEND&$MOVEPRODUCT~REMAINDER&"**"
    else
      setvar $MOVEPRODUCT~SEND $MOVEPRODUCT~SEND&"**"
    end

    if ((($MOVEPRODUCT~PRODUCT = 1) or ($MOVEPRODUCT~PRODUCT = 2)) and (PORT.BUYEQUIP[$MOVEPRODUCT~SOURCESECTOR] = 0))
      setvar $MOVEPRODUCT~SEND $MOVEPRODUCT~SEND&"0*"
    end
    if (($MOVEPRODUCT~PRODUCT = 1) and (PORT.BUYORG[$MOVEPRODUCT~SOURCESECTOR] = 0))
      setvar $MOVEPRODUCT~SEND $MOVEPRODUCT~SEND&"0*"
    end

  else


    if ($MOVEPRODUCT~PSCAN or (SECTOR.PLANETCOUNT[$MOVEPRODUCT~SOURCESECTOR] > 1))
      setvar $MOVEPRODUCT~SEND $MOVEPRODUCT~SEND&"l"&$MOVEPRODUCT~SOURCE&"*"
    else
      setvar $MOVEPRODUCT~SEND $MOVEPRODUCT~SEND&"l"
    end

    if (($MOVEPRODUCT~CYCLES = 1) and ($MOVEPRODUCT~REMAINDER > 0))
      setvar $MOVEPRODUCT~SEND $MOVEPRODUCT~SEND&$MOVEPRODUCT~PICKUPTEXT&$MOVEPRODUCT~REMAINDER&"*q"
    else
      setvar $MOVEPRODUCT~SEND $MOVEPRODUCT~SEND&$MOVEPRODUCT~PICKUPTEXT&"*q"
    end
  end


  setvar $MOVEPRODUCT~SEND $MOVEPRODUCT~SEND&"l"&$MOVEPRODUCT~DEST&"*"&$MOVEPRODUCT~DROPOFFTEXT&"*q"

  send $MOVEPRODUCT~SEND
  subtract $MOVEPRODUCT~CYCLES 1

  if (($MOVEPRODUCT~CYCLES = 1) and ($MOVEPRODUCT~REMAINDER > 0))
    add $MOVEPRODUCT~MOVED $MOVEPRODUCT~REMAINDER
  else
    add $MOVEPRODUCT~MOVED $MOVEPRODUCT~HOLDS
  end

  if ($MOVEPRODUCT~CYCLES <= 0)



    while ($MOVEPRODUCT~CLOCK < 4)
      waiton $MOVEPRODUCT~WAITTEXT
      add $MOVEPRODUCT~CLOCK 1
    end


    setvar $GAMEPREFS~BANK "MOVEPRODUCT"
    gosub :GAMEPREFS~SETGAMEPREFS

    send "l" $MOVEPRODUCT~DEST "*"
    waiton "Planet command (?=help)"

    gosub :MOVEPRODUCT~RESTOREHAGGLE
    return
  end

  if ($MOVEPRODUCT~CLOCK > 0)
    subtract $MOVEPRODUCT~CLOCK 1
  else
    if ($MOVEPRODUCT~SOURCE = "P")

      settextlinetrigger GETCREDITS :GETCREDITS "Your offer ["
      pause
      :MOVEPRODUCT~GETCREDITS
      getword CURRENTLINE $MOVEPRODUCT~OFFER 3
      striptext $MOVEPRODUCT~OFFER ","
      striptext $MOVEPRODUCT~OFFER "["
      striptext $MOVEPRODUCT~OFFER "]"
      subtract $MOVEPRODUCT~CREDITS $MOVEPRODUCT~OFFER

      if ($MOVEPRODUCT~CREDITS < 10000)

        setvar $MOVEPRODUCT~CYCLES 0
      end
    end
    waiton $MOVEPRODUCT~WAITTEXT
  end

  goto :CYCLE
end
:MOVEPRODUCT~RESTOREHAGGLE
if ($MOVEPRODUCT~RESTORE_HAGGLE = 1)
  autohaggle on
  setvar $MOVEPRODUCT~RESTORE_HAGGLE 0
end
return
:MOVEPRODUCT~SUB_LANDDEST


if ($MOVEPRODUCT~PSCAN or (SECTOR.PLANETCOUNT[$MOVEPRODUCT~DESTSECTOR] > 1))
  send "l " $MOVEPRODUCT~DEST "*"
else
  send "l "
end

return
:MOVEPRODUCT~SUB_LANDSOURCE

if ($MOVEPRODUCT~PSCAN or (SECTOR.PLANETCOUNT[$MOVEPRODUCT~SOURCESECTOR] > 1))
  send "l " $MOVEPRODUCT~SOURCE "*"
else
  send "l"
end

return
