#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
:PLANETHAGGLE~PLANETNEG
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
setvar $PLANETHAGGLE~OUTPUT_FILE ""
setvar $PLANETHAGGLE~SELLDELAY 0
setvar $PLANETHAGGLE~OREMCIC "-90"
setvar $PLANETHAGGLE~ORGMCIC "-75"
setvar $PLANETHAGGLE~EQUMCIC "-65"
setvar $PLANETHAGGLE~VERSION "3.0.0"
setvar $PLANETHAGGLE~STARTINGLOCATION $PLAYER~CURRENT_PROMPT

:PLANETHAGGLE~VERIFYPROMPT
if (($PLANETHAGGLE~STARTINGLOCATION <> "Citadel") and ($PLANETHAGGLE~STARTINGLOCATION <> "Planet"))
  setvar $PLANETHAGGLE~EXIT_MESSAGE "Must start at Citadel or Planet Prompt for Planet Nego"
  goto :EXITNEG
end

setvar $PLANETHAGGLE~_CK_PTRADESETTING $GAME~PTRADESETTING
setvar $PLANETHAGGLE~QUANTITYUNKNOWN 0

if ($PLANETHAGGLE~STARTINGLOCATION = "Citadel")
  send "Q"
elseif ($PLANETHAGGLE~STARTINGLOCATION = "Planet ")
  setvar $PLANETHAGGLE~STARTINGLOCATION "Planet"
end
gosub :PLANET~GETPLANETINFO
send "Q"
gosub :PLAYER~GETINFO
send "*"

send "|CR"&$PLAYER~CURRENT_SECTOR&"*"

settextlinetrigger FOUNDPORT :FOUNDPORT "Items     Status  Trading % of max OnBoard"
settextlinetrigger NOPORT :NOPORT "I have no information about a port in that sector."
settextlinetrigger NOPORT2 :NOPORT "You have never visted sector"
settextlinetrigger NOPORT3 :NOPORT "credits / next hold"
pause

:PLANETHAGGLE~NOPORT
send "Q|"
killtrigger FOUNDPORT
killtrigger NOPORT
killtrigger NOPORT2
killtrigger NOPORT3
gosub :NEGOTIATELAND
setvar $PLANETHAGGLE~EXIT_MESSAGE "No port to sell to"
goto :EXITNEG

:PLANETHAGGLE~FOUNDPORT
killtrigger FOUNDPORT
killtrigger NOPORT
killtrigger NOPORT2
killtrigger NOPORT3
settextlinetrigger PORTINFO1 :PORTINFO1 "Fuel Ore "
settextlinetrigger PORTINFO2 :PORTINFO2 "Organics"
settextlinetrigger PORTINFO3 :PORTINFO3 "Equipment"
settextlinetrigger GOTCR :GOTCR "Computer command [TL="
pause

:PLANETHAGGLE~PORTINFO1
getword CURRENTLINE $PLAYER~CURRENT_SECTOR.OREBUYING 3
getword CURRENTLINE $PLAYER~CURRENT_SECTOR.ORETRADING 4
getword CURRENTLINE $PLAYER~CURRENT_SECTOR.OREPERCENT 5
striptext $PLAYER~CURRENT_SECTOR.OREPERCENT "%"
pause

:PLANETHAGGLE~PORTINFO2
getword CURRENTLINE $PLAYER~CURRENT_SECTOR.ORGBUYING 2
getword CURRENTLINE $PLAYER~CURRENT_SECTOR.ORGTRADING 3
getword CURRENTLINE $PLAYER~CURRENT_SECTOR.ORGPERCENT 4
striptext $PLAYER~CURRENT_SECTOR.ORGPERCENT "%"
pause

:PLANETHAGGLE~PORTINFO3
getword CURRENTLINE $PLAYER~CURRENT_SECTOR.EQUBUYING 2
getword CURRENTLINE $PLAYER~CURRENT_SECTOR.EQUTRADING 3
getword CURRENTLINE $PLAYER~CURRENT_SECTOR.EQUPERCENT 4
striptext $PLAYER~CURRENT_SECTOR.EQUPERCENT "%"
send "Q|"
pause

:PLANETHAGGLE~GOTCR
killtrigger PORTINFO1
killtrigger PORTINFO2
killtrigger PORTINFO3
killtrigger GOTCR

setdelaytrigger JUSTASEC :JUSTASEC 200
pause

:PLANETHAGGLE~JUSTASEC
:PLANETHAGGLE~INITINFO

if ($PLAYER~TURNS <= 0)
  gosub :NEGOTIATELAND
  setvar $PLANETHAGGLE~EXIT_MESSAGE "I have no turns to negotiate this planet"
  goto :EXITNEG
end
if ($PLAYER~CREDITS > 900000000)
  gosub :NEGOTIATELAND
  setvar $PLANETHAGGLE~EXIT_MESSAGE "I have too much cash on hand"
  goto :EXITNEG
end

if ($PLANETHAGGLE~_CK_PNEGO_FUELTOSELL = "-1")
  setvar $PLANETHAGGLE~FUELTOSELL 0
elseif ($PLANETHAGGLE~_CK_PNEGO_FUELTOSELL = "max")
  setvar $PLANETHAGGLE~FUELTOSELL $PLANET~PLANETFUEL
else
  setvar $PLANETHAGGLE~FUELTOSELL $PLANETHAGGLE~_CK_PNEGO_FUELTOSELL

end
if ($PLANETHAGGLE~FUELTOSELL > $PLANET~PLANETFUEL)
  setvar $PLANETHAGGLE~FUELTOSELL $PLANET~PLANETFUEL
end

if ($PLANETHAGGLE~_CK_PNEGO_ORGTOSELL = "-1")
  setvar $PLANETHAGGLE~ORGTOSELL 0
elseif ($PLANETHAGGLE~_CK_PNEGO_ORGTOSELL = "max")
  setvar $PLANETHAGGLE~ORGTOSELL $PLANET~PLANETORG
else
  setvar $PLANETHAGGLE~ORGTOSELL $PLANETHAGGLE~_CK_PNEGO_ORGTOSELL

end
if ($PLANETHAGGLE~ORGTOSELL > $PLANET~PLANETORG)
  setvar $PLANETHAGGLE~ORGTOSELL $PLANET~PLANETORG
end

if ($PLANETHAGGLE~_CK_PNEGO_EQUIPTOSELL = "-1")
  setvar $PLANETHAGGLE~EQUIPTOSELL 0
elseif ($PLANETHAGGLE~_CK_PNEGO_EQUIPTOSELL = "max")
  setvar $PLANETHAGGLE~EQUIPTOSELL $PLANET~PLANETEQUIP
else
  setvar $PLANETHAGGLE~EQUIPTOSELL $PLANETHAGGLE~_CK_PNEGO_EQUIPTOSELL

end
if ($PLANETHAGGLE~EQUIPTOSELL > $PLANET~PLANETEQUIP)
  setvar $PLANETHAGGLE~EQUIPTOSELL $PLANET~PLANETEQUIP
end

if (($PLAYER~CURRENT_SECTOR.OREBUYING <> "Buying") or ($PLAYER~CURRENT_SECTOR.OREPERCENT < 15))
  setvar $PLANETHAGGLE~FUELTOSELL 0
end
if (($PLAYER~CURRENT_SECTOR.ORGBUYING <> "Buying") or ($PLAYER~CURRENT_SECTOR.ORGPERCENT < 15))
  setvar $PLANETHAGGLE~ORGTOSELL 0
end
if (($PLAYER~CURRENT_SECTOR.EQUBUYING <> "Buying") or ($PLAYER~CURRENT_SECTOR.EQUPERCENT < 15))
  setvar $PLANETHAGGLE~EQUIPTOSELL 0
end

:PLANETHAGGLE~SELLOFF
if (($PLANETHAGGLE~FUELTOSELL <> 0) or ($PLANETHAGGLE~ORGTOSELL <> 0) or ($PLANETHAGGLE~EQUIPTOSELL <> 0))
  setvar $PLANETHAGGLE~ORE_SELL_FAILURES 0
  setvar $PLANETHAGGLE~ORG_SELL_FAILURES 0
  setvar $PLANETHAGGLE~EQU_SELL_FAILURES 0
  setvar $PLANETHAGGLE~ORESELLOUTPUT ""
  setvar $PLANETHAGGLE~ORGSELLOUTPUT ""
  setvar $PLANETHAGGLE~EQUSELLOUTPUT ""
  setvar $PLANETHAGGLE~OREPROFIT 0
  setvar $PLANETHAGGLE~ORGPROFIT 0
  setvar $PLANETHAGGLE~EQUPROFIT 0

  send "|"
  gosub :SELL
  gosub :NEGOTIATELAND
  if ($PLANETHAGGLE~STARTINGLOCATION = "Citadel")

    if ($PLANETHAGGLE~OREPROFIT <> 0)
      send "TT"&$PLANETHAGGLE~OREPROFIT&"*"
      subtract $PLAYER~CREDITS $PLANETHAGGLE~OREPROFIT
    end
    if ($PLANETHAGGLE~ORGPROFIT <> 0)
      send "TT"&$PLANETHAGGLE~ORGPROFIT&"*"
      subtract $PLAYER~CREDITS $PLANETHAGGLE~ORGPROFIT
    end
    if ($PLANETHAGGLE~EQUPROFIT <> 0)
      send "TT"&$PLANETHAGGLE~EQUPROFIT&"*"
      subtract $PLAYER~CREDITS $PLANETHAGGLE~EQUPROFIT
    end
  end

  send "|"

  setvar $PLANETHAGGLE~GENERALOUTPUT "*Sector "&$PLAYER~CURRENT_SECTOR&"*"
  if ($PLANETHAGGLE~OUTPUT_FILE <> "")
    write $PLANETHAGGLE~OUTPUT_FILE $PLANETHAGGLE~GENERALOUTPUT
  end

  if ($PLANETHAGGLE~ORESELLOUTPUT <> "")

    setvar $SWITCHBOARD~MESSAGE "  *"&$PLANETHAGGLE~ORESELLOUTPUT
    if ($SWITCHBOARD~SELF_COMMAND <> TRUE)
      setvar $SWITCHBOARD~SELF_COMMAND 2
    end


    if ($PLANETHAGGLE~OUTPUT_FILE <> "")
      write $PLANETHAGGLE~OUTPUT_FILE $PLANETHAGGLE~ORESELLOUTPUT
    end
  end
  if ($PLANETHAGGLE~ORGSELLOUTPUT <> "")

    setvar $SWITCHBOARD~MESSAGE "  *"&$PLANETHAGGLE~ORGSELLOUTPUT
    if ($SWITCHBOARD~SELF_COMMAND <> TRUE)
      setvar $SWITCHBOARD~SELF_COMMAND 2
    end

    if ($PLANETHAGGLE~OUTPUT_FILE <> "")
      write $PLANETHAGGLE~OUTPUT_FILE $PLANETHAGGLE~ORGSELLOUTPUT
    end
  end
  if ($PLANETHAGGLE~EQUSELLOUTPUT <> "")

    setvar $SWITCHBOARD~MESSAGE "  *"&$PLANETHAGGLE~EQUSELLOUTPUT
    if ($SWITCHBOARD~SELF_COMMAND <> TRUE)
      setvar $SWITCHBOARD~SELF_COMMAND 2
    end

    if ($PLANETHAGGLE~OUTPUT_FILE <> "")
      write $PLANETHAGGLE~OUTPUT_FILE $PLANETHAGGLE~EQUSELLOUTPUT
    end
  end
  setvar $PLANETHAGGLE~EXIT_MESSAGE "Done with port"
  goto :EXITNEG
else
  gosub :NEGOTIATELAND
  setvar $PLANETHAGGLE~EXIT_MESSAGE "Nothing to sell"
  goto :EXITNEG
end

:PLANETHAGGLE~SELL
:PLANETHAGGLE~RESELL

if ($PLAYER~TURNS <= 0)
  send "'I'm out of turns*"
  return
end
setvar $PLANETHAGGLE~THISOREFAILED 0
setvar $PLANETHAGGLE~THISORGFAILED 0
setvar $PLANETHAGGLE~THISEQUFAILED 0
if ($PLANETHAGGLE~FUELTOSELL > 0)
  setvar $PLANETHAGGLE~ATTEMPTORE 1
  setvar $PLANETHAGGLE~ATTEMPTORECONFIRMED 0
end
if ($PLANETHAGGLE~ORGTOSELL > 0)
  setvar $PLANETHAGGLE~ATTEMPTORG 1
  setvar $PLANETHAGGLE~ATTEMPTORGCONFIRMED 0
end
if ($PLANETHAGGLE~EQUIPTOSELL > 0)
  setvar $PLANETHAGGLE~ATTEMPTEQU 1
  setvar $PLANETHAGGLE~ATTEMPTEQUCONFIRMED 0
end
isnumber $PLANETHAGGLE~NUMBER $PLANET~PLANET
setvar $PLANETHAGGLE~FINDPLANET 0
if ($PLANETHAGGLE~NUMBER = 0)
  send "PN"
  setvar $PLANETHAGGLE~FINDPLANET 1
else
  send "PN"
end

subtract $PLAYER~TURNS 1

:PLANETHAGGLE~GETPERCTS
settextlinetrigger OREPCT :OREPCT "Fuel Ore   Buying"
settextlinetrigger ORGPCT :ORGPCT "Organics   Buying"
settextlinetrigger EQUPCT :EQUPCT "Equipment  Buying"
settextlinetrigger GOTPERCTS :GOTPERCTS "Registry# and Planet Name"
pause

:PLANETHAGGLE~OREPCT
killtrigger OREPCT
killtrigger ORGPCT
killtrigger EQUPCT
killtrigger GOTPERCTS
getword CURRENTLINE $PLAYER~CURRENT_SECTOR.ORETRADING 4
getword CURRENTLINE $PLAYER~CURRENT_SECTOR.OREPERCENT 5
striptext $PLAYER~CURRENT_SECTOR.OREPERCENT "%"
if ($PLAYER~CURRENT_SECTOR.OREPERCENT < 100)
  add $PLAYER~CURRENT_SECTOR.OREPERCENT 1
end
goto :GETPERCTS

:PLANETHAGGLE~ORGPCT
killtrigger OREPCT
killtrigger ORGPCT
killtrigger EQUPCT
killtrigger GOTPERCTS
getword CURRENTLINE $PLAYER~CURRENT_SECTOR.ORGTRADING 3
getword CURRENTLINE $PLAYER~CURRENT_SECTOR.ORGPERCENT 4
striptext $PLAYER~CURRENT_SECTOR.ORGPERCENT "%"
if ($PLAYER~CURRENT_SECTOR.ORGPERCENT < 100)
  add $PLAYER~CURRENT_SECTOR.ORGPERCENT 1
end
goto :GETPERCTS

:PLANETHAGGLE~EQUPCT
killtrigger OREPCT
killtrigger ORGPCT
killtrigger EQUPCT
killtrigger GOTPERCTS
getword CURRENTLINE $PLAYER~CURRENT_SECTOR.EQUTRADING 3
getword CURRENTLINE $PLAYER~CURRENT_SECTOR.EQUPERCENT 4
striptext $PLAYER~CURRENT_SECTOR.EQUPERCENT "%"
if ($PLAYER~CURRENT_SECTOR.EQUPERCENT < 100)
  add $PLAYER~CURRENT_SECTOR.EQUPERCENT 1
end
goto :GETPERCTS

:PLANETHAGGLE~GOTPERCTS
isnumber $PLANETHAGGLE~TEST1 $PLAYER~CURRENT_SECTOR.ORETRADING
isnumber $PLANETHAGGLE~TEST2 $PLAYER~CURRENT_SECTOR.OREPERCENT
if (($PLANETHAGGLE~TEST1 = 0) or ($PLANETHAGGLE~TEST2 = 0))
  send "'DEBUG: NAN on oretrading:"&$PLANETHAGGLE~TEST1&" orepercent:" $PLANETHAGGLE~TEST2 "*"
  setvar $PLAYER~CURRENT_SECTOR.OREPERCENT 1
  setvar $PLAYER~CURRENT_SECTOR.ORETRADING 1
end
isnumber $PLANETHAGGLE~TEST3 $PLAYER~CURRENT_SECTOR.ORGTRADING
isnumber $PLANETHAGGLE~TEST4 $PLAYER~CURRENT_SECTOR.ORGPERCENT
if (($PLANETHAGGLE~TEST3 = 0) or ($PLANETHAGGLE~TEST2 = 0))
  send "'DEBUG: NAN on orgtrading:"&$PLANETHAGGLE~TEST3&" orgpercent:" $PLANETHAGGLE~TEST4 "*"
  setvar $PLAYER~CURRENT_SECTOR.ORGPERCENT 1
  setvar $PLAYER~CURRENT_SECTOR.ORGTRADING 1
end

isnumber $PLANETHAGGLE~TEST5 $PLAYER~CURRENT_SECTOR.EQUTRADING
isnumber $PLANETHAGGLE~TEST6 $PLAYER~CURRENT_SECTOR.EQUPERCENT
if (($PLANETHAGGLE~TEST5 = 0) or ($PLANETHAGGLE~TEST6 = 0))
  send "'DEBUG: NAN on equtrading:"&$PLANETHAGGLE~TEST5&" equpercent:" $PLANETHAGGLE~TEST6 "*"
  setvar $PLAYER~CURRENT_SECTOR.EQUPERCENT 1
  setvar $PLAYER~CURRENT_SECTOR.EQUTRADING 1
end
killtrigger OREPCT
killtrigger ORGPCT
killtrigger EQUPCT
killtrigger GOTPERCTS
if ($PLANETHAGGLE~FINDPLANET = 1)
  settextlinetrigger PLANETNUM :PLANETNUM "> "&$PLANET~PLANET
  setdelaytrigger NOPLANETNUM :NOPLANETNUM 3000
  pause
  :PLANETHAGGLE~NOPLANETNUM
  killalltriggers
  setvar $PLANETHAGGLE~EXIT_MESSAGE "Could not determine port number!"
  send "q*"
  goto :EXITNEG
  :PLANETHAGGLE~PLANETNUM
  killtrigger PLANETNUM
  killtrigger NOPLANETNUM
  getword CURRENTLINE $PLANET~PLANET 1
  striptext $PLANET~PLANET ">"
  send $PLANET~PLANET "*"
else
  send $PLANET~PLANET "*"
end

:PLANETHAGGLE~SELLPRODUCT
settexttrigger SELLFUEL :SELLFUEL "How many units of Fuel Ore"
settexttrigger SELLORG :SELLORG "How many units of Organics"
settexttrigger SELLEQU :SELLEQU "How many units of Equipment"
settexttrigger DONEWITHPORT :DONEWITHPORT "Command [TL="
killtrigger NOTOURS
settexttrigger NOTOURS :NOTOURS "You don't own that planet!  Were you expecting us to invade it?"
pause

:PLANETHAGGLE~NOTOURS
send "*"
setvar $PLANETHAGGLE~EXIT_MESSAGE "We don't own this planet!"
pause
:PLANETHAGGLE~SELLFUEL
killtrigger SELLFUEL
killtrigger SELLORG
killtrigger SELLEQU
killtrigger DONEWITHPORT
if ($PLANETHAGGLE~QUANTITYUNKNOWN = 1)
  getword CURRENTLINE $PLANETHAGGLE~FUELTOSELL 12
  striptext $PLANETHAGGLE~FUELTOSELL "["
  striptext $PLANETHAGGLE~FUELTOSELL "]"
  striptext $PLANETHAGGLE~FUELTOSELL "?"
end

isnumber $PLANETHAGGLE~TEST $PLANETHAGGLE~FUELTOSELL
if ($PLANETHAGGLE~TEST = 0)
  send "'DEBUG: NAN on fueltosell:"&$PLANETHAGGLE~FUELTOSELL "*"
  setvar $PLANETHAGGLE~FUELTOSELL 0
end
if (($PLAYER~CURRENT_SECTOR.OREPERCENT >= 15) and ($PLANETHAGGLE~FUELTOSELL > 0))
  if ($PLANETHAGGLE~FUELTOSELL > $PLAYER~CURRENT_SECTOR.ORETRADING)
    setvar $PLANETHAGGLE~FUELTOSELL $PLAYER~CURRENT_SECTOR.ORETRADING
  end
  setvar $PLANETHAGGLE~ATTEMPTORECONFIRMED 1
  setvar $PLANETHAGGLE~PRODTOSELL "ore"
  setvar $PLANETHAGGLE~PORTBUYING $PLANETHAGGLE~FUELTOSELL
  gosub :SELLHAGGLE
  if ($PLANETHAGGLE~CURRENTHAGGLE = "succeeded")
    setvar $PLANETHAGGLE~OREHAGGLE "succeeded"
    setvar $PLANETHAGGLE~FUELTOSELL 0
  else
    setvar $PLANETHAGGLE~OREHAGGLE "failed"
  end
else
  send "az0*"
  setvar $PLANETHAGGLE~FUELTOSELL 0
end
goto :SELLPRODUCT

:PLANETHAGGLE~SELLORG
killtrigger SELLFUEL
killtrigger SELLORG
killtrigger SELLEQU
killtrigger DONEWITHPORT
if ($PLANETHAGGLE~QUANTITYUNKNOWN = 1)
  getword CURRENTLINE $PLANETHAGGLE~ORGTOSELL 11
  striptext $PLANETHAGGLE~ORGTOSELL "["
  striptext $PLANETHAGGLE~ORGTOSELL "]"
  striptext $PLANETHAGGLE~ORGTOSELL "?"
end

isnumber $PLANETHAGGLE~TEST $PLANETHAGGLE~ORGTOSELL
if ($PLANETHAGGLE~TEST = 0)
  send "'DEBUG: NAN on orgtosell:"&$PLANETHAGGLE~ORGTOSELL "*"
  setvar $PLANETHAGGLE~ORGTOSELL 0
end
if (($PLAYER~CURRENT_SECTOR.ORGPERCENT >= 15) and ($PLANETHAGGLE~ORGTOSELL > 0))
  if ($PLANETHAGGLE~ORGTOSELL > $PLAYER~CURRENT_SECTOR.ORGTRADING)
    setvar $PLANETHAGGLE~ORGTOSELL $PLAYER~CURRENT_SECTOR.ORGTRADING
  end
  setvar $PLANETHAGGLE~ATTEMPTORGCONFIRMED 1
  setvar $PLANETHAGGLE~PRODTOSELL "org"
  setvar $PLANETHAGGLE~PORTBUYING $PLANETHAGGLE~ORGTOSELL
  gosub :SELLHAGGLE
  if ($PLANETHAGGLE~CURRENTHAGGLE = "succeeded")
    setvar $PLANETHAGGLE~ORGHAGGLE "succeeded"
    setvar $PLANETHAGGLE~ORGTOSELL 0
  else
    setvar $PLANETHAGGLE~ORGHAGGLE "failed"
  end
else
  send "az0*"
  setvar $PLANETHAGGLE~ORGTOSELL 0
end
goto :SELLPRODUCT

:PLANETHAGGLE~SELLEQU
killtrigger SELLFUEL
killtrigger SELLORG
killtrigger SELLEQU
killtrigger DONEWITHPORT
if ($PLANETHAGGLE~QUANTITYUNKNOWN = 1)
  getword CURRENTLINE $PLANETHAGGLE~EQUIPTOSELL 11
  striptext $PLANETHAGGLE~EQUIPTOSELL "["
  striptext $PLANETHAGGLE~EQUIPTOSELL "]"
  striptext $PLANETHAGGLE~EQUIPTOSELL "?"
end

isnumber $PLANETHAGGLE~TEST $PLANETHAGGLE~EQUIPTOSELL
if ($PLANETHAGGLE~TEST = 0)
  send "'DEBUG: NAN on equiptosell:"&$PLANETHAGGLE~EQUIPTOSELL "*"
  setvar $PLANETHAGGLE~EQUIPTOSELL 0
end
if (($PLAYER~CURRENT_SECTOR.EQUPERCENT >= 15) and ($PLANETHAGGLE~EQUIPTOSELL > 0))
  if ($PLANETHAGGLE~EQUIPTOSELL > $PLAYER~CURRENT_SECTOR.EQUTRADING)
    setvar $PLANETHAGGLE~EQUIPTOSELL $PLAYER~CURRENT_SECTOR.EQUTRADING
  end
  setvar $PLANETHAGGLE~ATTEMPTEQUCONFIRMED 1
  setvar $PLANETHAGGLE~PRODTOSELL "equ"
  setvar $PLANETHAGGLE~PORTBUYING $PLANETHAGGLE~EQUIPTOSELL
  gosub :SELLHAGGLE
  if ($PLANETHAGGLE~CURRENTHAGGLE = "succeeded")
    setvar $PLANETHAGGLE~EQUHAGGLE "succeeded"
    setvar $PLANETHAGGLE~EQUIPTOSELL 0
  else
    setvar $PLANETHAGGLE~EQUHAGGLE "failed"
  end
else
  send "az0*"
  setvar $PLANETHAGGLE~EQUIPTOSELL 0
end
goto :SELLPRODUCT

:PLANETHAGGLE~DONEWITHPORT
killtrigger SELLFUEL
killtrigger SELLORG
killtrigger SELLEQU
killtrigger DONEWITHPORT

if (($PLANETHAGGLE~ATTEMPTORE = 1) and ($PLANETHAGGLE~ATTEMPTORECONFIRMED = 0))

  setvar $PLANETHAGGLE~FUELTOSELL 0
end
if (($PLANETHAGGLE~ATTEMPTORG = 1) and ($PLANETHAGGLE~ATTEMPTORGCONFIRMED = 0))
  setvar $PLANETHAGGLE~ORGTOSELL 0
end
if (($PLANETHAGGLE~ATTEMPTEQU = 1) and ($PLANETHAGGLE~ATTEMPTEQUCONFIRMED = 0))
  setvar $PLANETHAGGLE~EQUIPTOSELL 0
end

if (($PLANETHAGGLE~ORE_SELL_FAILURES > 1) or ($PLANETHAGGLE~ORG_SELL_FAILURES > 4) or ($PLANETHAGGLE~EQU_SELL_FAILURES > 4))
  setvar $PLANETHAGGLE~SELLOUTPUT $PLANETHAGGLE~SELLOUTPUT&"Multiple Haggle Failures - Please cut and paste this haggling session and email to Cherokee*"
  return
elseif (($PLANETHAGGLE~FUELTOSELL = 0) and (($PLANETHAGGLE~ORGTOSELL = 0) and ($PLANETHAGGLE~EQUIPTOSELL = 0)))
  if (($PLANETHAGGLE~ATTEMPTORECONFIRMED = 0) and (($PLANETHAGGLE~ATTEMPTORGCONFIRMED = 0) and ($PLANETHAGGLE~ATTEMPTEQUCONFIRMED = 0)))
    setvar $PLANETHAGGLE~EXIT_MESSAGE "Nothing to sell here!"
  end
  return
else
  goto :RESELL
end

:PLANETHAGGLE~SELLHAGGLE
if (HAGGLE)
  goto :PLANETHAGGLE~SELLHAGGLENATIVE
end

killalltriggers
settextlinetrigger SELLFIRSTOFFER :SELLFIRSTOFFER "We'll buy them for"
send "az"&$PLANETHAGGLE~PORTBUYING&"*"
pause

:PLANETHAGGLE~SELLHAGGLENATIVE
setvar $PLANETHAGGLE~CURRENTHAGGLE "pending"
setvar $PLANETHAGGLE~OLDCREDITS $PLAYER~CREDITS
setvar $PLANETHAGGLE~MCIC ""
send $PLANETHAGGLE~PORTBUYING&"*"

:PLANETHAGGLE~SELLHAGGLENATIVEWAIT
killalltriggers
settextlinetrigger NATIVESELLEXPERIENCE :PLANETHAGGLE~NATIVESELLEXPERIENCE "experience point(s)"
settextlinetrigger NATIVESELLYOUHAVE :PLANETHAGGLE~NATIVESELLYOUHAVE "You have"
settextlinetrigger NATIVESELLNOTINTERESTED :PLANETHAGGLE~NATIVESELLNOTINTERESTED "We're not interested."
settextlinetrigger NATIVESELLPROMPT :PLANETHAGGLE~NATIVESELLPROMPT "Command [TL="
pause

:PLANETHAGGLE~NATIVESELLEXPERIENCE
killalltriggers
getword CURRENTLINE $PLANETHAGGLE~EXP_BONUS 7
isnumber $PLANETHAGGLE~TESTEXP $PLANETHAGGLE~EXP_BONUS
if ($PLANETHAGGLE~TESTEXP <> 0)
  add $PLANETHAGGLE~EXPERIENCE $PLANETHAGGLE~EXP_BONUS
end
goto :PLANETHAGGLE~SELLHAGGLENATIVEWAIT

:PLANETHAGGLE~NATIVESELLYOUHAVE
killalltriggers
getword CURRENTLINE $PLANETHAGGLE~CREDITS 3
striptext $PLANETHAGGLE~CREDITS ","
isnumber $PLANETHAGGLE~TESTCREDITS $PLANETHAGGLE~CREDITS
if ($PLANETHAGGLE~TESTCREDITS = 0)
  goto :PLANETHAGGLE~SELLHAGGLENATIVEWAIT
end
getword CURRENTLINE $PLANETHAGGLE~CREDITLABEL 4
if ($PLANETHAGGLE~CREDITLABEL <> "credits.")
  goto :PLANETHAGGLE~SELLHAGGLENATIVEWAIT
end
setvar $PLANETHAGGLE~COUNTER $PLANETHAGGLE~CREDITS
subtract $PLANETHAGGLE~COUNTER $PLANETHAGGLE~OLDCREDITS
setvar $PLAYER~CREDITS $PLANETHAGGLE~CREDITS
if ($PLANETHAGGLE~COUNTER <= 0)
  setvar $PLANETHAGGLE~CURRENTHAGGLE "failed"
  goto :SELLHAGGLEFAILED
end
setvar $PLANETHAGGLE~CURRENTHAGGLE "succeeded"
gosub :PLANETHAGGLE~LOADNATIVEMCIC
goto :SELLHAGGLESUCCEEDED

:PLANETHAGGLE~NATIVESELLNOTINTERESTED
killalltriggers
setvar $PLANETHAGGLE~CURRENTHAGGLE "failed"
goto :SELLHAGGLEFAILED

:PLANETHAGGLE~NATIVESELLPROMPT
killalltriggers
if ($PLANETHAGGLE~CURRENTHAGGLE <> "succeeded")
  setvar $PLANETHAGGLE~CURRENTHAGGLE "failed"
  goto :SELLHAGGLEFAILED
end
return

:PLANETHAGGLE~LOADNATIVEMCIC
setvar $PLANETHAGGLE~MCIC $HAGGLE~MCIC
isnumber $PLANETHAGGLE~MCICVALID $PLANETHAGGLE~MCIC
if ($PLANETHAGGLE~MCICVALID = 0)
  if ($PLANETHAGGLE~PRODTOSELL = "ore")
    getsectorparameter $PLAYER~CURRENT_SECTOR "OREMCIC" $PLANETHAGGLE~MCIC
  elseif ($PLANETHAGGLE~PRODTOSELL = "org")
    getsectorparameter $PLAYER~CURRENT_SECTOR "ORGMCIC" $PLANETHAGGLE~MCIC
  elseif ($PLANETHAGGLE~PRODTOSELL = "equ")
    getsectorparameter $PLAYER~CURRENT_SECTOR "EQUMCIC" $PLANETHAGGLE~MCIC
  end
  isnumber $PLANETHAGGLE~MCICVALID $PLANETHAGGLE~MCIC
end
if ($PLANETHAGGLE~MCICVALID = 0)
  if ($PLANETHAGGLE~PRODTOSELL = "ore")
    setvar $PLANETHAGGLE~MCIC $PLANETHAGGLE~OREMCIC
  elseif ($PLANETHAGGLE~PRODTOSELL = "org")
    setvar $PLANETHAGGLE~MCIC $PLANETHAGGLE~ORGMCIC
  elseif ($PLANETHAGGLE~PRODTOSELL = "equ")
    setvar $PLANETHAGGLE~MCIC $PLANETHAGGLE~EQUMCIC
  end
  isnumber $PLANETHAGGLE~MCICVALID $PLANETHAGGLE~MCIC
end
if ($PLANETHAGGLE~MCICVALID <> 0)
  if ($PLANETHAGGLE~PRODTOSELL = "ore")
    setvar $PLANETHAGGLE~OREMCIC $PLANETHAGGLE~MCIC
    setsectorparameter $PLAYER~CURRENT_SECTOR "OREMCIC" $PLANETHAGGLE~MCIC
  elseif ($PLANETHAGGLE~PRODTOSELL = "org")
    setvar $PLANETHAGGLE~ORGMCIC $PLANETHAGGLE~MCIC
    setsectorparameter $PLAYER~CURRENT_SECTOR "ORGMCIC" $PLANETHAGGLE~MCIC
  elseif ($PLANETHAGGLE~PRODTOSELL = "equ")
    setvar $PLANETHAGGLE~EQUMCIC $PLANETHAGGLE~MCIC
    setsectorparameter $PLAYER~CURRENT_SECTOR "EQUMCIC" $PLANETHAGGLE~MCIC
  end
end
return

:PLANETHAGGLE~SELLFIRSTOFFER
killtrigger SELLFIRSTOFFER
getword CURRENTLINE $PLANETHAGGLE~OFFER 5
striptext $PLANETHAGGLE~OFFER ","

gosub :PLAYER~SWATHOFF
if ($PLAYER~SWATHOFF = FALSE)
  gosub :NEGOTIATELAND
  setvar $PLANETHAGGLE~EXIT_MESSAGE $PLAYER~SWATHOFFMESSAGE
  goto :EXITNEG
end

setvar $PLANETHAGGLE~PERUNITINITOFFER $PLANETHAGGLE~OFFER
multiply $PLANETHAGGLE~PERUNITINITOFFER 100
divide $PLANETHAGGLE~PERUNITINITOFFER $PLANETHAGGLE~_CK_PTRADESETTING
multiply $PLANETHAGGLE~PERUNITINITOFFER 100
divide $PLANETHAGGLE~PERUNITINITOFFER $PLANETHAGGLE~PORTBUYING
setvar $PLANETHAGGLE~PORTMAXINIT $PLANETHAGGLE~PERUNITINITOFFER
divide $PLANETHAGGLE~PERUNITINITOFFER 10

if ($PLANETHAGGLE~PRODTOSELL = "ore")
  setvar $PLANETHAGGLE~BASEVALUE 256055800
  setvar $PLANETHAGGLE~BASEPERCENT 11725
  setvar $PLANETHAGGLE~BASEPERCENTINVERSE 88275
  setvar $PLANETHAGGLE~PERCENTFROMBASE $PLAYER~CURRENT_SECTOR.OREPERCENT
elseif ($PLANETHAGGLE~PRODTOSELL = "org")
  setvar $PLANETHAGGLE~BASEVALUE 506276400
  setvar $PLANETHAGGLE~BASEPERCENT 11287
  setvar $PLANETHAGGLE~BASEPERCENTINVERSE 88713
  setvar $PLANETHAGGLE~PERCENTFROMBASE $PLAYER~CURRENT_SECTOR.ORGPERCENT
elseif ($PLANETHAGGLE~PRODTOSELL = "equ")
  setvar $PLANETHAGGLE~BASEVALUE 906281000
  setvar $PLANETHAGGLE~BASEPERCENT 10989
  setvar $PLANETHAGGLE~BASEPERCENTINVERSE 89010
  setvar $PLANETHAGGLE~PERCENTFROMBASE $PLAYER~CURRENT_SECTOR.EQUPERCENT
end

if ($PLANETHAGGLE~PERCENTFROMBASE = 100)
  divide $PLANETHAGGLE~PORTMAXINIT 10
elseif ($PLANETHAGGLE~PERCENTFROMBASE >= 15)
  multiply $PLANETHAGGLE~PORTMAXINIT 100000
  subtract $PLANETHAGGLE~PORTMAXINIT $PLANETHAGGLE~BASEVALUE
  multiply $PLANETHAGGLE~PERCENTFROMBASE 1000
  subtract $PLANETHAGGLE~PERCENTFROMBASE $PLANETHAGGLE~BASEPERCENT
  divide $PLANETHAGGLE~PORTMAXINIT $PLANETHAGGLE~PERCENTFROMBASE
  multiply $PLANETHAGGLE~PORTMAXINIT $PLANETHAGGLE~BASEPERCENTINVERSE
  add $PLANETHAGGLE~PORTMAXINIT $PLANETHAGGLE~BASEVALUE
  divide $PLANETHAGGLE~PORTMAXINIT 1000000
elseif ($PLANETHAGGLE~PRODTOSELL = "ore")
  setvar $PLANETHAGGLE~PORTMAXINIT 340
elseif ($PLANETHAGGLE~PRODTOSELL = "org")
  setvar $PLANETHAGGLE~PORTMAXINIT 635
elseif ($PLANETHAGGLE~PRODTOSELL = "equ")
  setvar $PLANETHAGGLE~PORTMAXINIT 1063
end

if ($PLANETHAGGLE~PRODTOSELL = "ore")
  if ($PLANETHAGGLE~PORTMAXINIT >= 436)
    setvar $PLANETHAGGLE~MCIC "-90"
    setvar $PLANETHAGGLE~MULTIPLE 1494
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 434)
    setvar $PLANETHAGGLE~MCIC "-89"
    setvar $PLANETHAGGLE~MULTIPLE 1488
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 433)
    setvar $PLANETHAGGLE~MCIC "-88"
    setvar $PLANETHAGGLE~MULTIPLE 1482
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 431)
    setvar $PLANETHAGGLE~MCIC "-87"
    setvar $PLANETHAGGLE~MULTIPLE 1476
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 429)
    setvar $PLANETHAGGLE~MCIC "-86"
    setvar $PLANETHAGGLE~MULTIPLE 1470
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 427)
    setvar $PLANETHAGGLE~MCIC "-85"
    setvar $PLANETHAGGLE~MULTIPLE 1464
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 425)
    setvar $PLANETHAGGLE~MCIC "-84"
    setvar $PLANETHAGGLE~MULTIPLE 1458
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 424)
    setvar $PLANETHAGGLE~MCIC "-83"
    setvar $PLANETHAGGLE~MULTIPLE 1452
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 422)
    setvar $PLANETHAGGLE~MCIC "-82"
    setvar $PLANETHAGGLE~MULTIPLE 1446
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 420)
    setvar $PLANETHAGGLE~MCIC "-81"
    setvar $PLANETHAGGLE~MULTIPLE 1440
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 418)
    setvar $PLANETHAGGLE~MCIC "-80"
    setvar $PLANETHAGGLE~MULTIPLE 1434
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 416)
    setvar $PLANETHAGGLE~MCIC "-79"
    setvar $PLANETHAGGLE~MULTIPLE 1428
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 414)
    setvar $PLANETHAGGLE~MCIC "-78"
    setvar $PLANETHAGGLE~MULTIPLE 1423
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 412)
    setvar $PLANETHAGGLE~MCIC "-77"
    setvar $PLANETHAGGLE~MULTIPLE 1417
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 411)
    setvar $PLANETHAGGLE~MCIC "-76"
    setvar $PLANETHAGGLE~MULTIPLE 1411
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 409)
    setvar $PLANETHAGGLE~MCIC "-75"
    setvar $PLANETHAGGLE~MULTIPLE 1405
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 407)
    setvar $PLANETHAGGLE~MCIC "-74"
    setvar $PLANETHAGGLE~MULTIPLE 1399
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 405)
    setvar $PLANETHAGGLE~MCIC "-73"
    setvar $PLANETHAGGLE~MULTIPLE 1393
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 403)
    setvar $PLANETHAGGLE~MCIC "-72"
    setvar $PLANETHAGGLE~MULTIPLE 1387
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 401)
    setvar $PLANETHAGGLE~MCIC "-71"
    setvar $PLANETHAGGLE~MULTIPLE 1381
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 399)
    setvar $PLANETHAGGLE~MCIC "-70"
    setvar $PLANETHAGGLE~MULTIPLE 1375
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 397)
    setvar $PLANETHAGGLE~MCIC "-69"
    setvar $PLANETHAGGLE~MULTIPLE 1369
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 396)
    setvar $PLANETHAGGLE~MCIC "-68"
    setvar $PLANETHAGGLE~MULTIPLE 1363
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 394)
    setvar $PLANETHAGGLE~MCIC "-67"
    setvar $PLANETHAGGLE~MULTIPLE 1357
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 392)
    setvar $PLANETHAGGLE~MCIC "-66"
    setvar $PLANETHAGGLE~MULTIPLE 1351
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 390)
    setvar $PLANETHAGGLE~MCIC "-65"
    setvar $PLANETHAGGLE~MULTIPLE 1345
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 388)
    setvar $PLANETHAGGLE~MCIC "-64"
    setvar $PLANETHAGGLE~MULTIPLE 1341
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 386)
    setvar $PLANETHAGGLE~MCIC "-63"
    setvar $PLANETHAGGLE~MULTIPLE 1336
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 384)
    setvar $PLANETHAGGLE~MCIC "-62"
    setvar $PLANETHAGGLE~MULTIPLE 1330
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 382)
    setvar $PLANETHAGGLE~MCIC "-61"
    setvar $PLANETHAGGLE~MULTIPLE 1324
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 380)
    setvar $PLANETHAGGLE~MCIC "-60"
    setvar $PLANETHAGGLE~MULTIPLE 1318
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 378)
    setvar $PLANETHAGGLE~MCIC "-59"
    setvar $PLANETHAGGLE~MULTIPLE 1312
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 376)
    setvar $PLANETHAGGLE~MCIC "-58"
    setvar $PLANETHAGGLE~MULTIPLE 1306
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 374)
    setvar $PLANETHAGGLE~MCIC "-57"
    setvar $PLANETHAGGLE~MULTIPLE 1300
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 372)
    setvar $PLANETHAGGLE~MCIC "-56"
    setvar $PLANETHAGGLE~MULTIPLE 1294
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 370)
    setvar $PLANETHAGGLE~MCIC "-55"
    setvar $PLANETHAGGLE~MULTIPLE 1291
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 368)
    setvar $PLANETHAGGLE~MCIC "-54"
    setvar $PLANETHAGGLE~MULTIPLE 1285
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 366)
    setvar $PLANETHAGGLE~MCIC "-53"
    setvar $PLANETHAGGLE~MULTIPLE 1279
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 364)
    setvar $PLANETHAGGLE~MCIC "-52"
    setvar $PLANETHAGGLE~MULTIPLE 1273
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 362)
    setvar $PLANETHAGGLE~MCIC "-51"
    setvar $PLANETHAGGLE~MULTIPLE 1267
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 360)
    setvar $PLANETHAGGLE~MCIC "-50"
    setvar $PLANETHAGGLE~MULTIPLE 1261
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 358)
    setvar $PLANETHAGGLE~MCIC "-49"
    setvar $PLANETHAGGLE~MULTIPLE 1255
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 356)
    setvar $PLANETHAGGLE~MCIC "-48"
    setvar $PLANETHAGGLE~MULTIPLE 1249
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 354)
    setvar $PLANETHAGGLE~MCIC "-46"
    setvar $PLANETHAGGLE~MULTIPLE 1246
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 352)
    setvar $PLANETHAGGLE~MCIC "-46"
    setvar $PLANETHAGGLE~MULTIPLE 1240
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 350)
    setvar $PLANETHAGGLE~MCIC "-45"
    setvar $PLANETHAGGLE~MULTIPLE 1234
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 348)
    setvar $PLANETHAGGLE~MCIC "-44"
    setvar $PLANETHAGGLE~MULTIPLE 1228
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 346)
    setvar $PLANETHAGGLE~MCIC "-43"
    setvar $PLANETHAGGLE~MULTIPLE 1222
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 344)
    setvar $PLANETHAGGLE~MCIC "-42"
    setvar $PLANETHAGGLE~MULTIPLE 1219
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 342)
    setvar $PLANETHAGGLE~MCIC "-41"
    setvar $PLANETHAGGLE~MULTIPLE 1209
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 340)
    setvar $PLANETHAGGLE~MCIC "-40"
    setvar $PLANETHAGGLE~MULTIPLE 1208
  else
    setvar $PLANETHAGGLE~MCIC 0
    setvar $PLANETHAGGLE~MULTIPLE 1208
  end
elseif ($PLANETHAGGLE~PRODTOSELL = "org")
  if ($PLANETHAGGLE~PORTMAXINIT >= 813)
    setvar $PLANETHAGGLE~MCIC "-75"
    setvar $PLANETHAGGLE~MULTIPLE 1405
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 810)
    setvar $PLANETHAGGLE~MCIC "-74"
    setvar $PLANETHAGGLE~MULTIPLE 1399
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 806)
    setvar $PLANETHAGGLE~MCIC "-73"
    setvar $PLANETHAGGLE~MULTIPLE 1393
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 802)
    setvar $PLANETHAGGLE~MCIC "-72"
    setvar $PLANETHAGGLE~MULTIPLE 1387
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 798)
    setvar $PLANETHAGGLE~MCIC "-71"
    setvar $PLANETHAGGLE~MULTIPLE 1381
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 795)
    setvar $PLANETHAGGLE~MCIC "-70"
    setvar $PLANETHAGGLE~MULTIPLE 1375
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 791)
    setvar $PLANETHAGGLE~MCIC "-69"
    setvar $PLANETHAGGLE~MULTIPLE 1369
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 787)
    setvar $PLANETHAGGLE~MCIC "-68"
    setvar $PLANETHAGGLE~MULTIPLE 1363
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 783)
    setvar $PLANETHAGGLE~MCIC "-67"
    setvar $PLANETHAGGLE~MULTIPLE 1357
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 779)
    setvar $PLANETHAGGLE~MCIC "-66"
    setvar $PLANETHAGGLE~MULTIPLE 1351
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 775)
    setvar $PLANETHAGGLE~MCIC "-65"
    setvar $PLANETHAGGLE~MULTIPLE 1345
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 772)
    setvar $PLANETHAGGLE~MCIC "-64"
    setvar $PLANETHAGGLE~MULTIPLE 1339
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 768)
    setvar $PLANETHAGGLE~MCIC "-63"
    setvar $PLANETHAGGLE~MULTIPLE 1336
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 764)
    setvar $PLANETHAGGLE~MCIC "-62"
    setvar $PLANETHAGGLE~MULTIPLE 1330
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 760)
    setvar $PLANETHAGGLE~MCIC "-61"
    setvar $PLANETHAGGLE~MULTIPLE 1324
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 756)
    setvar $PLANETHAGGLE~MCIC "-60"
    setvar $PLANETHAGGLE~MULTIPLE 1318
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 752)
    setvar $PLANETHAGGLE~MCIC "-59"
    setvar $PLANETHAGGLE~MULTIPLE 1312
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 748)
    setvar $PLANETHAGGLE~MCIC "-58"
    setvar $PLANETHAGGLE~MULTIPLE 1306
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 744)
    setvar $PLANETHAGGLE~MCIC "-57"
    setvar $PLANETHAGGLE~MULTIPLE 1300
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 740)
    setvar $PLANETHAGGLE~MCIC "-56"
    setvar $PLANETHAGGLE~MULTIPLE 1294
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 737)
    setvar $PLANETHAGGLE~MCIC "-55"
    setvar $PLANETHAGGLE~MULTIPLE 1291
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 733)
    setvar $PLANETHAGGLE~MCIC "-54"
    setvar $PLANETHAGGLE~MULTIPLE 1285
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 729)
    setvar $PLANETHAGGLE~MCIC "-53"
    setvar $PLANETHAGGLE~MULTIPLE 1279
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 725)
    setvar $PLANETHAGGLE~MCIC "-52"
    setvar $PLANETHAGGLE~MULTIPLE 1273
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 721)
    setvar $PLANETHAGGLE~MCIC "-51"
    setvar $PLANETHAGGLE~MULTIPLE 1267
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 717)
    setvar $PLANETHAGGLE~MCIC "-50"
    setvar $PLANETHAGGLE~MULTIPLE 1261
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 713)
    setvar $PLANETHAGGLE~MCIC "-49"
    setvar $PLANETHAGGLE~MULTIPLE 1255
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 709)
    setvar $PLANETHAGGLE~MCIC "-48"
    setvar $PLANETHAGGLE~MULTIPLE 1252
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 705)
    setvar $PLANETHAGGLE~MCIC "-47"
    setvar $PLANETHAGGLE~MULTIPLE 1246
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 701)
    setvar $PLANETHAGGLE~MCIC "-46"
    setvar $PLANETHAGGLE~MULTIPLE 1236
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 697)
    setvar $PLANETHAGGLE~MCIC "-45"
    setvar $PLANETHAGGLE~MULTIPLE 1233
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 693)
    setvar $PLANETHAGGLE~MCIC "-44"
    setvar $PLANETHAGGLE~MULTIPLE 1227
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 688)
    setvar $PLANETHAGGLE~MCIC "-43"
    setvar $PLANETHAGGLE~MULTIPLE 1224
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 684)
    setvar $PLANETHAGGLE~MCIC "-42"
    setvar $PLANETHAGGLE~MULTIPLE 1214
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 680)
    setvar $PLANETHAGGLE~MCIC "-41"
    setvar $PLANETHAGGLE~MULTIPLE 1213
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 676)
    setvar $PLANETHAGGLE~MCIC "-40"
    setvar $PLANETHAGGLE~MULTIPLE 1203
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 672)
    setvar $PLANETHAGGLE~MCIC "-39"
    setvar $PLANETHAGGLE~MULTIPLE 1200
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 668)
    setvar $PLANETHAGGLE~MCIC "-38"
    setvar $PLANETHAGGLE~MULTIPLE 1194
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 664)
    setvar $PLANETHAGGLE~MCIC "-37"
    setvar $PLANETHAGGLE~MULTIPLE 1191
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 660)
    setvar $PLANETHAGGLE~MCIC "-36"
    setvar $PLANETHAGGLE~MULTIPLE 1181
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 656)
    setvar $PLANETHAGGLE~MCIC "-35"
    setvar $PLANETHAGGLE~MULTIPLE 1178
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 651)
    setvar $PLANETHAGGLE~MCIC "-34"
    setvar $PLANETHAGGLE~MULTIPLE 1172
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 647)
    setvar $PLANETHAGGLE~MCIC "-33"
    setvar $PLANETHAGGLE~MULTIPLE 1166
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 643)
    setvar $PLANETHAGGLE~MCIC "-32"
    setvar $PLANETHAGGLE~MULTIPLE 1160
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 639)
    setvar $PLANETHAGGLE~MCIC "-31"
    setvar $PLANETHAGGLE~MULTIPLE 1157
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 635)
    setvar $PLANETHAGGLE~MCIC "-30"
    setvar $PLANETHAGGLE~MULTIPLE 1154
  else
    setvar $PLANETHAGGLE~MCIC 0
    setvar $PLANETHAGGLE~MULTIPLE 1154
  end
elseif ($PLANETHAGGLE~PRODTOSELL = "equ")
  if ($PLANETHAGGLE~PORTMAXINIT >= 1393)
    setvar $PLANETHAGGLE~MCIC "-65"
    setvar $PLANETHAGGLE~MULTIPLE 1347
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 1386)
    setvar $PLANETHAGGLE~MCIC "-64"
    setvar $PLANETHAGGLE~MULTIPLE 1341
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 1379)
    setvar $PLANETHAGGLE~MCIC "-63"
    setvar $PLANETHAGGLE~MULTIPLE 1336
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 1372)
    setvar $PLANETHAGGLE~MCIC "-62"
    setvar $PLANETHAGGLE~MULTIPLE 1330
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 1365)
    setvar $PLANETHAGGLE~MCIC "-61"
    setvar $PLANETHAGGLE~MULTIPLE 1324
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 1358)
    setvar $PLANETHAGGLE~MCIC "-60"
    setvar $PLANETHAGGLE~MULTIPLE 1319
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 1351)
    setvar $PLANETHAGGLE~MCIC "-59"
    setvar $PLANETHAGGLE~MULTIPLE 1313
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 1344)
    setvar $PLANETHAGGLE~MCIC "-58"
    setvar $PLANETHAGGLE~MULTIPLE 1307
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 1337)
    setvar $PLANETHAGGLE~MCIC "-57"
    setvar $PLANETHAGGLE~MULTIPLE 1302
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 1329)
    setvar $PLANETHAGGLE~MCIC "-56"
    setvar $PLANETHAGGLE~MULTIPLE 1296
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 1323)
    setvar $PLANETHAGGLE~MCIC "-55"
    setvar $PLANETHAGGLE~MULTIPLE 1291
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 1315)
    setvar $PLANETHAGGLE~MCIC "-54"
    setvar $PLANETHAGGLE~MULTIPLE 1285
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 1308)
    setvar $PLANETHAGGLE~MCIC "-53"
    setvar $PLANETHAGGLE~MULTIPLE 1279
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 1301)
    setvar $PLANETHAGGLE~MCIC "-52"
    setvar $PLANETHAGGLE~MULTIPLE 1274
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 1294)
    setvar $PLANETHAGGLE~MCIC "-51"
    setvar $PLANETHAGGLE~MULTIPLE 1268
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 1287)
    setvar $PLANETHAGGLE~MCIC "-50"
    setvar $PLANETHAGGLE~MULTIPLE 1262
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 1279)
    setvar $PLANETHAGGLE~MCIC "-49"
    setvar $PLANETHAGGLE~MULTIPLE 1254
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 1272)
    setvar $PLANETHAGGLE~MCIC "-48"
    setvar $PLANETHAGGLE~MULTIPLE 1247
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 1265)
    setvar $PLANETHAGGLE~MCIC "-47"
    setvar $PLANETHAGGLE~MULTIPLE 1246
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 1258)
    setvar $PLANETHAGGLE~MCIC "-46"
    setvar $PLANETHAGGLE~MULTIPLE 1241
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 1251)
    setvar $PLANETHAGGLE~MCIC "-45"
    setvar $PLANETHAGGLE~MULTIPLE 1235
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 1243)
    setvar $PLANETHAGGLE~MCIC "-44"
    setvar $PLANETHAGGLE~MULTIPLE 1229
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 1236)
    setvar $PLANETHAGGLE~MCIC "-43"
    setvar $PLANETHAGGLE~MULTIPLE 1224
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 1229)
    setvar $PLANETHAGGLE~MCIC "-42"
    setvar $PLANETHAGGLE~MULTIPLE 1218
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 1221)
    setvar $PLANETHAGGLE~MCIC "-41"
    setvar $PLANETHAGGLE~MULTIPLE 1213
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 1214)
    setvar $PLANETHAGGLE~MCIC "-40"
    setvar $PLANETHAGGLE~MULTIPLE 1208
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 1206)
    setvar $PLANETHAGGLE~MCIC "-39"
    setvar $PLANETHAGGLE~MULTIPLE 1201
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 1199)
    setvar $PLANETHAGGLE~MCIC "-38"
    setvar $PLANETHAGGLE~MULTIPLE 1196
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 1192)
    setvar $PLANETHAGGLE~MCIC "-37"
    setvar $PLANETHAGGLE~MULTIPLE 1190
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 1184)
    setvar $PLANETHAGGLE~MCIC "-36"
    setvar $PLANETHAGGLE~MULTIPLE 1185
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 1177)
    setvar $PLANETHAGGLE~MCIC "-35"
    setvar $PLANETHAGGLE~MULTIPLE 1180
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 1169)
    setvar $PLANETHAGGLE~MCIC "-34"
    setvar $PLANETHAGGLE~MULTIPLE 1174
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 1162)
    setvar $PLANETHAGGLE~MCIC "-33"
    setvar $PLANETHAGGLE~MULTIPLE 1169
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 1154)
    setvar $PLANETHAGGLE~MCIC "-32"
    setvar $PLANETHAGGLE~MULTIPLE 1164
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 1147)
    setvar $PLANETHAGGLE~MCIC "-31"
    setvar $PLANETHAGGLE~MULTIPLE 1158
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 1139)
    setvar $PLANETHAGGLE~MCIC "-30"
    setvar $PLANETHAGGLE~MULTIPLE 1152
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 1132)
    setvar $PLANETHAGGLE~MCIC "-29"
    setvar $PLANETHAGGLE~MULTIPLE 1149
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 1124)
    setvar $PLANETHAGGLE~MCIC "-28"
    setvar $PLANETHAGGLE~MULTIPLE 1144
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 1116)
    setvar $PLANETHAGGLE~MCIC "-27"
    setvar $PLANETHAGGLE~MULTIPLE 1136
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 1109)
    setvar $PLANETHAGGLE~MCIC "-26"
    setvar $PLANETHAGGLE~MULTIPLE 1132
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 1101)
    setvar $PLANETHAGGLE~MCIC "-25"
    setvar $PLANETHAGGLE~MULTIPLE 1126
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 1093)
    setvar $PLANETHAGGLE~MCIC "-24"
    setvar $PLANETHAGGLE~MULTIPLE 1122
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 1086)
    setvar $PLANETHAGGLE~MCIC "-23"
    setvar $PLANETHAGGLE~MULTIPLE 1117
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 1078)
    setvar $PLANETHAGGLE~MCIC "-22"
    setvar $PLANETHAGGLE~MULTIPLE 1110
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 1071)
    setvar $PLANETHAGGLE~MCIC "-21"
    setvar $PLANETHAGGLE~MULTIPLE 1105
  elseif ($PLANETHAGGLE~PORTMAXINIT >= 1063)
    setvar $PLANETHAGGLE~MCIC "-20"
    setvar $PLANETHAGGLE~MULTIPLE 1102
  else
    setvar $PLANETHAGGLE~MCIC 0
    setvar $PLANETHAGGLE~MULTIPLE 1102
  end
end
setvar $PLANETHAGGLE~COUNTER $PLANETHAGGLE~OFFER
divide $PLANETHAGGLE~COUNTER 10
multiply $PLANETHAGGLE~COUNTER $PLANETHAGGLE~MULTIPLE
divide $PLANETHAGGLE~COUNTER 100
send "az"&$PLANETHAGGLE~COUNTER&"*"
setvar $PLANETHAGGLE~MIDHAGGLES 0

:PLANETHAGGLE~SELLOFFERLOOP
settextlinetrigger SELLPRICE :SELLPRICE "We'll buy them for"
settextlinetrigger SELLFINALOFFER :SELLFINALOFFER "Our final offer"
settextlinetrigger SELLEXPERIENCE :SELLEXPERIENCE "experience point(s)"
settextlinetrigger SELLYOUHAVE :SELLYOUHAVE "You have"
settextlinetrigger SELLSCREWUP1 :SELLSCREWUP "Get real ion-brain, make me a real offer."
settextlinetrigger SELLSCREWUP2 :SELLSCREWUP "This is the big leagues Jr.  Make a real offer."
settextlinetrigger SELLSCREWUP3 :SELLSCREWUP "My patience grows short with you."
settextlinetrigger SELLSCREWUP4 :SELLSCREWUP "I have much better things to do than waste my time.  Try again."
settextlinetrigger SELLSCREWUP5 :SELLSCREWUP "HA! HA, ha hahahhah hehehe hhhohhohohohh!  You choke me up!"
settextlinetrigger SELLSCREWUP6 :SELLSCREWUP "Quit playing around, you're wasting my time!"
settextlinetrigger SELLSCREWUP7 :SELLSCREWUP "Make a real offer or get the h"
settextlinetrigger SELLSCREWUP8 :SELLSCREWUP "WHAT?!@!? you must be crazy!"
settextlinetrigger SELLSCREWUP9 :SELLSCREWUP "So, you think I'm as stupid as you look? Make a real offer."
settextlinetrigger SELLSCREWUP10 :SELLSCREWUP "What do you take me for, a fool?  Make a real offer!"
settextlinetrigger SELLSCREWUP11 :SELLSCREWUP "Swine, go peddle your wares somewhere else, you make me sick."
settextlinetrigger SELLSCREWUP12 :SELLSCREWUP "I see you are as stupid as you look, get lost..."
settextlinetrigger SELLSCREWUP13 :SELLSCREWUP "HA!  You think me a fool?  Thats insane!  Get out of here!"
settextlinetrigger SELLSCREWUP14 :SELLSCREWUP "Get lost creep, that junk isn't worth half that much!"
settextlinetrigger SELLSCREWUP15 :SELLSCREWUP "I think you'd better leave if you value your life!"
pause
pause

:PLANETHAGGLE~SELLSCREWUP
killtrigger SELLPRICE
killtrigger SELLFINALOFFER
killtrigger SELLEXPERIENCE
killtrigger SELLYOUHAVE
killtrigger SELLSCREWUP1
killtrigger SELLSCREWUP2
killtrigger SELLSCREWUP3
killtrigger SELLSCREWUP4
killtrigger SELLSCREWUP5
killtrigger SELLSCREWUP6
killtrigger SELLSCREWUP7
killtrigger SELLSCREWUP8
killtrigger SELLSCREWUP9
killtrigger SELLSCREWUP10
killtrigger SELLSCREWUP11
killtrigger SELLSCREWUP12
killtrigger SELLSCREWUP13
killtrigger SELLSCREWUP14
killtrigger SELLSCREWUP15
echo "*## PICKUP up sell fail"
goto :SELLHAGGLEFAILED
echo "*### HSOULD NOT GET HERE NOW"
multiply $PLANETHAGGLE~COUNTER 98
divide $PLANETHAGGLE~COUNTER 100
send "az"&$PLANETHAGGLE~COUNTER&"*"
goto :SELLOFFERLOOP

:PLANETHAGGLE~SELLPRICE
killtrigger SELLPRICE
killtrigger SELLFINALOFFER
killtrigger SELLEXPERIENCE
killtrigger SELLYOUHAVE
killtrigger SELLSCREWUP1
killtrigger SELLSCREWUP2
killtrigger SELLSCREWUP3
killtrigger SELLSCREWUP4
killtrigger SELLSCREWUP5
killtrigger SELLSCREWUP6
killtrigger SELLSCREWUP7
killtrigger SELLSCREWUP8
killtrigger SELLSCREWUP9
killtrigger SELLSCREWUP10
killtrigger SELLSCREWUP11
killtrigger SELLSCREWUP12
killtrigger SELLSCREWUP13
killtrigger SELLSCREWUP14
killtrigger SELLSCREWUP15
add $PLANETHAGGLE~MIDHAGGLES 1
setvar $PLANETHAGGLE~OLD_OFFER $PLANETHAGGLE~OFFER
setvar $PLANETHAGGLE~OLD_COUNTER $PLANETHAGGLE~COUNTER
getword CURRENTLINE $PLANETHAGGLE~OFFER 5
striptext $PLANETHAGGLE~OFFER ","
setvar $PLANETHAGGLE~OFFER_CHANGE $PLANETHAGGLE~OFFER
subtract $PLANETHAGGLE~OFFER_CHANGE $PLANETHAGGLE~OLD_OFFER
if ($PLANETHAGGLE~MCIC > "-35")
  multiply $PLANETHAGGLE~OFFER_CHANGE 75
  divide $PLANETHAGGLE~OFFER_CHANGE 100
  subtract $PLANETHAGGLE~COUNTER $PLANETHAGGLE~OFFER_CHANGE
  subtract $PLANETHAGGLE~COUNTER 25
elseif ($PLANETHAGGLE~MCIC > "-55")
  multiply $PLANETHAGGLE~OFFER_CHANGE 65
  divide $PLANETHAGGLE~OFFER_CHANGE 100
  subtract $PLANETHAGGLE~COUNTER $PLANETHAGGLE~OFFER_CHANGE
  subtract $PLANETHAGGLE~COUNTER 25
else
  multiply $PLANETHAGGLE~OFFER_CHANGE 60
  divide $PLANETHAGGLE~OFFER_CHANGE 100
  subtract $PLANETHAGGLE~COUNTER $PLANETHAGGLE~OFFER_CHANGE
  subtract $PLANETHAGGLE~COUNTER 10
end
send "az"&$PLANETHAGGLE~COUNTER&"*"
goto :SELLOFFERLOOP

:PLANETHAGGLE~SELLFINALOFFER
killtrigger SELLPRICE
killtrigger SELLFINALOFFER
killtrigger SELLEXPERIENCE
killtrigger SELLYOUHAVE
killtrigger SELLSCREWUP1
killtrigger SELLSCREWUP2
killtrigger SELLSCREWUP3
killtrigger SELLSCREWUP4
killtrigger SELLSCREWUP5
killtrigger SELLSCREWUP6
killtrigger SELLSCREWUP7
killtrigger SELLSCREWUP8
killtrigger SELLSCREWUP9
killtrigger SELLSCREWUP10
killtrigger SELLSCREWUP11
killtrigger SELLSCREWUP12
killtrigger SELLSCREWUP13
killtrigger SELLSCREWUP14
killtrigger SELLSCREWUP15

if (($PLANETHAGGLE~PRODTOSELL = "ore") and (($PLANETHAGGLE~MCIC <= "-75") and (($PLANETHAGGLE~PORTBUYING >= 25000) and (($PLANETHAGGLE~MIDHAGGLES < 1) and ($PLANETHAGGLE~ORE_SELL_FAILURES < 2)))))
  setvar $PLANETHAGGLE~FORCEFAIL 1
  setvar $PLANETHAGGLE~THISOREFAILED 1
elseif (($PLANETHAGGLE~PRODTOSELL = "org") and ((($PLANETHAGGLE~MCIC <= "-60") and ((($PLANETHAGGLE~PORTBUYING >= 25000) and ((($PLANETHAGGLE~MIDHAGGLES < 2) and (($PLANETHAGGLE~THISOREFAILED = 1) or ($PLANETHAGGLE~ORG_SELL_FAILURES < 4)))))))))
  setvar $PLANETHAGGLE~FORCEFAIL 1
  setvar $PLANETHAGGLE~THISORGFAILED 1
elseif (($PLANETHAGGLE~PRODTOSELL = "org") and ((($PLANETHAGGLE~MCIC <= "-60") and ((($PLANETHAGGLE~PORTBUYING >= 15000) and ((($PLANETHAGGLE~MIDHAGGLES < 1) and (($PLANETHAGGLE~THISOREFAILED = 1) or ($PLANETHAGGLE~ORG_SELL_FAILURES < 2)))))))))
  setvar $PLANETHAGGLE~FORCEFAIL 1
  setvar $PLANETHAGGLE~THISORGFAILED 1
elseif (($PLANETHAGGLE~PRODTOSELL = "equ") and ((($PLANETHAGGLE~MCIC <= "-55") and ((($PLANETHAGGLE~PORTBUYING >= 20000) and ((($PLANETHAGGLE~MIDHAGGLES < 2) and (($PLANETHAGGLE~THISOREFAILED = 1) or ($PLANETHAGGLE~THISORGFAILED = 1) or ($PLANETHAGGLE~EQU_SELL_FAILURES < 4)))))))))
  setvar $PLANETHAGGLE~FORCEFAIL 1
  setvar $PLANETHAGGLE~THISEQUFAILED 1
elseif (($PLANETHAGGLE~PRODTOSELL = "equ") and ((($PLANETHAGGLE~MCIC <= "-55") and ((($PLANETHAGGLE~PORTBUYING >= 12000) and ((($PLANETHAGGLE~MIDHAGGLES < 1) and (($PLANETHAGGLE~THISOREFAILED = 1) or ($PLANETHAGGLE~THISORGFAILED = 1) or ($PLANETHAGGLE~EQU_SELL_FAILURES < 2)))))))))
  setvar $PLANETHAGGLE~FORCEFAIL 1
  setvar $PLANETHAGGLE~THISEQUFAILED 1
else
  setvar $PLANETHAGGLE~FORCEFAIL 0
end
if ($PLANETHAGGLE~PRODTOSELL = "ore")
  setsectorparameter $PLAYER~CURRENT_SECTOR "OREMCIC" $PLANETHAGGLE~MCIC
elseif ($PLANETHAGGLE~PRODTOSELL = "org")
  setsectorparameter $PLAYER~CURRENT_SECTOR "ORGMCIC" $PLANETHAGGLE~MCIC
elseif ($PLANETHAGGLE~PRODTOSELL = "equ")
  setsectorparameter $PLAYER~CURRENT_SECTOR "EQUMCIC" $PLANETHAGGLE~MCIC
end
if ($PLANETHAGGLE~FORCEFAIL = 0)
  setvar $PLANETHAGGLE~OLD_OFFER $PLANETHAGGLE~OFFER
  setvar $PLANETHAGGLE~OLD_COUNTER $PLANETHAGGLE~COUNTER
  getword CURRENTLINE $PLANETHAGGLE~OFFER 5
  striptext $PLANETHAGGLE~OFFER ","
  setvar $PLANETHAGGLE~OFFER_CHANGE $PLANETHAGGLE~OFFER
  subtract $PLANETHAGGLE~OFFER_CHANGE $PLANETHAGGLE~OLD_OFFER
  if ($PLANETHAGGLE~PRODTOSELL = "ore")
    multiply $PLANETHAGGLE~OFFER_CHANGE 30
  elseif ($PLANETHAGGLE~PRODTOSELL = "org")
    multiply $PLANETHAGGLE~OFFER_CHANGE 27
  elseif ($PLANETHAGGLE~PRODTOSELL = "equ")
    multiply $PLANETHAGGLE~OFFER_CHANGE 25
  end
  divide $PLANETHAGGLE~OFFER_CHANGE 10
  subtract $PLANETHAGGLE~COUNTER $PLANETHAGGLE~OFFER_CHANGE
  subtract $PLANETHAGGLE~COUNTER 10
  send "az"&$PLANETHAGGLE~COUNTER&"*"
else

  send "az"&$PLANETHAGGLE~COUNTER&"*"
end
goto :SELLOFFERLOOP

:PLANETHAGGLE~SELLNOTINTERESTED
killtrigger SELLPRICE
killtrigger SELLFINALOFFER
killtrigger SELLEXPERIENCE
killtrigger SELLYOUHAVE
killtrigger SELLSCREWUP1
killtrigger SELLSCREWUP2
killtrigger SELLSCREWUP3
killtrigger SELLSCREWUP4
killtrigger SELLSCREWUP5
killtrigger SELLSCREWUP6
killtrigger SELLSCREWUP7
killtrigger SELLSCREWUP8
killtrigger SELLSCREWUP9
killtrigger SELLSCREWUP10
killtrigger SELLSCREWUP11
killtrigger SELLSCREWUP12
killtrigger SELLSCREWUP13
killtrigger SELLSCREWUP14
killtrigger SELLSCREWUP15
goto :SELLHAGGLEFAILED

:PLANETHAGGLE~SELLEXPERIENCE
killtrigger SELLPRICE
killtrigger SELLFINALOFFER
killtrigger SELLEXPERIENCE
killtrigger SELLYOUHAVE
killtrigger SELLSCREWUP1
killtrigger SELLSCREWUP2
killtrigger SELLSCREWUP3
killtrigger SELLSCREWUP4
killtrigger SELLSCREWUP5
killtrigger SELLSCREWUP6
killtrigger SELLSCREWUP7
killtrigger SELLSCREWUP8
killtrigger SELLSCREWUP9
killtrigger SELLSCREWUP10
killtrigger SELLSCREWUP11
killtrigger SELLSCREWUP12
killtrigger SELLSCREWUP13
killtrigger SELLSCREWUP14
getword CURRENTLINE $PLANETHAGGLE~EXP_BONUS 7
add $PLANETHAGGLE~EXPERIENCE $PLANETHAGGLE~EXP_BONUS
goto :SELLOFFERLOOP

:PLANETHAGGLE~SELLYOUHAVE
killtrigger SELLPRICE
killtrigger SELLFINALOFFER
killtrigger SELLEXPERIENCE
killtrigger SELLYOUHAVE
killtrigger SELLSCREWUP1
killtrigger SELLSCREWUP2
killtrigger SELLSCREWUP3
killtrigger SELLSCREWUP4
killtrigger SELLSCREWUP5
killtrigger SELLSCREWUP6
killtrigger SELLSCREWUP7
killtrigger SELLSCREWUP8
killtrigger SELLSCREWUP9
killtrigger SELLSCREWUP10
killtrigger SELLSCREWUP11
killtrigger SELLSCREWUP12
killtrigger SELLSCREWUP13
killtrigger SELLSCREWUP14
killtrigger SELLSCREWUP15

setvar $PLANETHAGGLE~OLDCREDITS $PLAYER~CREDITS
getword CURRENTLINE $PLANETHAGGLE~CREDITS 3
striptext $PLANETHAGGLE~CREDITS ","

if ($PLANETHAGGLE~OLDCREDITS = $PLANETHAGGLE~CREDITS)
  setvar $PLANETHAGGLE~CURRENTHAGGLE "failed"
  goto :SELLHAGGLEFAILED
else
  setvar $PLANETHAGGLE~CURRENTHAGGLE "succeeded"
  goto :SELLHAGGLESUCCEEDED
end
:PLANETHAGGLE~SELLHAGGLEFAILED
if ($PLANETHAGGLE~PRODTOSELL = "ore")
  add $PLANETHAGGLE~ORE_SELL_FAILURES 1
elseif ($PLANETHAGGLE~PRODTOSELL = "org")
  add $PLANETHAGGLE~ORG_SELL_FAILURES 1
elseif ($PLANETHAGGLE~PRODTOSELL = "equ")
  add $PLANETHAGGLE~EQU_SELL_FAILURES 1
end
if ($PLANETHAGGLE~SELLDELAY > 99)
  setdelaytrigger SELLDELAY :SELLDELAY $PLANETHAGGLE~SELLDELAY
  pause
  :PLANETHAGGLE~SELLDELAY
end
return

:PLANETHAGGLE~SELLHAGGLESUCCEEDED
setvar $PLANETHAGGLE~PERUNIT $PLANETHAGGLE~COUNTER
divide $PLANETHAGGLE~PERUNIT $PLANETHAGGLE~PORTBUYING
setvar $PLANETHAGGLE~SELLOUTPUT ""
setvar $PLANETHAGGLE~SELLOUTPUT $PLANETHAGGLE~SELLOUTPUT&$PLANETHAGGLE~PORTBUYING&" "&$PLANETHAGGLE~PRODTOSELL&" for "&$PLANETHAGGLE~COUNTER&" cr"
setvar $PLANETHAGGLE~SELLOUTPUT $PLANETHAGGLE~SELLOUTPUT&" - "
if ($PLANETHAGGLE~PRODTOSELL = "ore")
  setvar $PLANETHAGGLE~SELLOUTPUT $PLANETHAGGLE~SELLOUTPUT&$PLANETHAGGLE~ORE_SELL_FAILURES
elseif ($PLANETHAGGLE~PRODTOSELL = "org")
  setvar $PLANETHAGGLE~SELLOUTPUT $PLANETHAGGLE~SELLOUTPUT&$PLANETHAGGLE~ORG_SELL_FAILURES
elseif ($PLANETHAGGLE~PRODTOSELL = "equ")
  setvar $PLANETHAGGLE~SELLOUTPUT $PLANETHAGGLE~SELLOUTPUT&$PLANETHAGGLE~EQU_SELL_FAILURES
end
setvar $PLANETHAGGLE~SELLOUTPUT $PLANETHAGGLE~SELLOUTPUT&" fails"
setvar $PLANETHAGGLE~SELLOUTPUT $PLANETHAGGLE~SELLOUTPUT&" - "&$PLANETHAGGLE~PERUNIT&"/unit"
setvar $PLANETHAGGLE~SELLOUTPUT $PLANETHAGGLE~SELLOUTPUT&" - MCIC "&$PLANETHAGGLE~MCIC
if ($PLANETHAGGLE~PRODTOSELL = "ore")
  setvar $PLANETHAGGLE~SELLOUTPUT $PLANETHAGGLE~SELLOUTPUT&"/-90*"
  setvar $PLANETHAGGLE~ORESELLOUTPUT $PLANETHAGGLE~SELLOUTPUT
  setvar $PLANETHAGGLE~OREPROFIT $PLANETHAGGLE~COUNTER
elseif ($PLANETHAGGLE~PRODTOSELL = "org")
  setvar $PLANETHAGGLE~SELLOUTPUT $PLANETHAGGLE~SELLOUTPUT&"/-75*"
  setvar $PLANETHAGGLE~ORGSELLOUTPUT $PLANETHAGGLE~SELLOUTPUT
  setvar $PLANETHAGGLE~ORGPROFIT $PLANETHAGGLE~COUNTER
elseif ($PLANETHAGGLE~PRODTOSELL = "equ")
  setvar $PLANETHAGGLE~SELLOUTPUT $PLANETHAGGLE~SELLOUTPUT&"/-65*"
  setvar $PLANETHAGGLE~EQUSELLOUTPUT $PLANETHAGGLE~SELLOUTPUT
  setvar $PLANETHAGGLE~EQUPROFIT $PLANETHAGGLE~COUNTER
end
if ($PLANETHAGGLE~SELLDELAY > 99)
  setdelaytrigger SELLDELAY :SELLDELAY2 $PLANETHAGGLE~SELLDELAY
  pause
  pause
  :PLANETHAGGLE~SELLDELAY2
end
return

:PLANETHAGGLE~NEGOTIATELAND
if ($PLANETHAGGLE~STARTINGLOCATION = "Citadel")
  send "L "&$PLANET~PLANET&"* "
  gosub :PLANET~GETPLANETINFO
  send "c "
elseif ($PLANETHAGGLE~STARTINGLOCATION = "Planet")
  send "L "&$PLANET~PLANET&"* "
  gosub :PLANET~GETPLANETINFO
end
return

:PLANETHAGGLE~EXITNEG
return

#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
:PLANETHAGGLE~BUY
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
setvar $PLAYER~OVERHAGGLEMULTIPLE 147
setvar $PLAYER~CYCLEBUFFER 1
setvar $PLAYER~CYCLEBUFFERLIMIT 20
setvar $PLAYER~BUYDOWN_RESTORE_HAGGLE 0
setvar $PLAYER~BUYDOWN_USENATIVEHAGGLE 0

if (HAGGLE)
  if ($PLAYER~BUYTYPE = "s")
    setvar $PLAYER~BUYDOWN_RESTORE_HAGGLE 1
    autohaggle off
  else
    setvar $PLAYER~BUYDOWN_USENATIVEHAGGLE 1
  end
end

if ($PLAYER~BUYDOWN_USENATIVEHAGGLE = 0)
  send "@"
  waiton "Average Interval Lag:"
end
gosub :PLAYER~QUIKSTATS
setvar $PLAYER~STARTINGLOCATION $PLAYER~CURRENT_PROMPT

setvar $PLAYER~OUTPUT ""
setvar $PLAYER~EQUIPROUNDS 0
setvar $PLAYER~ORGROUNDS 0
setvar $PLAYER~FUELROUNDS 0
if ($PLAYER~BUYDOWNROUNDSFROMPARAM <= 0)
  setvar $PLAYER~BUYDOWNROUNDSFROMPARAM 999999
end
if ($PLAYER~BUYTYPE = "w")
  setvar $PLAYER~BUYDOWN_MODE 3
elseif ($PLAYER~BUYTYPE = "b")
  setvar $PLAYER~BUYDOWN_MODE 2
else
  setvar $PLAYER~BUYDOWN_MODE 1
end
if ($PLAYER~BUYOBJECT = "e")
  setvar $PLAYER~BUYDOWN_EQUIPROUNDS $PLAYER~BUYDOWNROUNDSFROMPARAM
  setvar $PLAYER~BUYDOWN_ORGROUNDS 0
  setvar $PLAYER~BUYDOWN_FUELROUNDS 0
elseif ($PLAYER~BUYOBJECT = "o")
  setvar $PLAYER~BUYDOWN_EQUIPROUNDS 0
  setvar $PLAYER~BUYDOWN_ORGROUNDS $PLAYER~BUYDOWNROUNDSFROMPARAM
  setvar $PLAYER~BUYDOWN_FUELROUNDS 0
elseif ($PLAYER~BUYOBJECT = "f")
  setvar $PLAYER~BUYDOWN_EQUIPROUNDS 0
  setvar $PLAYER~BUYDOWN_ORGROUNDS 0
  setvar $PLAYER~BUYDOWN_FUELROUNDS $PLAYER~BUYDOWNROUNDSFROMPARAM
else
  setvar $PLAYER~EXIT_MESSAGE "Please use format buy [type] {speed} {#cycles} {override}*"
  return

end
if ($PLAYER~STARTINGLOCATION = "Citadel")
  send "Q"
end
send "t n l 1* t n l 2* t n l 3* s n l1*"
waiton "How many groups of Colonists do you want to leave"
gosub :PLANET~GETPLANETINFO
if ($PLAYER~STARTINGLOCATION = "Citadel")
  send "C s* "
else
  send "Q D"
end
gosub :PLAYER~GETINFO
if ($PLAYER~TOTAL_HOLDS <> $PLAYER~EMPTY_HOLDS)
  if ($PLAYER~STARTINGLOCATION <> "Citadel")
    gosub :PLANET~LANDINGSUB
  end
  setvar $SWITCHBOARD~MESSAGE "Planet full, cannot empty ship holds*"
  gosub :SWITCHBOARD~SWITCHBOARD
  goto :PLANETHAGGLE~BUYEXIT
end
gosub :PLAYER~VOIDADJACENT
gosub :PLAYER~GETPORTINFO
if ($PLAYER~VALIDPORTFOUND <> TRUE)
  echo "*No valid port found*"
  if ($PLAYER~STARTINGLOCATION <> "Citadel")
    gosub :PLANET~LANDINGSUB
  end
  gosub :PLAYER~CLEARADJACENT
  goto :PLANETHAGGLE~BUYEXIT
end
if ($PLAYER~STARTINGLOCATION = "Citadel")
  send "Q"
else
  send "L "&$PLANET~PLANET&"* "
end
setdelaytrigger PLANETBUYINITPAUSE :PLANETHAGGLE~BUYINITPAUSE 500
pause
:PLANETHAGGLE~BUYINITPAUSE
:PLANETHAGGLE~BUYGETINPUTS

setvar $PLAYER~TURNS_NEEDED 0
setvar $PLAYER~TURNS_ALLOWED $PLAYER~TURNS
subtract $PLAYER~TURNS_ALLOWED 1

if ($PLAYER~BUYDOWN_FUELROUNDS > 0)
  setvar $PLAYER~FUELROUNDS 0
  setvar $PLAYER~PLANETFUELROOM $PLANET~PLANET_FUEL_MAX
  subtract $PLAYER~PLANETFUELROOM $PLANET~PLANET_FUEL
  setvar $PLAYER~MAXFUELTOBUY $PLAYER~FUELSELLING
  if ($PLAYER~FUELSELLING > $PLAYER~PLANETFUELROOM)
    setvar $PLAYER~MAXFUELTOBUY $PLAYER~PLANETFUELROOM
  end
  setvar $PLAYER~MAXFUELROUNDS $PLAYER~MAXFUELTOBUY
  divide $PLAYER~MAXFUELROUNDS $PLAYER~TOTAL_HOLDS
  if ($PLAYER~MAXFUELROUNDS > $PLAYER~TURNS_ALLOWED)
    setvar $PLAYER~MAXFUELROUNDS $PLAYER~TURNS_ALLOWED
  end
  if ($PLAYER~MAXFUELROUNDS > $PLAYER~BUYDOWN_FUELROUNDS)
    setvar $PLAYER~MAXFUELROUNDS $PLAYER~BUYDOWN_FUELROUNDS
  end
  if ($PLAYER~MAXFUELROUNDS > 0)
    setvar $PLAYER~FUELROUNDS $PLAYER~MAXFUELROUNDS
  end
  add $PLAYER~TURNS_NEEDED $PLAYER~FUELROUNDS
  subtract $PLAYER~TURNS_ALLOWED $PLAYER~FUELROUNDS
end

if ($PLAYER~BUYDOWN_ORGROUNDS > 0)
  setvar $PLAYER~ORGROUNDS 0
  setvar $PLAYER~PLANETORGROOM $PLANET~PLANET_ORGANICS_MAX
  subtract $PLAYER~PLANETORGROOM $PLANET~PLANET_ORGANICS
  setvar $PLAYER~MAXORGTOBUY $PLAYER~ORGSELLING
  if ($PLAYER~ORGSELLING > $PLAYER~PLANETORGROOM)
    setvar $PLAYER~MAXORGTOBUY $PLAYER~PLANETORGROOM
  end
  setvar $PLAYER~MAXORGROUNDS $PLAYER~MAXORGTOBUY
  divide $PLAYER~MAXORGROUNDS $PLAYER~TOTAL_HOLDS
  if ($PLAYER~MAXORGROUNDS > $PLAYER~TURNS_ALLOWED)
    setvar $PLAYER~MAXORGROUNDS $PLAYER~TURNS_ALLOWED
  end
  if ($PLAYER~MAXORGROUNDS > $PLAYER~BUYDOWN_ORGROUNDS)
    setvar $PLAYER~MAXORGROUNDS $PLAYER~BUYDOWN_ORGROUNDS
  end
  if ($PLAYER~MAXORGROUNDS > 0)
    setvar $PLAYER~ORGROUNDS $PLAYER~MAXORGROUNDS
  end
  add $PLAYER~TURNS_NEEDED $PLAYER~ORGROUNDS
  subtract $PLAYER~TURNS_ALLOWED $PLAYER~ORGROUNDS
end

if ($PLAYER~BUYDOWN_EQUIPROUNDS > 0)
  setvar $PLAYER~EQUIPROUNDS 0
  setvar $PLAYER~PLANETEQUIPROOM $PLANET~PLANET_EQUIPMENT_MAX
  subtract $PLAYER~PLANETEQUIPROOM $PLANET~PLANET_EQUIPMENT
  setvar $PLAYER~MAXEQUIPTOBUY $PLAYER~EQUIPSELLING
  if ($PLAYER~EQUIPSELLING > $PLAYER~PLANETEQUIPROOM)
    setvar $PLAYER~MAXEQUIPTOBUY $PLAYER~PLANETEQUIPROOM
  end
  setvar $PLAYER~MAXEQUIPROUNDS $PLAYER~MAXEQUIPTOBUY
  divide $PLAYER~MAXEQUIPROUNDS $PLAYER~TOTAL_HOLDS
  if ($PLAYER~MAXEQUIPROUNDS > $PLAYER~TURNS_ALLOWED)
    setvar $PLAYER~MAXEQUIPROUNDS $PLAYER~TURNS_ALLOWED
  end
  if ($PLAYER~MAXEQUIPROUNDS > $PLAYER~BUYDOWN_EQUIPROUNDS)
    setvar $PLAYER~MAXEQUIPROUNDS $PLAYER~BUYDOWN_EQUIPROUNDS
  end
  if ($PLAYER~MAXEQUIPROUNDS > 0)
    setvar $PLAYER~EQUIPROUNDS $PLAYER~MAXEQUIPROUNDS
  end
  add $PLAYER~TURNS_NEEDED $PLAYER~EQUIPROUNDS
  subtract $PLAYER~TURNS_ALLOWED $PLAYER~EQUIPROUNDS
end
if (($PLAYER~FUELROUNDS = 0) and (($PLAYER~ORGROUNDS = 0) and ($PLAYER~EQUIPROUNDS = 0)))
  if ($PLAYER~STARTINGLOCATION = "Citadel")
    send "C "
  else
    send "q "
  end
  echo "*Nothing to buy*"
  gosub :PLAYER~CLEARADJACENT
  goto :PLANETHAGGLE~BUYEXIT
end

:PLANETHAGGLE~BUYGETMODE
if ($PLAYER~BUYDOWN_MODE = 1)
  setvar $PLAYER~BUYDOWN_MODE "Speedbuy"
elseif ($PLAYER~BUYDOWN_MODE = 2)
  setvar $PLAYER~BUYDOWN_MODE "Best Price"
elseif ($PLAYER~BUYDOWN_MODE = 3)
  setvar $PLAYER~BUYDOWN_MODE "Worst Price"
end
setvar $PLAYER~FUELROUNDSLEFT $PLAYER~FUELROUNDS
setvar $PLAYER~ORGROUNDSLEFT $PLAYER~ORGROUNDS
setvar $PLAYER~EQUIPROUNDSLEFT $PLAYER~EQUIPROUNDS
setvar $PLAYER~FUEL_CREDS_NEEDED 0
setvar $PLAYER~ORG_CREDS_NEEDED 0
setvar $PLAYER~EQUIP_CREDS_NEEDED 0

if ($PLAYER~FUELROUNDS > 0)
  setvar $PLAYER~FUEL_CREDS_NEEDED $PLAYER~FUELROUNDS
  multiply $PLAYER~FUEL_CREDS_NEEDED $PLAYER~TOTAL_HOLDS
  multiply $PLAYER~FUEL_CREDS_NEEDED 30
  if ($PLAYER~BUYDOWN_MODE = "Worst Price")
    multiply $PLAYER~FUEL_CREDS_NEEDED 3
    divide $PLAYER~FUEL_CREDS_NEEDED 2
  end
end
if ($PLAYER~ORGROUNDS > 0)
  setvar $PLAYER~ORG_CREDS_NEEDED $PLAYER~ORGROUNDS
  multiply $PLAYER~ORG_CREDS_NEEDED $PLAYER~TOTAL_HOLDS
  multiply $PLAYER~ORG_CREDS_NEEDED 60
  if ($PLAYER~BUYDOWN_MODE = "Worst Price")
    multiply $PLAYER~ORG_CREDS_NEEDED 3
    divide $PLAYER~ORG_CREDS_NEEDED 2
  end
end
if ($PLAYER~EQUIPROUNDS > 0)
  setvar $PLAYER~EQUIP_CREDS_NEEDED $PLAYER~EQUIPROUNDS
  multiply $PLAYER~EQUIP_CREDS_NEEDED $PLAYER~TOTAL_HOLDS
  multiply $PLAYER~EQUIP_CREDS_NEEDED 100
  if ($PLAYER~BUYDOWN_MODE = "Worst Price")
    multiply $PLAYER~EQUIP_CREDS_NEEDED 3
    divide $PLAYER~EQUIP_CREDS_NEEDED 2
  end
end
setvar $PLAYER~TOTAL_CREDS_NEEDED 0
add $PLAYER~TOTAL_CREDS_NEEDED $PLAYER~FUEL_CREDS_NEEDED
add $PLAYER~TOTAL_CREDS_NEEDED $PLAYER~ORG_CREDS_NEEDED
add $PLAYER~TOTAL_CREDS_NEEDED $PLAYER~EQUIP_CREDS_NEEDED
setvar $PLAYER~STARTINGCREDITS $PLAYER~CREDITS
if ($PLAYER~TOTAL_CREDS_NEEDED > $PLAYER~CREDITS)
  setvar $PLAYER~CASHONHAND $PLANET~CITADEL_CREDITS
  add $PLAYER~CASHONHAND $PLAYER~CREDITS
  if ($PLAYER~CASHONHAND > $PLAYER~TOTAL_CREDS_NEEDED)
    send "C"
    send "T T "&$PLAYER~CREDITS&"* "
    send "T F "&$PLAYER~TOTAL_CREDS_NEEDED&"* "
    setvar $PLAYER~CREDITS $PLAYER~TOTAL_CREDS_NEEDED
    send "Q"
  else
    if ($PLAYER~STARTINGLOCATION = "Citadel")
      send "C "
    else
      send "q "
    end
    setvar $PLAYER~EXIT_MESSAGE "Not enough cash onhand"
    gosub :PLAYER~CLEARADJACENT
    goto :PLANETHAGGLE~BUYEXIT
  end
end
setvar $PLAYER~INIT_CREDITS $PLAYER~CREDITS

:PLANETHAGGLE~BUYDOWNEQUIP
if ($PLAYER~EQUIPROUNDSLEFT > 0)
  send "Q P T  "
  if ($PLAYER~FUELSELLING > 0)
    send "0* "
  end
  if ($PLAYER~ORGSELLING > 0)
    send "0*"
  end
  gosub :PLANETHAGGLE~BUYCHOOSEHAGGLE
  send "L "&$PLANET~PLANET&"* t n l 3* "
  subtract $PLAYER~EQUIPROUNDSLEFT 1
  goto :PLANETHAGGLE~BUYDOWNEQUIP
end
if ($PLAYER~EQUIPROUNDS > 0)
  if ($PLAYER~BUYDOWN_MODE = "Worst Price")
    setvar $PLAYER~OUTPUT $PLAYER~OUTPUT&" - Equipment overhaggled at "&$PLAYER~OVERHAGGLEMULTIPLE&"*"
  end
end

:PLANETHAGGLE~BUYDOWNORG
if ($PLAYER~ORGROUNDSLEFT > 0)
  send "Q P T  "
  if ($PLAYER~FUELSELLING > 0)
    send "0*"
  end
  gosub :PLANETHAGGLE~BUYCHOOSEHAGGLE
  send "0* L "&$PLANET~PLANET&"* t n l 2* "
  subtract $PLAYER~ORGROUNDSLEFT 1
  goto :PLANETHAGGLE~BUYDOWNORG
end
if ($PLAYER~ORGROUNDS > 0)
  if ($PLAYER~BUYDOWN_MODE = "Worst Price")
    setvar $PLAYER~OUTPUT $PLAYER~OUTPUT&" - Organics overhaggled at "&$PLAYER~OVERHAGGLEMULTIPLE&"*"
  end
end

:PLANETHAGGLE~BUYDOWNFUEL
if ($PLAYER~FUELROUNDSLEFT > 0)
  send "Q P T "
  gosub :PLANETHAGGLE~BUYCHOOSEHAGGLE
  send "0* 0* L "&$PLANET~PLANET&"* t n l 1* "
  subtract $PLAYER~FUELROUNDSLEFT 1
  goto :PLANETHAGGLE~BUYDOWNFUEL
end
if ($PLAYER~FUELROUNDS > 0)
  if ($PLAYER~BUYDOWN_MODE = "Worst Price")
    setvar $PLAYER~OUTPUT $PLAYER~OUTPUT&" - Fuel Ore overhaggled at "&$PLAYER~OVERHAGGLEMULTIPLE&"*"
  end
end

:PLANETHAGGLE~BUYDOWNFINISH
if ($PLAYER~STARTINGLOCATION = "Citadel")
  send "C "
end
gosub :PLAYER~GETINFO
setvar $PLAYER~CREDITS_SPENT $PLAYER~INIT_CREDITS
subtract $PLAYER~CREDITS_SPENT $PLAYER~CREDITS
gosub :PLAYER~CLEARADJACENT
if ($PLAYER~STARTINGLOCATION = "Planet")
  send "L "&$PLANET~PLANET&"* "
end
if ($PLAYER~CREDITS > $PLAYER~STARTINGCREDITS)
  if ($PLAYER~STARTINGLOCATION = "Citadel")
    send "T T "&($PLAYER~CREDITS - $PLAYER~STARTINGCREDITS)&"* "
  end
end
setvar $PLAYER~EXIT_MESSAGE "Normal Exit"

:PLANETHAGGLE~BUYEXIT
if ($PLAYER~BUYDOWN_RESTORE_HAGGLE = 1)
  autohaggle on
  setvar $PLAYER~BUYDOWN_RESTORE_HAGGLE 0
end
return

:PLANETHAGGLE~BUYCHOOSEHAGGLE
if ($PLAYER~BUYDOWN_USENATIVEHAGGLE = 1)
  gosub :PLANETHAGGLE~BUYNATIVEHAGGLE
elseif ($PLAYER~BUYDOWN_MODE = "Speedbuy")
  gosub :PLANETHAGGLE~BUYNOHAGGLE
else
  gosub :PLANETHAGGLE~BUYHAGGLE
end
return

:PLANETHAGGLE~BUYNATIVEHAGGLE
setvar $PLAYER~EMPTY $PLAYER~TOTAL_HOLDS
send "*"
settextlinetrigger PLANETBUYEMPTY :PLANETHAGGLE~BUYEMPTY "empty cargo holds"
settextlinetrigger PLANETBUYNOTINTERESTED :PLANETHAGGLE~BUYNOTINTERESTED "We're not interested."
settexttrigger PLANETBUYNATIVEDONE :PLANETHAGGLE~BUYHAGGLESUCCEEDED "Command [TL="
pause

:PLANETHAGGLE~BUYHAGGLE
killtrigger PLANETBUYFIRSTOFFER
setvar $PLAYER~EMPTY $PLAYER~TOTAL_HOLDS
send "*"
settextlinetrigger PLANETBUYFIRSTOFFER :PLANETHAGGLE~BUYFIRSTOFFER "We'll sell them for"
pause

:PLANETHAGGLE~BUYFIRSTOFFER
gosub :PLANETHAGGLE~BUYKILLTRIGGERS
getword CURRENTLINE $PLAYER~OFFER 5
striptext $PLAYER~OFFER ","
gosub :PLAYER~SWATHOFF
if ($PLAYER~SWATHOFF = 0)
  send "L "&$PLANET~PLANET&"* "
  if ($PLAYER~STARTINGLOCATION = "Citadel")
    send "C "
  end
  setvar $PLAYER~EXIT_MESSAGE $PLAYER~SWATHOFFMESSAGE
  goto :PLANETHAGGLE~BUYEXIT
end

setvar $PLAYER~COUNTER $PLAYER~OFFER
if ($PLAYER~BUYDOWN_MODE = "Best Price")
  multiply $PLAYER~COUNTER 92
  divide $PLAYER~COUNTER 100
elseif ($PLAYER~BUYDOWN_MODE = "Worst Price")
  multiply $PLAYER~COUNTER $PLAYER~OVERHAGGLEMULTIPLE
  divide $PLAYER~COUNTER 100
end
send $PLAYER~COUNTER&"*"

:PLANETHAGGLE~BUYOFFERLOOP
settextlinetrigger PLANETBUYPRICE :PLANETHAGGLE~BUYPRICE "We'll sell them for"
settextlinetrigger PLANETBUYFINALOFFER :PLANETHAGGLE~BUYFINALOFFER "Our final offer"
settextlinetrigger PLANETBUYNOTINTERESTED :PLANETHAGGLE~BUYNOTINTERESTED "We're not interested."
settextlinetrigger PLANETBUYEXPERIENCE :PLANETHAGGLE~BUYEXPERIENCE "experience point(s)"
settextlinetrigger PLANETBUYEMPTY :PLANETHAGGLE~BUYEMPTY "empty cargo holds"
settextlinetrigger PLANETBUYSCREWUP1 :PLANETHAGGLE~BUYSCREWUP "Get real ion-brain, make me a real offer."
settextlinetrigger PLANETBUYSCREWUP2 :PLANETHAGGLE~BUYSCREWUP "This is the big leagues Jr.  Make a real offer."
settextlinetrigger PLANETBUYSCREWUP3 :PLANETHAGGLE~BUYSCREWUP "My patience grows short with you."
settextlinetrigger PLANETBUYSCREWUP4 :PLANETHAGGLE~BUYSCREWUP "I have much better things to do than waste my time.  Try again."
settextlinetrigger PLANETBUYSCREWUP5 :PLANETHAGGLE~BUYSCREWUP "HA! HA, ha hahahhah hehehe hhhohhohohohh!  You choke me up!"
settextlinetrigger PLANETBUYSCREWUP6 :PLANETHAGGLE~BUYSCREWUP "Quit playing around, you're wasting my time!"
settextlinetrigger PLANETBUYSCREWUP7 :PLANETHAGGLE~BUYSCREWUP "Make a real offer or get the "
settextlinetrigger PLANETBUYSCREWUP8 :PLANETHAGGLE~BUYSCREWUP "WHAT?!@!? you must be crazy!"
settextlinetrigger PLANETBUYSCREWUP9 :PLANETHAGGLE~BUYSCREWUP "So, you think I'm as stupid as you look? Make a real offer."
settextlinetrigger PLANETBUYSCREWUP10 :PLANETHAGGLE~BUYSCREWUP "What do you take me for, a fool?  Make a real offer!"
pause
pause
:PLANETHAGGLE~BUYSCREWUP
gosub :PLANETHAGGLE~BUYKILLTRIGGERS
if ($PLAYER~BUYDOWN_MODE = "Best Price")
  multiply $PLAYER~COUNTER 102
  divide $PLAYER~COUNTER 100
elseif ($PLAYER~BUYDOWN_MODE = "Worst Price")
  subtract $PLAYER~OVERHAGGLEMULTIPLE 1
  setvar $PLAYER~COUNTER $PLAYER~OFFER
  multiply $PLAYER~COUNTER $PLAYER~OVERHAGGLEMULTIPLE
  divide $PLAYER~COUNTER 100
end
send $PLAYER~COUNTER&"*"
goto :PLANETHAGGLE~BUYOFFERLOOP
:PLANETHAGGLE~BUYPRICE
gosub :PLANETHAGGLE~BUYKILLTRIGGERS
setvar $PLAYER~OLD_OFFER $PLAYER~OFFER
setvar $PLAYER~OLD_COUNTER $PLAYER~COUNTER
getword CURRENTLINE $PLAYER~OFFER 5
striptext $PLAYER~OFFER ","
setvar $PLAYER~OFFER_PCT $PLAYER~OFFER
multiply $PLAYER~OFFER_PCT 1000
divide $PLAYER~OFFER_PCT $PLAYER~OLD_OFFER
if ($PLAYER~OFFER_PCT > 990)
  setvar $PLAYER~OFFER_PCT 990
end
multiply $PLAYER~COUNTER 1000
divide $PLAYER~COUNTER $PLAYER~OFFER_PCT
if ($PLAYER~COUNTER <= $PLAYER~OLD_COUNTER)
  add $PLAYER~COUNTER 1
end
send $PLAYER~COUNTER&"*"
goto :PLANETHAGGLE~BUYOFFERLOOP
:PLANETHAGGLE~BUYFINALOFFER
gosub :PLANETHAGGLE~BUYKILLTRIGGERS
setvar $PLAYER~OLD_OFFER $PLAYER~OFFER
setvar $PLAYER~OLD_COUNTER $PLAYER~COUNTER
getword CURRENTLINE $PLAYER~OFFER 5
striptext $PLAYER~OFFER ","
setvar $PLAYER~OFFER_CHANGE $PLAYER~OFFER
subtract $PLAYER~OFFER_CHANGE $PLAYER~OLD_OFFER
subtract $PLAYER~OFFER_CHANGE 1
multiply $PLAYER~OFFER_CHANGE 25
divide $PLAYER~OFFER_CHANGE 10
subtract $PLAYER~COUNTER $PLAYER~OFFER_CHANGE
if ($PLAYER~COUNTER = $PLAYER~OLD_COUNTER)
  add $PLAYER~COUNTER 1
end
add $PLAYER~COUNTER 1
send $PLAYER~COUNTER&"*"
goto :PLANETHAGGLE~BUYOFFERLOOP
:PLANETHAGGLE~BUYNOTINTERESTED
gosub :PLANETHAGGLE~BUYKILLTRIGGERS
send "0* "
send "0* "
goto :PLANETHAGGLE~BUYHAGGLEFAILED
:PLANETHAGGLE~BUYEXPERIENCE
gosub :PLANETHAGGLE~BUYKILLTRIGGERS
getword CURRENTLINE $PLAYER~EXP_BONUS 7
add $PLAYER~EXP $PLAYER~EXP_BONUS
add $PLAYER~JETBONUS $PLAYER~EXP_BONUS
goto :PLANETHAGGLE~BUYOFFERLOOP
:PLANETHAGGLE~BUYEMPTY
gosub :PLANETHAGGLE~BUYKILLTRIGGERS
getword CURRENTLINE $PLAYER~CREDITS 3
striptext $PLAYER~CREDITS ","
setvar $PLAYER~OLDEMPTY $PLAYER~EMPTY
getword CURRENTLINE $PLAYER~EMPTY 6
if ($PLAYER~OLDEMPTY = $PLAYER~EMPTY)
  goto :PLANETHAGGLE~BUYHAGGLEFAILED
else
  goto :PLANETHAGGLE~BUYHAGGLESUCCEEDED
end
:PLANETHAGGLE~BUYHAGGLEFAILED
setvar $PLAYER~BUYHAGGLE 0
return
:PLANETHAGGLE~BUYHAGGLESUCCEEDED
setvar $PLAYER~BUYHAGGLE 1
return

:PLANETHAGGLE~BUYNOHAGGLE
if ($PLAYER~SWATHOFF = 0)

  waiton "How many holds of"
  send "*"
  gosub :PLAYER~SWATHOFF
  send "*"
else
  send "**"
end
setvar $PLAYER~CYCLEBUFFERLIMIT 20
add $PLAYER~CYCLEBUFFER 1
if ($PLAYER~CYCLEBUFFER = $PLAYER~CYCLEBUFFERLIMIT)
  setvar $PLAYER~CYCLEBUFFER 1
  send "/"
  waiton " Sect "
end
return

:PLANETHAGGLE~BUYKILLTRIGGERS
killtrigger PLANETBUYPRICE
killtrigger PLANETBUYFINALOFFER
killtrigger PLANETBUYNOTINTERESTED
killtrigger PLANETBUYEXPERIENCE
killtrigger PLANETBUYEMPTY
killtrigger PLANETBUYNATIVEDONE
killtrigger PLANETBUYSCREWUP1
killtrigger PLANETBUYSCREWUP2
killtrigger PLANETBUYSCREWUP3
killtrigger PLANETBUYSCREWUP4
killtrigger PLANETBUYSCREWUP5
killtrigger PLANETBUYSCREWUP6
killtrigger PLANETBUYSCREWUP7
killtrigger PLANETBUYSCREWUP8
killtrigger PLANETBUYSCREWUP9
killtrigger PLANETBUYSCREWUP10
return
