#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
:PLANETNAMES~MAKE_PLANET_ARRAY
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
setarray $planetnames~PLANET_NAMES 1000
setvar $planetnames~PLANET_NAMES[1] "LoneStar's Circle"
setvar $planetnames~PLANET_NAMES[2] "Manton Outpost"
setvar $planetnames~PLANET_NAMES[3] "Triax Annex"
setvar $planetnames~PLANET_NAMES[4] "New Ovid"
setvar $planetnames~PLANET_NAMES[5] "Napier Minor"
setvar $planetnames~PLANET_NAMES[6] "New Barite"
setvar $planetnames~PLANET_NAMES[7] "Agamotto II"
setvar $planetnames~PLANET_NAMES[8] "Poincare Thunder"
setvar $planetnames~PLANET_NAMES[9] "Camelopardus"
setvar $planetnames~PLANET_NAMES[10] "Ticonderoga Annex"
setvar $planetnames~PLANET_NAMES[11] "Cana Annex"
setvar $planetnames~PLANET_NAMES[12] "Rifts II"
setvar $planetnames~PLANET_NAMES[13] "Arago Annex"
setvar $planetnames~PLANET_NAMES[14] "Grosseteste Primus"
setvar $planetnames~PLANET_NAMES[15] "Lablon Minor"
setvar $planetnames~PLANET_NAMES[16] "Ampilean Minor"
setvar $planetnames~PLANET_NAMES[17] "Pappus II"
setvar $planetnames~PLANET_NAMES[18] "Buddha Gaya II"
setvar $planetnames~PLANET_NAMES[19] "Phlogiston Major"
setvar $planetnames~PLANET_NAMES[20] "Pilar Dawn"
setvar $planetnames~PLANET_NAMES[21] "Vergil"
setvar $planetnames~PLANET_NAMES[22] "Zennor Primus"
setvar $planetnames~PLANET_NAMES[23] "Vigara Outpost"
setvar $planetnames~PLANET_NAMES[24] "l'Hopital"
setvar $planetnames~PLANET_NAMES[25] "Axe-Gonne Annex"
setvar $planetnames~PLANET_NAMES[26] "New Plaskett"
setvar $planetnames~PLANET_NAMES[27] "Quadrono Fury"
setvar $planetnames~PLANET_NAMES[28] "Cuirass Annex"
setvar $planetnames~PLANET_NAMES[29] "Bendor II"
setvar $planetnames~PLANET_NAMES[30] "Catuz II"
setvar $planetnames~PLANET_NAMES[31] "New Barazole"
setvar $planetnames~PLANET_NAMES[32] "Burgundy Outpost"
setvar $planetnames~PLANET_NAMES[33] "Tibanna Annex"
setvar $planetnames~PLANET_NAMES[34] "New Vesta"
setvar $planetnames~PLANET_NAMES[35] "Aerobe Minor"
setvar $planetnames~PLANET_NAMES[36] "Cornu Primus"
setvar $planetnames~PLANET_NAMES[37] "Heguz Outpost"
setvar $planetnames~PLANET_NAMES[38] "Khrytarrm II"
setvar $planetnames~PLANET_NAMES[39] "Zodiac"
setvar $planetnames~PLANET_NAMES[40] "Bevey Primus"
setvar $planetnames~PLANET_NAMES[41] "Pauli Stars"
setvar $planetnames~PLANET_NAMES[42] "Axanar Outpost"
setvar $planetnames~PLANET_NAMES[43] "Veialstroum"
setvar $planetnames~PLANET_NAMES[44] "Dedendum"
setvar $planetnames~PLANET_NAMES[45] "Parthenon Outpost"
setvar $planetnames~PLANET_NAMES[46] "Ahzdar Primus"
setvar $planetnames~PLANET_NAMES[47] "Tionale Minor"
setvar $planetnames~PLANET_NAMES[48] "Fomalhaut Minor"
setvar $planetnames~PLANET_NAMES[49] "Calandra Index"
setvar $planetnames~PLANET_NAMES[50] "New Drude"
setvar $planetnames~PLANET_NAMES[51] "Troi Primus"
setvar $planetnames~PLANET_NAMES[52] "Tourmaline Primus"
setvar $planetnames~PLANET_NAMES[53] "Adurol"
setvar $planetnames~PLANET_NAMES[54] "Zaibon Outpost"
setvar $planetnames~PLANET_NAMES[55] "Cipango Annex"
setvar $planetnames~PLANET_NAMES[56] "Saxbury Annex"
setvar $planetnames~PLANET_NAMES[57] "New Oomaru"
setvar $planetnames~PLANET_NAMES[58] "Weiland Minor"
setvar $planetnames~PLANET_NAMES[59] "Bertian II"
setvar $planetnames~PLANET_NAMES[60] "Strahd Outpost"
setvar $planetnames~PLANET_NAMES[61] "Hallwachs Primus"
setvar $planetnames~PLANET_NAMES[62] "Fabrina Primus"
setvar $planetnames~PLANET_NAMES[63] "Ovid"
setvar $planetnames~PLANET_NAMES[64] "Campell II"
setvar $planetnames~PLANET_NAMES[65] "Osnabruck Major"
setvar $planetnames~PLANET_NAMES[66] "Merrimac Minor"
setvar $planetnames~PLANET_NAMES[67] "Toscanelli Major"
setvar $planetnames~PLANET_NAMES[68] "Hoover Minor"
setvar $planetnames~PLANET_NAMES[69] "Pangelinan Outpost"
setvar $planetnames~PLANET_NAMES[70] "Bethune Minor"
setvar $planetnames~PLANET_NAMES[71] "Fafnir"
setvar $planetnames~PLANET_NAMES[72] "Gideon Outpost"
setvar $planetnames~PLANET_NAMES[73] "Tajarhi Primus"
setvar $planetnames~PLANET_NAMES[74] "Catoblepas Major"
setvar $planetnames~PLANET_NAMES[75] "Steel Major"
setvar $planetnames~PLANET_NAMES[76] "Grey Mist"
setvar $planetnames~PLANET_NAMES[77] "Boreas Minor"
setvar $planetnames~PLANET_NAMES[78] "New Entrailia"
setvar $planetnames~PLANET_NAMES[79] "Saturn Primus"
setvar $planetnames~PLANET_NAMES[80] "Aerolone Major"
setvar $planetnames~PLANET_NAMES[81] "Camelot Primus"
setvar $planetnames~PLANET_NAMES[82] "Copus Outpost"
setvar $planetnames~PLANET_NAMES[83] "Bedoz Whispers"
setvar $planetnames~PLANET_NAMES[84] "Czar'ak II"
setvar $planetnames~PLANET_NAMES[85] "Mastro"
setvar $planetnames~PLANET_NAMES[86] "Venus Outpost"
setvar $planetnames~PLANET_NAMES[87] "New Io"
setvar $planetnames~PLANET_NAMES[88] "Tsox II"
setvar $planetnames~PLANET_NAMES[89] "Acropolis II"
setvar $planetnames~PLANET_NAMES[90] "CSM-101 Annex"
setvar $planetnames~PLANET_NAMES[91] "Apian II"
setvar $planetnames~PLANET_NAMES[92] "New Brodie"
setvar $planetnames~PLANET_NAMES[93] "Clone Annex"
setvar $planetnames~PLANET_NAMES[94] "K'hotan Major"
setvar $planetnames~PLANET_NAMES[95] "Indusium Primus"
setvar $planetnames~PLANET_NAMES[96] "Javelle Minor"
setvar $planetnames~PLANET_NAMES[97] "Gold Major"
setvar $planetnames~PLANET_NAMES[98] "New Poincare"
setvar $planetnames~PLANET_NAMES[99] "New Ohm"
setvar $planetnames~PLANET_NAMES[100] "Jeeves"
setvar $planetnames~PLANET_NAMES[101] "Ahriman Primus"
setvar $planetnames~PLANET_NAMES[102] "Bajor II"
setvar $planetnames~PLANET_NAMES[103] "Pickering Primus"
setvar $planetnames~PLANET_NAMES[104] "Pagoda Outpost"
setvar $planetnames~PLANET_NAMES[105] "Midgard"
setvar $planetnames~PLANET_NAMES[106] "New Lutum"
setvar $planetnames~PLANET_NAMES[107] "Curie Primus"
setvar $planetnames~PLANET_NAMES[108] "New Kerogen"
setvar $planetnames~PLANET_NAMES[109] "Brevico Outpost"
setvar $planetnames~PLANET_NAMES[110] "Cleisthenes Annex"
setvar $planetnames~PLANET_NAMES[111] "Banalg Primus"
setvar $planetnames~PLANET_NAMES[112] "Hiruko Primus"
setvar $planetnames~PLANET_NAMES[113] "New Canis Staz"
setvar $planetnames~PLANET_NAMES[114] "Herschel Prime"
setvar $planetnames~PLANET_NAMES[115] "Feesu Annex"
setvar $planetnames~PLANET_NAMES[116] "Sluagh Minor"
setvar $planetnames~PLANET_NAMES[117] "Acacia Primus"
setvar $planetnames~PLANET_NAMES[118] "Zagreus Minor"
setvar $planetnames~PLANET_NAMES[119] "Aud Outpost"
setvar $planetnames~PLANET_NAMES[120] "Leo Annex"
setvar $planetnames~PLANET_NAMES[121] "Inx Primus"
setvar $planetnames~PLANET_NAMES[122] "Plugh Major"
setvar $planetnames~PLANET_NAMES[123] "Keltcher II"
setvar $planetnames~PLANET_NAMES[124] "El Nath Major"
setvar $planetnames~PLANET_NAMES[125] "Thalim Outpost"
setvar $planetnames~PLANET_NAMES[126] "Achilles Annex"
setvar $planetnames~PLANET_NAMES[127] "New Janvier"
setvar $planetnames~PLANET_NAMES[128] "New Mare"
setvar $planetnames~PLANET_NAMES[129] "Osnabruck Minor"
setvar $planetnames~PLANET_NAMES[130] "New Atropine"
setvar $planetnames~PLANET_NAMES[131] "Hyksos Outpost"
setvar $planetnames~PLANET_NAMES[132] "Ionicus Annex"
setvar $planetnames~PLANET_NAMES[133] "Atwood Annex"
setvar $planetnames~PLANET_NAMES[134] "Ektron II"
setvar $planetnames~PLANET_NAMES[135] "New Debarre"
setvar $planetnames~PLANET_NAMES[136] "New Hubble"
setvar $planetnames~PLANET_NAMES[137] "Acridine Annex"
setvar $planetnames~PLANET_NAMES[138] "Atchison Annex"
setvar $planetnames~PLANET_NAMES[139] "Aeschylus Annex"
setvar $planetnames~PLANET_NAMES[140] "Triceratops II"
setvar $planetnames~PLANET_NAMES[141] "Ovid 962 Outpost"
setvar $planetnames~PLANET_NAMES[142] "Laon Annex"
setvar $planetnames~PLANET_NAMES[143] "Feesu II"
setvar $planetnames~PLANET_NAMES[144] "Pysadi Outpost"
setvar $planetnames~PLANET_NAMES[145] "Bansin II"
setvar $planetnames~PLANET_NAMES[146] "Grimaldi Outpost"
setvar $planetnames~PLANET_NAMES[147] "Kashyyyk Annex"
setvar $planetnames~PLANET_NAMES[148] "New Pickering"
setvar $planetnames~PLANET_NAMES[149] "Sardaukar"
setvar $planetnames~PLANET_NAMES[150] "Poritrin Annex"
setvar $planetnames~PLANET_NAMES[151] "Biela Minor"
setvar $planetnames~PLANET_NAMES[152] "Autun Minor"
setvar $planetnames~PLANET_NAMES[153] "Akira Primus"
setvar $planetnames~PLANET_NAMES[154] "Bohemia III"
setvar $planetnames~PLANET_NAMES[155] "Caspan Primus"
setvar $planetnames~PLANET_NAMES[156] "Barite Minor"
setvar $planetnames~PLANET_NAMES[157] "Loki Outpost"
setvar $planetnames~PLANET_NAMES[158] "Argos Primus"
setvar $planetnames~PLANET_NAMES[159] "Drake Annex"
setvar $planetnames~PLANET_NAMES[160] "Jaspilate Outpost"
setvar $planetnames~PLANET_NAMES[161] "New Tacaxeb"
setvar $planetnames~PLANET_NAMES[162] "Brevico Primus"
setvar $planetnames~PLANET_NAMES[163] "Bolivar Minor"
setvar $planetnames~PLANET_NAMES[164] "Trennen Major"
setvar $planetnames~PLANET_NAMES[165] "Bainite Annex"
setvar $planetnames~PLANET_NAMES[166] "Amber Primus"
setvar $planetnames~PLANET_NAMES[167] "Remorhaz"
setvar $planetnames~PLANET_NAMES[168] "Politzer"
setvar $planetnames~PLANET_NAMES[169] "Thisbe"
setvar $planetnames~PLANET_NAMES[170] "Ekinus"
setvar $planetnames~PLANET_NAMES[171] "Agamotto Annex"
setvar $planetnames~PLANET_NAMES[172] "Ixzotz"
setvar $planetnames~PLANET_NAMES[173] "Coliar"
setvar $planetnames~PLANET_NAMES[174] "Dragon Major"
setvar $planetnames~PLANET_NAMES[175] "Minimi Outpost"
setvar $planetnames~PLANET_NAMES[176] "Comani II"
setvar $planetnames~PLANET_NAMES[177] "Saladin Major"
setvar $planetnames~PLANET_NAMES[178] "New CSM-101"
setvar $planetnames~PLANET_NAMES[179] "Winston"
setvar $planetnames~PLANET_NAMES[180] "Putman Outpost"
setvar $planetnames~PLANET_NAMES[181] "Zarathrustra"
setvar $planetnames~PLANET_NAMES[182] "Bacchus Outpost"
setvar $planetnames~PLANET_NAMES[183] "Demantoid Annex"
setvar $planetnames~PLANET_NAMES[184] "Aarite Outpost"
setvar $planetnames~PLANET_NAMES[185] "Langres Primus"
setvar $planetnames~PLANET_NAMES[186] "New Myk"
setvar $planetnames~PLANET_NAMES[187] "Castalia Minor"
setvar $planetnames~PLANET_NAMES[188] "Feyd Major"
setvar $planetnames~PLANET_NAMES[189] "Gauss"
setvar $planetnames~PLANET_NAMES[190] "Adurol Primus"
setvar $planetnames~PLANET_NAMES[191] "Pingos Annex"
setvar $planetnames~PLANET_NAMES[192] "Shih Hwang-ti Major"
setvar $planetnames~PLANET_NAMES[193] "Homonculous Annex"
setvar $planetnames~PLANET_NAMES[194] "Calandra Annex"
setvar $planetnames~PLANET_NAMES[195] "Tartarus Minor"
setvar $planetnames~PLANET_NAMES[196] "Njord Major"
setvar $planetnames~PLANET_NAMES[197] "Melusine II"
setvar $planetnames~PLANET_NAMES[198] "Cepheus"
setvar $planetnames~PLANET_NAMES[199] "Huggins Primus"
setvar $planetnames~PLANET_NAMES[200] "Buchanan"
setvar $planetnames~PLANET_NAMES[201] "Bleigh Outpost"
setvar $planetnames~PLANET_NAMES[202] "Abohm Annex"
setvar $planetnames~PLANET_NAMES[203] "Freaque Primus"
setvar $planetnames~PLANET_NAMES[204] "Bespin Outpost"
setvar $planetnames~PLANET_NAMES[205] "Shklovsky"
setvar $planetnames~PLANET_NAMES[206] "Heimdall Minor"
setvar $planetnames~PLANET_NAMES[207] "New Bentylol"
setvar $planetnames~PLANET_NAMES[208] "Lebeau"
setvar $planetnames~PLANET_NAMES[209] "New Siva"
setvar $planetnames~PLANET_NAMES[210] "Biggs Outpost"
setvar $planetnames~PLANET_NAMES[211] "Auroran Major"
setvar $planetnames~PLANET_NAMES[212] "Phoenix"
setvar $planetnames~PLANET_NAMES[213] "Chaeta Major"
setvar $planetnames~PLANET_NAMES[214] "Anacel Minor"
setvar $planetnames~PLANET_NAMES[215] "Zeycude Minor"
setvar $planetnames~PLANET_NAMES[216] "Akarso Major"
setvar $planetnames~PLANET_NAMES[217] "Bifrost Primus"
setvar $planetnames~PLANET_NAMES[218] "Jolotre Outpost"
setvar $planetnames~PLANET_NAMES[219] "New Tutankhamen"
setvar $planetnames~PLANET_NAMES[220] "Adams Outpost"
setvar $planetnames~PLANET_NAMES[221] "Feynman Minor"
setvar $planetnames~PLANET_NAMES[222] "Grant Primus"
setvar $planetnames~PLANET_NAMES[223] "Aeon Primus"
setvar $planetnames~PLANET_NAMES[224] "Sacajawea Minor"
setvar $planetnames~PLANET_NAMES[225] "Thor Outpost"
setvar $planetnames~PLANET_NAMES[226] "New Kashyyyk"
setvar $planetnames~PLANET_NAMES[227] "Underwood Minor"
setvar $planetnames~PLANET_NAMES[228] "Yukawa Major"
setvar $planetnames~PLANET_NAMES[229] "Feesu Minor"
setvar $planetnames~PLANET_NAMES[230] "Accurbron Major"
setvar $planetnames~PLANET_NAMES[231] "Parthenon Major"
setvar $planetnames~PLANET_NAMES[232] "Calan Outpost"
setvar $planetnames~PLANET_NAMES[233] "Tali Annex"
setvar $planetnames~PLANET_NAMES[234] "Cogri Outpost"
setvar $planetnames~PLANET_NAMES[235] "Atwood Minor"
setvar $planetnames~PLANET_NAMES[236] "Aldebaran"
setvar $planetnames~PLANET_NAMES[237] "New Atreides"
setvar $planetnames~PLANET_NAMES[238] "Abae Annex"
setvar $planetnames~PLANET_NAMES[239] "Aurva Primus"
setvar $planetnames~PLANET_NAMES[240] "Pogson Primus"
setvar $planetnames~PLANET_NAMES[241] "Degtyarev Major"
setvar $planetnames~PLANET_NAMES[242] "Wollaston"
setvar $planetnames~PLANET_NAMES[243] "Eagle Annex"
setvar $planetnames~PLANET_NAMES[244] "Atacon Annex"
setvar $planetnames~PLANET_NAMES[245] "Lanth Major"
setvar $planetnames~PLANET_NAMES[246] "Reber Primus"
setvar $planetnames~PLANET_NAMES[247] "Aleph Minor"
setvar $planetnames~PLANET_NAMES[248] "Dollond"
setvar $planetnames~PLANET_NAMES[249] "H'Catha Minor"
setvar $planetnames~PLANET_NAMES[250] "New Bacta"
setvar $planetnames~PLANET_NAMES[251] "Galina Annex"
setvar $planetnames~PLANET_NAMES[252] "New Nadrin"
setvar $planetnames~PLANET_NAMES[253] "Ajacs Primus"
setvar $planetnames~PLANET_NAMES[254] "Holland Annex"
setvar $planetnames~PLANET_NAMES[255] "New Baraka"
setvar $planetnames~PLANET_NAMES[256] "Alencika Minor"
setvar $planetnames~PLANET_NAMES[257] "Wypoc"
setvar $planetnames~PLANET_NAMES[258] "Mytus Major"
setvar $planetnames~PLANET_NAMES[259] "Garuda Outpost"
setvar $planetnames~PLANET_NAMES[260] "Nog Outpost"
setvar $planetnames~PLANET_NAMES[261] "Arcturus Annex"
setvar $planetnames~PLANET_NAMES[262] "El Cid II"
setvar $planetnames~PLANET_NAMES[263] "Autun"
setvar $planetnames~PLANET_NAMES[264] "Omega Major"
setvar $planetnames~PLANET_NAMES[265] "Antike Outpost"
setvar $planetnames~PLANET_NAMES[266] "Triceratops Primus"
setvar $planetnames~PLANET_NAMES[267] "Caladan II"
setvar $planetnames~PLANET_NAMES[268] "Gnosis II"
setvar $planetnames~PLANET_NAMES[269] "Freedom"
setvar $planetnames~PLANET_NAMES[270] "Solomon Primus"
setvar $planetnames~PLANET_NAMES[271] "Flamarion Major"
setvar $planetnames~PLANET_NAMES[272] "Massassi Minor"
setvar $planetnames~PLANET_NAMES[273] "Baclofin Major"
setvar $planetnames~PLANET_NAMES[274] "New Berubigen"
setvar $planetnames~PLANET_NAMES[275] "Hydra"
setvar $planetnames~PLANET_NAMES[276] "Ylaven Annex"
setvar $planetnames~PLANET_NAMES[277] "Shcawbe"
setvar $planetnames~PLANET_NAMES[278] "Dallia Primus"
setvar $planetnames~PLANET_NAMES[279] "New FerNics"
setvar $planetnames~PLANET_NAMES[280] "Cyzicus Outpost"
setvar $planetnames~PLANET_NAMES[281] "Belenus"
setvar $planetnames~PLANET_NAMES[282] "Kudu Minor"
setvar $planetnames~PLANET_NAMES[283] "Shadout"
setvar $planetnames~PLANET_NAMES[284] "Tetanus Major"
setvar $planetnames~PLANET_NAMES[285] "Mecha Major"
setvar $planetnames~PLANET_NAMES[286] "Blunderbuss Outpost"
setvar $planetnames~PLANET_NAMES[287] "Castile"
setvar $planetnames~PLANET_NAMES[288] "Dollond Annex"
setvar $planetnames~PLANET_NAMES[289] "Condyole II"
setvar $planetnames~PLANET_NAMES[290] "Benemid Outpost"
setvar $planetnames~PLANET_NAMES[291] "New Kether"
setvar $planetnames~PLANET_NAMES[292] "Scarabaeus"
setvar $planetnames~PLANET_NAMES[293] "Spector Major"
setvar $planetnames~PLANET_NAMES[294] "Nambu Annex"
setvar $planetnames~PLANET_NAMES[295] "Yamoto II"
setvar $planetnames~PLANET_NAMES[296] "Lockyer Major"
setvar $planetnames~PLANET_NAMES[297] "New Huggins"
setvar $planetnames~PLANET_NAMES[298] "Gorram"
setvar $planetnames~PLANET_NAMES[299] "Minimi Minor"
setvar $planetnames~PLANET_NAMES[300] "Sorel Major"
setvar $planetnames~PLANET_NAMES[301] "El Nath Primus"
setvar $planetnames~PLANET_NAMES[302] "Lumineaux Outpost"
setvar $planetnames~PLANET_NAMES[303] "Richter Primus"
setvar $planetnames~PLANET_NAMES[304] "Ilianeou"
setvar $planetnames~PLANET_NAMES[305] "Xyvitix Annex"
setvar $planetnames~PLANET_NAMES[306] "Benisone Minor"
setvar $planetnames~PLANET_NAMES[307] "Fanning"
setvar $planetnames~PLANET_NAMES[308] "Flamsteed"
setvar $planetnames~PLANET_NAMES[309] "Shklovsky Primus"
setvar $planetnames~PLANET_NAMES[310] "Toshi Annex"
setvar $planetnames~PLANET_NAMES[311] "New Bumex"
setvar $planetnames~PLANET_NAMES[312] "Noirmoutier"
setvar $planetnames~PLANET_NAMES[313] "Macross"
setvar $planetnames~PLANET_NAMES[314] "Du Fay Major"
setvar $planetnames~PLANET_NAMES[315] "Ross Outpost"
setvar $planetnames~PLANET_NAMES[316] "Xi Primus"
setvar $planetnames~PLANET_NAMES[317] "Leyline II"
setvar $planetnames~PLANET_NAMES[318] "Vergil Minor"
setvar $planetnames~PLANET_NAMES[319] "Diocletian Outpost"
setvar $planetnames~PLANET_NAMES[320] "Eisenhower Minor"
setvar $planetnames~PLANET_NAMES[321] "Cithaeron Annex"
setvar $planetnames~PLANET_NAMES[322] "Pockels Major"
setvar $planetnames~PLANET_NAMES[323] "Rangent Major"
setvar $planetnames~PLANET_NAMES[324] "Pascal Annex"
setvar $planetnames~PLANET_NAMES[325] "Avitene Primus"
setvar $planetnames~PLANET_NAMES[326] "Fantasia Primus"
setvar $planetnames~PLANET_NAMES[327] "Baridium II"
setvar $planetnames~PLANET_NAMES[328] "Von Zacjh II"
setvar $planetnames~PLANET_NAMES[329] "Jasmine Annex"
setvar $planetnames~PLANET_NAMES[330] "Bagasse II"
setvar $planetnames~PLANET_NAMES[331] "Wern"
setvar $planetnames~PLANET_NAMES[332] "Tenelphi Primus"
setvar $planetnames~PLANET_NAMES[333] "Elmarin Major"
setvar $planetnames~PLANET_NAMES[334] "New Rech"
setvar $planetnames~PLANET_NAMES[335] "Massassi Major"
setvar $planetnames~PLANET_NAMES[336] "Tintao"
setvar $planetnames~PLANET_NAMES[337] "Engadine II"
setvar $planetnames~PLANET_NAMES[338] "New Ektron"
setvar $planetnames~PLANET_NAMES[339] "Ochecate"
setvar $planetnames~PLANET_NAMES[340] "Peleus Minor"
setvar $planetnames~PLANET_NAMES[341] "Balboa Minor"
setvar $planetnames~PLANET_NAMES[342] "New Phobos"
setvar $planetnames~PLANET_NAMES[343] "Elmarin II"
setvar $planetnames~PLANET_NAMES[344] "Garion Primus"
setvar $planetnames~PLANET_NAMES[345] "Sharrip Major"
setvar $planetnames~PLANET_NAMES[346] "Breughel"
setvar $planetnames~PLANET_NAMES[347] "Eisenhower II"
setvar $planetnames~PLANET_NAMES[348] "Cusa II"
setvar $planetnames~PLANET_NAMES[349] "Bralgu Annex"
setvar $planetnames~PLANET_NAMES[350] "Copernicus II"
setvar $planetnames~PLANET_NAMES[351] "Putman Annex"
setvar $planetnames~PLANET_NAMES[352] "Pylus Minor"
setvar $planetnames~PLANET_NAMES[353] "Alkaid"
setvar $planetnames~PLANET_NAMES[354] "Proudelxak Primus"
setvar $planetnames~PLANET_NAMES[355] "Putman II"
setvar $planetnames~PLANET_NAMES[356] "Ganymede Major"
setvar $planetnames~PLANET_NAMES[357] "Hotchkiss II"
setvar $planetnames~PLANET_NAMES[358] "Eikonal Primus"
setvar $planetnames~PLANET_NAMES[359] "New Nelson"
setvar $planetnames~PLANET_NAMES[360] "Behemoth Annex"
setvar $planetnames~PLANET_NAMES[361] "Daleth"
setvar $planetnames~PLANET_NAMES[362] "Circe Primus"
setvar $planetnames~PLANET_NAMES[363] "Ueilerm Annex"
setvar $planetnames~PLANET_NAMES[364] "Winston Primus"
setvar $planetnames~PLANET_NAMES[365] "Roentgen II"
setvar $planetnames~PLANET_NAMES[366] "New Bentyl"
setvar $planetnames~PLANET_NAMES[367] "Bainite Primus"
setvar $planetnames~PLANET_NAMES[368] "Uranus Minor"
setvar $planetnames~PLANET_NAMES[369] "Triumviri Outpost"
setvar $planetnames~PLANET_NAMES[370] "Dearth Minor"
setvar $planetnames~PLANET_NAMES[371] "Quare Minor"
setvar $planetnames~PLANET_NAMES[372] "Ariel II"
setvar $planetnames~PLANET_NAMES[373] "Agamotto"
setvar $planetnames~PLANET_NAMES[374] "Mithras II"
setvar $planetnames~PLANET_NAMES[375] "Agena II"
setvar $planetnames~PLANET_NAMES[376] "Anchorhead Minor"
setvar $planetnames~PLANET_NAMES[377] "Atarax Major"
setvar $planetnames~PLANET_NAMES[378] "T'xe"
setvar $planetnames~PLANET_NAMES[379] "Fedaykin Major"
setvar $planetnames~PLANET_NAMES[380] "Kai Outpost"
setvar $planetnames~PLANET_NAMES[381] "Pompey Major"
setvar $planetnames~PLANET_NAMES[382] "Jarsone Major"
setvar $planetnames~PLANET_NAMES[383] "Percy 1640 Major"
setvar $planetnames~PLANET_NAMES[384] "Kraken Outpost"
setvar $planetnames~PLANET_NAMES[385] "Tiree"
setvar $planetnames~PLANET_NAMES[386] "New Corbiet"
setvar $planetnames~PLANET_NAMES[387] "Celepina Minor"
setvar $planetnames~PLANET_NAMES[388] "Augustus Annex"
setvar $planetnames~PLANET_NAMES[389] "New H'Catha"
setvar $planetnames~PLANET_NAMES[390] "New Aldrin"
setvar $planetnames~PLANET_NAMES[391] "Bacarate II"
setvar $planetnames~PLANET_NAMES[392] "Drude II"
setvar $planetnames~PLANET_NAMES[393] "Millennium"
setvar $planetnames~PLANET_NAMES[394] "Kwisatz"
setvar $planetnames~PLANET_NAMES[395] "Rebka"
setvar $planetnames~PLANET_NAMES[396] "Rebka II"
setvar $planetnames~PLANET_NAMES[397] "Flamsteed Outpost"
setvar $planetnames~PLANET_NAMES[398] "Garibaldi Minor"
setvar $planetnames~PLANET_NAMES[399] "Hounstyr Annex"
setvar $planetnames~PLANET_NAMES[400] "Flinte"
setvar $planetnames~PLANET_NAMES[401] "Dodonna Major"
setvar $planetnames~PLANET_NAMES[402] "Ueilerm Minor"
setvar $planetnames~PLANET_NAMES[403] "Kaula"
setvar $planetnames~PLANET_NAMES[404] "Orkney Outpost"
setvar $planetnames~PLANET_NAMES[405] "Appollyon Primus"
setvar $planetnames~PLANET_NAMES[406] "New Natoko"
setvar $planetnames~PLANET_NAMES[407] "Heroni Major"
setvar $planetnames~PLANET_NAMES[408] "Haderach Primus"
setvar $planetnames~PLANET_NAMES[409] "Dinom Major"
setvar $planetnames~PLANET_NAMES[410] "Darion Minor"
setvar $planetnames~PLANET_NAMES[411] "Medusa II"
setvar $planetnames~PLANET_NAMES[412] "Kaladan Outpost"
setvar $planetnames~PLANET_NAMES[413] "Kep Salu Annex"
setvar $planetnames~PLANET_NAMES[414] "New Minos"
setvar $planetnames~PLANET_NAMES[415] "Jeeves Major"
setvar $planetnames~PLANET_NAMES[416] "Exodus"
setvar $planetnames~PLANET_NAMES[417] "Euler Annex"
setvar $planetnames~PLANET_NAMES[418] "Capricornus II"
setvar $planetnames~PLANET_NAMES[419] "Milan Primus"
setvar $planetnames~PLANET_NAMES[420] "Beben Outpost"
setvar $planetnames~PLANET_NAMES[421] "New Kohlrausch"
setvar $planetnames~PLANET_NAMES[422] "Brombay"
setvar $planetnames~PLANET_NAMES[423] "Alvarado Minor"
setvar $planetnames~PLANET_NAMES[424] "New Franchi"
setvar $planetnames~PLANET_NAMES[425] "Melior"
setvar $planetnames~PLANET_NAMES[426] "Atrivis"
setvar $planetnames~PLANET_NAMES[427] "Lepton II"
setvar $planetnames~PLANET_NAMES[428] "Dyson Outpost"
setvar $planetnames~PLANET_NAMES[429] "Feyd Outpost"
setvar $planetnames~PLANET_NAMES[430] "Wypoc II"
setvar $planetnames~PLANET_NAMES[431] "Peridot Primus"
setvar $planetnames~PLANET_NAMES[432] "Yona II"
setvar $planetnames~PLANET_NAMES[433] "Caduceus Major"
setvar $planetnames~PLANET_NAMES[434] "Kruhious II"
setvar $planetnames~PLANET_NAMES[435] "Melior Outpost"
setvar $planetnames~PLANET_NAMES[436] "Ryloth Major"
setvar $planetnames~PLANET_NAMES[437] "Becquerel Annex"
setvar $planetnames~PLANET_NAMES[438] "Intrepid"
setvar $planetnames~PLANET_NAMES[439] "Gascogne Annex"
setvar $planetnames~PLANET_NAMES[440] "Free State II"
setvar $planetnames~PLANET_NAMES[441] "Ozawa Minor"
setvar $planetnames~PLANET_NAMES[442] "Mewey Primus"
setvar $planetnames~PLANET_NAMES[443] "Xylene Outpost"
setvar $planetnames~PLANET_NAMES[444] "Pohl Annex"
setvar $planetnames~PLANET_NAMES[445] "Absarokite"
setvar $planetnames~PLANET_NAMES[446] "Phardos Annex"
setvar $planetnames~PLANET_NAMES[447] "Axolotl Minor"
setvar $planetnames~PLANET_NAMES[448] "van der Waals Primus"
setvar $planetnames~PLANET_NAMES[449] "Hydropon"
setvar $planetnames~PLANET_NAMES[450] "Tesla Minor"
setvar $planetnames~PLANET_NAMES[451] "Kender Annex"
setvar $planetnames~PLANET_NAMES[452] "Aphrodite Primus"
setvar $planetnames~PLANET_NAMES[453] "New Addax"
setvar $planetnames~PLANET_NAMES[454] "New Castile"
setvar $planetnames~PLANET_NAMES[455] "Atlas Major"
setvar $planetnames~PLANET_NAMES[456] "Van de Graaff II"
setvar $planetnames~PLANET_NAMES[457] "Chrysa II"
setvar $planetnames~PLANET_NAMES[458] "Dirac Outpost"
setvar $planetnames~PLANET_NAMES[459] "Aachen Annex"
setvar $planetnames~PLANET_NAMES[460] "Skinfaxi II"
setvar $planetnames~PLANET_NAMES[461] "Carthage Primus"
setvar $planetnames~PLANET_NAMES[462] "Elmarin Outpost"
setvar $planetnames~PLANET_NAMES[463] "Mikado Primus"
setvar $planetnames~PLANET_NAMES[464] "Rydberg Minor"
setvar $planetnames~PLANET_NAMES[465] "Hallwachs Major"
setvar $planetnames~PLANET_NAMES[466] "Banderlog Major"
setvar $planetnames~PLANET_NAMES[467] "New Grosseteste"
setvar $planetnames~PLANET_NAMES[468] "Caliver II"
setvar $planetnames~PLANET_NAMES[469] "Jokwa Primus"
setvar $planetnames~PLANET_NAMES[470] "New Auxerre"
setvar $planetnames~PLANET_NAMES[471] "Demilich"
setvar $planetnames~PLANET_NAMES[472] "New Karelia"
setvar $planetnames~PLANET_NAMES[473] "Rueschhoff"
setvar $planetnames~PLANET_NAMES[474] "Taro Minor"
setvar $planetnames~PLANET_NAMES[475] "Dianoga Annex"
setvar $planetnames~PLANET_NAMES[476] "Quevedo Major"
setvar $planetnames~PLANET_NAMES[477] "New Leviathan"
setvar $planetnames~PLANET_NAMES[478] "Raydrad Primus"
setvar $planetnames~PLANET_NAMES[479] "New Daleth"
setvar $planetnames~PLANET_NAMES[480] "Metztla'Xym"
setvar $planetnames~PLANET_NAMES[481] "Aix-la-Chapelle Annex"
setvar $planetnames~PLANET_NAMES[482] "Spume Outpost"
setvar $planetnames~PLANET_NAMES[483] "Lysander II"
setvar $planetnames~PLANET_NAMES[484] "Simorg Minor"
setvar $planetnames~PLANET_NAMES[485] "Van Maanen Outpost"
setvar $planetnames~PLANET_NAMES[486] "Alexander II"
setvar $planetnames~PLANET_NAMES[487] "Istar Annex"
setvar $planetnames~PLANET_NAMES[488] "Crecy Major"
setvar $planetnames~PLANET_NAMES[489] "Bethune Outpost"
setvar $planetnames~PLANET_NAMES[490] "Cittert Major"
setvar $planetnames~PLANET_NAMES[491] "Edinina II"
setvar $planetnames~PLANET_NAMES[492] "Imbrium"
setvar $planetnames~PLANET_NAMES[493] "New Tycho"
setvar $planetnames~PLANET_NAMES[494] "Nordenfelt Annex"
setvar $planetnames~PLANET_NAMES[495] "Dixon Primus"
setvar $planetnames~PLANET_NAMES[496] "Biggs Major"
setvar $planetnames~PLANET_NAMES[497] "Far Station II"
setvar $planetnames~PLANET_NAMES[498] "Puparkin II"
setvar $planetnames~PLANET_NAMES[499] "New Duras"
setvar $planetnames~PLANET_NAMES[500] "Freedom II"
setvar $planetnames~PLANET_NAMES[501] "Ardonyx Major"
setvar $planetnames~PLANET_NAMES[502] "Focaline Major"
setvar $planetnames~PLANET_NAMES[503] "Jacent II"
setvar $planetnames~PLANET_NAMES[504] "Jimson Primus"
setvar $planetnames~PLANET_NAMES[505] "Andromeda Primus"
setvar $planetnames~PLANET_NAMES[506] "Adenine Outpost"
setvar $planetnames~PLANET_NAMES[507] "Ampere Major"
setvar $planetnames~PLANET_NAMES[508] "Cordoba Major"
setvar $planetnames~PLANET_NAMES[509] "Garion Major"
setvar $planetnames~PLANET_NAMES[510] "Gormenghast Primus"
setvar $planetnames~PLANET_NAMES[511] "Roxana II"
setvar $planetnames~PLANET_NAMES[512] "New Duriron"
setvar $planetnames~PLANET_NAMES[513] "Islip Annex"
setvar $planetnames~PLANET_NAMES[514] "New Powaza"
setvar $planetnames~PLANET_NAMES[515] "Thisbe II"
setvar $planetnames~PLANET_NAMES[516] "Ney Annex"
setvar $planetnames~PLANET_NAMES[517] "Phlogiston Annex"
setvar $planetnames~PLANET_NAMES[518] "Ganymede II"
setvar $planetnames~PLANET_NAMES[519] "Joshi Major"
setvar $planetnames~PLANET_NAMES[520] "Hajj Annex"
setvar $planetnames~PLANET_NAMES[521] "Aceta Major"
setvar $planetnames~PLANET_NAMES[522] "Idris II"
setvar $planetnames~PLANET_NAMES[523] "New Gelugon"
setvar $planetnames~PLANET_NAMES[524] "Shai-Hulud II"
setvar $planetnames~PLANET_NAMES[525] "Towers Major"
setvar $planetnames~PLANET_NAMES[526] "Tulan Primus"
setvar $planetnames~PLANET_NAMES[527] "Massassi Primus"
setvar $planetnames~PLANET_NAMES[528] "Taaug Annex"
setvar $planetnames~PLANET_NAMES[529] "Baruch Outpost"
setvar $planetnames~PLANET_NAMES[530] "Castalia"
setvar $planetnames~PLANET_NAMES[531] "Penkwhar Outpost"
setvar $planetnames~PLANET_NAMES[532] "Baugi Outpost"
setvar $planetnames~PLANET_NAMES[533] "Draconis Outpost"
setvar $planetnames~PLANET_NAMES[534] "Crimson II"
setvar $planetnames~PLANET_NAMES[535] "Smoug Major"
setvar $planetnames~PLANET_NAMES[536] "Asmussen Primus"
setvar $planetnames~PLANET_NAMES[537] "Oort"
setvar $planetnames~PLANET_NAMES[538] "Rousseau Major"
setvar $planetnames~PLANET_NAMES[539] "Lahara Outpost"
setvar $planetnames~PLANET_NAMES[540] "Belemmite Primus"
setvar $planetnames~PLANET_NAMES[541] "Mainz Outpost"
setvar $planetnames~PLANET_NAMES[542] "Corbino Outpost"
setvar $planetnames~PLANET_NAMES[543] "Tanar'ri Major"
setvar $planetnames~PLANET_NAMES[544] "Conway"
setvar $planetnames~PLANET_NAMES[545] "Raweh II"
setvar $planetnames~PLANET_NAMES[546] "New Hefry"
setvar $planetnames~PLANET_NAMES[547] "Pinus Nigra Annex"
setvar $planetnames~PLANET_NAMES[548] "Celepina Primus"
setvar $planetnames~PLANET_NAMES[549] "Zaire Outpost"
setvar $planetnames~PLANET_NAMES[550] "Medusa Annex"
setvar $planetnames~PLANET_NAMES[551] "Tyrfing Outpost"
setvar $planetnames~PLANET_NAMES[552] "Gormenghast Minor"
setvar $planetnames~PLANET_NAMES[553] "Iliopoulos Annex"
setvar $planetnames~PLANET_NAMES[554] "New Sacha"
setvar $planetnames~PLANET_NAMES[555] "Tulan Outpost"
setvar $planetnames~PLANET_NAMES[556] "Chaucer Primus"
setvar $planetnames~PLANET_NAMES[557] "Carbonara Major"
setvar $planetnames~PLANET_NAMES[558] "Zivije Minor"
setvar $planetnames~PLANET_NAMES[559] "New Grant"
setvar $planetnames~PLANET_NAMES[560] "Hadron Annex"
setvar $planetnames~PLANET_NAMES[561] "New Chattur"
setvar $planetnames~PLANET_NAMES[562] "Simeon Outpost"
setvar $planetnames~PLANET_NAMES[563] "Moriarity Major"
setvar $planetnames~PLANET_NAMES[564] "Heisenberg Outpost"
setvar $planetnames~PLANET_NAMES[565] "Vingolf Major"
setvar $planetnames~PLANET_NAMES[566] "Mammon Outpost"
setvar $planetnames~PLANET_NAMES[567] "Ceres Outpost"
setvar $planetnames~PLANET_NAMES[568] "Mantene"
setvar $planetnames~PLANET_NAMES[569] "Capon Annex"
setvar $planetnames~PLANET_NAMES[570] "Pockels Outpost"
setvar $planetnames~PLANET_NAMES[571] "New Valiant"
setvar $planetnames~PLANET_NAMES[572] "Buchanan II"
setvar $planetnames~PLANET_NAMES[573] "Bevey Minor"
setvar $planetnames~PLANET_NAMES[574] "New DarGer"
setvar $planetnames~PLANET_NAMES[575] "Tatooine Primus"
setvar $planetnames~PLANET_NAMES[576] "Rabwhar Primus"
setvar $planetnames~PLANET_NAMES[577] "Trin Minor"
setvar $planetnames~PLANET_NAMES[578] "Tyr Annex"
setvar $planetnames~PLANET_NAMES[579] "Klystron"
setvar $planetnames~PLANET_NAMES[580] "Zamine"
setvar $planetnames~PLANET_NAMES[581] "Canis Staz II"
setvar $planetnames~PLANET_NAMES[582] "Gungnir Minor"
setvar $planetnames~PLANET_NAMES[583] "Alupent Major"
setvar $planetnames~PLANET_NAMES[584] "Gideon Minor"
setvar $planetnames~PLANET_NAMES[585] "Raweh Annex"
setvar $planetnames~PLANET_NAMES[586] "Kamerlingh Annex"
setvar $planetnames~PLANET_NAMES[587] "Camazotz Minor"
setvar $planetnames~PLANET_NAMES[588] "Aeolus II"
setvar $planetnames~PLANET_NAMES[589] "Grant Annex"
setvar $planetnames~PLANET_NAMES[590] "Betelgeuse"
setvar $planetnames~PLANET_NAMES[591] "New Dammar"
setvar $planetnames~PLANET_NAMES[592] "Ursula"
setvar $planetnames~PLANET_NAMES[593] "Fermi Minor"
setvar $planetnames~PLANET_NAMES[594] "New Mewey"
setvar $planetnames~PLANET_NAMES[595] "Elixabeth Outpost"
setvar $planetnames~PLANET_NAMES[596] "Glashow II"
setvar $planetnames~PLANET_NAMES[597] "Inchin"
setvar $planetnames~PLANET_NAMES[598] "Antike"
setvar $planetnames~PLANET_NAMES[599] "Iliopoulos Primus"
setvar $planetnames~PLANET_NAMES[600] "Sigma Annex"
setvar $planetnames~PLANET_NAMES[601] "Tetanus II"
setvar $planetnames~PLANET_NAMES[602] "New Laika"
setvar $planetnames~PLANET_NAMES[603] "Lorentz"
setvar $planetnames~PLANET_NAMES[604] "Hefry"
setvar $planetnames~PLANET_NAMES[605] "Smoug Annex"
setvar $planetnames~PLANET_NAMES[606] "New Rutledge"
setvar $planetnames~PLANET_NAMES[607] "Knossos"
setvar $planetnames~PLANET_NAMES[608] "Cyclone II"
setvar $planetnames~PLANET_NAMES[609] "New Milan"
setvar $planetnames~PLANET_NAMES[610] "Mammon Major"
setvar $planetnames~PLANET_NAMES[611] "Indium II"
setvar $planetnames~PLANET_NAMES[612] "Tleilaxu Annex"
setvar $planetnames~PLANET_NAMES[613] "Krosec II"
setvar $planetnames~PLANET_NAMES[614] "New Surplus"
setvar $planetnames~PLANET_NAMES[615] "Aerolone Primus"
setvar $planetnames~PLANET_NAMES[616] "Nerewhon Outpost"
setvar $planetnames~PLANET_NAMES[617] "Trexalon Primus"
setvar $planetnames~PLANET_NAMES[618] "Spider Primus"
setvar $planetnames~PLANET_NAMES[619] "Ontalak"
setvar $planetnames~PLANET_NAMES[620] "Benemid Minor"
setvar $planetnames~PLANET_NAMES[621] "Belenus Primus"
setvar $planetnames~PLANET_NAMES[622] "Bismarck"
setvar $planetnames~PLANET_NAMES[623] "New Carson"
setvar $planetnames~PLANET_NAMES[624] "Rayl Major"
setvar $planetnames~PLANET_NAMES[625] "New Fedaykin"
setvar $planetnames~PLANET_NAMES[626] "Ent II"
setvar $planetnames~PLANET_NAMES[627] "Cetacean II"
setvar $planetnames~PLANET_NAMES[628] "Artemis"
setvar $planetnames~PLANET_NAMES[629] "Shakespeare Major"
setvar $planetnames~PLANET_NAMES[630] "Pepin Minor"
setvar $planetnames~PLANET_NAMES[631] "Priedo Annex"
setvar $planetnames~PLANET_NAMES[632] "Ryloth Annex"
setvar $planetnames~PLANET_NAMES[633] "Pangelinan Annex"
setvar $planetnames~PLANET_NAMES[634] "Arels II"
setvar $planetnames~PLANET_NAMES[635] "Epsilon Major"
setvar $planetnames~PLANET_NAMES[636] "Bayer Primus"
setvar $planetnames~PLANET_NAMES[637] "Kruger Outpost"
setvar $planetnames~PLANET_NAMES[638] "Chandrasekher Outpost"
setvar $planetnames~PLANET_NAMES[639] "Imbrium Major"
setvar $planetnames~PLANET_NAMES[640] "New Jolotre"
setvar $planetnames~PLANET_NAMES[641] "Dearth II"
setvar $planetnames~PLANET_NAMES[642] "New Hallwachs"
setvar $planetnames~PLANET_NAMES[643] "Hounstyr II"
setvar $planetnames~PLANET_NAMES[644] "Niepce Primus"
setvar $planetnames~PLANET_NAMES[645] "Minddagger's Throne"
setvar $planetnames~PLANET_NAMES[646] "Carnot Outpost"
setvar $planetnames~PLANET_NAMES[647] "Diancecht Outpost"
setvar $planetnames~PLANET_NAMES[648] "Gormenghast Annex"
setvar $planetnames~PLANET_NAMES[649] "Adansonia Primus"
setvar $planetnames~PLANET_NAMES[650] "Tolchock Primus"
setvar $planetnames~PLANET_NAMES[651] "Cordwainer"
setvar $planetnames~PLANET_NAMES[652] "Rahman Primus"
setvar $planetnames~PLANET_NAMES[653] "Amicar Outpost"
setvar $planetnames~PLANET_NAMES[654] "Galahad II"
setvar $planetnames~PLANET_NAMES[655] "New Khancuhn"
setvar $planetnames~PLANET_NAMES[656] "Glyth Major"
setvar $planetnames~PLANET_NAMES[657] "Dolldus Major"
setvar $planetnames~PLANET_NAMES[658] "Reigar Outpost"
setvar $planetnames~PLANET_NAMES[659] "Aristophanes"
setvar $planetnames~PLANET_NAMES[660] "Foelen"
setvar $planetnames~PLANET_NAMES[661] "Gagarin Annex"
setvar $planetnames~PLANET_NAMES[662] "Yucca"
setvar $planetnames~PLANET_NAMES[663] "Earwig"
setvar $planetnames~PLANET_NAMES[664] "Ithaca Primus"
setvar $planetnames~PLANET_NAMES[665] "El Cid Annex"
setvar $planetnames~PLANET_NAMES[666] "Geronimo Outpost"
setvar $planetnames~PLANET_NAMES[667] "Couatl Minor"
setvar $planetnames~PLANET_NAMES[668] "New Kahn"
setvar $planetnames~PLANET_NAMES[669] "New Acetylene"
setvar $planetnames~PLANET_NAMES[670] "Nebuchadnezzar Annex"
setvar $planetnames~PLANET_NAMES[671] "Jimson Minor"
setvar $planetnames~PLANET_NAMES[672] "Iota Outpost"
setvar $planetnames~PLANET_NAMES[673] "Carse II"
setvar $planetnames~PLANET_NAMES[674] "Opus Outpost"
setvar $planetnames~PLANET_NAMES[675] "Smekal"
setvar $planetnames~PLANET_NAMES[676] "Ypsilon Primus"
setvar $planetnames~PLANET_NAMES[677] "New Auralgan"
setvar $planetnames~PLANET_NAMES[678] "Nin'arth Minor"
setvar $planetnames~PLANET_NAMES[679] "Hohenstaufen II"
setvar $planetnames~PLANET_NAMES[680] "Hefry Major"
setvar $planetnames~PLANET_NAMES[681] "Faust Outpost"
setvar $planetnames~PLANET_NAMES[682] "New Hagal"
setvar $planetnames~PLANET_NAMES[683] "IronWollobick Annex"
setvar $planetnames~PLANET_NAMES[684] "Sisko Minor"
setvar $planetnames~PLANET_NAMES[685] "Piazzi Minor"
setvar $planetnames~PLANET_NAMES[686] "Mirazh II"
setvar $planetnames~PLANET_NAMES[687] "Myk Outpost"
setvar $planetnames~PLANET_NAMES[688] "Bumex Minor"
setvar $planetnames~PLANET_NAMES[689] "Feyd II"
setvar $planetnames~PLANET_NAMES[690] "Hadron Major"
setvar $planetnames~PLANET_NAMES[691] "Cyberdyne Outpost"
setvar $planetnames~PLANET_NAMES[692] "D'Alembert Primus"
setvar $planetnames~PLANET_NAMES[693] "Brigantia Annex"
setvar $planetnames~PLANET_NAMES[694] "Miaplacidas Primus"
setvar $planetnames~PLANET_NAMES[695] "Schwarzlose Annex"
setvar $planetnames~PLANET_NAMES[696] "Datolite Annex"
setvar $planetnames~PLANET_NAMES[697] "Gormenghast Outpost"
setvar $planetnames~PLANET_NAMES[698] "Ithaca II"
setvar $planetnames~PLANET_NAMES[699] "Condaria Primus"
setvar $planetnames~PLANET_NAMES[700] "Draconis"
setvar $planetnames~PLANET_NAMES[701] "Praxis"
setvar $planetnames~PLANET_NAMES[702] "Brodie Primus"
setvar $planetnames~PLANET_NAMES[703] "Katana Outpost"
setvar $planetnames~PLANET_NAMES[704] "New Zoptica"
setvar $planetnames~PLANET_NAMES[705] "New Bonta"
setvar $planetnames~PLANET_NAMES[706] "Deschuner Primus"
setvar $planetnames~PLANET_NAMES[707] "Hecate II"
setvar $planetnames~PLANET_NAMES[708] "Siembieda Primus"
setvar $planetnames~PLANET_NAMES[709] "Edinina Annex"
setvar $planetnames~PLANET_NAMES[710] "Saxe Outpost"
setvar $planetnames~PLANET_NAMES[711] "Fractine Annex"
setvar $planetnames~PLANET_NAMES[712] "Schrodinger Primus"
setvar $planetnames~PLANET_NAMES[713] "Gautier"
setvar $planetnames~PLANET_NAMES[714] "Akkad Outpost"
setvar $planetnames~PLANET_NAMES[715] "Polk Minor"
setvar $planetnames~PLANET_NAMES[716] "New Brae Taera"
setvar $planetnames~PLANET_NAMES[717] "DeGleash Outpost"
setvar $planetnames~PLANET_NAMES[718] "Breon Annex"
setvar $planetnames~PLANET_NAMES[719] "Adjutant"
setvar $planetnames~PLANET_NAMES[720] "Bridger"
setvar $planetnames~PLANET_NAMES[721] "New Dinomn"
setvar $planetnames~PLANET_NAMES[722] "Sinmora"
setvar $planetnames~PLANET_NAMES[723] "Wein Major"
setvar $planetnames~PLANET_NAMES[724] "Skuld Major"
setvar $planetnames~PLANET_NAMES[725] "Tau Major"
setvar $planetnames~PLANET_NAMES[726] "Eocene Primus"
setvar $planetnames~PLANET_NAMES[727] "Russel"
setvar $planetnames~PLANET_NAMES[728] "Samson"
setvar $planetnames~PLANET_NAMES[729] "Ponsby Primus"
setvar $planetnames~PLANET_NAMES[730] "Koenig Minor"
setvar $planetnames~PLANET_NAMES[731] "Constellate"
setvar $planetnames~PLANET_NAMES[732] "New Verdun"
setvar $planetnames~PLANET_NAMES[733] "New Heroni"
setvar $planetnames~PLANET_NAMES[734] "New Dopp"
setvar $planetnames~PLANET_NAMES[735] "Adhara Primus"
setvar $planetnames~PLANET_NAMES[736] "Van Maanen II"
setvar $planetnames~PLANET_NAMES[737] "Prokhorov II"
setvar $planetnames~PLANET_NAMES[738] "Fabrina II"
setvar $planetnames~PLANET_NAMES[739] "Ambartsumian Major"
setvar $planetnames~PLANET_NAMES[740] "New Toro"
setvar $planetnames~PLANET_NAMES[741] "New Sirius"
setvar $planetnames~PLANET_NAMES[742] "Poisson II"
setvar $planetnames~PLANET_NAMES[743] "New Deris"
setvar $planetnames~PLANET_NAMES[744] "Nadrin Primus"
setvar $planetnames~PLANET_NAMES[745] "Riyal Primus"
setvar $planetnames~PLANET_NAMES[746] "New Hippocrates"
setvar $planetnames~PLANET_NAMES[747] "Bainite Major"
setvar $planetnames~PLANET_NAMES[748] "Hertz Annex"
setvar $planetnames~PLANET_NAMES[749] "Athach"
setvar $planetnames~PLANET_NAMES[750] "Torment Primus"
setvar $planetnames~PLANET_NAMES[751] "Bohr Outpost"
setvar $planetnames~PLANET_NAMES[752] "Copalite Outpost"
setvar $planetnames~PLANET_NAMES[753] "Vero"
setvar $planetnames~PLANET_NAMES[754] "Alfa Primus"
setvar $planetnames~PLANET_NAMES[755] "Wolf II"
setvar $planetnames~PLANET_NAMES[756] "Banalg"
setvar $planetnames~PLANET_NAMES[757] "Lepton"
setvar $planetnames~PLANET_NAMES[758] "Bardeleben II"
setvar $planetnames~PLANET_NAMES[759] "Boyle Minor"
setvar $planetnames~PLANET_NAMES[760] "Aston Annex"
setvar $planetnames~PLANET_NAMES[761] "Proxima Centauri Major"
setvar $planetnames~PLANET_NAMES[762] "Bielids Primus"
setvar $planetnames~PLANET_NAMES[763] "Amber Major"
setvar $planetnames~PLANET_NAMES[764] "Gorgimera II"
setvar $planetnames~PLANET_NAMES[765] "Mortai Minor"
setvar $planetnames~PLANET_NAMES[766] "Hecate Primus"
setvar $planetnames~PLANET_NAMES[767] "Sabine"
setvar $planetnames~PLANET_NAMES[768] "Kintaro Annex"
setvar $planetnames~PLANET_NAMES[769] "Knorbes"
setvar $planetnames~PLANET_NAMES[770] "Sirion Primus"
setvar $planetnames~PLANET_NAMES[771] "New Priedo"
setvar $planetnames~PLANET_NAMES[772] "Deris"
setvar $planetnames~PLANET_NAMES[773] "Sakai II"
setvar $planetnames~PLANET_NAMES[774] "Jefferson II"
setvar $planetnames~PLANET_NAMES[775] "Flinte Minor"
setvar $planetnames~PLANET_NAMES[776] "New Gaillot"
setvar $planetnames~PLANET_NAMES[777] "New Ozawa"
setvar $planetnames~PLANET_NAMES[778] "Valkyrie Major"
setvar $planetnames~PLANET_NAMES[779] "Helios Primus"
setvar $planetnames~PLANET_NAMES[780] "Castor Annex"
setvar $planetnames~PLANET_NAMES[781] "Lysander Outpost"
setvar $planetnames~PLANET_NAMES[782] "Engrange Major"
setvar $planetnames~PLANET_NAMES[783] "Hektor Outpost"
setvar $planetnames~PLANET_NAMES[784] "Quasi Primus"
setvar $planetnames~PLANET_NAMES[785] "Minimi Annex"
setvar $planetnames~PLANET_NAMES[786] "Cetacean Primus"
setvar $planetnames~PLANET_NAMES[787] "Mondoloy"
setvar $planetnames~PLANET_NAMES[788] "Hadozee II"
setvar $planetnames~PLANET_NAMES[789] "Giedi Staz Primus"
setvar $planetnames~PLANET_NAMES[790] "Sarnoff Primus"
setvar $planetnames~PLANET_NAMES[791] "Symbiont Annex"
setvar $planetnames~PLANET_NAMES[792] "New Atrivis"
setvar $planetnames~PLANET_NAMES[793] "Adurol Outpost"
setvar $planetnames~PLANET_NAMES[794] "Agamar Minor"
setvar $planetnames~PLANET_NAMES[795] "de Tocqueville II"
setvar $planetnames~PLANET_NAMES[796] "Kentaurus"
setvar $planetnames~PLANET_NAMES[797] "Nebecula"
setvar $planetnames~PLANET_NAMES[798] "Mach Primus"
setvar $planetnames~PLANET_NAMES[799] "New Marconi"
setvar $planetnames~PLANET_NAMES[800] "Pixie Outpost"
setvar $planetnames~PLANET_NAMES[801] "Scorpio II"
setvar $planetnames~PLANET_NAMES[802] "Greyhawk Outpost"
setvar $planetnames~PLANET_NAMES[803] "New Bernoulli"
setvar $planetnames~PLANET_NAMES[804] "Myk"
setvar $planetnames~PLANET_NAMES[805] "New Snell"
setvar $planetnames~PLANET_NAMES[806] "Buccal II"
setvar $planetnames~PLANET_NAMES[807] "Surplus Outpost"
setvar $planetnames~PLANET_NAMES[808] "Agathinon"
setvar $planetnames~PLANET_NAMES[809] "Esabl Major"
setvar $planetnames~PLANET_NAMES[810] "l'Hopital Primus"
setvar $planetnames~PLANET_NAMES[811] "New Farquahar"
setvar $planetnames~PLANET_NAMES[812] "Calit Annex"
setvar $planetnames~PLANET_NAMES[813] "Forni-Copus Primus"
setvar $planetnames~PLANET_NAMES[814] "Dreath Annex"
setvar $planetnames~PLANET_NAMES[815] "Messier II"
setvar $planetnames~PLANET_NAMES[816] "New Bethune"
setvar $planetnames~PLANET_NAMES[817] "Avauld Major"
setvar $planetnames~PLANET_NAMES[818] "New Brassica"
setvar $planetnames~PLANET_NAMES[819] "Scheiner Minor"
setvar $planetnames~PLANET_NAMES[820] "Focaline II"
setvar $planetnames~PLANET_NAMES[821] "Xructocex Minor"
setvar $planetnames~PLANET_NAMES[822] "Atozine II"
setvar $planetnames~PLANET_NAMES[823] "Alupent Annex"
setvar $planetnames~PLANET_NAMES[824] "Moran II"
setvar $planetnames~PLANET_NAMES[825] "Bularia II"
setvar $planetnames~PLANET_NAMES[826] "Natoko Major"
setvar $planetnames~PLANET_NAMES[827] "Jenghe"
setvar $planetnames~PLANET_NAMES[828] "Thanber II"
setvar $planetnames~PLANET_NAMES[829] "Aeacus Major"
setvar $planetnames~PLANET_NAMES[830] "New Avignon"
setvar $planetnames~PLANET_NAMES[831] "Annobon Primus"
setvar $planetnames~PLANET_NAMES[832] "Majorana"
setvar $planetnames~PLANET_NAMES[833] "Alarm Major"
setvar $planetnames~PLANET_NAMES[834] "Messier"
setvar $planetnames~PLANET_NAMES[835] "Steele Minor"
setvar $planetnames~PLANET_NAMES[836] "Njord II"
setvar $planetnames~PLANET_NAMES[837] "Diabase Primus"
setvar $planetnames~PLANET_NAMES[838] "Pagaton Minor"
setvar $planetnames~PLANET_NAMES[839] "Aston Major"
setvar $planetnames~PLANET_NAMES[840] "Rashomon Outpost"
setvar $planetnames~PLANET_NAMES[841] "Yiktor"
setvar $planetnames~PLANET_NAMES[842] "Azactam II"
setvar $planetnames~PLANET_NAMES[843] "Anastasya II"
setvar $planetnames~PLANET_NAMES[844] "Cogri"
setvar $planetnames~PLANET_NAMES[845] "Macross Minor"
setvar $planetnames~PLANET_NAMES[846] "Asteres Major"
setvar $planetnames~PLANET_NAMES[847] "Bernoulli II"
setvar $planetnames~PLANET_NAMES[848] "New Pagoda"
setvar $planetnames~PLANET_NAMES[849] "Einherjar Primus"
setvar $planetnames~PLANET_NAMES[850] "Palpatine"
setvar $planetnames~PLANET_NAMES[851] "New Ghanima"
setvar $planetnames~PLANET_NAMES[852] "Poitiers II"
setvar $planetnames~PLANET_NAMES[853] "Nautiloid II"
setvar $planetnames~PLANET_NAMES[854] "Zoptica Minor"
setvar $planetnames~PLANET_NAMES[855] "Wern II"
setvar $planetnames~PLANET_NAMES[856] "Cascara Annex"
setvar $planetnames~PLANET_NAMES[857] "Yurst Outpost"
setvar $planetnames~PLANET_NAMES[858] "Breughel Major"
setvar $planetnames~PLANET_NAMES[859] "Anchorhead Outpost"
setvar $planetnames~PLANET_NAMES[860] "Woden Annex"
setvar $planetnames~PLANET_NAMES[861] "Gaia"
setvar $planetnames~PLANET_NAMES[862] "New Orwell"
setvar $planetnames~PLANET_NAMES[863] "Diocletian Primus"
setvar $planetnames~PLANET_NAMES[864] "New Exedore"
setvar $planetnames~PLANET_NAMES[865] "Jupura Major"
setvar $planetnames~PLANET_NAMES[866] "Kerogen"
setvar $planetnames~PLANET_NAMES[867] "Krono Major"
setvar $planetnames~PLANET_NAMES[868] "Marmoutier Major"
setvar $planetnames~PLANET_NAMES[869] "Stokes Annex"
setvar $planetnames~PLANET_NAMES[870] "New Pluto"
setvar $planetnames~PLANET_NAMES[871] "Hornet II"
setvar $planetnames~PLANET_NAMES[872] "Telegraph Major"
setvar $planetnames~PLANET_NAMES[873] "Bolivar Outpost"
setvar $planetnames~PLANET_NAMES[874] "Iolcus II"
setvar $planetnames~PLANET_NAMES[875] "Noegi Major"
setvar $planetnames~PLANET_NAMES[876] "New Saladin"
setvar $planetnames~PLANET_NAMES[877] "Cambridge Annex"
setvar $planetnames~PLANET_NAMES[878] "Gelugon"
setvar $planetnames~PLANET_NAMES[879] "Lazarus II"
setvar $planetnames~PLANET_NAMES[880] "Achernar Primus"
setvar $planetnames~PLANET_NAMES[881] "Langmuir"
setvar $planetnames~PLANET_NAMES[882] "Buie Annex"
setvar $planetnames~PLANET_NAMES[883] "Spica"
setvar $planetnames~PLANET_NAMES[884] "Puparkin Outpost"
setvar $planetnames~PLANET_NAMES[885] "Maya Major"
setvar $planetnames~PLANET_NAMES[886] "New Polk"
setvar $planetnames~PLANET_NAMES[887] "Solon Minor"
setvar $planetnames~PLANET_NAMES[888] "Flamarion Primus"
setvar $planetnames~PLANET_NAMES[889] "Jupura Minor"
setvar $planetnames~PLANET_NAMES[890] "New Lahara"
setvar $planetnames~PLANET_NAMES[891] "New Hermes"
setvar $planetnames~PLANET_NAMES[892] "New Krono"
setvar $planetnames~PLANET_NAMES[893] "Starling Primus"
setvar $planetnames~PLANET_NAMES[894] "Vanant"
setvar $planetnames~PLANET_NAMES[895] "New Rebka"
setvar $planetnames~PLANET_NAMES[896] "Julian Major"
setvar $planetnames~PLANET_NAMES[897] "Faeroes"
setvar $planetnames~PLANET_NAMES[898] "Kongo"
setvar $planetnames~PLANET_NAMES[899] "Lorraine Annex"
setvar $planetnames~PLANET_NAMES[900] "Gautier Outpost"
setvar $planetnames~PLANET_NAMES[901] "New Hadar"
setvar $planetnames~PLANET_NAMES[902] "Nexine II"
setvar $planetnames~PLANET_NAMES[903] "Lindbergh Annex"
setvar $planetnames~PLANET_NAMES[904] "Ranger"
setvar $planetnames~PLANET_NAMES[905] "Strad Primus"
setvar $planetnames~PLANET_NAMES[906] "Yuro Minor"
setvar $planetnames~PLANET_NAMES[907] "New Ilium"
setvar $planetnames~PLANET_NAMES[908] "Peale"
setvar $planetnames~PLANET_NAMES[909] "Faisal Primus"
setvar $planetnames~PLANET_NAMES[910] "Skinfaxi Major"
setvar $planetnames~PLANET_NAMES[911] "Gaea Primus"
setvar $planetnames~PLANET_NAMES[912] "Ayat Major"
setvar $planetnames~PLANET_NAMES[913] "Charlemagne Minor"
setvar $planetnames~PLANET_NAMES[914] "Dixon II"
setvar $planetnames~PLANET_NAMES[915] "Pequan Annex"
setvar $planetnames~PLANET_NAMES[916] "Arden Annex"
setvar $planetnames~PLANET_NAMES[917] "Palitzsch II"
setvar $planetnames~PLANET_NAMES[918] "Seneca Annex"
setvar $planetnames~PLANET_NAMES[919] "Bozarth Annex"
setvar $planetnames~PLANET_NAMES[920] "Bicornn Outpost"
setvar $planetnames~PLANET_NAMES[921] "Djinn Primus"
setvar $planetnames~PLANET_NAMES[922] "Nabopolassar II"
setvar $planetnames~PLANET_NAMES[923] "Adhara Major"
setvar $planetnames~PLANET_NAMES[924] "New Nagant"
setvar $planetnames~PLANET_NAMES[925] "Julian"
setvar $planetnames~PLANET_NAMES[926] "Upatnieks Annex"
setvar $planetnames~PLANET_NAMES[927] "New Guatama"
setvar $planetnames~PLANET_NAMES[928] "Isolux Outpost"
setvar $planetnames~PLANET_NAMES[929] "Archon Annex"
setvar $planetnames~PLANET_NAMES[930] "Planitia Major"
setvar $planetnames~PLANET_NAMES[931] "Li Kao Minor"
setvar $planetnames~PLANET_NAMES[932] "Cogri Minor"
setvar $planetnames~PLANET_NAMES[933] "New Shcawbe"
setvar $planetnames~PLANET_NAMES[934] "Kruhious Outpost"
setvar $planetnames~PLANET_NAMES[935] "Castor Hideout"
setvar $planetnames~PLANET_NAMES[936] "Clastic Outpost"
setvar $planetnames~PLANET_NAMES[937] "New Capybara"
setvar $planetnames~PLANET_NAMES[938] "Durer"
setvar $planetnames~PLANET_NAMES[939] "New Durendal"
setvar $planetnames~PLANET_NAMES[940] "Tivid"
setvar $planetnames~PLANET_NAMES[941] "New Vreibefger"
setvar $planetnames~PLANET_NAMES[942] "Baugi Major"
setvar $planetnames~PLANET_NAMES[943] "Lorraine Minor"
setvar $planetnames~PLANET_NAMES[944] "Chalcedony Major"
setvar $planetnames~PLANET_NAMES[945] "Rousseau Annex"
setvar $planetnames~PLANET_NAMES[946] "Palique Outpost"
setvar $planetnames~PLANET_NAMES[947] "Valence Annex"
setvar $planetnames~PLANET_NAMES[948] "Ralhe Minor"
setvar $planetnames~PLANET_NAMES[949] "Kruxas Ruz Annex"
setvar $planetnames~PLANET_NAMES[950] "Pyris Primus"
setvar $planetnames~PLANET_NAMES[951] "New Earwig"
setvar $planetnames~PLANET_NAMES[952] "New Wintjen"
setvar $planetnames~PLANET_NAMES[953] "Pennington"
setvar $planetnames~PLANET_NAMES[954] "Koalinth"
setvar $planetnames~PLANET_NAMES[955] "Antike Annex"
setvar $planetnames~PLANET_NAMES[956] "Bach Major"
setvar $planetnames~PLANET_NAMES[957] "Kikusui"
setvar $planetnames~PLANET_NAMES[958] "Guatama Minor"
setvar $planetnames~PLANET_NAMES[959] "Gaderffii"
setvar $planetnames~PLANET_NAMES[960] "Kender"
setvar $planetnames~PLANET_NAMES[961] "Mithra Minor"
setvar $planetnames~PLANET_NAMES[962] "Osnabruck Primus"
setvar $planetnames~PLANET_NAMES[963] "Pedase II"
setvar $planetnames~PLANET_NAMES[964] "Murchison Primus"
setvar $planetnames~PLANET_NAMES[965] "Lafaayette Outpost"
setvar $planetnames~PLANET_NAMES[966] "Dawnworld"
setvar $planetnames~PLANET_NAMES[967] "Ajacs"
setvar $planetnames~PLANET_NAMES[968] "Raven Outpost"
setvar $planetnames~PLANET_NAMES[969] "Bravera II"
setvar $planetnames~PLANET_NAMES[970] "Edenelt Primus"
setvar $planetnames~PLANET_NAMES[971] "New Nicholson"
setvar $planetnames~PLANET_NAMES[972] "Suleiman Outpost"
setvar $planetnames~PLANET_NAMES[973] "Alva"
setvar $planetnames~PLANET_NAMES[974] "Amertet Annex"
setvar $planetnames~PLANET_NAMES[975] "Guellan Minor"
setvar $planetnames~PLANET_NAMES[976] "Thagar"
setvar $planetnames~PLANET_NAMES[977] "Kegena"
setvar $planetnames~PLANET_NAMES[978] "Ari Outpost"
setvar $planetnames~PLANET_NAMES[979] "Hawk Primus"
setvar $planetnames~PLANET_NAMES[980] "Abraxas Minor"
setvar $planetnames~PLANET_NAMES[981] "Columbus"
setvar $planetnames~PLANET_NAMES[982] "Rutledge Major"
setvar $planetnames~PLANET_NAMES[983] "Efate Major"
setvar $planetnames~PLANET_NAMES[984] "Xylem Primus"
setvar $planetnames~PLANET_NAMES[985] "Anaspaz Major"
setvar $planetnames~PLANET_NAMES[986] "Garoo Minor"
setvar $planetnames~PLANET_NAMES[987] "Kruhious Minor"
setvar $planetnames~PLANET_NAMES[988] "Camelot Major"
setvar $planetnames~PLANET_NAMES[989] "Singer Minor"
setvar $planetnames~PLANET_NAMES[990] "Aegospotami Primus"
setvar $planetnames~PLANET_NAMES[991] "Modelei Annex"
setvar $planetnames~PLANET_NAMES[992] "Skuld Outpost"
setvar $planetnames~PLANET_NAMES[993] "Oisin Outpost"
setvar $planetnames~PLANET_NAMES[994] "Baruch Major"
setvar $planetnames~PLANET_NAMES[995] "Pyramus II"
setvar $planetnames~PLANET_NAMES[996] "Thornastor Outpost"
setvar $planetnames~PLANET_NAMES[997] "Suleiman"
setvar $planetnames~PLANET_NAMES[998] "Pompey Primus"
setvar $planetnames~PLANET_NAMES[999] "New Aeschylus"
setvar $planetnames~PLANET_NAMES[1000] "Bounty's Horizon"
return
