:USER_INTERFACE~CHECK_ROUTING_ALL
setvar $USER_INTERFACE~TEMP_BOT_NAME "all"
goto :DO_ROUTING
:USER_INTERFACE~CHECK_ROUTING_TEAM
setvar $USER_INTERFACE~TEMP_BOT_NAME $BOT~BOT_TEAM_NAME
goto :DO_ROUTING
:USER_INTERFACE~CHECK_ROUTING
setvar $USER_INTERFACE~TEMP_BOT_NAME $SWITCHBOARD~BOT_NAME
:USER_INTERFACE~DO_ROUTING

setvar $USER_INTERFACE~CURRENTLINE CURRENTLINE
setvar $USER_INTERFACE~CURRENTANSILINE CURRENTANSILINE
gosub :BOT~KILLTHETRIGGERS
getword CURRENTLINE $USER_INTERFACE~ROUTING 1
if ($USER_INTERFACE~ROUTING = "'"&$USER_INTERFACE~TEMP_BOT_NAME)
  goto :OWN_COMMAND
elseif ($USER_INTERFACE~ROUTING = "R")
  goto :COMMAND
elseif ($USER_INTERFACE~ROUTING = "P")
  goto :PAGE_COMMAND
else
  goto :BOT~WAIT_FOR_COMMAND
end
:USER_INTERFACE~OWN_COMMAND

cuttext $USER_INTERFACE~CURRENTANSILINE $USER_INTERFACE~ANSI_CK1 1 1
if ($USER_INTERFACE~ANSI_CK1 <> "")
  goto :BOT~WAIT_FOR_COMMAND
end
getword $USER_INTERFACE~CURRENTLINE $USER_INTERFACE~RADIO_TYPE 1
striptext $USER_INTERFACE~RADIO_TYPE $USER_INTERFACE~TEMP_BOT_NAME
setvar $BOT~USER_COMMAND_LINE $USER_INTERFACE~CURRENTLINE
setvar $BOT~USER_COMMAND_LINE $BOT~USER_COMMAND_LINE&"              "
lowercase $BOT~COMMAND_LINES[$USER_INTERFACE~B]
if ($USER_INTERFACE~RADIO_TYPE = "'")
  getlength "'"&$USER_INTERFACE~TEMP_BOT_NAME&" " $USER_INTERFACE~LENGTH
  cuttext $BOT~USER_COMMAND_LINE $BOT~USER_COMMAND_LINE ($USER_INTERFACE~LENGTH + 1) 9999
  setvar $USER_INTERFACE~USER_SEC_LEVEL 9
  getword $USER_INTERFACE~CURRENTLINE $BOT~COMMAND 2
  getwordpos $BOT~COMMAND $USER_INTERFACE~POS "'"
  getwordpos $BOT~COMMAND $USER_INTERFACE~POS2 "`"
  if (($USER_INTERFACE~POS = 1) or ($USER_INTERFACE~POS2 = 1))
    goto :BOT~WAIT_FOR_COMMAND
  end
  setvar $BOT~COMMAND_CALLER "self"
  savevar $BOT~COMMAND_CALLER
  getwordpos $BOT~USER_COMMAND_LINE $USER_INTERFACE~POS "|"
  if ($USER_INTERFACE~POS > 0)
    savevar $SWITCHBOARD~SELF_COMMAND
    savevar $BOT~USER_COMMAND_LINE
    load "scripts\"&$BOT~MOMBOT_DIRECTORY&"\commands\general\run.cts"
    goto :BOT~WAIT_FOR_COMMAND
  end
  gosub :CHECK_FOR_MULTI_COMMANDS
  goto :COMMAND_PROCESSING
else
  goto :BOT~WAIT_FOR_COMMAND
end
:USER_INTERFACE~COMMAND

setvar $USER_INTERFACE~ANSI_LINE $USER_INTERFACE~CURRENTANSILINE
getwordpos $USER_INTERFACE~ANSI_LINE $USER_INTERFACE~POS "[36mR"
getwordpos $USER_INTERFACE~ANSI_LINE $USER_INTERFACE~POS2 "[0;36mR"
if (($USER_INTERFACE~POS <= 0) and ($USER_INTERFACE~POS2 <= 0))
  goto :BOT~WAIT_FOR_COMMAND
end
cuttext $USER_INTERFACE~CURRENTLINE $USER_INTERFACE~USER_NAME 3 6

gosub :VERIFY_USER_STATUS
if ($USER_INTERFACE~AUTHORIZATION = 0)
  goto :BOT~WAIT_FOR_COMMAND
end

cuttext $USER_INTERFACE~CURRENTLINE $BOT~USER_COMMAND_LINE 10 999
getword $BOT~USER_COMMAND_LINE $USER_INTERFACE~BOTNAME_CHK 1
if ($USER_INTERFACE~BOTNAME_CHK <> $USER_INTERFACE~TEMP_BOT_NAME)
  goto :BOT~WAIT_FOR_COMMAND
end
getlength $USER_INTERFACE~TEMP_BOT_NAME&" " $USER_INTERFACE~LENGTH
cuttext $BOT~USER_COMMAND_LINE&"          " $BOT~USER_COMMAND_LINE ($USER_INTERFACE~LENGTH + 1) 9999
setvar $BOT~USER_COMMAND_LINE $BOT~USER_COMMAND_LINE&"              "
getword $BOT~USER_COMMAND_LINE $BOT~COMMAND 1
if (($BOT~COMMAND = "bot") or ($BOT~COMMAND = "relog"))
  goto :BOT~WAIT_FOR_COMMAND
end
getwordpos $BOT~USER_COMMAND_LINE $USER_INTERFACE~POS "|"
if ($USER_INTERFACE~POS > 0)
  savevar $SWITCHBOARD~SELF_COMMAND
  savevar $BOT~USER_COMMAND_LINE
  load "scripts\"&$BOT~MOMBOT_DIRECTORY&"\commands\general\run.cts"
  goto :BOT~WAIT_FOR_COMMAND
end
gosub :CHECK_FOR_MULTI_COMMANDS
goto :COMMAND_PROCESSING
:USER_INTERFACE~PAGE_COMMAND

cuttext $USER_INTERFACE~CURRENTLINE $USER_INTERFACE~USER_NAME 3 6
cuttext $USER_INTERFACE~CURRENTLINE $BOT~USER_COMMAND_LINE 10 999
getwordpos $BOT~USER_COMMAND_LINE $USER_INTERFACE~POS $SWITCHBOARD~BOT_NAME&":"&$BOT~BOT_PASSWORD&":"&$BOT~SUBSPACE
if ($USER_INTERFACE~POS > 0)
  add $BOT~CORPYCOUNT 1
  setvar $BOT~CORPY[$BOT~CORPYCOUNT] $USER_INTERFACE~USER_NAME
  setvar $USER_INTERFACE~LOGGEDIN[$USER_INTERFACE~USER_NAME] 1
  setvar $switchboard~message "User Verified - " $USER_INTERFACE~USER_NAME "*"
  gosub :switchboard~switchboard
else
  gosub :VERIFY_USER_STATUS
  if ($USER_INTERFACE~AUTHORIZATION = 0)
    echo "*"&ANSI_14&"["&ANSI_15&"Bad attempt to control bot through private message."&ANSI_14&"]*"
    goto :BOT~WAIT_FOR_COMMAND
  end
  getword $BOT~USER_COMMAND_LINE $USER_INTERFACE~BOTNAME_CHK 1
  if ($USER_INTERFACE~BOTNAME_CHK <> $USER_INTERFACE~TEMP_BOT_NAME)
    goto :BOT~WAIT_FOR_COMMAND
  end
  getlength $USER_INTERFACE~TEMP_BOT_NAME&" " $USER_INTERFACE~LENGTH
  cuttext $BOT~USER_COMMAND_LINE&"          " $BOT~USER_COMMAND_LINE ($USER_INTERFACE~LENGTH + 1) 9999
  lowercase $BOT~USER_COMMAND_LINE
  setvar $BOT~USER_COMMAND_LINE $BOT~USER_COMMAND_LINE&"              "
  getword $BOT~USER_COMMAND_LINE $BOT~COMMAND 1
  if (($BOT~COMMAND = "bot") or ($BOT~COMMAND = "relog"))
    goto :BOT~WAIT_FOR_COMMAND
  end
  getwordpos $BOT~USER_COMMAND_LINE $USER_INTERFACE~POS "|"
  if ($USER_INTERFACE~POS > 0)
    savevar $SWITCHBOARD~SELF_COMMAND
    savevar $BOT~USER_COMMAND_LINE
    load "scripts\"&$BOT~MOMBOT_DIRECTORY&"\commands\general\run.cts"
    goto :BOT~WAIT_FOR_COMMAND
  end
  gosub :CHECK_FOR_MULTI_COMMANDS
  goto :COMMAND_PROCESSING
end
goto :BOT~WAIT_FOR_COMMAND
:USER_INTERFACE~USER_ACCESS



gosub :BIGDELAY_KILLTHETRIGGERS
gosub :SELFCOMMANDPROMPT
setvar $BOT~COMMAND_CALLER "self"
savevar $BOT~COMMAND_CALLER
lowercase $BOT~USER_COMMAND_LINE
if ($BOT~USER_COMMAND_LINE = "")
  echo CURRENTANSILINE
  goto :BOT~WAIT_FOR_COMMAND
end
setvar $SWITCHBOARD~SELF_COMMAND TRUE
getwordpos $BOT~USER_COMMAND_LINE $USER_INTERFACE~POS "|"
if ($USER_INTERFACE~POS > 0)
  savevar $SWITCHBOARD~SELF_COMMAND
  savevar $BOT~USER_COMMAND_LINE
  load "scripts\"&$BOT~MOMBOT_DIRECTORY&"\commands\general\run.cts"
  goto :BOT~WAIT_FOR_COMMAND
end
:USER_INTERFACE~RUNUSERCOMMANDLINE
setvar $BOT~USER_COMMAND_LINE $BOT~USER_COMMAND_LINE&"              "
setvar $USER_INTERFACE~AUTHORIZATION 9
setvar $USER_INTERFACE~USER_SEC_LEVEL 9

gosub :CHECK_FOR_MULTI_COMMANDS

goto :COMMAND_PROCESSING
:USER_INTERFACE~CHECK_FOR_MULTI_COMMANDS

gosub :USER_INTERFACE~NORMALIZE_USER_COMMAND_LINE















setarray $BOT~COMMAND_LINES 10 10
setarray $USER_INTERFACE~TYPED_COMMANDS 10
getwordpos $BOT~USER_COMMAND_LINE $USER_INTERFACE~POS "|"
if ($USER_INTERFACE~POS > 0)

  splittext $BOT~USER_COMMAND_LINE $BOT~COMMANDS "|"
  setvar $USER_INTERFACE~B 1
  setvar $BOT~COMMAND_LINES 0
  while ($USER_INTERFACE~B <= $BOT~COMMANDS)
    getword $BOT~COMMANDS[$USER_INTERFACE~B] $BOT~COMMAND_LINES[$USER_INTERFACE~B][9] 1
    getlength $BOT~COMMAND_LINES[$USER_INTERFACE~B][9]&" " $BOT~COMMANDLENGTH
    getwordpos $BOT~COMMAND_LINES[$USER_INTERFACE~B][9] $USER_INTERFACE~POS "'"
    getwordpos $BOT~COMMAND_LINES[$USER_INTERFACE~B][9] $USER_INTERFACE~POS2 "`"
    if (($USER_INTERFACE~POS <> 1) and ($USER_INTERFACE~POS2 <> 1))
      cuttext $BOT~COMMANDS[$USER_INTERFACE~B]&"    " $BOT~COMMANDS[$USER_INTERFACE~B] ($BOT~COMMANDLENGTH + 1) 9999
    end
    setvar $BOT~COMMAND_LINES[$USER_INTERFACE~B] $BOT~COMMANDS[$USER_INTERFACE~B]
    setvar $BOT~COMMAND_LINES[$USER_INTERFACE~B][9] $BOT~COMMAND_LINES[$USER_INTERFACE~B][9]

    setvar $BOT~COMMAND_LINES[$USER_INTERFACE~B] $BOT~COMMANDS[$USER_INTERFACE~B]
    gosub :GETPARAMETERS
    add $BOT~COMMAND_LINES 1
    add $USER_INTERFACE~B 1
  end
else
  setarray $BOT~COMMAND_LINES 1
  setvar $BOT~COMMAND_LINES 1
  setvar $BOT~COMMAND_LINES[1] $BOT~USER_COMMAND_LINE
  getword $BOT~COMMAND_LINES[1] $BOT~COMMAND_LINES[1][9] 1
  getlength $BOT~COMMAND_LINES[1][9]&" " $BOT~COMMANDLENGTH
  getwordpos $BOT~COMMAND_LINES[1][9] $USER_INTERFACE~POS "'"
  getwordpos $BOT~COMMAND_LINES[1][9] $USER_INTERFACE~POS2 "`"
  if (($USER_INTERFACE~POS <> 1) and ($USER_INTERFACE~POS2 <> 1))
    cuttext $BOT~COMMAND_LINES[1]&"    " $BOT~COMMAND_LINES[1] ($BOT~COMMANDLENGTH + 1) 9999
  end
  setvar $USER_INTERFACE~B 1
  gosub :GETPARAMETERS
end

return
:USER_INTERFACE~NORMALIZE_USER_COMMAND_LINE
setvar $USER_INTERFACE~RAW_COMMAND_LINE $BOT~USER_COMMAND_LINE
getlength $USER_INTERFACE~RAW_COMMAND_LINE $USER_INTERFACE~RAW_LENGTH
if ($USER_INTERFACE~RAW_LENGTH <= 0)
  return
end

setvar $USER_INTERFACE~NORMALIZED_COMMAND_LINE ""
setvar $USER_INTERFACE~CURSOR 1
setvar $USER_INTERFACE~I 1
while ($USER_INTERFACE~I <= $USER_INTERFACE~RAW_LENGTH)
  cuttext $USER_INTERFACE~RAW_COMMAND_LINE $USER_INTERFACE~CURRENT_CHAR $USER_INTERFACE~I 1
  if ($USER_INTERFACE~CURRENT_CHAR = #8)
    if ($USER_INTERFACE~CURSOR > 1)
      subtract $USER_INTERFACE~CURSOR 1
    end
  elseif ($USER_INTERFACE~CURRENT_CHAR <> #13)
    getlength $USER_INTERFACE~NORMALIZED_COMMAND_LINE $USER_INTERFACE~NORMALIZED_LENGTH
    if ($USER_INTERFACE~CURSOR > $USER_INTERFACE~NORMALIZED_LENGTH)
      setvar $USER_INTERFACE~NORMALIZED_COMMAND_LINE $USER_INTERFACE~NORMALIZED_COMMAND_LINE & $USER_INTERFACE~CURRENT_CHAR
    else
      if ($USER_INTERFACE~CURSOR > 1)
        cuttext $USER_INTERFACE~NORMALIZED_COMMAND_LINE $USER_INTERFACE~NORMALIZED_FRONT 1 ($USER_INTERFACE~CURSOR - 1)
      else
        setvar $USER_INTERFACE~NORMALIZED_FRONT ""
      end
      cuttext $USER_INTERFACE~NORMALIZED_COMMAND_LINE $USER_INTERFACE~NORMALIZED_TAIL ($USER_INTERFACE~CURSOR + 1) 9999
      setvar $USER_INTERFACE~NORMALIZED_COMMAND_LINE $USER_INTERFACE~NORMALIZED_FRONT & $USER_INTERFACE~CURRENT_CHAR & $USER_INTERFACE~NORMALIZED_TAIL
    end
    add $USER_INTERFACE~CURSOR 1
  end
  add $USER_INTERFACE~I 1
end
trim $USER_INTERFACE~NORMALIZED_COMMAND_LINE
setvar $BOT~USER_COMMAND_LINE $USER_INTERFACE~NORMALIZED_COMMAND_LINE
return
:USER_INTERFACE~GETPARAMETERS




setvar $USER_INTERFACE~TEST_VALUE 0
setvar $USER_INTERFACE~I 1
while ($USER_INTERFACE~TEST_VALUE <> "")
  getword " "&$BOT~COMMAND_LINES[$USER_INTERFACE~B]&" " $USER_INTERFACE~TEST_VALUE $USER_INTERFACE~I ""
  getwordpos " "&$USER_INTERFACE~TEST_VALUE&" " $USER_INTERFACE~POSTHOUSANDS "k "
  getwordpos " "&$USER_INTERFACE~TEST_VALUE&" " $USER_INTERFACE~POSMILLIONS "m "
  getwordpos " "&$USER_INTERFACE~TEST_VALUE&" " $USER_INTERFACE~POSBILLIONS "b "
  if (($USER_INTERFACE~POSMILLIONS > 0) or ($USER_INTERFACE~POSTHOUSANDS > 0) or ($USER_INTERFACE~POSBILLIONS > 0))
    replacetext $USER_INTERFACE~TEST_VALUE "k" ""
    replacetext $USER_INTERFACE~TEST_VALUE "m" ""
    replacetext $USER_INTERFACE~TEST_VALUE "b" ""
    trim $USER_INTERFACE~TEST_VALUE
    isnumber $USER_INTERFACE~IS_A_NUMBER $USER_INTERFACE~TEST_VALUE
    if ($USER_INTERFACE~IS_A_NUMBER = TRUE)
      if ($USER_INTERFACE~TEST_VALUE <> 0)
        replacetext $BOT~COMMAND_LINES[$USER_INTERFACE~B] $USER_INTERFACE~TEST_VALUE&"k" $USER_INTERFACE~TEST_VALUE&000
        replacetext $BOT~COMMAND_LINES[$USER_INTERFACE~B] $USER_INTERFACE~TEST_VALUE&"m" $USER_INTERFACE~TEST_VALUE&000000
        replacetext $BOT~COMMAND_LINES[$USER_INTERFACE~B] $USER_INTERFACE~TEST_VALUE&"b" $USER_INTERFACE~TEST_VALUE&000000000
      end
    end
  end
  add $USER_INTERFACE~I 1
end

setvar $USER_INTERFACE~I 1
while ($USER_INTERFACE~I <= 8)
  getword " "&$BOT~COMMAND_LINES[$USER_INTERFACE~B]&" " $BOT~COMMAND_LINES[$USER_INTERFACE~B][$USER_INTERFACE~I] $USER_INTERFACE~I ""
  add $USER_INTERFACE~I 1
end
return
:USER_INTERFACE~SELFCOMMANDPROMPT

loadvar $BOT~HISTORYSTRING
setvar $BOT~HISTORYCOUNT 0
getwordpos $BOT~HISTORYSTRING $USER_INTERFACE~POS "<<|HS|>>"
while (($USER_INTERFACE~POS > 0) and ($BOT~HISTORYCOUNT < $BOT~HISTORYMAX))
  cuttext $BOT~HISTORYSTRING $USER_INTERFACE~ARCHIVE 1 ($USER_INTERFACE~POS - 1)
  replacetext $BOT~HISTORYSTRING $USER_INTERFACE~ARCHIVE&"<<|HS|>>" ""
  setvar $BOT~HISTORY[($BOT~HISTORYCOUNT + 1)] $USER_INTERFACE~ARCHIVE
  add $BOT~HISTORYCOUNT 1
  getwordpos $BOT~HISTORYSTRING $USER_INTERFACE~POS "<<|HS|>>"
end
gosub :BOT~BIGDELAY_KILLTHETRIGGERS
setvar $USER_INTERFACE~PROMPT ANSI_10&#27&"[255D"&#27&"[255B"&#27&"[K"&ANSI_4&"{"&ANSI_14&$BOT~MODE&ANSI_4&"}"&ANSI_15&" "&$SWITCHBOARD~BOT_NAME&ANSI_2&">"&ANSI_7
echo $USER_INTERFACE~PROMPT
:USER_INTERFACE~GETINPUT
setvar $BOT~PROMPTOUTPUT ""
killtrigger TEXT
killtrigger REECHO
killtrigger KEEPALIVE
settextouttrigger TEXT :GETCHARACTER
setdelaytrigger KEEPALIVE :CONNECTIVITY~KEEPALIVE 30000
settexttrigger REECHO :REECHO
pause
:USER_INTERFACE~GETCHARACTER
getouttext $USER_INTERFACE~CHARACTER
setvar $USER_INTERFACE~FOUND_ENTER_KEY FALSE
if ($USER_INTERFACE~CHARACTER = #13)
  gosub :DO_ENTER_KEY
  goto :DONESELFCOMMANDPROMPT
end
if (($USER_INTERFACE~CHARACTER = ">") and ($BOT~CHARCOUNT <= 0))
  :USER_INTERFACE~CLEARGRIDPROMPT
  loadvar $PLANET~PLANET
  gosub :BOT~BIGDELAY_KILLTHETRIGGERS
  gosub :PLAYER~QUIKSTATS
  settextouttrigger TEXT :GETCHARACTER
  setdelaytrigger KEEPALIVE :CONNECTIVITY~KEEPALIVE 30000
  settexttrigger REECHO :REECHO
  setdelaytrigger GRIDDELAY :GRID_MENU_CONTINUE 30
  pause
  :USER_INTERFACE~GRID_MENU_CONTINUE
  echo #27&"[2J"
  echo "**"
  :USER_INTERFACE~GRIDPROMPT
  setdelaytrigger GRIDDELAY2 :GRID_MENU_CONTINUE2 50
  pause
  :USER_INTERFACE~GRID_MENU_CONTINUE2
  gosub :BOT~BIGDELAY_KILLTHETRIGGERS
  setvar $USER_INTERFACE~DOHOLO FALSE
  setvar $USER_INTERFACE~DODENS FALSE

  gosub :MAP~DISPLAYADJACENTGRIDANSI
  setvar $USER_INTERFACE~GRIDPROMPT ANSI_10&#27&"[255D"&#27&"[255B"&#27&"[K"&ANSI_4&"{"&ANSI_14&"Grid Menu - ["&ANSI_15&"H"&ANSI_14&"]olo ["&ANSI_15&"D"&ANSI_14&"]ens ["&ANSI_15&"S"&ANSI_14&"]urround "
  if ($PLAYER~PHOTONS > 0)
    setvar $USER_INTERFACE~GRIDPROMPT $USER_INTERFACE~GRIDPROMPT&"["&ANSI_15&">"&ANSI_14&"] Photon "
  end
  if ($PLAYER~CURRENT_PROMPT = "Citadel")
    setvar $USER_INTERFACE~GRIDPROMPT $USER_INTERFACE~GRIDPROMPT&"["&ANSI_15&"+"&ANSI_14&"]["&ANSI_15&$BOT~PGRID_TYPE&ANSI_14&"] ["&ANSI_15&1&ANSI_14&"-"&ANSI_15&$MAP~GRIDWARPCOUNT&ANSI_14&"]"&ANSI_4&"}"&ANSI_14&ANSI_2&">"&ANSI_7&" "
  elseif ($PLAYER~CURRENT_PROMPT = "Command")
    setvar $USER_INTERFACE~GRIDPROMPT $USER_INTERFACE~GRIDPROMPT&"["&ANSI_15&1&ANSI_14&"-"&ANSI_15&$MAP~GRIDWARPCOUNT&ANSI_14&"]"&ANSI_4&"}"&ANSI_14&" Move"&ANSI_4&"}"&ANSI_2&">"&ANSI_7
  else
    echo ANSI_12&"*Wrong prompt for Grid Menu*"
    goto :DONEGRIDDINGPROMPT
  end
  echo $USER_INTERFACE~GRIDPROMPT
  gosub :BOT~BIGDELAY_KILLTHETRIGGERS
  settexttrigger REECHOGRIDMENU :REECHOGRIDMENU
  settextouttrigger TEXT0 :GRIDPROMPT "?"
  if ($PLAYER~PHOTONS > 0)
    settextouttrigger TEXT12 :PHOTONPROMPT ">"
  end
  setdelaytrigger KEEPALIVE :CONNECTIVITY~KEEPALIVE 30000
  setvar $USER_INTERFACE~I 1
  while ($USER_INTERFACE~I <= $MAP~GRIDWARPCOUNT)
    settextouttrigger "grid_map"&$USER_INTERFACE~I :VISITSECTORPGRID $USER_INTERFACE~I
    add $USER_INTERFACE~I 1
  end
  settextouttrigger TEXT7 :HOLOGRID #72
  settextouttrigger TEXT8 :HOLOGRID #104
  settextouttrigger TEXT13 :HOLOGRID "h"
  settextouttrigger TEXT14 :HOLOGRID "H"
  settextouttrigger TEXT20 :SURROUNDGRID #115
  settextouttrigger TEXT16 :SURROUNDGRID #83
  settextouttrigger TEXT17 :SURROUNDGRID "s"
  settextouttrigger TEXT18 :SURROUNDGRID "S"
  settextouttrigger TEXT9 :DENSGRID #68
  settextouttrigger TEXT10 :DENSGRID #100
  if ($PLAYER~CURRENT_PROMPT = "Citadel")
    settextouttrigger TEXT15 :CHANGEPGRIDTYPE "+"
  end
  settextouttrigger TEXT11 :DONEGRIDDINGPROMPT
  pause
  :USER_INTERFACE~PHOTONPROMPT
  setdelaytrigger PHOTONDELAY :PHOTON_MENU_CONTINUE 50
  pause
  :USER_INTERFACE~PHOTON_MENU_CONTINUE
  gosub :BOT~BIGDELAY_KILLTHETRIGGERS
  echo #27&"[2J"
  echo "**"
  echo ANSI_10&#27&"[255D"&#27&"[255B"&#27&"[K"
  echo ANSI_7&"               -----------------------------------*"
  echo ANSI_7&"               | "&ANSI_4&"PHOTON "&ANSI_15&"armed and ready to fire! "&ANSI_7&"|*"
  echo ANSI_7&"               -----------------------------------*"
  gosub :MAP~DISPLAYADJACENTGRIDANSI
  setvar $USER_INTERFACE~GRIDPROMPT ANSI_10&#27&"[255D"&#27&"[255B"&#27&"[K"&ANSI_4&"{"&ANSI_14&"Photon Menu - ["&ANSI_15&"H"&ANSI_14&"]olo ["&ANSI_15&"D"&ANSI_14&"]ens "
  if ($PLAYER~CURRENT_PROMPT = "Citadel")
    setvar $USER_INTERFACE~GRIDPROMPT $USER_INTERFACE~GRIDPROMPT&"["&ANSI_12&1&ANSI_14&"-"&ANSI_12&$MAP~GRIDWARPCOUNT&ANSI_14&"]"&ANSI_4&"}"&ANSI_14&ANSI_2&">"&ANSI_7&" "
  elseif ($PLAYER~CURRENT_PROMPT = "Command")
    setvar $USER_INTERFACE~GRIDPROMPT $USER_INTERFACE~GRIDPROMPT&"["&ANSI_15&1&ANSI_14&"-"&ANSI_15&$MAP~GRIDWARPCOUNT&ANSI_14&"]"&ANSI_4&"}"&ANSI_4&"}"&ANSI_2&">"&ANSI_7
  else
    echo ANSI_12&"*Wrong prompt for Photon Menu*"
    goto :DONEGRIDDINGPROMPT
  end
  echo $USER_INTERFACE~GRIDPROMPT
  gosub :BOT~BIGDELAY_KILLTHETRIGGERS
  settexttrigger REECHOGRIDMENU :REECHOGRIDMENU
  settextouttrigger TEXT0 :PHOTONPROMPT "?"
  settextouttrigger TEXT12 :CLEARGRIDPROMPT ">"
  setdelaytrigger KEEPALIVE :CONNECTIVITY~KEEPALIVE 30000
  setvar $USER_INTERFACE~I 1
  while ($USER_INTERFACE~I <= $MAP~GRIDWARPCOUNT)
    settextouttrigger "grid_map"&$USER_INTERFACE~I :PHOTONSECTORPGRID $USER_INTERFACE~I
    add $USER_INTERFACE~I 1
  end
  settextouttrigger TEXT7 :HOLOPHOTON #72
  settextouttrigger TEXT8 :HOLOPHOTON #104
  settextouttrigger TEXT13 :HOLOPHOTON "h"
  settextouttrigger TEXT14 :HOLOPHOTON "H"
  settextouttrigger TEXT9 :DENSPHOTON #68
  settextouttrigger TEXT10 :DENSPHOTON #100
  settextouttrigger TEXT11 :DONEGRIDDINGPROMPT
  pause
  :USER_INTERFACE~SURROUNDGRID

  gosub :BOT~BIGDELAY_KILLTHETRIGGERS

  setvar $BOT~COMMAND "surround"
  setvar $BOT~USER_COMMAND_LINE " surround"
  setvar $BOT~PARM1 ""
  savevar $BOT~PARM1
  savevar $BOT~COMMAND
  savevar $BOT~USER_COMMAND_LINE
  load "scripts\"&$BOT~MOMBOT_DIRECTORY&"\commands\grid\surround.cts"
  seteventtrigger SURROUNDENDED :SURROUNDENDED "SCRIPT STOPPED" "scripts\"&$BOT~MOMBOT_DIRECTORY&"\commands\grid\surround.cts"
  pause
  :USER_INTERFACE~SURROUNDENDED

  goto :GRIDPROMPT
  :USER_INTERFACE~HOLOPHOTON
  setvar $USER_INTERFACE~DOHOLO TRUE
  gosub :DOGRIDSCAN
  goto :PHOTONPROMPT
  :USER_INTERFACE~DENSPHOTON
  setvar $USER_INTERFACE~DODENS TRUE
  gosub :DOGRIDSCAN
  goto :PHOTONPROMPT
  :USER_INTERFACE~HOLOGRID
  setvar $USER_INTERFACE~DOHOLO TRUE
  gosub :DOGRIDSCAN
  goto :GRIDPROMPT
  :USER_INTERFACE~DENSGRID
  setvar $USER_INTERFACE~DODENS TRUE
  gosub :DOGRIDSCAN
  goto :GRIDPROMPT
  :USER_INTERFACE~DOGRIDSCAN
  gosub :BOT~BIGDELAY_KILLTHETRIGGERS
  if ($PLAYER~CURRENT_PROMPT = "Citadel")
    setvar $USER_INTERFACE~SCANTEXT "q q z n "
  else
    setvar $USER_INTERFACE~SCANTEXT ""
  end
  if ($USER_INTERFACE~DOHOLO = TRUE)
    setvar $USER_INTERFACE~SCANTEXT $USER_INTERFACE~SCANTEXT&"szhzn* "
  elseif ($USER_INTERFACE~DODENS = TRUE)
    setvar $USER_INTERFACE~SCANTEXT $USER_INTERFACE~SCANTEXT&"sdz* "
  end
  if ($PLAYER~CURRENT_PROMPT = "Citadel")
    setvar $USER_INTERFACE~SCANTEXT $USER_INTERFACE~SCANTEXT&"l "&$PLANET~PLANET&"*  c  "
  end
  send $USER_INTERFACE~SCANTEXT
  if ($PLAYER~CURRENT_PROMPT = "Citadel")
    waiton "<Enter Citadel>"
  else
    waiton "["&CURRENTSECTOR&"]"
  end
  return
  :USER_INTERFACE~CHANGEPGRIDTYPE
  if ($BOT~PGRID_TYPE = "Normal")
    if ($BOT~SAFE_SHIP <= 0)
      setvar $BOT~PGRID_TYPE "Xport (Not Available)"
      setvar $BOT~PGRID_END_COMMAND " scan "
    else
      setvar $BOT~PGRID_TYPE "Xport"
      setvar $BOT~PGRID_END_COMMAND " x:"&$BOT~SAFE_SHIP&" scan "
    end
  elseif (($BOT~PGRID_TYPE = "Xport") or ($BOT~PGRID_TYPE = "Xport (Not Available)"))
    setvar $BOT~PGRID_TYPE "Retreat"
    setvar $BOT~PGRID_END_COMMAND " r scan "
  else
    setvar $BOT~PGRID_TYPE "Normal"
    setvar $BOT~PGRID_END_COMMAND " scan "
  end
  goto :GRIDPROMPT
  :USER_INTERFACE~VISITSECTORPGRID
  getouttext $USER_INTERFACE~SECTOR
  gosub :BOT~BIGDELAY_KILLTHETRIGGERS
  if (SECTOR.WARPS[CURRENTSECTOR][$USER_INTERFACE~SECTOR] > 0)
    if ($PLAYER~CURRENT_PROMPT = "Citadel")
      getsectorparameter SECTOR.WARPS[CURRENTSECTOR][$USER_INTERFACE~SECTOR] "FIGSEC" $USER_INTERFACE~ISFIGGED
      if ($USER_INTERFACE~ISFIGGED)
        setvar $BOT~USER_COMMAND_LINE "p "&SECTOR.WARPS[CURRENTSECTOR][$USER_INTERFACE~SECTOR]&" scan"
        goto :RUNUSERCOMMANDLINE
      else
        if (($BOT~PGRID_BOT <> "") and ($BOT~PGRID_BOT <> 0))
          send "'"&$BOT~PGRID_BOT&" pgrid "&SECTOR.WARPS[CURRENTSECTOR][$USER_INTERFACE~SECTOR]&" d:"&SECTOR.DENSITY[SECTOR.WARPS[CURRENTSECTOR][$USER_INTERFACE~SECTOR]]&" "&$BOT~PGRID_END_COMMAND "**"
        else
          setvar $BOT~USER_COMMAND_LINE "pgrid "&SECTOR.WARPS[CURRENTSECTOR][$USER_INTERFACE~SECTOR]&" "&$BOT~PGRID_END_COMMAND
          goto :RUNUSERCOMMANDLINE
        end
      end

    elseif ($PLAYER~CURRENT_PROMPT = "Command")
      setvar $MOVE~MOVEINTOSECTOR SECTOR.WARPS[CURRENTSECTOR][$USER_INTERFACE~SECTOR]
      gosub :MOVE~MOVEINTOSECTOR
    end
  end
  :USER_INTERFACE~DONEGRIDDINGPROMPT
  echo #27&"[255D"&#27&"[255B"&#27&"[K"
  setvar $USER_INTERFACE~ANSI CURRENTANSILINE
  striptext $USER_INTERFACE~ANSI "Y"
  echo $USER_INTERFACE~ANSI
  goto :BOT~WAIT_FOR_COMMAND
  :USER_INTERFACE~PHOTONSECTORPGRID
  getouttext $USER_INTERFACE~SECTOR
  gosub :BOT~BIGDELAY_KILLTHETRIGGERS
  if (SECTOR.WARPS[CURRENTSECTOR][$USER_INTERFACE~SECTOR] > 0)
    setvar $BOT~USER_COMMAND_LINE "photon "&SECTOR.WARPS[CURRENTSECTOR][$USER_INTERFACE~SECTOR]
    goto :RUNUSERCOMMANDLINE
  end
  goto :DONEGRIDDINGPROMPT
  :USER_INTERFACE~NEXTMENU
  settextouttrigger TEXT12 :NEXTMENU ">"
  pause
  :USER_INTERFACE~REECHOGRIDMENU
  echo ANSI_10&#27&"[255D"&#27&"[255B"&#27&"[K"&$USER_INTERFACE~GRIDPROMPT
  settexttrigger REECHOGRIDMENU :REECHOGRIDMENU
  pause
else
  getlength $USER_INTERFACE~CHARACTER $USER_INTERFACE~CHARACTERLENGTH
  if (($USER_INTERFACE~CHARACTERLENGTH > 1) or ($USER_INTERFACE~CHARACTER = #8))
    if ($USER_INTERFACE~CHARACTER = #8)
      if ($BOT~CHARCOUNT <= 0)
        setvar $BOT~CHARCOUNT 0
        setvar $BOT~CHARPOS 0
      else
        if ($BOT~CHARPOS >= $BOT~CHARCOUNT)
          setvar $USER_INTERFACE~FRONTMACRO $BOT~PROMPTOUTPUT
          setvar $USER_INTERFACE~TAILMACRO ""
        else
          cuttext $BOT~PROMPTOUTPUT $USER_INTERFACE~TAILMACRO ($BOT~CHARPOS + 1) 9999
          cuttext $BOT~PROMPTOUTPUT $USER_INTERFACE~FRONTMACRO 1 $BOT~CHARPOS
        end
        getlength $USER_INTERFACE~FRONTMACRO $USER_INTERFACE~FRONTLENGTH
        if ($USER_INTERFACE~FRONTLENGTH > 1)
          cuttext $USER_INTERFACE~FRONTMACRO $USER_INTERFACE~FRONTMACRO 1 ($USER_INTERFACE~FRONTLENGTH - 1)
        else
          setvar $USER_INTERFACE~FRONTMACRO ""
        end
        setvar $BOT~PROMPTOUTPUT $USER_INTERFACE~FRONTMACRO&$USER_INTERFACE~TAILMACRO
        getlength $BOT~PROMPTOUTPUT $BOT~CHARCOUNT
        subtract $BOT~CHARPOS 1
        if ($BOT~CHARPOS <= 0)
          setvar $BOT~CHARPOS 0
        end
        if (($BOT~CHARCOUNT - $BOT~CHARPOS) > 0)
          echo $USER_INTERFACE~PROMPT $BOT~PROMPTOUTPUT #27 "[" ($BOT~CHARCOUNT - $BOT~CHARPOS) "D"
        else
          echo $USER_INTERFACE~PROMPT $BOT~PROMPTOUTPUT
        end
      end
    elseif (($USER_INTERFACE~CHARACTER = #27&"[A") or ($USER_INTERFACE~CHARACTER = #28) or ($USER_INTERFACE~CHARACTER = #27&#79&#65))
      if ($BOT~HISTORYCOUNT > 0)
        if ($BOT~HISTORYINDEX <= 0)
          setvar $BOT~CURRENTPROMPTTEXT $BOT~PROMPTOUTPUT
        end
        add $BOT~HISTORYINDEX 1
        if ($BOT~HISTORYINDEX > $BOT~HISTORYMAX)
          setvar $BOT~HISTORYINDEX $BOT~HISTORYMAX
        elseif ($BOT~HISTORYINDEX > $BOT~HISTORYCOUNT)
          setvar $BOT~HISTORYINDEX $BOT~HISTORYCOUNT
        end
        getlength $BOT~HISTORY[$BOT~HISTORYINDEX] $BOT~CHARCOUNT
        setvar $BOT~CHARPOS $BOT~CHARCOUNT
        echo $USER_INTERFACE~PROMPT $BOT~HISTORY[$BOT~HISTORYINDEX]
        setvar $BOT~PROMPTOUTPUT $BOT~HISTORY[$BOT~HISTORYINDEX]
      end
    elseif (($USER_INTERFACE~CHARACTER = #27&"[B") or ($USER_INTERFACE~CHARACTER = #29) or ($USER_INTERFACE~CHARACTER = #27&#79&#66))
      if ($BOT~HISTORYCOUNT > 0)
        if ($BOT~HISTORYINDEX <= 0)
          setvar $BOT~CURRENTPROMPTTEXT $BOT~PROMPTOUTPUT
        end
        subtract $BOT~HISTORYINDEX 1
        if ($BOT~HISTORYINDEX < 1)
          setvar $BOT~HISTORYINDEX 0
          getlength $BOT~CURRENTPROMPTTEXT $BOT~CHARCOUNT
          setvar $BOT~CHARPOS $BOT~CHARCOUNT
          echo $USER_INTERFACE~PROMPT $BOT~CURRENTPROMPTTEXT
          setvar $BOT~PROMPTOUTPUT $BOT~CURRENTPROMPTTEXT
        else
          getlength $BOT~HISTORY[$BOT~HISTORYINDEX] $BOT~CHARCOUNT
          setvar $BOT~CHARPOS $BOT~CHARCOUNT
          echo $USER_INTERFACE~PROMPT $BOT~HISTORY[$BOT~HISTORYINDEX]
          setvar $BOT~PROMPTOUTPUT $BOT~HISTORY[$BOT~HISTORYINDEX]
        end
      end
    elseif (($USER_INTERFACE~CHARACTER = #27&"[D") or ($USER_INTERFACE~CHARACTER = #31))
      if ($BOT~CHARPOS > 0)
        subtract $BOT~CHARPOS 1
        echo ANSI_10 $USER_INTERFACE~CHARACTER
      end
    elseif (($USER_INTERFACE~CHARACTER = #27&"[C") or ($USER_INTERFACE~CHARACTER = #30))
      if ($BOT~CHARPOS <= $BOT~CHARCOUNT)
        add $BOT~CHARPOS 1
        echo ANSI_10 $USER_INTERFACE~CHARACTER
      end
    else
      getwordpos $USER_INTERFACE~CHARACTER $USER_INTERFACE~POS #13
      if ($USER_INTERFACE~POS > 0)
        setvar $USER_INTERFACE~FOUND_ENTER_KEY TRUE
      end
      striptext $USER_INTERFACE~CHARACTER #27&"[A"
      striptext $USER_INTERFACE~CHARACTER #27&"[B"
      striptext $USER_INTERFACE~CHARACTER #27&"[C"
      striptext $USER_INTERFACE~CHARACTER #27&"[D"
      striptext $USER_INTERFACE~CHARACTER #8
      striptext $USER_INTERFACE~CHARACTER #13
      getlength $USER_INTERFACE~CHARACTER $USER_INTERFACE~CHARACTERLENGTH
      goto :TREATASUSUAL
    end
  else
    :USER_INTERFACE~TREATASUSUAL
    if ($BOT~CHARPOS >= $BOT~CHARCOUNT)
      setvar $USER_INTERFACE~FRONTMACRO $BOT~PROMPTOUTPUT
      setvar $USER_INTERFACE~TAILMACRO ""&$USER_INTERFACE~CHARACTER&""
    else
      cuttext $BOT~PROMPTOUTPUT $USER_INTERFACE~FRONTMACRO 1 $BOT~CHARPOS
      cuttext $BOT~PROMPTOUTPUT $USER_INTERFACE~TAILMACRO ($BOT~CHARPOS + 1) ($BOT~CHARCOUNT - ($BOT~CHARPOS - 1))
      setvar $USER_INTERFACE~FRONTMACRO $USER_INTERFACE~FRONTMACRO&$USER_INTERFACE~CHARACTER
    end
    setvar $BOT~PROMPTOUTPUT $USER_INTERFACE~FRONTMACRO&$USER_INTERFACE~TAILMACRO
    getlength $BOT~PROMPTOUTPUT $BOT~CHARCOUNT
    add $BOT~CHARPOS $USER_INTERFACE~CHARACTERLENGTH
    if (($BOT~CHARCOUNT - $BOT~CHARPOS) > 0)
      echo $USER_INTERFACE~PROMPT $BOT~PROMPTOUTPUT #27 "[" ($BOT~CHARCOUNT - ($BOT~CHARPOS + 1)) "D"
    else
      echo $USER_INTERFACE~PROMPT $BOT~PROMPTOUTPUT
    end
    if ($USER_INTERFACE~FOUND_ENTER_KEY)
      gosub :DO_ENTER_KEY
      goto :DONESELFCOMMANDPROMPT
    end

  end
end
settextouttrigger TEXT :GETCHARACTER
pause
:USER_INTERFACE~REECHO
if (($BOT~CHARCOUNT - $BOT~CHARPOS) > 0)
  echo $USER_INTERFACE~PROMPT&$BOT~PROMPTOUTPUT&#27&"["&($BOT~CHARCOUNT - ($BOT~CHARPOS + 1))&"D"
else
  echo $USER_INTERFACE~PROMPT&$BOT~PROMPTOUTPUT
end
settexttrigger REECHO :REECHO
pause
:USER_INTERFACE~DONESELFCOMMANDPROMPT
killtrigger TEXT
killtrigger REECHO
return
:USER_INTERFACE~DO_ENTER_KEY

echo #27&"[255D"&#27&"[255B"&#27&"[K"
setvar $BOT~USER_COMMAND_LINE $BOT~PROMPTOUTPUT
gosub :DOADDHISTORY
return
:USER_INTERFACE~DOADDHISTORY


setvar $BOT~CHARCOUNT 0
setvar $BOT~CURRENTPROMPTTEXT ""
setvar $BOT~HISTORYINDEX 0
setvar $BOT~CHARPOS 0
setvar $BOT~PROMPTOUTPUT ""
setvar $BOT~HISTORYSTRING ""
cuttext $BOT~USER_COMMAND_LINE&"  " $USER_INTERFACE~CHECKFORCHAT 1 1
if ($BOT~USER_COMMAND_LINE <> "")
  add $BOT~HISTORYCOUNT 1
  if ($BOT~HISTORYCOUNT > 1)
    setvar $USER_INTERFACE~I $BOT~HISTORYMAX
    while ($USER_INTERFACE~I > 1)
      setvar $BOT~HISTORY[$USER_INTERFACE~I] $BOT~HISTORY[($USER_INTERFACE~I - 1)]
      setvar $BOT~HISTORYSTRING $BOT~HISTORY[$USER_INTERFACE~I]&"<<|HS|>>"&$BOT~HISTORYSTRING
      subtract $USER_INTERFACE~I 1
    end
  end

  if ($USER_INTERFACE~CHECKFORCHAT <> "`")
    setvar $BOT~HISTORY[1] $BOT~USER_COMMAND_LINE
    setvar $BOT~HISTORYSTRING $BOT~HISTORY[1]&"<<|HS|>>"&$BOT~HISTORYSTRING
  end
  savevar $BOT~HISTORYSTRING
end
return
:USER_INTERFACE~COMMAND_PROCESSING

gosub :BOT~LOAD_WATCHER_VARIABLES
setvar $USER_INTERFACE~B 1
while ($USER_INTERFACE~B <= $BOT~COMMAND_LINES)
  lowercase $BOT~COMMAND_LINES[$USER_INTERFACE~B][9]
  :USER_INTERFACE~COMMAND_FILTERING
  cuttext $BOT~COMMAND_LINES[$USER_INTERFACE~B][9]&"  " $USER_INTERFACE~CHECKFORCHAT 1 1
  cuttext $BOT~COMMAND_LINES[$USER_INTERFACE~B][9]&"  " $USER_INTERFACE~CHECKFORFINDER 1 1
  if ($USER_INTERFACE~CHECKFORCHAT = "'")
    cuttext $BOT~COMMAND_LINES[$USER_INTERFACE~B] $BOT~COMMAND_LINES[$USER_INTERFACE~B] 2 9999
    setvar $BOT~COMMAND_LINES[$USER_INTERFACE~B][9] "ss"
  elseif ($USER_INTERFACE~CHECKFORCHAT = "`")
    cuttext $BOT~COMMAND_LINES[$USER_INTERFACE~B] $BOT~COMMAND_LINES[$USER_INTERFACE~B] 2 9999
    setvar $BOT~COMMAND_LINES[$USER_INTERFACE~B][9] "fed"
  end
  if ($BOT~COMMAND_CALLER <> "self")
    if (($BOT~COMMAND_LINES[$USER_INTERFACE~B][9] = "ss") or ($BOT~COMMAND_LINES[$USER_INTERFACE~B][9] = "fed"))

      goto :BOT~WAIT_FOR_COMMAND
    end
  end
  savevar $SWITCHBOARD~SELF_COMMAND
  setvar $USER_INTERFACE~TYPED_COMMANDS[$USER_INTERFACE~B] $BOT~COMMAND_LINES[$USER_INTERFACE~B][9]
  gosub :USER_INTERFACE~RESOLVE_COMMAND_ALIAS
  if ($USER_INTERFACE~TYPED_COMMANDS[$USER_INTERFACE~B] = $BOT~COMMAND_LINES[$USER_INTERFACE~B][9])
    setvar $USER_INTERFACE~TYPED_COMMANDS[$USER_INTERFACE~B] ""
  end
  setvar $USER_INTERFACE~UPDATE_LIST " limps figs armids cim "
  getwordpos " "&$BOT~COMMAND_LINES[$USER_INTERFACE~B]&" " $USER_INTERFACE~POS " override "
  getwordpos " "&$BOT~COMMAND_LINES[$USER_INTERFACE~B]&" " $USER_INTERFACE~POS2 " overide "
  setvar $PLAYER~OVERRIDE FALSE
  if (($USER_INTERFACE~POS > 0) or ($USER_INTERFACE~POS2 > 0))
    setvar $PLAYER~OVERRIDE TRUE
  end
  savevar $PLAYER~OVERRIDE
  getwordpos $USER_INTERFACE~UPDATE_LIST $USER_INTERFACE~POS " "&$BOT~COMMAND_LINES[$USER_INTERFACE~B][9]&" "
  if ($USER_INTERFACE~POS > 0)
    setvar $BOT~COMMAND_LINES[$USER_INTERFACE~B][8] $BOT~COMMAND_LINES[$USER_INTERFACE~B][9]
    setvar $BOT~COMMAND_LINES[$USER_INTERFACE~B][9] "update"
    setvar $BOT~COMMAND_LINES[$USER_INTERFACE~B] $BOT~COMMAND_LINES[$USER_INTERFACE~B][1]&" "&$BOT~COMMAND_LINES[$USER_INTERFACE~B][2]&" "&$BOT~COMMAND_LINES[$USER_INTERFACE~B][3]&" "&$BOT~COMMAND_LINES[$USER_INTERFACE~B][4]&" "&$BOT~COMMAND_LINES[$USER_INTERFACE~B][5]&" "&$BOT~COMMAND_LINES[$USER_INTERFACE~B][6]&" "&$BOT~COMMAND_LINES[$USER_INTERFACE~B][7]&" "&$BOT~COMMAND_LINES[$USER_INTERFACE~B][8]&" "
  end
  setvar $USER_INTERFACE~DEPLOY_LIST " lay put place limp mine armid plimp mines climp cmine pmine topoff mines fig "
  getwordpos $USER_INTERFACE~DEPLOY_LIST $USER_INTERFACE~POS " "&$BOT~COMMAND_LINES[$USER_INTERFACE~B][9]&" "
  if ($USER_INTERFACE~POS > 0)
    if (($BOT~COMMAND_LINES[$USER_INTERFACE~B][9] <> "lay") or ($BOT~COMMAND_LINES[$USER_INTERFACE~B][9] <> "put") or ($BOT~COMMAND_LINES[$USER_INTERFACE~B][9] <> "place"))
      setvar $BOT~COMMAND_LINES[$USER_INTERFACE~B][8] $BOT~COMMAND_LINES[$USER_INTERFACE~B][9]
    end
    setvar $BOT~COMMAND_LINES[$USER_INTERFACE~B][9] "deploy"
    setvar $BOT~COMMAND_LINES[$USER_INTERFACE~B] $BOT~COMMAND_LINES[$USER_INTERFACE~B][1]&" "&$BOT~COMMAND_LINES[$USER_INTERFACE~B][2]&" "&$BOT~COMMAND_LINES[$USER_INTERFACE~B][3]&" "&$BOT~COMMAND_LINES[$USER_INTERFACE~B][4]&" "&$BOT~COMMAND_LINES[$USER_INTERFACE~B][5]&" "&$BOT~COMMAND_LINES[$USER_INTERFACE~B][6]&" "&$BOT~COMMAND_LINES[$USER_INTERFACE~B][7]&" "&$BOT~COMMAND_LINES[$USER_INTERFACE~B][8]&" "
  end
  if (($BOT~COMMAND_LINES[$USER_INTERFACE~B][9] = "figmove") or ($BOT~COMMAND_LINES[$USER_INTERFACE~B][9] = "movefigs"))
    setvar $BOT~COMMAND_LINES[$USER_INTERFACE~B][9] "movefig"
  end
  if (($BOT~COMMAND_LINES[$USER_INTERFACE~B][9] = "build") or ($BOT~COMMAND_LINES[$USER_INTERFACE~B][9] = "create") or ($BOT~COMMAND_LINES[$USER_INTERFACE~B][9] = "make"))


    if ($BOT~COMMAND_LINES[$USER_INTERFACE~B][1] = "port")
      setvar $BOT~COMMAND_LINES[$USER_INTERFACE~B][9] $BOT~COMMAND_LINES[$USER_INTERFACE~B][1]
    elseif ($BOT~COMMAND_LINES[$USER_INTERFACE~B][1] = "planet")
      setvar $BOT~COMMAND_LINES[$USER_INTERFACE~B][9] $BOT~COMMAND_LINES[$USER_INTERFACE~B][1]
    else
      setvar $BOT~COMMAND_LINES[$USER_INTERFACE~B][9] "port"
    end
    setvar $BOT~COMMAND_LINES[$USER_INTERFACE~B][8] $BOT~COMMAND_LINES[$USER_INTERFACE~B][7]
    setvar $BOT~COMMAND_LINES[$USER_INTERFACE~B][7] $BOT~COMMAND_LINES[$USER_INTERFACE~B][6]
    setvar $BOT~COMMAND_LINES[$USER_INTERFACE~B][6] $BOT~COMMAND_LINES[$USER_INTERFACE~B][5]
    setvar $BOT~COMMAND_LINES[$USER_INTERFACE~B][5] $BOT~COMMAND_LINES[$USER_INTERFACE~B][4]
    setvar $BOT~COMMAND_LINES[$USER_INTERFACE~B][4] $BOT~COMMAND_LINES[$USER_INTERFACE~B][3]
    setvar $BOT~COMMAND_LINES[$USER_INTERFACE~B][3] $BOT~COMMAND_LINES[$USER_INTERFACE~B][2]
    setvar $BOT~COMMAND_LINES[$USER_INTERFACE~B][2] $BOT~COMMAND_LINES[$USER_INTERFACE~B][1]
    setvar $BOT~COMMAND_LINES[$USER_INTERFACE~B][1] "create"
    setvar $BOT~COMMAND_LINES[$USER_INTERFACE~B] $BOT~COMMAND_LINES[$USER_INTERFACE~B][1]&" "&$BOT~COMMAND_LINES[$USER_INTERFACE~B][2]&" "&$BOT~COMMAND_LINES[$USER_INTERFACE~B][3]&" "&$BOT~COMMAND_LINES[$USER_INTERFACE~B][4]&" "&$BOT~COMMAND_LINES[$USER_INTERFACE~B][5]&" "&$BOT~COMMAND_LINES[$USER_INTERFACE~B][6]&" "&$BOT~COMMAND_LINES[$USER_INTERFACE~B][7]&" "&$BOT~COMMAND_LINES[$USER_INTERFACE~B][8]&" "
  end
  if (($BOT~COMMAND_LINES[$USER_INTERFACE~B][9] = "kill") or ($BOT~COMMAND_LINES[$USER_INTERFACE~B][9] = "destroy") or ($BOT~COMMAND_LINES[$USER_INTERFACE~B][9] = "blow"))
    if ($BOT~COMMAND_LINES[$USER_INTERFACE~B][1] = "port")
      setvar $BOT~COMMAND_LINES[$USER_INTERFACE~B][9] $BOT~COMMAND_LINES[$USER_INTERFACE~B][1]
      setvar $BOT~COMMAND_LINES[$USER_INTERFACE~B][1] "kill"
    elseif ($BOT~COMMAND_LINES[$USER_INTERFACE~B][1] = "planet")
      setvar $BOT~COMMAND_LINES[$USER_INTERFACE~B][9] $BOT~COMMAND_LINES[$USER_INTERFACE~B][1]
      setvar $BOT~COMMAND_LINES[$USER_INTERFACE~B][1] "kill"
    else



      setvar $BOT~COMMAND_LINES[$USER_INTERFACE~B][9] "kill"
    end
    setvar $BOT~COMMAND_LINES[$USER_INTERFACE~B] $BOT~COMMAND_LINES[$USER_INTERFACE~B][1]&" "&$BOT~COMMAND_LINES[$USER_INTERFACE~B][2]&" "&$BOT~COMMAND_LINES[$USER_INTERFACE~B][3]&" "&$BOT~COMMAND_LINES[$USER_INTERFACE~B][4]&" "&$BOT~COMMAND_LINES[$USER_INTERFACE~B][5]&" "&$BOT~COMMAND_LINES[$USER_INTERFACE~B][6]&" "&$BOT~COMMAND_LINES[$USER_INTERFACE~B][7]&" "&$BOT~COMMAND_LINES[$USER_INTERFACE~B][8]&" "
  end
  if (($BOT~COMMAND_LINES[$USER_INTERFACE~B][9] = "upgrade") or ($BOT~COMMAND_LINES[$USER_INTERFACE~B][9] = "max"))
    if ($BOT~COMMAND_LINES[$USER_INTERFACE~B][1] = "port")
      setvar $BOT~COMMAND_LINES[$USER_INTERFACE~B][9] $BOT~COMMAND_LINES[$USER_INTERFACE~B][1]
    elseif ($BOT~COMMAND_LINES[$USER_INTERFACE~B][1] = "planet")
      setvar $BOT~COMMAND_LINES[$USER_INTERFACE~B][9] $BOT~COMMAND_LINES[$USER_INTERFACE~B][1]
    else
      setvar $BOT~COMMAND_LINES[$USER_INTERFACE~B][9] "port"
    end
    setvar $BOT~COMMAND_LINES[$USER_INTERFACE~B][8] $BOT~COMMAND_LINES[$USER_INTERFACE~B][7]
    setvar $BOT~COMMAND_LINES[$USER_INTERFACE~B][7] $BOT~COMMAND_LINES[$USER_INTERFACE~B][6]
    setvar $BOT~COMMAND_LINES[$USER_INTERFACE~B][6] $BOT~COMMAND_LINES[$USER_INTERFACE~B][5]
    setvar $BOT~COMMAND_LINES[$USER_INTERFACE~B][5] $BOT~COMMAND_LINES[$USER_INTERFACE~B][4]
    setvar $BOT~COMMAND_LINES[$USER_INTERFACE~B][4] $BOT~COMMAND_LINES[$USER_INTERFACE~B][3]
    setvar $BOT~COMMAND_LINES[$USER_INTERFACE~B][3] $BOT~COMMAND_LINES[$USER_INTERFACE~B][2]
    setvar $BOT~COMMAND_LINES[$USER_INTERFACE~B][2] $BOT~COMMAND_LINES[$USER_INTERFACE~B][1]
    setvar $BOT~COMMAND_LINES[$USER_INTERFACE~B][1] "upgrade"
    setvar $BOT~COMMAND_LINES[$USER_INTERFACE~B] $BOT~COMMAND_LINES[$USER_INTERFACE~B][1]&" "&$BOT~COMMAND_LINES[$USER_INTERFACE~B][2]&" "&$BOT~COMMAND_LINES[$USER_INTERFACE~B][3]&" "&$BOT~COMMAND_LINES[$USER_INTERFACE~B][4]&" "&$BOT~COMMAND_LINES[$USER_INTERFACE~B][5]&" "&$BOT~COMMAND_LINES[$USER_INTERFACE~B][6]&" "&$BOT~COMMAND_LINES[$USER_INTERFACE~B][7]&" "&$BOT~COMMAND_LINES[$USER_INTERFACE~B][8]&" "
  end
  if (($BOT~COMMAND_LINES[$USER_INTERFACE~B][9] = "f") or ($BOT~COMMAND_LINES[$USER_INTERFACE~B][9] = "fde") or ($BOT~COMMAND_LINES[$USER_INTERFACE~B][9] = "ufde") or ($BOT~COMMAND_LINES[$USER_INTERFACE~B][9] = "nf") or ($BOT~COMMAND_LINES[$USER_INTERFACE~B][9] = "uf") or ($BOT~COMMAND_LINES[$USER_INTERFACE~B][9] = "de") or ($BOT~COMMAND_LINES[$USER_INTERFACE~B][9] = "fp") or ($BOT~COMMAND_LINES[$USER_INTERFACE~B][9] = "fup") or ($BOT~COMMAND_LINES[$USER_INTERFACE~B][9] = "nfup"))
    setvar $BOT~COMMAND_LINES[$USER_INTERFACE~B][8] $BOT~COMMAND_LINES[$USER_INTERFACE~B][7]
    setvar $BOT~COMMAND_LINES[$USER_INTERFACE~B][7] $BOT~COMMAND_LINES[$USER_INTERFACE~B][6]
    setvar $BOT~COMMAND_LINES[$USER_INTERFACE~B][6] $BOT~COMMAND_LINES[$USER_INTERFACE~B][5]
    setvar $BOT~COMMAND_LINES[$USER_INTERFACE~B][5] $BOT~COMMAND_LINES[$USER_INTERFACE~B][4]
    setvar $BOT~COMMAND_LINES[$USER_INTERFACE~B][4] $BOT~COMMAND_LINES[$USER_INTERFACE~B][3]
    setvar $BOT~COMMAND_LINES[$USER_INTERFACE~B][3] $BOT~COMMAND_LINES[$USER_INTERFACE~B][2]
    setvar $BOT~COMMAND_LINES[$USER_INTERFACE~B][2] $BOT~COMMAND_LINES[$USER_INTERFACE~B][1]
    setvar $BOT~COMMAND_LINES[$USER_INTERFACE~B][1] $BOT~COMMAND_LINES[$USER_INTERFACE~B][9]
    setvar $BOT~COMMAND_LINES[$USER_INTERFACE~B][9] "find"
    setvar $BOT~COMMAND_LINES[$USER_INTERFACE~B] $BOT~COMMAND_LINES[$USER_INTERFACE~B][1]&" "&$BOT~COMMAND_LINES[$USER_INTERFACE~B][2]&" "&$BOT~COMMAND_LINES[$USER_INTERFACE~B][3]&" "&$BOT~COMMAND_LINES[$USER_INTERFACE~B][4]&" "&$BOT~COMMAND_LINES[$USER_INTERFACE~B][5]&" "&$BOT~COMMAND_LINES[$USER_INTERFACE~B][6]&" "&$BOT~COMMAND_LINES[$USER_INTERFACE~B][7]&" "&$BOT~COMMAND_LINES[$USER_INTERFACE~B][8]&" "
  end
  setvar $USER_INTERFACE~I 1
  while ($USER_INTERFACE~I <= 8)
    if ($BOT~COMMAND_LINES[$USER_INTERFACE~B][$USER_INTERFACE~I] = "s")
      setvar $BOT~COMMAND_LINES[$USER_INTERFACE~B][$USER_INTERFACE~I] $MAP~STARDOCK
    elseif ($BOT~COMMAND_LINES[$USER_INTERFACE~B][$USER_INTERFACE~I] = "r")
      setvar $BOT~COMMAND_LINES[$USER_INTERFACE~B][$USER_INTERFACE~I] $MAP~RYLOS
    elseif ($BOT~COMMAND_LINES[$USER_INTERFACE~B][$USER_INTERFACE~I] = "a")
      setvar $BOT~COMMAND_LINES[$USER_INTERFACE~B][$USER_INTERFACE~I] $MAP~ALPHA_CENTAURI
    elseif ($BOT~COMMAND_LINES[$USER_INTERFACE~B][$USER_INTERFACE~I] = "h")
      setvar $BOT~COMMAND_LINES[$USER_INTERFACE~B][$USER_INTERFACE~I] $MAP~HOME_SECTOR
    elseif ($BOT~COMMAND_LINES[$USER_INTERFACE~B][$USER_INTERFACE~I] = "b")
      setvar $BOT~COMMAND_LINES[$USER_INTERFACE~B][$USER_INTERFACE~I] $MAP~BACKDOOR
    elseif ($BOT~COMMAND_LINES[$USER_INTERFACE~B][$USER_INTERFACE~I] = "x")
      setvar $BOT~COMMAND_LINES[$USER_INTERFACE~B][$USER_INTERFACE~I] $BOT~SAFE_SHIP
    elseif ($BOT~COMMAND_LINES[$USER_INTERFACE~B][$USER_INTERFACE~I] = "l")
      if (($BOT~SAFE_PLANET <> "") and ($BOT~SAFE_PLANET <> 0))
        getsectorparameter $BOT~SAFE_PLANET "PSECTOR" $USER_INTERFACE~CHECK
        setvar $BOT~COMMAND_LINES[$USER_INTERFACE~B][$USER_INTERFACE~I] $USER_INTERFACE~CHECK
      end
    end
    add $USER_INTERFACE~I 1
  end
  setvar $USER_INTERFACE~TRAVELCOMMANDS "mow twarp bwarp pwarp smow m t b p "

  getwordpos $USER_INTERFACE~TRAVELCOMMANDS $USER_INTERFACE~POS $BOT~COMMAND_LINES[$USER_INTERFACE~B][9]
  if ($USER_INTERFACE~POS > 0)
    getwordpos " "&$BOT~COMMAND_LINES[$USER_INTERFACE~B]&" " $USER_INTERFACE~POS " planet "
    if ($USER_INTERFACE~POS > 0)
      if ($BOT~COMMAND_LINES[$USER_INTERFACE~B][1] = "planet")
        setvar $BOT~COMMAND_LINES[$USER_INTERFACE~B][1] $BOT~COMMAND_LINES[$USER_INTERFACE~B][2]

        getsectorparameter $BOT~COMMAND_LINES[$USER_INTERFACE~B][1] "PSECTOR" $BOT~COMMAND_LINES[$USER_INTERFACE~B][1]
      end
      setvar $USER_INTERFACE~I 1
      while ($USER_INTERFACE~I <= $BOT~PARMS)
        if ($BOT~COMMAND_LINES[$USER_INTERFACE~B][$USER_INTERFACE~I] = "planet")
          setvar $USER_INTERFACE~OLD_VALUE $BOT~COMMAND_LINES[$USER_INTERFACE~B][1]
          setvar $BOT~COMMAND_LINES[$USER_INTERFACE~B][$USER_INTERFACE~I] ""
          setvar $BOT~COMMAND_LINES[$USER_INTERFACE~B][2] $BOT~COMMAND_LINES[$USER_INTERFACE~B][1]
          getsectorparameter $BOT~COMMAND_LINES[$USER_INTERFACE~B][1] "PSECTOR" $BOT~COMMAND_LINES[$USER_INTERFACE~B][1]
        end
        add $USER_INTERFACE~I 1
      end
    end
  end

  setvar $BOT~PARM1 $BOT~COMMAND_LINES[$USER_INTERFACE~B][1]
  setvar $BOT~PARM2 $BOT~COMMAND_LINES[$USER_INTERFACE~B][2]
  setvar $BOT~PARM3 $BOT~COMMAND_LINES[$USER_INTERFACE~B][3]
  setvar $BOT~PARM4 $BOT~COMMAND_LINES[$USER_INTERFACE~B][4]
  setvar $BOT~PARM5 $BOT~COMMAND_LINES[$USER_INTERFACE~B][5]
  setvar $BOT~PARM6 $BOT~COMMAND_LINES[$USER_INTERFACE~B][6]
  setvar $BOT~PARM7 $BOT~COMMAND_LINES[$USER_INTERFACE~B][7]
  setvar $BOT~PARM8 $BOT~COMMAND_LINES[$USER_INTERFACE~B][8]
  if ($BOT~COMMAND_LINES[$USER_INTERFACE~B][9] = 0)
    loadvar $PLAYER~CURRENT_SECTOR
    if (($PLAYER~CURRENT_SECTOR = 0) or ($PLAYER~CURRENT_SECTOR = ""))
      gosub :PLAYER~QUIKSTATS
    end
    send "'["&$BOT~MODE&"] ["&$PLAYER~CURRENT_SECTOR&"] {"&$SWITCHBOARD~BOT_NAME&"} - You are logged into this bot.  Use "&$SWITCHBOARD~BOT_NAME&" help for commands.*"
    goto :BOT~WAIT_FOR_COMMAND
  end
  getwordpos " "&$BOT~COMMAND_LINES[$USER_INTERFACE~B]&" " $USER_INTERFACE~STOPCHECK " off "
  gosub :FORMATCOMMAND
  gosub :FINDCOMMAND
  if ($USER_INTERFACE~CURRENTCATEGORY = "Modes")
    if ($USER_INTERFACE~STOPCHECK > 0)
      killtrigger SHUTDOWNTHEMODULE
      stop $BOT~LAST_LOADED_MODULE
      setvar $BOT~MODE "General"
      savevar $BOT~MODE
      setvar $switchboard~message ""&$USER_INTERFACE~FORMATTED_COMMAND&" mode is now off.*"
      gosub :switchboard~switchboard
      goto :BOT~WAIT_FOR_COMMAND
    end
  end
  setvar $USER_INTERFACE~ISFOUND FALSE
  if (($USER_INTERFACE~DOESEXIST > 0) or ($USER_INTERFACE~DOESEXISTHIDDEN > 0))
    setvar $USER_INTERFACE~ISFOUND TRUE
    gosub :LOAD_THE_MODULE
    if ($USER_INTERFACE~B < $BOT~COMMAND_LINES)

      killtrigger LOADENDED
      seteventtrigger LOADENDED :LOADENDED "SCRIPT STOPPED" $USER_INTERFACE~LOADED
      pause
      :USER_INTERFACE~LOADENDED
      if ($USER_INTERFACE~CURRENTCATEGORY = "Modes")
        setvar $BOT~MODE "General"
        savevar $BOT~MODE
      end
    else
      goto :BOT~WAIT_FOR_COMMAND
    end
  else
    getwordpos $BOT~INTERNALCOMMANDLIST&$BOT~DOUBLEDCOMMANDLIST $USER_INTERFACE~POS " "&$BOT~COMMAND_LINES[$USER_INTERFACE~B][9]&" "
    if ($USER_INTERFACE~POS > 0)
      setvar $USER_INTERFACE~ISFOUND TRUE
      gosub :BOT~KILLTHETRIGGERS
      gosub ":INTERNAL_COMMANDS~"&$BOT~COMMAND_LINES[$USER_INTERFACE~B][9]
    end
  end
  if ($USER_INTERFACE~ISFOUND <> TRUE)
    if ($USER_INTERFACE~TEMP_BOT_NAME <> "all")
      setvar $SWITCHBOARD~MESSAGE $USER_INTERFACE~FORMATTED_COMMAND&" is not a valid command.*"
      gosub :SWITCHBOARD~SWITCHBOARD
    end
  end
  add $USER_INTERFACE~B 1
end
goto :BOT~WAIT_FOR_COMMAND
:USER_INTERFACE~RESOLVE_COMMAND_ALIAS

fileexists $USER_INTERFACE~ALIASES_EXIST "scripts\"&$BOT~MOMBOT_DIRECTORY&"\aliases.cfg"
if ($USER_INTERFACE~ALIASES_EXIST <> TRUE)
  return
end

readtoarray "scripts\"&$BOT~MOMBOT_DIRECTORY&"\aliases.cfg" $USER_INTERFACE~ALIAS_LINES
setvar $USER_INTERFACE~ALIAS_PASS 1
while ($USER_INTERFACE~ALIAS_PASS <= 5)
  setvar $USER_INTERFACE~ALIAS_MATCH FALSE
  setvar $USER_INTERFACE~ALIAS_INDEX 1
  while ($USER_INTERFACE~ALIAS_INDEX <= $USER_INTERFACE~ALIAS_LINES)
    setvar $USER_INTERFACE~ALIAS_LINE $USER_INTERFACE~ALIAS_LINES[$USER_INTERFACE~ALIAS_INDEX]
    cuttext $USER_INTERFACE~ALIAS_LINE&" " $USER_INTERFACE~ALIAS_FIRST_CHAR 1 1
    if ($USER_INTERFACE~ALIAS_FIRST_CHAR <> "#")
      getwordpos $USER_INTERFACE~ALIAS_LINE $USER_INTERFACE~ALIAS_EQ_POS "="
      if ($USER_INTERFACE~ALIAS_EQ_POS > 1)
        cuttext $USER_INTERFACE~ALIAS_LINE $USER_INTERFACE~ALIAS_NAME 1 ($USER_INTERFACE~ALIAS_EQ_POS - 1)
        cuttext $USER_INTERFACE~ALIAS_LINE $USER_INTERFACE~ALIAS_TARGET ($USER_INTERFACE~ALIAS_EQ_POS + 1) 9999
        lowercase $USER_INTERFACE~ALIAS_NAME
        lowercase $USER_INTERFACE~ALIAS_TARGET
        setvar $USER_INTERFACE~ALIAS_NAMES ","&$USER_INTERFACE~ALIAS_NAME&","
        striptext $USER_INTERFACE~ALIAS_NAMES " "
        getwordpos $USER_INTERFACE~ALIAS_NAMES $USER_INTERFACE~ALIAS_NAME_POS ","&$BOT~COMMAND_LINES[$USER_INTERFACE~B][9]&","
        if ($USER_INTERFACE~ALIAS_NAME_POS > 0)
          setvar $BOT~COMMAND_LINES[$USER_INTERFACE~B][9] $USER_INTERFACE~ALIAS_TARGET
          setvar $USER_INTERFACE~ALIAS_MATCH TRUE
          goto :USER_INTERFACE~NEXT_ALIAS_PASS
        end
      end
    end
    add $USER_INTERFACE~ALIAS_INDEX 1
  end

  if ($USER_INTERFACE~ALIAS_MATCH <> TRUE)
    return
  end

  :USER_INTERFACE~NEXT_ALIAS_PASS
  add $USER_INTERFACE~ALIAS_PASS 1
end
return
:USER_INTERFACE~FORMATCOMMAND

cuttext $BOT~COMMAND_LINES[$USER_INTERFACE~B][9]&" " $USER_INTERFACE~FIRSTCHAR 1 1
cuttext $BOT~COMMAND_LINES[$USER_INTERFACE~B][9]&" " $USER_INTERFACE~RESTOFCOMMAND 2 999
uppercase $USER_INTERFACE~FIRSTCHAR
setvar $USER_INTERFACE~FORMATTED_COMMAND $USER_INTERFACE~FIRSTCHAR&$USER_INTERFACE~RESTOFCOMMAND
striptext $USER_INTERFACE~FORMATTED_COMMAND " "
return
:USER_INTERFACE~FINDCOMMAND
setvar $BOT~MODULECATEGORY ""
gosub :USER_INTERFACE~CHECK_PRELOAD
if ($USER_INTERFACE~DOESEXISTHIDDEN)
  return
end
setvar $USER_INTERFACE~I 1
while ($USER_INTERFACE~I <= 3)
  setvar $USER_INTERFACE~J 1
  while ($USER_INTERFACE~J <= 7)
    if ($USER_INTERFACE~I = 3)
      fileexists $USER_INTERFACE~DOESEXIST "scripts\"&$BOT~MOMBOT_DIRECTORY&"\"&$BOT~CATAGORIES[$USER_INTERFACE~I]&"\"&$BOT~COMMAND_LINES[$USER_INTERFACE~B][9]&".cts"
      fileexists $USER_INTERFACE~DOESEXISTHIDDEN "scripts\"&$BOT~MOMBOT_DIRECTORY&"\"&$BOT~CATAGORIES[$USER_INTERFACE~I]&"\_"&$BOT~COMMAND_LINES[$USER_INTERFACE~B][9]&".cts"
      if ($USER_INTERFACE~DOESEXIST or $USER_INTERFACE~DOESEXISTHIDDEN)
        setvar $USER_INTERFACE~CURRENTCATEGORY $BOT~CATAGORIES[$USER_INTERFACE~I]
        if ($USER_INTERFACE~DOESEXISTHIDDEN)
          setvar $BOT~MODULECATEGORY $BOT~CATAGORIES[$USER_INTERFACE~I]&"\_"
        else
          setvar $BOT~MODULECATEGORY $BOT~CATAGORIES[$USER_INTERFACE~I]&"\"
        end
        setvar $USER_INTERFACE~CURRENTLIST $BOT~INTERNALCOMMANDLIST[$USER_INTERFACE~J]
        return
      end
    else
      fileexists $USER_INTERFACE~DOESEXIST "scripts\"&$BOT~MOMBOT_DIRECTORY&"\"&$BOT~CATAGORIES[$USER_INTERFACE~I]&"\"&$BOT~TYPES[$USER_INTERFACE~J]&"\"&$BOT~COMMAND_LINES[$USER_INTERFACE~B][9]&".cts"
      fileexists $USER_INTERFACE~DOESEXISTHIDDEN "scripts\"&$BOT~MOMBOT_DIRECTORY&"\"&$BOT~CATAGORIES[$USER_INTERFACE~I]&"\"&$BOT~TYPES[$USER_INTERFACE~J]&"\_"&$BOT~COMMAND_LINES[$USER_INTERFACE~B][9]&".cts"
      if ($USER_INTERFACE~DOESEXIST or $USER_INTERFACE~DOESEXISTHIDDEN)
        setvar $USER_INTERFACE~CURRENTCATEGORY $BOT~CATAGORIES[$USER_INTERFACE~I]
        if ($USER_INTERFACE~DOESEXISTHIDDEN)
          setvar $BOT~MODULECATEGORY $BOT~CATAGORIES[$USER_INTERFACE~I]&"\"&$BOT~TYPES[$USER_INTERFACE~J]&"\_"
        else
          setvar $BOT~MODULECATEGORY $BOT~CATAGORIES[$USER_INTERFACE~I]&"\"&$BOT~TYPES[$USER_INTERFACE~J]&"\"
        end
        setvar $USER_INTERFACE~CURRENTLIST $BOT~INTERNALCOMMANDLIST[$USER_INTERFACE~J]
        return
      end
    end
    add $USER_INTERFACE~J 1
  end
  add $USER_INTERFACE~I 1
end
return
:USER_INTERFACE~CHECK_PRELOAD
setvar $USER_INTERFACE~DOESEXIST 0
setvar $USER_INTERFACE~DOESEXISTHIDDEN 0
fileexists $USER_INTERFACE~DOESEXISTHIDDEN "scripts\"&$BOT~MOMBOT_DIRECTORY&"\preload\_"&$BOT~COMMAND_LINES[$USER_INTERFACE~B][9]&".cts"
if ($USER_INTERFACE~DOESEXISTHIDDEN <> TRUE)
  return
end

setvar $BOT~MODULECATEGORY "preload\_"
if ($BOT~COMMAND_LINES[$USER_INTERFACE~B][9] = "ldrop")
  setvar $USER_INTERFACE~CURRENTCATEGORY "Modes"
  setvar $USER_INTERFACE~CURRENTLIST $BOT~INTERNALCOMMANDLIST[6]
elseif ($BOT~COMMAND_LINES[$USER_INTERFACE~B][9] = "macro_kit")
  setvar $USER_INTERFACE~CURRENTCATEGORY "Commands"
  setvar $USER_INTERFACE~CURRENTLIST $BOT~INTERNALCOMMANDLIST[3]
elseif ($BOT~COMMAND_LINES[$USER_INTERFACE~B][9] = "dock_shopper")
  setvar $USER_INTERFACE~CURRENTCATEGORY "Commands"
  setvar $USER_INTERFACE~CURRENTLIST $BOT~INTERNALCOMMANDLIST[7]
elseif ($BOT~COMMAND_LINES[$USER_INTERFACE~B][9] = "kazi")
  setvar $USER_INTERFACE~CURRENTCATEGORY "Commands"
  setvar $USER_INTERFACE~CURRENTLIST $BOT~INTERNALCOMMANDLIST[6]
else
  setvar $USER_INTERFACE~CURRENTCATEGORY "Commands"
  setvar $USER_INTERFACE~CURRENTLIST ""
end
return
:USER_INTERFACE~RUN_MODULE

gosub :LOAD_THE_MODULE
goto :BOT~WAIT_FOR_COMMAND
:USER_INTERFACE~LOAD_THE_MODULE

setvar $BOT~USER_COMMAND_LINE $BOT~COMMAND_LINES[$USER_INTERFACE~B]
setvar $BOT~COMMAND $BOT~COMMAND_LINES[$USER_INTERFACE~B][9]
setvar $BOT~COMMAND_TYPED $USER_INTERFACE~TYPED_COMMANDS[$USER_INTERFACE~B]
setvar $BOT~PARM1 $BOT~COMMAND_LINES[$USER_INTERFACE~B][1]
setvar $BOT~PARM2 $BOT~COMMAND_LINES[$USER_INTERFACE~B][2]
setvar $BOT~PARM3 $BOT~COMMAND_LINES[$USER_INTERFACE~B][3]
setvar $BOT~PARM4 $BOT~COMMAND_LINES[$USER_INTERFACE~B][4]
setvar $BOT~PARM5 $BOT~COMMAND_LINES[$USER_INTERFACE~B][5]
setvar $BOT~PARM6 $BOT~COMMAND_LINES[$USER_INTERFACE~B][6]
setvar $BOT~PARM7 $BOT~COMMAND_LINES[$USER_INTERFACE~B][7]
setvar $BOT~PARM8 $BOT~COMMAND_LINES[$USER_INTERFACE~B][8]
gosub :BOT~BACKWARDS_COMPATIBLE
getwordpos " "&$BOT~COMMAND_LINES[$USER_INTERFACE~B]&" " $USER_INTERFACE~HELPCHECK " help "
getwordpos " "&$BOT~COMMAND_LINES[$USER_INTERFACE~B]&" " $USER_INTERFACE~HELPCHECK2 " ? "
if (($USER_INTERFACE~CURRENTCATEGORY = "Modes") and (($USER_INTERFACE~HELPCHECK <= 0) and ($USER_INTERFACE~HELPCHECK2 <= 0)))
  stop $BOT~LAST_LOADED_MODULE
  setvar $BOT~LAST_LOADED_MODULE "scripts\"&$BOT~MOMBOT_DIRECTORY&"\"&$BOT~MODULECATEGORY&$BOT~COMMAND_LINES[$USER_INTERFACE~B][9]&".cts"
  setvar $BOT~MODE $USER_INTERFACE~FORMATTED_COMMAND
  savevar $BOT~MODE
  savevar $BOT~LAST_LOADED_MODULE
end
setvar $USER_INTERFACE~LOADED "scripts\"&$BOT~MOMBOT_DIRECTORY&"\"&$BOT~MODULECATEGORY&$BOT~COMMAND_LINES[$USER_INTERFACE~B][9]&".cts"
stop $USER_INTERFACE~LOADED
load $USER_INTERFACE~LOADED
return
:USER_INTERFACE~HOTKEY_ACCESS


gosub :BOT~BIGDELAY_KILLTHETRIGGERS
setvar $SWITCHBOARD~SELF_COMMAND TRUE
setvar $USER_INTERFACE~B 1
setvar $BOT~COMMAND_LINES[$USER_INTERFACE~B][9] ""
setvar $USER_INTERFACE~INVALID FALSE
setvar $BOT~PARM1 ""
setvar $BOT~PARM2 ""
setvar $BOT~PARM3 ""
setvar $BOT~PARM4 ""
setvar $BOT~PARM5 ""
setvar $BOT~PARM6 ""
setvar $BOT~PARM7 ""
setvar $BOT~PARM8 ""


echo #27 "[1A" #27 "[K" ANSI_15 "**Hotkey" ANSI_4
getconsoleinput $USER_INTERFACE~TEMPCHARACTER SINGLEKEY
:USER_INTERFACE~CHECKHOTKEY
getcharcode $USER_INTERFACE~TEMPCHARACTER $USER_INTERFACE~CHARCODE
gosub :BOT~KILLTHETRIGGERS
if ($USER_INTERFACE~CHARCODE <= 0)
  echo #27 "[10D          " #27 "[10D"
  goto :BOT~WAIT_FOR_COMMAND
end
setvar $USER_INTERFACE~TEMP $BOT~HOTKEYS[$USER_INTERFACE~CHARCODE]
if (($USER_INTERFACE~TEMP <> 0) and ($USER_INTERFACE~TEMP <> ""))
  setvar $BOT~COMMAND_LINES[$USER_INTERFACE~B][9] $BOT~CUSTOM_COMMANDS[$USER_INTERFACE~TEMP]
else
  setvar $USER_INTERFACE~INVALID TRUE
end
cuttext $BOT~COMMAND_LINES[$USER_INTERFACE~B][9]&"  " $USER_INTERFACE~TEST 1 1
if ($USER_INTERFACE~CHARCODE = 48)
  setvar $USER_INTERFACE~I 10
  goto :RUNHOTSCRIPT
elseif ($USER_INTERFACE~CHARCODE = 63)
  setvar $BOT~COMMAND_LINES[$USER_INTERFACE~B] "help"
  goto :RUNUSERCOMMANDLINE
elseif (($USER_INTERFACE~CHARCODE >= 49) and ($USER_INTERFACE~CHARCODE <= 57))
  setvar $USER_INTERFACE~I ($USER_INTERFACE~CHARCODE - 48)
  goto :RUNHOTSCRIPT
elseif (($USER_INTERFACE~TEST = ":") and ($USER_INTERFACE~INVALID = FALSE))
  goto $BOT~COMMAND_LINES[$USER_INTERFACE~B][9]
elseif ($USER_INTERFACE~INVALID = FALSE)
  setvar $BOT~COMMAND_LINES[$USER_INTERFACE~B] $BOT~COMMAND_LINES[$USER_INTERFACE~B][9]
  goto :RUNUSERCOMMANDLINE
end
echo #27 "[10D          " #27 "[10D"
goto :BOT~WAIT_FOR_COMMAND
:USER_INTERFACE~SCRIPT_ACCESS


gosub :BOT~KILLTHETRIGGERS
setvar $USER_INTERFACE~I 1
echo #27 "[3A" #27 "[K*" #27 "[K*" #27 "[K*" ANSI_14 "*Which script to run?                      *----------------------------------"
while (($USER_INTERFACE~I <= $BOT~HOTKEY_SCRIPTS) and ($USER_INTERFACE~I <= 10))
  if ($BOT~HOTKEY_SCRIPTS[$USER_INTERFACE~I] <> 0)
    if ($USER_INTERFACE~I >= 10)
      settextouttrigger "key"&$USER_INTERFACE~I :TRIGGERHOTSCRIPT 0
      echo "*"&ANSI_15&0&ANSI_14&") "&ANSI_15&$BOT~HOTKEY_SCRIPTS[$USER_INTERFACE~I][1]
    else
      settextouttrigger "key"&$USER_INTERFACE~I :TRIGGERHOTSCRIPT $USER_INTERFACE~I
      echo "*"&ANSI_15&$USER_INTERFACE~I&ANSI_14&") "&ANSI_15&$BOT~HOTKEY_SCRIPTS[$USER_INTERFACE~I][1]
    end
  end
  add $USER_INTERFACE~I 1
end
settextouttrigger ECHOHELP2 :SCRIPT_ACCESS #63
setdelaytrigger NOTFASTENOUGH2 :DONESCRIPTS 9000
settextouttrigger NONEAVAIL2 :DONESCRIPTS
echo #27 "[1A" #27 "[K" ANSI_14 "***Scripts" ANSI_15 ">" ANSI_7
pause
:USER_INTERFACE~DONESCRIPTS
echo #27 "[10D          " #27 "[10D"
goto :BOT~WAIT_FOR_COMMAND
:USER_INTERFACE~TRIGGERHOTSCRIPT
getouttext $USER_INTERFACE~I
if ($USER_INTERFACE~I = 0)
  setvar $USER_INTERFACE~I 10
end
:USER_INTERFACE~RUNHOTSCRIPT
load $BOT~HOTKEY_SCRIPTS[$USER_INTERFACE~I]
getwordpos $BOT~HOTKEY_SCRIPTS[$USER_INTERFACE~I] $USER_INTERFACE~POS "scripts/"
if ($USER_INTERFACE~POS > 0)
  fileexists $USER_INTERFACE~CHK $BOT~HOTKEY_SCRIPTS[$USER_INTERFACE~I]
else
  fileexists $USER_INTERFACE~CHK "scripts/"&$BOT~HOTKEY_SCRIPTS[$USER_INTERFACE~I]
end
if ($USER_INTERFACE~CHK <> TRUE)
  echo ANSI_4&"*"&$BOT~HOTKEY_SCRIPTS[$USER_INTERFACE~I]&" does not exist in specified location.  Please check your "&$BOT~SCRIPT_FILE&" file to make sure it is correct.*"&ANSI_7
end
goto :BOT~WAIT_FOR_COMMAND
:USER_INTERFACE~VERIFY_USER_STATUS



setvar $USER_INTERFACE~I 1
lowercase $USER_INTERFACE~USER_NAME
while ($USER_INTERFACE~I <= $BOT~CORPYCOUNT)
  cuttext $BOT~CORPY[$USER_INTERFACE~I] $USER_INTERFACE~NAME 1 6
  setvar $USER_INTERFACE~UNSTRIPPED_NAME $USER_INTERFACE~NAME
  lowercase $USER_INTERFACE~NAME
  trim $USER_INTERFACE~USER_NAME
  trim $USER_INTERFACE~NAME
  if ($USER_INTERFACE~USER_NAME = $USER_INTERFACE~NAME)
    setvar $BOT~COMMAND_CALLER $USER_INTERFACE~UNSTRIPPED_NAME
    savevar $BOT~COMMAND_CALLER
    setvar $USER_INTERFACE~AUTHORIZATION 1
    return
  end
  add $USER_INTERFACE~I 1
end
return
:USER_INTERFACE~CHK_LOGIN
if ($USER_INTERFACE~LOGGEDIN[$USER_INTERFACE~USER_NAME] = 1)
  setvar $USER_INTERFACE~LOGGED 1
else
  setvar $USER_INTERFACE~LOGGED 0
end
return

:BIGDELAY_KILLTHETRIGGERS
killalltriggers
setdelaytrigger UNFREEZINGTRIGGERBIGDELAY :UNFREEZEBOT 1800000
return
:UNFREEZEBOT
echo "*Bot timed out, unfreezing..*"
setdeafclients FALSE
setvar $switchboard~message "Bot frozen for over 100 seconds, resetting...*"
gosub :switchboard~switchboard
goto :BOT~WAIT_FOR_COMMAND

include "source\include\internal_commands"
include "source\include\move"
include "source\include\bot"
