:COMBAT~FASTCITADELATTACK
if ($SHIP~SHIP_MAX_ATTACK <= 0)
  gosub :SHIP~GETSHIPSTATS
end
setvar $COMBAT~REFURBSTRING " l "&$PLANET~PLANET&" * n n * j m * * * "
setvar $COMBAT~ATTACKSTRING ""
setvar $COMBAT~TARGETSTRING "a z "
setvar $COMBAT~TARGETSHOTGUN "a z z y z"&$SHIP~SHIP_MAX_ATTACK&"* * a z z * y z"&$SHIP~SHIP_MAX_ATTACK&"* * a z z * * y z"&$COMBAT~SHIP_MAX_ATTACK&"* * "
setvar $PLAYER~ISFOUND FALSE
if ($PLAYER~FIGHTERS > 0)
  if ($PLAYER~FEDSPACE <> TRUE)
    getwordpos $SECTOR~SECTORDATA $COMBAT~BEACONPOS "[0m[35mBeacon  [1;33m:"
    if ($COMBAT~BEACONPOS > 0)
      setvar $COMBAT~TARGETSTRING $COMBAT~TARGETSTRING&"*"
    end
  end
else
  send "q m***c "
  gosub :PLAYER~QUIKSTATS
  if ($PLAYER~FIGHTERS <= 0)
    send "'{" $SWITCHBOARD~BOT_NAME "} - Out of fighters, shutting down "&$BOT~COMMAND&".*"
    setvar $KILLING~ERROR TRUE
    return
  end
end
if (($SECTOR~EMPTYSHIPCOUNT + ($SECTOR~FAKETRADERCOUNT + $SECTOR~REALTRADERCOUNT)) > 0)
  setvar $COMBAT~I 0
  while ($COMBAT~I < ($SECTOR~EMPTYSHIPCOUNT + $SECTOR~FAKETRADERCOUNT))
    setvar $COMBAT~TARGETSTRING $COMBAT~TARGETSTRING&"* "
    add $COMBAT~I 1
  end
  setvar $COMBAT~C 1
  if (($COMBAT~C <= $SECTOR~REALTRADERCOUNT) and ($PLAYER~ISFOUND = FALSE))
    if (($PLAYER~FEDSPACE = TRUE) and ($PLAYER~TRADERS[$COMBAT~C][2] = TRUE))
      setvar $COMBAT~TARGETSTRING $COMBAT~TARGETSTRING&"* "
    elseif (($PLAYER~TRADERS[$COMBAT~C][1] = $PLAYER~CORP) or ($PLAYER~TRADERS[$COMBAT~C][1] = 100000))
      setvar $COMBAT~TARGETSTRING $COMBAT~TARGETSTRING&"* "
    elseif (($PLAYER~TARGETINGCORP = TRUE) and ($PLAYER~TRADERS[$COMBAT~C][1] <> $COMBAT~TARGET))
      setvar $COMBAT~TARGETSTRING $COMBAT~TARGETSTRING&"* "
    elseif (($PLAYER~TARGETINGPERSON = TRUE) and ($PLAYER~TRADERS[$COMBAT~C] <> $COMBAT~TARGET))
      setvar $COMBAT~TARGETSTRING $COMBAT~TARGETSTRING&"* "
    else
      setvar $PLAYER~ISFOUND TRUE
      setvar $COMBAT~TARGETSTRING $COMBAT~TARGETSTRING&"z y z"

    end
    add $COMBAT~C 1

  end
else
  setvar $SWITCHBOARD~MESSAGE ANSI_12&"*You have no targets.*"&ANSI_7
  gosub :BOT~ECHO
  return
end
if ($PLAYER~ISFOUND = TRUE)
  setvar $PLAYER~THISKILLTARGET ""
  setvar $PLAYER~LASTKILLTARGET ""
  if ($PLAYER~SMART)
    setvar $COMBAT~ATTACKSTRING ""
    send "q "
    setvar $COMBAT~COUNT 8
    while ($COMBAT~COUNT > 0)
      if ($PLAYER~SHOTGUN)
        send $COMBAT~ATTACKSTRING $COMBAT~ATTACKSTRING&"q "&$COMBAT~TARGETSHOTGUN&$COMBAT~REFURBSTRING
      else
        if ($PLAYER~DOUBLETAP)
          send $COMBAT~ATTACKSTRING $COMBAT~ATTACKSTRING&"q "&$COMBAT~TARGETSTRING&$SHIP~SHIP_MAX_ATTACK&"* * "&$COMBAT~TARGETSTRING&$SHIP~SHIP_MAX_ATTACK&"* * "&$COMBAT~REFURBSTRING
        else
          send $COMBAT~ATTACKSTRING $COMBAT~ATTACKSTRING&"q "&$COMBAT~TARGETSTRING&$SHIP~SHIP_MAX_ATTACK&"* * "&$COMBAT~REFURBSTRING
        end
      end
      settexttrigger FOUNDKILLTARGET :FOUNDKILLTARGET "(Y/N) [N]? Y"
      settextlinetrigger NOKTARGET :NOKILLTARGETS "Do you want instructions (Y/N) [N]?"
      pause
      :COMBAT~FOUNDKILLTARGET
      killalltriggers
      setvar $COMBAT~KILL_SHIP_INFO CURRENTLINE
      setvar $PLAYER~THISKILLTARGET CURRENTANSILINE
      getwordpos $PLAYER~THISKILLTARGET $COMBAT~POS "[0;33m([1;36m"
      cuttext $PLAYER~THISKILLTARGET $PLAYER~THISKILLTARGET 1 $COMBAT~POS
      getwordpos $PLAYER~THISKILLTARGET $COMBAT~POS "'s "
      while ($COMBAT~POS > 0)
        cuttext $PLAYER~THISKILLTARGET $PLAYER~THISKILLTARGET ($COMBAT~POS + 3) 9999
        getwordpos $PLAYER~THISKILLTARGET $COMBAT~POS "'s "
      end
      gettext $PLAYER~THISKILLTARGET $PLAYER~THISKILLTARGET #27&"[0m"&#27 #27&"["
      gettext $PLAYER~THISKILLTARGET&"/\ENDOFSHIPTAG/\" $PLAYER~THISKILLTARGET "m" "/\ENDOFSHIPTAG/\"
      getwordpos $PLAYER~TRADERS[($COMBAT~C - 1)][1] $COMBAT~POS $PLAYER~THISKILLTARGET
      if (($PLAYER~LASTKILLTARGET <> "") and ($PLAYER~THISKILLTARGET <> $PLAYER~LASTKILLTARGET))
        setvar $SWITCHBOARD~MESSAGE "*Target has changed, time to rescan..*"
        gosub :BOT~ECHO
        send " c "
        goto :DONEKILL
      end
      setvar $PLAYER~LASTKILLTARGET $PLAYER~THISKILLTARGET
      :COMBAT~NOKILLTARGETS
      killalltriggers

      subtract $COMBAT~COUNT 1
    end
    send " c "
  else
    setvar $COMBAT~ATTACKSTRING ""
    setvar $COMBAT~COUNT 8
    while ($COMBAT~COUNT > 0)
      if ($PLAYER~SHOTGUN)
        setvar $COMBAT~ATTACKSTRING $COMBAT~ATTACKSTRING&"q "&$COMBAT~TARGETSHOTGUN&$COMBAT~REFURBSTRING
      else
        if ($PLAYER~DOUBLETAP)
          setvar $COMBAT~ATTACKSTRING $COMBAT~ATTACKSTRING&"q "&$COMBAT~TARGETSTRING&$SHIP~SHIP_MAX_ATTACK&"* * "&$COMBAT~TARGETSTRING&$SHIP~SHIP_MAX_ATTACK&"* * "&$COMBAT~REFURBSTRING
        else
          setvar $COMBAT~ATTACKSTRING $COMBAT~ATTACKSTRING&"q "&$COMBAT~TARGETSTRING&$SHIP~SHIP_MAX_ATTACK&"* * "&$COMBAT~REFURBSTRING
        end
      end
      subtract $COMBAT~COUNT 1
    end
    send " q "&$COMBAT~ATTACKSTRING&" c "
  end
else
  setvar $SWITCHBOARD~MESSAGE ANSI_12&"*You have no valid targets.*"&ANSI_7
  gosub :BOT~ECHO
  return
end
:COMBAT~DONEKILL
return
