:MAIN
setvar "\$A" CURRENTSECTOR
setvar "\$B" CURRENTTURNS
setvar "\$C" CURRENTCREDITS
setvar "\$D" CURRENTFIGHTERS
setvar "\$E" CURRENTSHIELDS
setvar "\$F" CURRENTHOLDS
setvar "\$G" CURRENTOREHOLDS
setvar "\$H" CURRENTORGHOLDS
setvar "\$I" CURRENTEQUHOLDS
setvar "\$J" CURRENTCOLHOLDS
setvar "\$K" CURRENTEMPTYHOLDS
setvar "\$L" CURRENTPHOTONS
setvar "\$M" CURRENTARMIDS
setvar "\$N" CURRENTLIMPETS
setvar "\$O" CURRENTTWARPTYPE
setvar "\$P" CURRENTSCANTYPE
setvar "\$Q" CURRENTALIGNMENT
setvar "\$R" CURRENTCORP
setvar "\$S" CURRENTSHIPNUMBER
halt
