:PLAYER~QUIKSTATS

setvar $PLAYER~CURRENT_PROMPT "Undefined"
killtrigger NOPROMPT
killtrigger PROMPT
killtrigger STATLINETRIG
killtrigger GETLINE2
setvar $PLAYER~FEDSPACE FALSE
if ($PLAYER~TOWED = 0)
  setvar $PLAYER~TOWED ""
end
loadvar $PLAYER~UNLIMITEDGAME
settextlinetrigger PROMPT :ALLPROMPTS #145&#8
settextlinetrigger STATLINETRIG :STATSTART #179
send #145&"/"
pause
:PLAYER~ALLPROMPTS
getword CURRENTLINE $PLAYER~CURRENT_PROMPT 1
setvar $PLAYER~FULL_CURRENT_PROMPT CURRENTLINE
striptext $PLAYER~FULL_CURRENT_PROMPT #145
striptext $PLAYER~FULL_CURRENT_PROMPT #8
striptext $PLAYER~CURRENT_PROMPT #145
striptext $PLAYER~CURRENT_PROMPT #8
settextlinetrigger PROMPT :ALLPROMPTS #145&#8
pause
:PLAYER~STATSTART
killtrigger PROMPT
setvar $PLAYER~STATS ""
setvar $PLAYER~WORDY ""
:PLAYER~STATSLINE
killtrigger STATLINETRIG
killtrigger GETLINE2
setvar $PLAYER~LINE2 CURRENTLINE
replacetext $PLAYER~LINE2 #179 " "
striptext $PLAYER~LINE2 ","
setvar $PLAYER~STATS $PLAYER~STATS&$PLAYER~LINE2
getwordpos $PLAYER~LINE2 $PLAYER~POS "Ship"
if ($PLAYER~POS > 0)
  goto :GOTSTATS
else
  settextlinetrigger GETLINE2 :STATSLINE
  pause
end
:PLAYER~GOTSTATS
setvar $PLAYER~STATS $PLAYER~STATS&" @@@"
setvar $PLAYER~CURRENT_WORD 0
if ($PLAYER~WORDY <> "@@@")
  if ($PLAYER~WORDY = "Sect")
    getword $PLAYER~STATS $PLAYER~CURRENT_SECTOR ($PLAYER~CURRENT_WORD + 1)
    if (($PLAYER~CURRENT_SECTOR <= 10) or ($PLAYER~CURRENT_SECTOR = STARDOCK) or ($PLAYER~CURRENT_SECTOR = $MAP~STARDOCK))
      setvar $PLAYER~FEDSPACE TRUE
    end
  elseif ($PLAYER~WORDY = "Turns")
    getword $PLAYER~STATS $PLAYER~TURNS ($PLAYER~CURRENT_WORD + 1)
    if ($PLAYER~UNLIMITEDGAME = TRUE)
      setvar $PLAYER~TURNS 65000
    end
  elseif ($PLAYER~WORDY = "Creds")
    getword $PLAYER~STATS $PLAYER~CREDITS ($PLAYER~CURRENT_WORD + 1)
  elseif ($PLAYER~WORDY = "Figs")
    getword $PLAYER~STATS $PLAYER~FIGHTERS ($PLAYER~CURRENT_WORD + 1)
  elseif ($PLAYER~WORDY = "Shlds")
    getword $PLAYER~STATS $PLAYER~SHIELDS ($PLAYER~CURRENT_WORD + 1)
  elseif ($PLAYER~WORDY = "Hlds")
    getword $PLAYER~STATS $PLAYER~TOTAL_HOLDS ($PLAYER~CURRENT_WORD + 1)
  elseif ($PLAYER~WORDY = "Ore")
    getword $PLAYER~STATS $PLAYER~ORE_HOLDS ($PLAYER~CURRENT_WORD + 1)
  elseif ($PLAYER~WORDY = "Org")
    getword $PLAYER~STATS $PLAYER~ORGANIC_HOLDS ($PLAYER~CURRENT_WORD + 1)
  elseif ($PLAYER~WORDY = "Equ")
    getword $PLAYER~STATS $PLAYER~EQUIPMENT_HOLDS ($PLAYER~CURRENT_WORD + 1)
  elseif ($PLAYER~WORDY = "Col")
    getword $PLAYER~STATS $PLAYER~COLONIST_HOLDS ($PLAYER~CURRENT_WORD + 1)
  elseif ($PLAYER~WORDY = "Phot")
    getword $PLAYER~STATS $PLAYER~PHOTONS ($PLAYER~CURRENT_WORD + 1)
  elseif ($PLAYER~WORDY = "Armd")
    getword $PLAYER~STATS $PLAYER~ARMIDS ($PLAYER~CURRENT_WORD + 1)
  elseif ($PLAYER~WORDY = "Lmpt")
    getword $PLAYER~STATS $PLAYER~LIMPETS ($PLAYER~CURRENT_WORD + 1)
  elseif ($PLAYER~WORDY = "GTorp")
    getword $PLAYER~STATS $PLAYER~GENESIS ($PLAYER~CURRENT_WORD + 1)
  elseif ($PLAYER~WORDY = "TWarp")
    getword $PLAYER~STATS $PLAYER~TWARP_TYPE ($PLAYER~CURRENT_WORD + 1)
  elseif ($PLAYER~WORDY = "Clks")
    getword $PLAYER~STATS $PLAYER~CLOAKS ($PLAYER~CURRENT_WORD + 1)
  elseif ($PLAYER~WORDY = "Beacns")
    getword $PLAYER~STATS $PLAYER~BEACONS ($PLAYER~CURRENT_WORD + 1)
  elseif ($PLAYER~WORDY = "AtmDt")
    getword $PLAYER~STATS $PLAYER~ATOMIC ($PLAYER~CURRENT_WORD + 1)
  elseif ($PLAYER~WORDY = "Corbo")
    getword $PLAYER~STATS $PLAYER~CORBO ($PLAYER~CURRENT_WORD + 1)
  elseif ($PLAYER~WORDY = "EPrb")
    getword $PLAYER~STATS $PLAYER~EPROBES ($PLAYER~CURRENT_WORD + 1)
  elseif ($PLAYER~WORDY = "MDis")
    getword $PLAYER~STATS $PLAYER~MINE_DISRUPTORS ($PLAYER~CURRENT_WORD + 1)
  elseif ($PLAYER~WORDY = "PsPrb")
    getword $PLAYER~STATS $PLAYER~PSYCHIC_PROBE ($PLAYER~CURRENT_WORD + 1)
  elseif ($PLAYER~WORDY = "PlScn")
    getword $PLAYER~STATS $PLAYER~PLANET_SCANNER ($PLAYER~CURRENT_WORD + 1)
  elseif ($PLAYER~WORDY = "LRS")
    getword $PLAYER~STATS $PLAYER~SCAN_TYPE ($PLAYER~CURRENT_WORD + 1)
  elseif ($PLAYER~WORDY = "Aln")
    getword $PLAYER~STATS $PLAYER~ALIGNMENT ($PLAYER~CURRENT_WORD + 1)
  elseif ($PLAYER~WORDY = "Exp")
    getword $PLAYER~STATS $PLAYER~EXPERIENCE ($PLAYER~CURRENT_WORD + 1)
  elseif ($PLAYER~WORDY = "Corp")
    getword $PLAYER~STATS $PLAYER~CORP ($PLAYER~CURRENT_WORD + 1)
    setvar $PLAYER~CORPNUMBER $PLAYER~CORP
    savevar $PLAYER~CORPNUMBER
  elseif ($PLAYER~WORDY = "Ship")
    getword $PLAYER~STATS $PLAYER~SHIP_NUMBER ($PLAYER~CURRENT_WORD + 1)
  end
  add $PLAYER~CURRENT_WORD 1
  getword $PLAYER~STATS $PLAYER~WORDY $PLAYER~CURRENT_WORD
end
:PLAYER~DONEQUIKSTATS
killtrigger STATLINETRIG
killtrigger GETLINE2
savevar $PLAYER~UNLIMITEDGAME
if ($PLAYER~SAVE)
  savevar $PLAYER~CORP
  savevar $PLAYER~CREDITS
  savevar $PLAYER~CURRENT_SECTOR
  savevar $PLAYER~TURNS
  savevar $PLAYER~FIGHTERS
  savevar $PLAYER~SHIELDS
  savevar $PLAYER~TOTAL_HOLDS
  savevar $PLAYER~ORE_HOLDS
  savevar $PLAYER~ORGANIC_HOLDS
  savevar $PLAYER~EQUIPMENT_HOLDS
  savevar $PLAYER~COLONIST_HOLDS
  savevar $PLAYER~PHOTONS
  savevar $PLAYER~ARMIDS
  savevar $PLAYER~LIMPETS
  savevar $PLAYER~GENESIS
  savevar $PLAYER~TWARP_TYPE
  savevar $PLAYER~CLOAKS
  savevar $PLAYER~BEACONS
  savevar $PLAYER~ATOMIC
  savevar $PLAYER~CORBO
  savevar $PLAYER~EPROBES
  savevar $PLAYER~MINE_DISRUPTORS
  savevar $PLAYER~PSYCHIC_PROBE
  savevar $PLAYER~PLANET_SCANNER
  savevar $PLAYER~SCAN_TYPE
  savevar $PLAYER~ALIGNMENT
  savevar $PLAYER~EXPERIENCE
  savevar $PLAYER~SHIP_NUMBER
  savevar $PLAYER~TRADER_NAME
end
return
