:PLANET~LOADPLANETINFO
setvar $PLANET~PLANETCOUNTER 1
loadvar $PLANET~PLANET_FILE
fileexists $PLANET~EXISTS $PLANET~PLANET_FILE
:PLANET~COUNT_THE_PLANETS
if ($PLANET~EXISTS)
  setvar $PLANET~I 1
  readtoarray $PLANET~PLANET_FILE $PLANET~PLANET_ARRAY
  setarray $PLANET~PLANETLIST $PLANET~PLANET_ARRAY 7
  while ($PLANET~I <= $PLANET~PLANET_ARRAY)
    setvar $PLANET~PLANETINF $PLANET~PLANET_ARRAY[$PLANET~I]
    gosub :PROCESS_PLANET_LINE
    setvar $PLANET~PLANETLIST[$PLANET~I] $PLANET~PLANETNAME
    setvar $PLANET~PLANETLIST[$PLANET~I][1] $PLANET~PLANET_FUEL_COLONISTS_MIN
    setvar $PLANET~PLANETLIST[$PLANET~I][2] $PLANET~PLANET_FUEL_COLONISTS_MAX
    setvar $PLANET~PLANETLIST[$PLANET~I][3] $PLANET~PLANET_ORG_COLONISTS_MIN
    setvar $PLANET~PLANETLIST[$PLANET~I][4] $PLANET~PLANET_ORG_COLONISTS_MAX
    setvar $PLANET~PLANETLIST[$PLANET~I][5] $PLANET~PLANET_EQUIP_COLONISTS_MIN
    setvar $PLANET~PLANETLIST[$PLANET~I][6] $PLANET~PLANET_EQUIP_COLONISTS_MAX
    setvar $PLANET~PLANETLIST[$PLANET~I][7] $PLANET~PLANET_IS_KEEPER
    add $PLANET~I 1
  end
  setvar $PLANET~PLANETCOUNTER $PLANET~PLANET_ARRAY
  setvar $PLANET~PLANETSTATS TRUE
else
  echo "*No Planet File Found!*"
end
return
:PLANET~PROCESS_PLANET_LINE

getword $PLANET~PLANETINF $PLANET~PLANET_FUEL_COLONISTS_MIN 1
getlength $PLANET~PLANET_FUEL_COLONISTS_MIN $PLANET~LENGTH1
getword $PLANET~PLANETINF $PLANET~PLANET_FUEL_COLONISTS_MAX 2
getlength $PLANET~PLANET_FUEL_COLONISTS_MAX $PLANET~LENGTH2
getword $PLANET~PLANETINF $PLANET~PLANET_ORG_COLONISTS_MIN 3
getlength $PLANET~PLANET_ORG_COLONISTS_MIN $PLANET~LENGTH3
getword $PLANET~PLANETINF $PLANET~PLANET_ORG_COLONISTS_MAX 4
getlength $PLANET~PLANET_ORG_COLONISTS_MAX $PLANET~LENGTH4
getword $PLANET~PLANETINF $PLANET~PLANET_EQUIP_COLONISTS_MIN 5
getlength $PLANET~PLANET_EQUIP_COLONISTS_MIN $PLANET~LENGTH5
getword $PLANET~PLANETINF $PLANET~PLANET_EQUIP_COLONISTS_MAX 6
getlength $PLANET~PLANET_EQUIP_COLONISTS_MAX $PLANET~LENGTH6
getword $PLANET~PLANETINF $PLANET~PLANET_IS_KEEPER 7
getlength $PLANET~PLANET_IS_KEEPER $PLANET~LENGTH7
setvar $PLANET~STARTLEN ($PLANET~LENGTH1 + ($PLANET~LENGTH2 + ($PLANET~LENGTH3 + ($PLANET~LENGTH4 + ($PLANET~LENGTH5 + ($PLANET~LENGTH6 + ($PLANET~LENGTH7 + 7)))))))
getlength $PLANET~PLANETINF $PLANET~LENGTH_PLANET_NAME
if ($PLANET~STARTLEN < $PLANET~LENGTH_PLANET_NAME)
  cuttext $PLANET~PLANETINF $PLANET~PLANETNAME $PLANET~STARTLEN 999
else
  echo "*"&$PLANET~PLANETINF&" error during processing planets.*"
end
return
