:PROMPT~CHECKSTARTINGPROMPT




getwordpos " "&$PROMPT~VALIDPROMPTS&" " $PROMPT~POS $PROMPT~STARTINGLOCATION
if ($PROMPT~POS <= 0)
  setvar $SWITCHBOARD~MESSAGE "Invalid starting prompt: ["&$PROMPT~STARTINGLOCATION&"]. Valid prompt(s) for this command: ["&$PROMPT~VALIDPROMPTS&"]*"
  gosub :SWITCHBOARD~SWITCHBOARD
  if ($PROMPT~RETURN)
    return
  end
  halt
end
return
:PROMPT~CURRENT_PROMPT


settexttrigger PROMPT :ALLPROMPTSCATCH #145&#8
setdelaytrigger PROMPT_DELAY :CURRENT_PROMPT_DELAY 5000
send #145
pause
:PROMPT~CURRENT_PROMPT_DELAY
settextouttrigger ATKEYS :CURRENT_PROMPT_AT_KEYS
setdelaytrigger PROMPT_DELAY :VERIFYDELAY 30000
pause
:PROMPT~CURRENT_PROMPT_AT_KEYS
getouttext $PROMPT~OUT
send $PROMPT~OUT
killtrigger PROMPT_DELAY
return
:PROMPT~ALLPROMPTSCATCH
killtrigger PROMPT_DELAY
getword CURRENTLINE $PROMPT~CURRENT_PROMPT 1
if ($PROMPT~CURRENT_PROMPT = 0)
  getword CURRENTANSILINE $PROMPT~CURRENT_PROMPT 1
end
striptext $PROMPT~CURRENT_PROMPT #145
striptext $PROMPT~CURRENT_PROMPT #8
setvar $PROMPT~STARTINGLOCATION $PROMPT~CURRENT_PROMPT
return
