:SECTOR~GETEMPTYSHIPS
getwordpos $SECTOR~SECTORDATA $SECTOR~POSSHIPS "[0m[33mShips   [1m:"
if ($SECTOR~POSSHIPS > 0)
  gettext $SECTOR~SECTORDATA $SECTOR~SHIPDATA "[0m[33mShips   [1m:" "[0m[1;32mWarps to Sector(s) [33m:"
  setvar $SECTOR~SHIPDATA $SECTOR~STARTLINE&$SECTOR~SHIPDATA
  gettext $SECTOR~SHIPDATA $SECTOR~TEMP $SECTOR~STARTLINE $SECTOR~ENDLINE
  setvar $SECTOR~EMPTYSHIPCOUNT 0
  setvar $SECTOR~MYSHIPCOUNT 0
  while ($SECTOR~TEMP <> "")
    getlength $SECTOR~STARTLINE&$SECTOR~TEMP&$SECTOR~ENDLINE $SECTOR~LENGTH
    cuttext $SECTOR~SHIPDATA $SECTOR~SHIPDATA ($SECTOR~LENGTH + 1) 9999
    striptext $SECTOR~TEMP $SECTOR~STARTLINE
    striptext $SECTOR~TEMP "  "
    striptext $SECTOR~TEMP $SECTOR~ENDLINE
    getwordpos $SECTOR~TEMP $SECTOR~POS2 "[0;35m[[31mOwned by[35m]"
    if ($SECTOR~POS2 > 0)
      cuttext $SECTOR~TEMP $SECTOR~TEMP $SECTOR~POS2 9999
      striptext $SECTOR~TEMP "[0;35m[[31mOwned by[35m] "
      getwordpos $SECTOR~TEMP $SECTOR~POS3 ",[0;32m w/"
      cuttext $SECTOR~TEMP $SECTOR~TEMP 0 $SECTOR~POS3
      getwordpos $SECTOR~TEMP $SECTOR~POS4 "[34m[[1;36m"
      striptext $SECTOR~TEMP "[1;33m,"
      if ($SECTOR~POS4 > 0)
        cuttext $SECTOR~TEMP $SECTOR~TEMP $SECTOR~POS4 9999
        striptext $SECTOR~TEMP "[34m[[1;36m"
        striptext $SECTOR~TEMP "[0;34m]"
      end
      setvar $PLAYER~EMPTYSHIPS[($SECTOR~EMPTYSHIPCOUNT + 1)] $SECTOR~TEMP
      if (($PLAYER~EMPTYSHIPS[($SECTOR~EMPTYSHIPCOUNT + 1)] = $PLAYER~CORP) or ($PLAYER~EMPTYSHIPS[($SECTOR~EMPTYSHIPCOUNT + 1)] = $PLAYER~TRADER_NAME))
        add $SECTOR~MYSHIPCOUNT 1
      end
      add $SECTOR~EMPTYSHIPCOUNT 1
    end
    gettext $SECTOR~SHIPDATA $SECTOR~TEMP $SECTOR~STARTLINE $SECTOR~ENDLINE
  end
else
  setvar $SECTOR~EMPTYSHIPCOUNT 0
  setvar $SECTOR~MYSHIPCOUNT 0
end
return
