:PLAYER~FORMATPERCENTAGESFORSPACES
if ($PLAYER~INPUTVARIABLE < 10)
  setvar $PLAYER~OUTPUTVARIABLE "  ("&$PLAYER~INPUTVARIABLE&"%)"
elseif ($PLAYER~INPUTVARIABLE < 100)
  setvar $PLAYER~OUTPUTVARIABLE " ("&$PLAYER~INPUTVARIABLE&"%)"
elseif ($PLAYER~INPUTVARIABLE < 1000)
  setvar $PLAYER~OUTPUTVARIABLE "("&$PLAYER~INPUTVARIABLE&"%)"
else
  setvar $PLAYER~OUTPUTVARIABLE $PLAYER~INPUTVARIABLE
end
return
