:PLANET~GETPLANETINFO









setvar $PLANET~CURRENT_SECTOR 0
setvar $PLANET~PLANET 0
setvar $PLANET~PLANET_FUEL 0
setvar $PLANET~PLANET_FUEL_MAX 0
setvar $PLANET~PLANET_ORGANICS 0
setvar $PLANET~PLANET_ORGANICS_MAX 0
setvar $PLANET~PLANET_EQUIPMENT 0
setvar $PLANET~PLANET_EQUIPMENT_MAX 0
setvar $PLANET~PLANET_FIGHTERS 0
setvar $PLANET~PLANET_FIGHTERS_MAX 0
setvar $PLANET~CITADEL 0
setvar $PLANET~CITADEL_CREDITS 0
setvar $PLANET~ATMOSPHERE_CANNON 0
setvar $PLANET~SECTOR_CANNON 0
setvar $PLANET~PLANET_CLASS_NAME "undefined"



send "*"
settextlinetrigger PLANETINFO2 :PLANETINFO2 "Planet #"
pause
:PLANET~PLANETINFO2

setvar $PLANET~CITADEL 0
setvar $PLANET~SECTOR_CANNON 0
setvar $PLANET~ATMOSPHERE_CANNON 0
setvar $PLANET~CITADEL_CREDITS 0
getword CURRENTLINE $PLANET~PLANET 2
striptext $PLANET~PLANET "#"
getword CURRENTLINE $PLANET~CURRENT_SECTOR 5
striptext $PLANET~CURRENT_SECTOR ":"

settextlinetrigger CLASS :GETCLASS "Class "
pause
:PLANET~GETCLASS
setvar $PLANET~PLANET_CLASS_NAME CURRENTLINE
waitfor "2 Build 1   Product    Amount     Amount     Maximum"
:PLANET~GETPLANETSTUFF

settextlinetrigger FUELSTART :FUELSTART "Fuel Ore"
settextlinetrigger ORGSTART :ORGSTART "Organics"
settextlinetrigger EQUIPSTART :EQUIPSTART "Equipment"
settextlinetrigger FIGSTART :FIGSTART "Fighters        N/A"
settextlinetrigger CITADELSTART :CITADELSTART "Planet has a level"
settextlinetrigger CANNON :CANNONSTART ", AtmosLvl="
settexttrigger PLANETINFODONE :PLANETINFODONE "Planet command (?=help)"
pause
:PLANET~FUELSTART

getword CURRENTLINE $PLANET~PLANET_FUEL 6
getword CURRENTLINE $PLANET~PLANET_FUEL_MAX 8
striptext $PLANET~PLANET_FUEL ","
striptext $PLANET~PLANET_FUEL_MAX ","
pause
:PLANET~ORGSTART

getword CURRENTLINE $PLANET~PLANET_ORGANICS 5
getword CURRENTLINE $PLANET~PLANET_ORGANICS_MAX 7
striptext $PLANET~PLANET_ORGANICS ","
striptext $PLANET~PLANET_ORGANICS_MAX ","
pause
:PLANET~EQUIPSTART

getword CURRENTLINE $PLANET~PLANET_EQUIPMENT 5
getword CURRENTLINE $PLANET~PLANET_EQUIPMENT_MAX 7
striptext $PLANET~PLANET_EQUIPMENT ","
striptext $PLANET~PLANET_EQUIPMENT_MAX ","
pause
:PLANET~FIGSTART

getword CURRENTLINE $PLANET~PLANET_FIGHTERS 5
getword CURRENTLINE $PLANET~PLANET_FIGHTERS_MAX 7
striptext $PLANET~PLANET_FIGHTERS ","
striptext $PLANET~PLANET_FIGHTERS_MAX ","
pause
:PLANET~CITADELSTART

getword CURRENTLINE $PLANET~CITADEL 5
getword CURRENTLINE $PLANET~CITADEL_CREDITS 9
striptext $PLANET~CITADEL_CREDITS ","
pause
:PLANET~CANNONSTART

getword CURRENTLINE $PLANET~ATMOSPHERE_CANNON 5
getword CURRENTLINE $PLANET~SECTOR_CANNON 6
striptext $PLANET~SECTOR_CANNON "SectLvl="
striptext $PLANET~SECTOR_CANNON "%"
striptext $PLANET~ATMOSPHERE_CANNON "AtmosLvl="
striptext $PLANET~ATMOSPHERE_CANNON "%"
striptext $PLANET~ATMOSPHERE_CANNON ","
pause
:PLANET~PLANETINFODONE
killtrigger CITADELSTART
killtrigger CANNON

setvar $PLANET~CURRENTBOTPLANET $PLANET~PLANET
savevar $PLANET~CURRENTBOTPLANET
return
:PLANET~LANDINGSUB







send "l" $PLANET~PLANET "*z  n  z  n  *  "
setvar $PLANET~SUCESSFULCITADEL FALSE
setvar $PLANET~SUCESSFULPLANET FALSE
settextlinetrigger NOPLANET :NOPLANET "There isn't a planet in this sector."
settextlinetrigger NO_LAND :NO_LAND "since it couldn't possibly stand"
settextlinetrigger PLANET :PLANET "Planet #"
settextlinetrigger WRONGONE :WRONG_NUM "That planet is not in this sector."
pause
:PLANET~NOPLANET
killtrigger NO_LAND
killtrigger PLANET
killtrigger WRONGONE
setvar $SWITCHBOARD~MESSAGE "No Planet in Sector!*"
gosub :SWITCHBOARD~SWITCHBOARD
return
:PLANET~NO_LAND
killtrigger NOPLANET
killtrigger PLANET
killtrigger WRONGONE
setvar $SWITCHBOARD~MESSAGE "This ship cannot land!*"
gosub :SWITCHBOARD~SWITCHBOARD
return
:PLANET~PLANET
getword CURRENTLINE $PLANET~PNUM_CK 2
striptext $PLANET~PNUM_CK "#"
if ($PLANET~PNUM_CK <> $PLANET~PLANET)
  killtrigger NO_LAND
  killtrigger WRONGONE
  killtrigger NO_PLANET
  send "q"
  goto :WRONG_NUM
end
killtrigger NOPLANET
killtrigger NO_LAND
killtrigger WRONGONE
settexttrigger WRONG_NUM :WRONG_NUM "That planet is not in this sector."
settexttrigger PLANET :PLANET_PROMPT "Planet command"
pause
:PLANET~WRONG_NUM
killtrigger PLANET
send "**"
setvar $SWITCHBOARD~MESSAGE "Incorrect Planet Number*"
gosub :SWITCHBOARD~SWITCHBOARD
return
:PLANET~PLANET_PROMPT
killtrigger WRONG_NUM
setvar $PLANET~CURRENTBOTPLANET $PLANET~PLANET
savevar $PLANET~CURRENTBOTPLANET
savevar $PLANET~PLANET
send "m* * * c*"
settexttrigger BUILD_CIT :BUILD_CIT "Do you wish to construct one?"
settexttrigger IN_CIT :IN_CIT "Citadel command"
settexttrigger NOCITALLOWED :BUILD_CIT "Citadels are not allowed in FedSpace."
settexttrigger CITNOTBUILTYET :BUILD_CIT "Be patient, your Citadel is not yet finished."
pause
:PLANET~BUILD_CIT
killtrigger IN_CIT
killtrigger NOCITALLOWED
killtrigger BUILD_CIT
killtrigger CITNOTBUILTYET
setvar $PLANET~SUCESSFULPLANET TRUE
setvar $PLANET~STARTINGLOCATION "Planet"
return
:PLANET~IN_CIT
killtrigger IN_CIT
killtrigger NOCITALLOWED
killtrigger BUILD_CIT
killtrigger CITNOTBUILTYET
setvar $PLANET~SUCESSFULCITADEL TRUE
setvar $PLANET~STARTINGLOCATION "Citadel"
return
:PLANET~GETPLANETSTATS


send "cn"
waiton "(2) Animation display"
getword CURRENTLINE $PLANET~ANSI_ONOFF 5
if ($PLANET~ANSI_ONOFF = "On")
  send "2qq"
else
  send "qq"
end
setarray $PLANET~ALPHA 20
delete $PLANET~PLANET_FILE
setvar $PLANET~ALPHA[1] "A"
setvar $PLANET~ALPHA[2] "B"
setvar $PLANET~ALPHA[3] "C"
setvar $PLANET~ALPHA[4] "D"
setvar $PLANET~ALPHA[5] "E"
setvar $PLANET~ALPHA[6] "F"
setvar $PLANET~ALPHA[7] "G"
setvar $PLANET~ALPHA[8] "H"
setvar $PLANET~ALPHA[9] "I"
setvar $PLANET~ALPHA[10] "J"
setvar $PLANET~ALPHA[11] "K"
setvar $PLANET~ALPHA[12] "L"
setvar $PLANET~ALPHA[13] "M"
setvar $PLANET~ALPHA[14] "N"
setvar $PLANET~ALPHA[15] "O"
setvar $PLANET~ALPHA[16] "P"
setvar $PLANET~ALPHA[17] "R"
setvar $PLANET~ALPHALOOP 0
setvar $PLANET~TOTALPLANETS 0
setvar $PLANET~NEXTPAGE 1
send "CJ?"
waiton "(?=List) ?"
:PLANET~SHP_LOOP

settextlinetrigger GRAB_PLANET :SHP_PLANETNAMES
pause
:PLANET~SHP_PLANETNAMES
if (CURRENTLINE = "")
  goto :SHP_LOOP
end
getword CURRENTLINE $PLANET~STOPPER 1
if ($PLANET~STOPPER = "<+>")
  send "+"
  waiton "(?=List) ?"
  setvar $PLANET~NEXTPAGE 1
  goto :SHP_LOOP
elseif ($PLANET~STOPPER = "<Q>")
  goto :SHP_GETPLANETSTATS
end
if ($PLANET~NEXTPAGE = 1)
  setvar $PLANET~PLANETNAME CURRENTLINE
  striptext $PLANET~PLANETNAME "<A> "
  if ($PLANET~PLANETNAME = $PLANET~FIRSTPLANETNAME)
    goto :SHP_GETPLANETSTATS
  end
  setvar $PLANET~NEXTPAGE 0
end
add $PLANET~TOTALPLANETS 1
if ($PLANET~TOTALPLANETS = 1)
  setvar $PLANET~FIRSTPLANETNAME CURRENTLINE
  striptext $PLANET~FIRSTPLANETNAME "<A> "
end
goto :SHP_LOOP
:PLANET~SHP_GETPLANETSTATS
setvar $PLANET~PLANETSTATLOOP 0
:PLANET~SHP_PLANETSTATS
while ($PLANET~PLANETSTATLOOP < $PLANET~TOTALPLANETS)
  add $PLANET~PLANETSTATLOOP 1
  add $PLANET~ALPHALOOP 1
  if ($PLANET~ALPHALOOP > 17)
    send "+"
    setvar $PLANET~ALPHALOOP 1
  end
  send $PLANET~ALPHA[$PLANET~ALPHALOOP]
  settextlinetrigger SN :SN "Planet Category #"
  pause
  :PLANET~SN
  setvar $PLANET~LINE CURRENTLINE
  getwordpos $PLANET~LINE $PLANET~POS "Class"

  cuttext $PLANET~LINE $PLANET~PLANET_NAME $PLANET~POS 999
  write $PLANET~PLANET_FILE "50000 50000 50000 0  "&$PLANET~PLANET_NAME
end
send "qq"
return
:PLANET~LOADPLANETINFO

setvar $PLANET~PLANETCOUNTER 1
:PLANET~COUNT_THE_PLANETS
read $PLANET~PLANET_FILE $PLANET~PLANETINF $PLANET~PLANETCOUNTER
if ($PLANET~PLANETINF <> "EOF")
  add $PLANET~PLANETCOUNTER 1
  goto :COUNT_THE_PLANETS
end
setarray $PLANET~PLANETLIST $PLANET~PLANETCOUNTER 4
setvar $PLANET~PLANETCOUNTER 1
:PLANET~READPLANETLIST
read $PLANET~PLANET_FILE $PLANET~PLANETINF $PLANET~PLANETCOUNTER
if ($PLANET~PLANETINF <> "EOF")
  gosub :PROCESS_PLANET_LINE
  setvar $PLANET~PLANETLIST[$PLANET~PLANETCOUNTER] $PLANET~PLANETNAME
  setvar $PLANET~PLANETLIST[$PLANET~PLANETCOUNTER][1] $PLANET~PLANET_FUEL_COLONISTS_MAX
  setvar $PLANET~PLANETLIST[$PLANET~PLANETCOUNTER][2] $PLANET~PLANET_ORG_COLONISTS_MAX
  setvar $PLANET~PLANETLIST[$PLANET~PLANETCOUNTER][3] $PLANET~PLANET_EQUIP_COLONISTS_MAX
  setvar $PLANET~PLANETLIST[$PLANET~PLANETCOUNTER][4] $PLANET~PLANET_IS_KEEPER
  add $PLANET~PLANETCOUNTER 1
  goto :READPLANETLIST
end
setvar $PLANET~PLANETSTATS TRUE
return
:PLANET~PROCESS_PLANET_LINE

getword $PLANET~PLANETINF $PLANET~PLANET_FUEL_COLONISTS_MAX 1
getlength $PLANET~PLANET_FUEL_COLONISTS_MAX $PLANET~LENGTH1
getword $PLANET~PLANETINF $PLANET~PLANET_ORG_COLONISTS_MAX 2
getlength $PLANET~PLANET_ORG_COLONISTS_MAX $PLANET~LENGTH2
getword $PLANET~PLANETINF $PLANET~PLANET_EQUIP_COLONISTS_MAX 3
getlength $PLANET~PLANET_EQUIP_COLONISTS_MAX $PLANET~LENGTH3
getword $PLANET~PLANETINF $PLANET~PLANET_IS_KEEPER 4
getlength $PLANET~PLANET_IS_KEEPER $PLANET~LENGTH4
setvar $PLANET~STARTLEN ($PLANET~LENGTH1 + ($PLANET~LENGTH2 + ($PLANET~LENGTH3 + ($PLANET~LENGTH4 + 4))))
cuttext $PLANET~PLANETINF $PLANET~PLANETNAME $PLANET~STARTLEN 999
return
