:SWITCHBOARD~SWITCHBOARD






setvar $SWITCHBOARD~MSG_HEADER_ECHO ANSI_9&"{"&ANSI_14&$SWITCHBOARD~BOT_NAME&ANSI_9&"} "&ANSI_15
setvar $SWITCHBOARD~MSG_HEADER_SS_1 "'{"&$SWITCHBOARD~BOT_NAME&"} - "
setvar $SWITCHBOARD~MSG_HEADER_SS_2 "'*{"&$SWITCHBOARD~BOT_NAME&"} - *"
if ($SWITCHBOARD~MESSAGE <> "")
  killalltriggers
  if ($SWITCHBOARD~SELF_COMMAND > 0)
    setvar $SWITCHBOARD~LENGTH 0
  else
    getlength $SWITCHBOARD~BOT_NAME $SWITCHBOARD~LENGTH
  end
  setvar $SWITCHBOARD~I 1
  setvar $SWITCHBOARD~SPACING ""
  if ($SWITCHBOARD~SELF_COMMAND <> 0)
    if ($SWITCHBOARD~SELF_COMMAND > 1)
      striptext $SWITCHBOARD~MESSAGE ANSI_1
      striptext $SWITCHBOARD~MESSAGE ANSI_2
      striptext $SWITCHBOARD~MESSAGE ANSI_3
      striptext $SWITCHBOARD~MESSAGE ANSI_4
      striptext $SWITCHBOARD~MESSAGE ANSI_5
      striptext $SWITCHBOARD~MESSAGE ANSI_6
      striptext $SWITCHBOARD~MESSAGE ANSI_7
      striptext $SWITCHBOARD~MESSAGE ANSI_8
      striptext $SWITCHBOARD~MESSAGE ANSI_9
      striptext $SWITCHBOARD~MESSAGE ANSI_10
      striptext $SWITCHBOARD~MESSAGE ANSI_11
      striptext $SWITCHBOARD~MESSAGE ANSI_12
      striptext $SWITCHBOARD~MESSAGE ANSI_13
      striptext $SWITCHBOARD~MESSAGE ANSI_14
      striptext $SWITCHBOARD~MESSAGE ANSI_15
      if ($SWITCHBOARD~HELPLIST <> TRUE)
      end
    end

    while ($SWITCHBOARD~I <= $SWITCHBOARD~LENGTH)
      setvar $SWITCHBOARD~SPACING $SWITCHBOARD~SPACING&" "
      add $SWITCHBOARD~I 1
    end

    setvar $SWITCHBOARD~NEW_MESSAGE ""
    setvar $SWITCHBOARD~MESSAGE_LINE ""
    replacetext $SWITCHBOARD~MESSAGE "**" "{END_OF_LINE}"
    replacetext $SWITCHBOARD~MESSAGE "*" "{END_OF_LINE}"
    gettext "{START_OF_MESSAGE}"&$SWITCHBOARD~MESSAGE $SWITCHBOARD~MESSAGE_LINE "{START_OF_MESSAGE}" "{END_OF_LINE}"
    while ($SWITCHBOARD~MESSAGE_LINE <> "")
      setvar $SWITCHBOARD~NEW_MESSAGE $SWITCHBOARD~NEW_MESSAGE&$SWITCHBOARD~SPACING&$SWITCHBOARD~MESSAGE_LINE&"*"
      getlength "{START_OF_MESSAGE}"&$SWITCHBOARD~MESSAGE_LINE&"{END_OF_LINE}" $SWITCHBOARD~CUTLENGTH
      cuttext "{START_OF_MESSAGE}"&$SWITCHBOARD~MESSAGE&"     " $SWITCHBOARD~MESSAGE ($SWITCHBOARD~CUTLENGTH + 1) 99999
      gettext "{START_OF_MESSAGE}"&$SWITCHBOARD~MESSAGE $SWITCHBOARD~MESSAGE_LINE "{START_OF_MESSAGE}" "{END_OF_LINE}"
    end
  else
    setvar $SWITCHBOARD~NEW_MESSAGE $SWITCHBOARD~MESSAGE
  end
  if ($SWITCHBOARD~SELF_COMMAND = 1)
    echo "*"&$SWITCHBOARD~MSG_HEADER_ECHO&$SWITCHBOARD~NEW_MESSAGE
    send #145
  elseif ($SWITCHBOARD~SELF_COMMAND = 0)
    send $SWITCHBOARD~MSG_HEADER_SS_1&$SWITCHBOARD~NEW_MESSAGE
  elseif ($SWITCHBOARD~SELF_COMMAND > 1)
    send $SWITCHBOARD~MSG_HEADER_SS_2&$SWITCHBOARD~NEW_MESSAGE&"*"
  end
  setvar $SWITCHBOARD~MESSAGE ""
end
setvar $SWITCHBOARD~HELPLIST FALSE
return
