:PLAYER~BUY









setvar $PLAYER~OVERHAGGLEMULTIPLE 147
setvar $PLAYER~CYCLEBUFFER 1
setvar $PLAYER~CYCLEBUFFERLIMIT 20



send "@"
waiton "Average Interval Lag:"
gosub :QUIKSTATS
setvar $PLAYER~STARTINGLOCATION $PLAYER~CURRENT_PROMPT

setvar $PLAYER~OUTPUT ""
setvar $PLAYER~EQUIPROUNDS 0
setvar $PLAYER~ORGROUNDS 0
setvar $PLAYER~FUELROUNDS 0
if ($PLAYER~BUYDOWNROUNDSFROMPARAM <= 0)
  setvar $PLAYER~BUYDOWNROUNDSFROMPARAM 999999
end
if ($PLAYER~BUYTYPE = "w")
  setvar $PLAYER~BUYDOWN_MODE 3
elseif ($PLAYER~BUYTYPE = "b")
  setvar $PLAYER~BUYDOWN_MODE 2
else
  setvar $PLAYER~BUYDOWN_MODE 1
end
if ($PLAYER~BUYOBJECT = "e")
  setvar $PLAYER~BUYDOWN_EQUIPROUNDS $PLAYER~BUYDOWNROUNDSFROMPARAM
  setvar $PLAYER~BUYDOWN_ORGROUNDS 0
  setvar $PLAYER~BUYDOWN_FUELROUNDS 0
elseif ($PLAYER~BUYOBJECT = "o")
  setvar $PLAYER~BUYDOWN_EQUIPROUNDS 0
  setvar $PLAYER~BUYDOWN_ORGROUNDS $PLAYER~BUYDOWNROUNDSFROMPARAM
  setvar $PLAYER~BUYDOWN_FUELROUNDS 0
elseif ($PLAYER~BUYOBJECT = "f")
  setvar $PLAYER~BUYDOWN_EQUIPROUNDS 0
  setvar $PLAYER~BUYDOWN_ORGROUNDS 0
  setvar $PLAYER~BUYDOWN_FUELROUNDS $PLAYER~BUYDOWNROUNDSFROMPARAM
else
  setvar $PLAYER~EXIT_MESSAGE "Please use format buy [type] {speed} {#cycles} {override}*"
  return

end
if ($PLAYER~STARTINGLOCATION = "Citadel")
  send "Q"
end
send "t n l 1* t n l 2* t n l 3* s n l1*"
waiton "How many groups of Colonists do you want to leave"
gosub :PLANET~GETPLANETINFO
if ($PLAYER~STARTINGLOCATION = "Citadel")
  send "C s* "
else
  send "Q D"
end
gosub :GETINFO
if ($PLAYER~TOTAL_HOLDS <> $PLAYER~EMPTY_HOLDS)
  if ($PLAYER~STARTINGLOCATION <> "Citadel")
    gosub :PLANET~LANDINGSUB
  end
  setvar $SWITCHBOARD~MESSAGE "Planet full, cannot empty ship holds*"
  gosub :SWITCHBOARD~SWITCHBOARD
  goto :BUYDOWNEXIT
end
gosub :VOIDADJACENT
gosub :GETPORTINFO
if ($PLAYER~VALIDPORTFOUND <> TRUE)
  echo "*No valid port found*"
  if ($PLAYER~STARTINGLOCATION <> "Citadel")
    gosub :PLANET~LANDINGSUB
  end
  gosub :CLEARADJACENT
  goto :BUYDOWNEXIT
end
if ($PLAYER~STARTINGLOCATION = "Citadel")
  send "Q"
else
  send "L "&$PLANET~PLANET&"* "
end
setdelaytrigger INITPAUSE :INITPAUSE 500
pause
:PLAYER~INITPAUSE
:PLAYER~GETINPUTS



setvar $PLAYER~TURNS_NEEDED 0
setvar $PLAYER~TURNS_ALLOWED $PLAYER~TURNS
subtract $PLAYER~TURNS_ALLOWED 1


if ($PLAYER~BUYDOWN_FUELROUNDS > 0)
  setvar $PLAYER~FUELROUNDS 0
  setvar $PLAYER~PLANETFUELROOM $PLANET~PLANET_FUEL_MAX
  subtract $PLAYER~PLANETFUELROOM $PLANET~PLANET_FUEL
  setvar $PLAYER~MAXFUELTOBUY $PLAYER~FUELSELLING
  if ($PLAYER~FUELSELLING > $PLAYER~PLANETFUELROOM)
    setvar $PLAYER~MAXFUELTOBUY $PLAYER~PLANETFUELROOM
  end
  setvar $PLAYER~MAXFUELROUNDS $PLAYER~MAXFUELTOBUY
  divide $PLAYER~MAXFUELROUNDS $PLAYER~TOTAL_HOLDS
  if ($PLAYER~MAXFUELROUNDS > $PLAYER~TURNS_ALLOWED)
    setvar $PLAYER~MAXFUELROUNDS $PLAYER~TURNS_ALLOWED
  end
  if ($PLAYER~MAXFUELROUNDS > $PLAYER~BUYDOWN_FUELROUNDS)
    setvar $PLAYER~MAXFUELROUNDS $PLAYER~BUYDOWN_FUELROUNDS
  end
  if ($PLAYER~MAXFUELROUNDS > 0)
    setvar $PLAYER~FUELROUNDS $PLAYER~MAXFUELROUNDS
  end
  add $PLAYER~TURNS_NEEDED $PLAYER~FUELROUNDS
  subtract $PLAYER~TURNS_ALLOWED $PLAYER~FUELROUNDS
end

if ($PLAYER~BUYDOWN_ORGROUNDS > 0)
  setvar $PLAYER~ORGROUNDS 0
  setvar $PLAYER~PLANETORGROOM $PLANET~PLANET_ORGANICS_MAX
  subtract $PLAYER~PLANETORGROOM $PLANET~PLANET_ORGANICS
  setvar $PLAYER~MAXORGTOBUY $PLAYER~ORGSELLING
  if ($PLAYER~ORGSELLING > $PLAYER~PLANETORGROOM)
    setvar $PLAYER~MAXORGTOBUY $PLAYER~PLANETORGROOM
  end
  setvar $PLAYER~MAXORGROUNDS $PLAYER~MAXORGTOBUY
  divide $PLAYER~MAXORGROUNDS $PLAYER~TOTAL_HOLDS
  if ($PLAYER~MAXORGROUNDS > $PLAYER~TURNS_ALLOWED)
    setvar $PLAYER~MAXORGROUNDS $PLAYER~TURNS_ALLOWED
  end
  if ($PLAYER~MAXORGROUNDS > $PLAYER~BUYDOWN_ORGROUNDS)
    setvar $PLAYER~MAXORGROUNDS $PLAYER~BUYDOWN_ORGROUNDS
  end
  if ($PLAYER~MAXORGROUNDS > 0)
    setvar $PLAYER~ORGROUNDS $PLAYER~MAXORGROUNDS
  end
  add $PLAYER~TURNS_NEEDED $PLAYER~ORGROUNDS
  subtract $PLAYER~TURNS_ALLOWED $PLAYER~ORGROUNDS
end

if ($PLAYER~BUYDOWN_EQUIPROUNDS > 0)
  setvar $PLAYER~EQUIPROUNDS 0
  setvar $PLAYER~PLANETEQUIPROOM $PLANET~PLANET_EQUIPMENT_MAX
  subtract $PLAYER~PLANETEQUIPROOM $PLANET~PLANET_EQUIPMENT
  setvar $PLAYER~MAXEQUIPTOBUY $PLAYER~EQUIPSELLING
  if ($PLAYER~EQUIPSELLING > $PLAYER~PLANETEQUIPROOM)
    setvar $PLAYER~MAXEQUIPTOBUY $PLAYER~PLANETEQUIPROOM
  end
  setvar $PLAYER~MAXEQUIPROUNDS $PLAYER~MAXEQUIPTOBUY
  divide $PLAYER~MAXEQUIPROUNDS $PLAYER~TOTAL_HOLDS
  if ($PLAYER~MAXEQUIPROUNDS > $PLAYER~TURNS_ALLOWED)
    setvar $PLAYER~MAXEQUIPROUNDS $PLAYER~TURNS_ALLOWED
  end
  if ($PLAYER~MAXEQUIPROUNDS > $PLAYER~BUYDOWN_EQUIPROUNDS)
    setvar $PLAYER~MAXEQUIPROUNDS $PLAYER~BUYDOWN_EQUIPROUNDS
  end
  if ($PLAYER~MAXEQUIPROUNDS > 0)
    setvar $PLAYER~EQUIPROUNDS $PLAYER~MAXEQUIPROUNDS
  end
  add $PLAYER~TURNS_NEEDED $PLAYER~EQUIPROUNDS
  subtract $PLAYER~TURNS_ALLOWED $PLAYER~EQUIPROUNDS
end
if (($PLAYER~FUELROUNDS = 0) and (($PLAYER~ORGROUNDS = 0) and ($PLAYER~EQUIPROUNDS = 0)))
  if ($PLAYER~STARTINGLOCATION = "Citadel")
    send "C "
  else
    send "q "
  end
  echo "*Nothing to buy*"
  gosub :CLEARADJACENT
  goto :BUYDOWNEXIT
end
:PLAYER~GETMODE

if ($PLAYER~BUYDOWN_MODE = 1)
  setvar $PLAYER~BUYDOWN_MODE "Speedbuy"
elseif ($PLAYER~BUYDOWN_MODE = 2)
  setvar $PLAYER~BUYDOWN_MODE "Best Price"
elseif ($PLAYER~BUYDOWN_MODE = 3)
  setvar $PLAYER~BUYDOWN_MODE "Worst Price"
end
setvar $PLAYER~FUELROUNDSLEFT $PLAYER~FUELROUNDS
setvar $PLAYER~ORGROUNDSLEFT $PLAYER~ORGROUNDS
setvar $PLAYER~EQUIPROUNDSLEFT $PLAYER~EQUIPROUNDS
setvar $PLAYER~FUEL_CREDS_NEEDED 0
setvar $PLAYER~ORG_CREDS_NEEDED 0
setvar $PLAYER~EQUIP_CREDS_NEEDED 0


if ($PLAYER~FUELROUNDS > 0)
  setvar $PLAYER~FUEL_CREDS_NEEDED $PLAYER~FUELROUNDS
  multiply $PLAYER~FUEL_CREDS_NEEDED $PLAYER~TOTAL_HOLDS
  multiply $PLAYER~FUEL_CREDS_NEEDED 30
  if ($PLAYER~BUYDOWN_MODE = "Worst Price")
    multiply $PLAYER~FUEL_CREDS_NEEDED 3
    divide $PLAYER~FUEL_CREDS_NEEDED 2
  end
end
if ($PLAYER~ORGROUNDS > 0)
  setvar $PLAYER~ORG_CREDS_NEEDED $PLAYER~ORGROUNDS
  multiply $PLAYER~ORG_CREDS_NEEDED $PLAYER~TOTAL_HOLDS
  multiply $PLAYER~ORG_CREDS_NEEDED 60
  if ($PLAYER~BUYDOWN_MODE = "Worst Price")
    multiply $PLAYER~ORG_CREDS_NEEDED 3
    divide $PLAYER~ORG_CREDS_NEEDED 2
  end
end
if ($PLAYER~EQUIPROUNDS > 0)
  setvar $PLAYER~EQUIP_CREDS_NEEDED $PLAYER~EQUIPROUNDS
  multiply $PLAYER~EQUIP_CREDS_NEEDED $PLAYER~TOTAL_HOLDS
  multiply $PLAYER~EQUIP_CREDS_NEEDED 100
  if ($PLAYER~BUYDOWN_MODE = "Worst Price")
    multiply $PLAYER~EQUIP_CREDS_NEEDED 3
    divide $PLAYER~EQUIP_CREDS_NEEDED 2
  end
end
setvar $PLAYER~TOTAL_CREDS_NEEDED 0
add $PLAYER~TOTAL_CREDS_NEEDED $PLAYER~FUEL_CREDS_NEEDED
add $PLAYER~TOTAL_CREDS_NEEDED $PLAYER~ORG_CREDS_NEEDED
add $PLAYER~TOTAL_CREDS_NEEDED $PLAYER~EQUIP_CREDS_NEEDED
setvar $PLAYER~STARTINGCREDITS $PLAYER~CREDITS
if ($PLAYER~TOTAL_CREDS_NEEDED > $PLAYER~CREDITS)
  setvar $PLAYER~CASHONHAND $PLANET~CITADEL_CREDITS
  add $PLAYER~CASHONHAND $PLAYER~CREDITS
  if ($PLAYER~CASHONHAND > $PLAYER~TOTAL_CREDS_NEEDED)
    send "C"
    send "T T "&$PLAYER~CREDITS&"* "
    send "T F "&$PLAYER~TOTAL_CREDS_NEEDED&"* "
    setvar $PLAYER~CREDITS $PLAYER~TOTAL_CREDS_NEEDED
    send "Q"
  else
    if ($PLAYER~STARTINGLOCATION = "Citadel")
      send "C "
    else
      send "q "
    end
    setvar $PLAYER~EXIT_MESSAGE "Not enough cash onhand"
    gosub :CLEARADJACENT
    goto :BUYDOWNEXIT
  end
end
setvar $PLAYER~INIT_CREDITS $PLAYER~CREDITS
:PLAYER~BUYDOWNEQUIP

if ($PLAYER~EQUIPROUNDSLEFT > 0)
  send "Q P T  "
  if ($PLAYER~FUELSELLING > 0)
    send "0* "
  end
  if ($PLAYER~ORGSELLING > 0)
    send "0*"
  end
  gosub :CHOOSEHAGGLE
  send "L "&$PLANET~PLANET&"* t n l 3* "
  subtract $PLAYER~EQUIPROUNDSLEFT 1
  goto :BUYDOWNEQUIP
end
if ($PLAYER~EQUIPROUNDS > 0)
  if ($PLAYER~BUYDOWN_MODE = "Worst Price")
    setvar $PLAYER~OUTPUT $PLAYER~OUTPUT&" - Equipment overhaggled at "&$PLAYER~OVERHAGGLEMULTIPLE&"*"
  end
end
:PLAYER~BUYDOWNORG

if ($PLAYER~ORGROUNDSLEFT > 0)
  send "Q P T  "
  if ($PLAYER~FUELSELLING > 0)
    send "0*"
  end
  gosub :CHOOSEHAGGLE
  send "0* L "&$PLANET~PLANET&"* t n l 2* "
  subtract $PLAYER~ORGROUNDSLEFT 1
  goto :BUYDOWNORG
end
if ($PLAYER~ORGROUNDS > 0)
  if ($PLAYER~BUYDOWN_MODE = "Worst Price")
    setvar $PLAYER~OUTPUT $PLAYER~OUTPUT&" - Organics overhaggled at "&$PLAYER~OVERHAGGLEMULTIPLE&"*"
  end
end
:PLAYER~BUYDOWNFUEL

if ($PLAYER~FUELROUNDSLEFT > 0)
  send "Q P T "
  gosub :CHOOSEHAGGLE
  send "0* 0* L "&$PLANET~PLANET&"* t n l 1* "
  subtract $PLAYER~FUELROUNDSLEFT 1
  goto :BUYDOWNFUEL
end
if ($PLAYER~FUELROUNDS > 0)
  if ($PLAYER~BUYDOWN_MODE = "Worst Price")
    setvar $PLAYER~OUTPUT $PLAYER~OUTPUT&" - Fuel Ore overhaggled at "&$PLAYER~OVERHAGGLEMULTIPLE&"*"
  end
end
:PLAYER~BUYDOWNFINISH

if ($PLAYER~STARTINGLOCATION = "Citadel")
  send "C "
end
gosub :GETINFO
setvar $PLAYER~CREDITS_SPENT $PLAYER~INIT_CREDITS
subtract $PLAYER~CREDITS_SPENT $PLAYER~CREDITS
gosub :CLEARADJACENT
if ($PLAYER~STARTINGLOCATION = "Planet")
  send "L "&$PLANET~PLANET&"* "
end
if ($PLAYER~CREDITS > $PLAYER~STARTINGCREDITS)
  if ($PLAYER~STARTINGLOCATION = "Citadel")
    send "T T "&($PLAYER~CREDITS - $PLAYER~STARTINGCREDITS)&"* "
  end
end
setvar $PLAYER~EXIT_MESSAGE "Normal Exit"
:PLAYER~BUYDOWNEXIT

return
:PLAYER~CHOOSEHAGGLE





if ($PLAYER~BUYDOWN_MODE = "Speedbuy")
  gosub :BUYNOHAGGLE
else
  gosub :BUYHAGGLE
end
return
:PLAYER~BUYHAGGLE



killtrigger BUYFIRSTOFFER

setvar $PLAYER~EMPTY $PLAYER~TOTAL_HOLDS
send "*"
settextlinetrigger BUYFIRSTOFFER :BUYFIRSTOFFER "We'll sell them for"
pause
:PLAYER~BUYFIRSTOFFER

gosub :KILLBUYTRIGGERS
getword CURRENTLINE $PLAYER~OFFER 5
striptext $PLAYER~OFFER ","

gosub :SWATHOFF
if ($PLAYER~SWATHOFF = 0)
  send "L "&$PLANET~PLANET&"* "
  if ($PLAYER~STARTINGLOCATION = "Citadel")
    send "C "
  end
  setvar $PLAYER~EXIT_MESSAGE $PLAYER~SWATHOFFMESSAGE
  goto :BUYDOWNEXIT
end


setvar $PLAYER~COUNTER $PLAYER~OFFER
if ($PLAYER~BUYDOWN_MODE = "Best Price")
  multiply $PLAYER~COUNTER 92
  divide $PLAYER~COUNTER 100
elseif ($PLAYER~BUYDOWN_MODE = "Worst Price")
  multiply $PLAYER~COUNTER $PLAYER~OVERHAGGLEMULTIPLE
  divide $PLAYER~COUNTER 100
end
send $PLAYER~COUNTER&"*"
:PLAYER~BUYOFFERLOOP
settextlinetrigger BUYPRICE :BUYPRICE "We'll sell them for"
settextlinetrigger BUYFINALOFFER :BUYFINALOFFER "Our final offer"
settextlinetrigger BUYNOTINTERESTED :BUYNOTINTERESTED "We're not interested."
settextlinetrigger BUYEXPERIENCE :BUYEXPERIENCE "experience point(s)"
settextlinetrigger BUYEMPTY :BUYEMPTY "empty cargo holds"
settextlinetrigger BUYSCREWUP1 :BUYSCREWUP "Get real ion-brain, make me a real offer."
settextlinetrigger BUYSCREWUP2 :BUYSCREWUP "This is the big leagues Jr.  Make a real offer."
settextlinetrigger BUYSCREWUP3 :BUYSCREWUP "My patience grows short with you."
settextlinetrigger BUYSCREWUP4 :BUYSCREWUP "I have much better things to do than waste my time.  Try again."
settextlinetrigger BUYSCREWUP5 :BUYSCREWUP "HA! HA, ha hahahhah hehehe hhhohhohohohh!  You choke me up!"
settextlinetrigger BUYSCREWUP6 :BUYSCREWUP "Quit playing around, you're wasting my time!"
settextlinetrigger BUYSCREWUP7 :BUYSCREWUP "Make a real offer or get the "
settextlinetrigger BUYSCREWUP8 :BUYSCREWUP "WHAT?!@!? you must be crazy!"
settextlinetrigger BUYSCREWUP9 :BUYSCREWUP "So, you think I'm as stupid as you look? Make a real offer."
settextlinetrigger BUYSCREWUP10 :BUYSCREWUP "What do you take me for, a fool?  Make a real offer!"
pause
pause
:PLAYER~BUYSCREWUP
gosub :KILLBUYTRIGGERS
if ($PLAYER~BUYDOWN_MODE = "Best Price")
  multiply $PLAYER~COUNTER 102
  divide $PLAYER~COUNTER 100
elseif ($PLAYER~BUYDOWN_MODE = "Worst Price")
  subtract $PLAYER~OVERHAGGLEMULTIPLE 1
  setvar $PLAYER~COUNTER $PLAYER~OFFER
  multiply $PLAYER~COUNTER $PLAYER~OVERHAGGLEMULTIPLE
  divide $PLAYER~COUNTER 100
end
send $PLAYER~COUNTER&"*"
goto :BUYOFFERLOOP
:PLAYER~BUYPRICE
gosub :KILLBUYTRIGGERS
setvar $PLAYER~OLD_OFFER $PLAYER~OFFER
setvar $PLAYER~OLD_COUNTER $PLAYER~COUNTER
getword CURRENTLINE $PLAYER~OFFER 5
striptext $PLAYER~OFFER ","
setvar $PLAYER~OFFER_PCT $PLAYER~OFFER
multiply $PLAYER~OFFER_PCT 1000
divide $PLAYER~OFFER_PCT $PLAYER~OLD_OFFER
if ($PLAYER~OFFER_PCT > 990)
  setvar $PLAYER~OFFER_PCT 990
end
multiply $PLAYER~COUNTER 1000
divide $PLAYER~COUNTER $PLAYER~OFFER_PCT
if ($PLAYER~COUNTER <= $PLAYER~OLD_COUNTER)
  add $PLAYER~COUNTER 1
end
send $PLAYER~COUNTER&"*"
goto :BUYOFFERLOOP
:PLAYER~BUYFINALOFFER
gosub :KILLBUYTRIGGERS
setvar $PLAYER~OLD_OFFER $PLAYER~OFFER
setvar $PLAYER~OLD_COUNTER $PLAYER~COUNTER
getword CURRENTLINE $PLAYER~OFFER 5
striptext $PLAYER~OFFER ","
setvar $PLAYER~OFFER_CHANGE $PLAYER~OFFER
subtract $PLAYER~OFFER_CHANGE $PLAYER~OLD_OFFER
subtract $PLAYER~OFFER_CHANGE 1
multiply $PLAYER~OFFER_CHANGE 25
divide $PLAYER~OFFER_CHANGE 10
subtract $PLAYER~COUNTER $PLAYER~OFFER_CHANGE
if ($PLAYER~COUNTER = $PLAYER~OLD_COUNTER)
  add $PLAYER~COUNTER 1
end
add $PLAYER~COUNTER 1
send $PLAYER~COUNTER&"*"
goto :BUYOFFERLOOP
:PLAYER~BUYNOTINTERESTED
gosub :KILLBUYTRIGGERS
send "0* "
send "0* "
goto :BUYHAGGLEFAILED
:PLAYER~BUYEXPERIENCE
gosub :KILLBUYTRIGGERS
getword CURRENTLINE $PLAYER~EXP_BONUS 7
add $PLAYER~EXP $PLAYER~EXP_BONUS
add $PLAYER~JETBONUS $PLAYER~EXP_BONUS
goto :BUYOFFERLOOP
:PLAYER~BUYEMPTY
gosub :KILLBUYTRIGGERS
getword CURRENTLINE $PLAYER~CREDITS 3
striptext $PLAYER~CREDITS ","
setvar $PLAYER~OLDEMPTY $PLAYER~EMPTY
getword CURRENTLINE $PLAYER~EMPTY 6
if ($PLAYER~OLDEMPTY = $PLAYER~EMPTY)
  goto :BUYHAGGLEFAILED
else
  goto :BUYHAGGLESUCCEEDED
end
:PLAYER~BUYHAGGLEFAILED
setvar $PLAYER~BUYHAGGLE 0
return
:PLAYER~BUYHAGGLESUCCEEDED
setvar $PLAYER~BUYHAGGLE 1
return
:PLAYER~BUYNOHAGGLE



if ($PLAYER~SWATHOFF = 0)

  waiton "How many holds of"
  send "*"
  gosub :SWATHOFF
  send "*"
else
  send "**"
end
setvar $PLAYER~CYCLEBUFFERLIMIT 20
add $PLAYER~CYCLEBUFFER 1
if ($PLAYER~CYCLEBUFFER = $PLAYER~CYCLEBUFFERLIMIT)
  setvar $PLAYER~CYCLEBUFFER 1
  send "/"
  waiton " Sect "
end
return
:PLAYER~KILLBUYTRIGGERS


killtrigger BUYPRICE
killtrigger BUYFINALOFFER
killtrigger BUYNOTINTERESTED
killtrigger BUYEXPERIENCE
killtrigger BUYEMPTY
killtrigger BUYSCREWUP1
killtrigger BUYSCREWUP2
killtrigger BUYSCREWUP3
killtrigger BUYSCREWUP4
killtrigger BUYSCREWUP5
killtrigger BUYSCREWUP6
killtrigger BUYSCREWUP7
killtrigger BUYSCREWUP8
killtrigger BUYSCREWUP9
killtrigger BUYSCREWUP10
return
