:SHIP~LOADSHIPINFO


setvar $SHIP~SHIPCOUNTER 1
:SHIP~COUNT_THE_SHIPS
loadvar $SHIP~CAP_FILE
fileexists $SHIP~EXISTS $SHIP~CAP_FILE
if ($SHIP~EXISTS)
  read $SHIP~CAP_FILE $SHIP~SHIPINF $SHIP~SHIPCOUNTER
  if ($SHIP~SHIPINF <> "EOF")
    add $SHIP~SHIPCOUNTER 1
    goto :COUNT_THE_SHIPS
  end
  setarray $SHIP~SHIPLIST $SHIP~SHIPCOUNTER 9
  setvar $SHIP~SHIPCOUNTER 1
  :SHIP~READSHIPLIST
  read $SHIP~CAP_FILE $SHIP~SHIPINF $SHIP~SHIPCOUNTER
  if ($SHIP~SHIPINF <> "EOF")
    gosub :PROCESS_SHIP_LINE
    setvar $SHIP~SHIP[$SHIP~SHIPNAME] $SHIP~SHIELDS&" "&$SHIP~DEFODD
    setvar $SHIP~SHIPLIST[$SHIP~SHIPCOUNTER] $SHIP~SHIPNAME
    setvar $SHIP~SHIPLIST[$SHIP~SHIPCOUNTER][1] $SHIP~SHIELDS
    setvar $SHIP~SHIPLIST[$SHIP~SHIPCOUNTER][2] $SHIP~DEFODD
    setvar $SHIP~SHIPLIST[$SHIP~SHIPCOUNTER][3] $SHIP~OFF_ODDS
    setvar $SHIP~SHIPLIST[$SHIP~SHIPCOUNTER][4] $SHIP~MAX_HOLDS
    setvar $SHIP~SHIPLIST[$SHIP~SHIPCOUNTER][5] $SHIP~MAX_FIGHTERS
    setvar $SHIP~SHIPLIST[$SHIP~SHIPCOUNTER][6] $SHIP~INIT_HOLDS
    setvar $SHIP~SHIPLIST[$SHIP~SHIPCOUNTER][7] $SHIP~TPW
    setvar $SHIP~SHIPLIST[$SHIP~SHIPCOUNTER][8] $SHIP~ISDEFENDER
    setvar $SHIP~SHIPLIST[$SHIP~SHIPCOUNTER][9] $SHIP~SHIP_COST
    add $SHIP~SHIPCOUNTER 1
    goto :READSHIPLIST
  end
  setvar $SHIP~SHIPSTATS TRUE
end
return
:SHIP~PROCESS_SHIP_LINE

getword $SHIP~SHIPINF $SHIP~SHIELDS 1
getlength $SHIP~SHIELDS $SHIP~SHIELDLEN
getword $SHIP~SHIPINF $SHIP~DEFODD 2
getlength $SHIP~DEFODD $SHIP~DEFODDLEN
getword $SHIP~SHIPINF $SHIP~OFF_ODDS 3
getlength $SHIP~OFF_ODDS $SHIP~FILLER1LEN
getword $SHIP~SHIPINF $SHIP~SHIP_COST 4
getlength $SHIP~SHIP_COST $SHIP~FILLER2LEN
getword $SHIP~SHIPINF $SHIP~MAX_HOLDS 5
getlength $SHIP~MAX_HOLDS $SHIP~FILLER3LEN
getword $SHIP~SHIPINF $SHIP~MAX_FIGHTERS 6
getlength $SHIP~MAX_FIGHTERS $SHIP~FILLER4LEN
getword $SHIP~SHIPINF $SHIP~INIT_HOLDS 7
getlength $SHIP~INIT_HOLDS $SHIP~FILLER5LEN
getword $SHIP~SHIPINF $SHIP~TPW 8
getlength $SHIP~TPW $SHIP~FILLER6LEN
getword $SHIP~SHIPINF $SHIP~ISDEFENDER 9
getlength $SHIP~ISDEFENDER $SHIP~FILLER7LEN
setvar $SHIP~STARTLEN ($SHIP~SHIELDLEN + ($SHIP~DEFODDLEN + ($SHIP~FILLER1LEN + ($SHIP~FILLER2LEN + ($SHIP~FILLER3LEN + ($SHIP~FILLER4LEN + ($SHIP~FILLER5LEN + ($SHIP~FILLER6LEN + ($SHIP~FILLER7LEN + 10)))))))))
cuttext $SHIP~SHIPINF $SHIP~SHIPNAME $SHIP~STARTLEN 999
return
