:SWITCHBOARD~SWITCHBOARD





loadvar $BOT~BOTISDEAF
loadvar $BOT~MODE

setvar $SWITCHBOARD~MSG_HEADER_ECHO ANSI_9&"{"&ANSI_14&$SWITCHBOARD~BOT_NAME&ANSI_9&"} "&ANSI_15
setvar $SWITCHBOARD~MSG_HEADER_SS_1 "'["&$BOT~MODE&"] {"&$SWITCHBOARD~BOT_NAME&"} - "
setvar $SWITCHBOARD~MSG_HEADER_SS_2 "'*["&$BOT~MODE&"] {"&$SWITCHBOARD~BOT_NAME&"} - *"
if ($SWITCHBOARD~MESSAGE <> "")

  if ($SWITCHBOARD~SELF_COMMAND > 0)
    setvar $SWITCHBOARD~LENGTH 0
  else
    getlength $SWITCHBOARD~BOT_NAME $SWITCHBOARD~LENGTH
  end
  setvar $SWITCHBOARD~I 1
  setvar $SWITCHBOARD~SPACING ""
  getwordpos " "&$BOT~USER_COMMAND_LINE&" " $SWITCHBOARD~ISBROADCAST " ss "
  getwordpos " "&$BOT~USER_COMMAND_LINE&" " $SWITCHBOARD~ISSILENT " silent "

  if ($SWITCHBOARD~SELF_COMMAND <> 0)

    if (($BOT~COMMAND <> "help") and ($BOT~ONLY_HELP <> TRUE))
      if ($SWITCHBOARD~SELF_COMMAND > 1) or (($SWITCHBOARD~SELF_COMMAND = 1) and (($BOT~SILENT_RUNNING <> TRUE) and ($SWITCHBOARD~ISSILENT <= 0)))
        striptext $SWITCHBOARD~MESSAGE ANSI_1
        striptext $SWITCHBOARD~MESSAGE ANSI_2
        striptext $SWITCHBOARD~MESSAGE ANSI_3
        striptext $SWITCHBOARD~MESSAGE ANSI_4
        striptext $SWITCHBOARD~MESSAGE ANSI_5
        striptext $SWITCHBOARD~MESSAGE ANSI_6
        striptext $SWITCHBOARD~MESSAGE ANSI_7
        striptext $SWITCHBOARD~MESSAGE ANSI_8
        striptext $SWITCHBOARD~MESSAGE ANSI_9
        striptext $SWITCHBOARD~MESSAGE ANSI_10
        striptext $SWITCHBOARD~MESSAGE ANSI_11
        striptext $SWITCHBOARD~MESSAGE ANSI_12
        striptext $SWITCHBOARD~MESSAGE ANSI_13
        striptext $SWITCHBOARD~MESSAGE ANSI_14
        striptext $SWITCHBOARD~MESSAGE ANSI_15
        if ($SWITCHBOARD~HELPLIST <> TRUE)
        end
      end
    end

    while ($SWITCHBOARD~I <= $SWITCHBOARD~LENGTH)
      setvar $SWITCHBOARD~SPACING $SWITCHBOARD~SPACING&" "
      add $SWITCHBOARD~I 1
    end
    setvar $SWITCHBOARD~NEW_MESSAGE ""
    setvar $SWITCHBOARD~MESSAGE_LINE ""
    gosub :FORMAT_RAW_MESSAGE
  else
    gosub :FORMAT_RAW_MESSAGE
  end

  getwordpos " "&$SWITCHBOARD~NEW_MESSAGE&" " $SWITCHBOARD~POS "*"
  getlength $SWITCHBOARD~NEW_MESSAGE $SWITCHBOARD~LENGTH

  if ($SWITCHBOARD~SELF_COMMAND > 1)
    setvar $SWITCHBOARD~SELF_COMMAND FALSE
  end
  if ($SWITCHBOARD~POS < $SWITCHBOARD~LENGTH)
    setvar $SWITCHBOARD~MULTIPLE_LINES TRUE
  else
    setvar $SWITCHBOARD~MULTIPLE_LINES FALSE
  end


  if ($SWITCHBOARD~ISSILENT > 0) or (($BOT~SILENT_RUNNING = TRUE) and ($SWITCHBOARD~SELF_COMMAND = TRUE)) or (((($SWITCHBOARD~SELF_COMMAND = TRUE) and (($BOT~COMMAND = "help") or ($BOT~ONLY_HELP = TRUE)))) and ($SWITCHBOARD~ISBROADCAST <= 0))
    if ($BOT~BOTISDEAF <> TRUE)
      echo "*"&$SWITCHBOARD~MSG_HEADER_ECHO&$SWITCHBOARD~NEW_MESSAGE
      send #145
    else
      setvar $SWITCHBOARD~WINDOW_CONTENT $SWITCHBOARD~NEW_MESSAGE
      replacetext $SWITCHBOARD~WINDOW_CONTENT "*" "[][]"
      savevar $SWITCHBOARD~WINDOW_CONTENT
    end
  elseif ($SWITCHBOARD~MULTIPLE_LINES = FALSE)
    send $SWITCHBOARD~MSG_HEADER_SS_1&$SWITCHBOARD~NEW_MESSAGE
  else
    send $SWITCHBOARD~MSG_HEADER_SS_2&$SWITCHBOARD~NEW_MESSAGE&"*"
  end
  setvar $SWITCHBOARD~MESSAGE ""
end
setvar $SWITCHBOARD~HELPLIST FALSE
return
:SWITCHBOARD~FORMAT_RAW_MESSAGE



getwordpos " "&$SWITCHBOARD~MESSAGE&" " $SWITCHBOARD~POS "*"
getlength $SWITCHBOARD~MESSAGE $SWITCHBOARD~MESSAGE_LENGTH

if ($SWITCHBOARD~POS < $SWITCHBOARD~MESSAGE_LENGTH)
  setvar $SWITCHBOARD~MULTIPLE_LINES TRUE
else
  setvar $SWITCHBOARD~MULTIPLE_LINES FALSE
end


if (($BOT~ONLY_HELP <> TRUE) and ($SWITCHBOARD~MULTIPLE_LINES <> TRUE))
  setvar $SWITCHBOARD~NEXT_LENGTH 60
  setvar $SWITCHBOARD~I 1
  setvar $SWITCHBOARD~LENGTH 1
  while ($SWITCHBOARD~I <= $SWITCHBOARD~MESSAGE_LENGTH)
    cuttext $SWITCHBOARD~MESSAGE $SWITCHBOARD~CHARACTER $SWITCHBOARD~I 1
    if (($SWITCHBOARD~CHARACTER = " ") and ($SWITCHBOARD~LENGTH > $SWITCHBOARD~NEXT_LENGTH))
      cuttext $SWITCHBOARD~MESSAGE $SWITCHBOARD~FIRST_HALF 1 $SWITCHBOARD~I
      cuttext $SWITCHBOARD~MESSAGE $SWITCHBOARD~SECOND_HALF $SWITCHBOARD~I 999999999
      setvar $SWITCHBOARD~SECOND_HALF "*"&$SWITCHBOARD~SECOND_HALF
      replacetext $SWITCHBOARD~SECOND_HALF "* " "*"
      setvar $SWITCHBOARD~MESSAGE $SWITCHBOARD~FIRST_HALF&$SWITCHBOARD~SECOND_HALF
      setvar $SWITCHBOARD~LENGTH 0
    end
    add $SWITCHBOARD~LENGTH 1
    add $SWITCHBOARD~I 1
  end
  replacetext $SWITCHBOARD~SECOND_HALF "***" "**"
end
setvar $SWITCHBOARD~NEW_MESSAGE $SWITCHBOARD~MESSAGE

return
