:GRID~SURROUND
:GRID~STARTSURROUND




send "szh* "
killtrigger SURROUNDSECTOR
settexttrigger SURROUNDSECTOR :CONTINUESURROUNDSECTOR "["&$PLAYER~CURRENT_SECTOR&"]"
pause
:GRID~CONTINUESURROUNDSECTOR
if ($GRID~ALREADY_CHECKED_SHIP <> TRUE)
  gosub :SHIP~GETSHIPSTATS
end
if ($SHIP~SHIP_MAX_ATTACK > $PLAYER~FIGHTERS)
  setvar $SHIP~SHIP_MAX_ATTACK ($PLAYER~FIGHTERS / 2)
end

setvar $GRID~I 1
setvar $GRID~SURROUNDSTRING "c v 0* y* "&$PLAYER~CURRENT_SECTOR&"* q "
setvar $PLAYER~SURROUNDOUTPUT ""
setvar $GRID~YOUROWNCOUNT 0
if ($PLAYER~DROPOFFENSIVE = TRUE)
  setvar $GRID~DEPLOYFIG "o"
elseif ($PLAYER~DROPTOLL = TRUE)
  setvar $GRID~DEPLOYFIG "t"
else
  setvar $GRID~DEPLOYFIG "d"
end
setvar $GRID~TOTALWARPS SECTOR.WARPCOUNT[$PLAYER~CURRENT_SECTOR]
if (SECTOR.WARPS[$PLAYER~CURRENT_SECTOR][$GRID~I] > 0)
  setvar $GRID~ADJ_SEC SECTOR.WARPS[$PLAYER~CURRENT_SECTOR][$GRID~I]
  getdistance $GRID~DISTANCE $GRID~ADJ_SEC $PLAYER~CURRENT_SECTOR
  if ($GRID~DISTANCE <= 0)
    send "^f"&$GRID~ADJ_SEC&"*"&$PLAYER~CURRENT_SECTOR&"*q"
    waiton "ENDINTERROG"
    getdistance $GRID~DISTANCE $GRID~ADJ_SEC $PLAYER~CURRENT_SECTOR
  end
  setvar $GRID~CONTAINSSHIELDEDPLANET FALSE
  setvar $GRID~P 1
  while ($GRID~P <= SECTOR.PLANETCOUNT[$GRID~ADJ_SEC])
    getword SECTOR.PLANETS[$GRID~ADJ_SEC][$GRID~P] $GRID~TEST 1
    if ($GRID~TEST = "<<<<")
      setvar $GRID~CONTAINSSHIELDEDPLANET TRUE
    end
    add $GRID~P 1
  end
  setvar $GRID~TEMPOFFODD $SHIP~SHIP_OFFENSIVE_ODDS
  multiply $GRID~TEMPOFFODD $SHIP~SHIP_MAX_ATTACK
  divide $GRID~TEMPOFFODD 12
  setvar $GRID~FIGOWNER SECTOR.FIGS.OWNER[$GRID~ADJ_SEC]
  setvar $GRID~MINEOWNER SECTOR.MINES.OWNER[$GRID~ADJ_SEC]
  setvar $GRID~LIMPOWNER SECTOR.LIMPETS.OWNER[$GRID~ADJ_SEC]
  getword $GRID~FIGOWNER $GRID~ALIENCHECK 1
  lowercase $GRID~ALIENCHECK

  if (($PLAYER~SURROUNDOVERWRITE = FALSE) and (($GRID~FIGOWNER = "belong to your Corp") or ($GRID~FIGOWNER = "yours")))
    add $GRID~YOUROWNCOUNT 1
    if ($GRID~YOUROWNCOUNT = $GRID~TOTALWARPS)
      setvar $PLAYER~SURROUNDOUTPUT $PLAYER~SURROUNDOUTPUT&"(Surround) All sectors around are friendly fighters.*"
    end
  elseif (SECTOR.FIGS.QUANTITY[$GRID~ADJ_SEC] >= $GRID~TEMPOFFODD)
    setvar $PLAYER~SURROUNDOUTPUT $PLAYER~SURROUNDOUTPUT&"(Surround) Too many fighters in sector "&$GRID~ADJ_SEC&".*"
  elseif (($GRID~ADJ_SEC <= 10) or ($GRID~ADJ_SEC = $MAP~STARDOCK))
    setvar $PLAYER~SURROUNDOUTPUT $PLAYER~SURROUNDOUTPUT&"(Surround) Avoided Fed Space, sector "&$GRID~ADJ_SEC&".*"
  elseif ((SECTOR.PLANETCOUNT[$GRID~ADJ_SEC] > 0) and $PLAYER~SURROUNDAVOIDALLPLANETS)
    setvar $PLAYER~SURROUNDOUTPUT $PLAYER~SURROUNDOUTPUT&"(Surround) Avoided planet in sector "&$GRID~ADJ_SEC&".*"
  elseif (($GRID~CONTAINSSHIELDEDPLANET = TRUE) and ($PLAYER~SURROUNDAVOIDSHIELDEDONLY = TRUE))
    setvar $PLAYER~SURROUNDOUTPUT $PLAYER~SURROUNDOUTPUT&"(Surround) Avoided shielded planet in sector "&$GRID~ADJ_SEC&".*"
  elseif ($GRID~DISTANCE > 1)
    setvar $PLAYER~SURROUNDOUTPUT $PLAYER~SURROUNDOUTPUT&"(Surround) Avoided one way in sector "&$GRID~ADJ_SEC&".*"
  elseif (($PLAYER~SURROUNDPASSIVE = TRUE) and (((SECTOR.ANOMOLY[$GRID~ADJ_SEC] = TRUE) and (($GRID~LIMPOWNER <> "belong to your Corp") and ($GRID~LIMPOWNER <> "yours"))) or ((SECTOR.FIGS.QUANTITY[$GRID~ADJ_SEC] > 0) and ($GRID~ALIENCHECK <> "the")) or ((SECTOR.MINES.QUANTITY[$GRID~ADJ_SEC] > 0) and (($GRID~MINEOWNER <> "belong to your Corp") and ($GRID~MINEOWNER <> "yours")))))
    setvar $PLAYER~SURROUNDOUTPUT $PLAYER~SURROUNDOUTPUT&"(Surround) Avoided non-passive situation in sector "&$GRID~ADJ_SEC&".*"
  else
    setvar $GRID~SURROUNDSTRING $GRID~SURROUNDSTRING&" m z "&$GRID~ADJ_SEC&"* z a "&$SHIP~SHIP_MAX_ATTACK&"* * "
    if (($PLAYER~SURROUNDFIGS > 0) and ($PLAYER~FIGHTERS > $PLAYER~SURROUNDFIGS))
      setvar $GRID~SURROUNDSTRING $GRID~SURROUNDSTRING&"f z"&$PLAYER~SURROUNDFIGS&"*zc"&$GRID~DEPLOYFIG&"*  "
      subtract $PLAYER~FIGHTERS $PLAYER~SURROUNDFIGS
      setvar $GRID~TARGET $GRID~ADJ_SEC
      setsectorparameter $GRID~TARGET "FIGSEC" TRUE
    end
    if (($PLAYER~SURROUNDLIMP > 0) and (($PLAYER~LIMPETS > $PLAYER~SURROUNDLIMP) and ($PLAYER~LIMPETS > 0)))
      setvar $GRID~SURROUNDSTRING $GRID~SURROUNDSTRING&"h2 z"&$PLAYER~SURROUNDLIMP&"*zc* "
      subtract $PLAYER~LIMPETS $PLAYER~SURROUNDLIMP
    end

    if (($PLAYER~SURROUNDMINE > 0) and (($PLAYER~ARMIDS > $PLAYER~SURROUNDMINE) and ($PLAYER~ARMIDS > 0)))
      setvar $GRID~SURROUNDSTRING $GRID~SURROUNDSTRING&"h1 z"&$PLAYER~SURROUNDMINE&"*zc* "
      subtract $PLAYER~ARMIDS $PLAYER~SURROUNDMINE
    end

    setvar $GRID~SURROUNDSTRING $GRID~SURROUNDSTRING&"m z"&$PLAYER~CURRENT_SECTOR&"* "
    setvar $GRID~SURROUNDSTRING $GRID~SURROUNDSTRING&"za z "&$SHIP~SHIP_MAX_ATTACK&"* * "
  end
  add $GRID~I 1
end
if ((($PLAYER~SURROUNDFIGS > 0) and ($PLAYER~FIGHTERS > $PLAYER~SURROUNDFIGS)) and (($PLAYER~CURRENT_SECTOR <> $MAP~STARDOCK) and ($PLAYER~CURRENT_SECTOR > 10)))
  setvar $GRID~SURROUNDSTRING $GRID~SURROUNDSTRING&"f z"&$PLAYER~SURROUNDFIGS&"*zc"&$GRID~DEPLOYFIG&"*  "
  subtract $PLAYER~FIGHTERS $PLAYER~SURROUNDFIGS
  setvar $GRID~TARGET $PLAYER~CURRENT_SECTOR
  setsectorparameter $GRID~TARGET "FIGSEC" TRUE
end
send $GRID~SURROUNDSTRING
return
