:SECTOR~GETSECTORDATA
setvar $SECTOR~ENDLINE "_ENDLINE_"
setvar $SECTOR~STARTLINE "_STARTLINE_"

killalltriggers
if ($PLAYER~STARTINGLOCATION = "Citadel")
  send "s* "
else
  if ($PLAYER~FEDSPACE = TRUE)
    send "*"
  else
    send "** "
  end
end
setvar $SECTOR~SECTORDATA ""
:SECTOR~SECTORSLINE_CIT_KILL
setvar $SECTOR~LINE CURRENTANSILINE
setvar $SECTOR~LINE $SECTOR~STARTLINE&$SECTOR~LINE&$SECTOR~ENDLINE
setvar $SECTOR~SECTORDATA $SECTOR~SECTORDATA&$SECTOR~LINE
getwordpos $SECTOR~LINE $SECTOR~POS "Warps to Sector(s) "
if ($SECTOR~POS > 0)
  goto :GOTSECTORDATA
else
  settextlinetrigger GETLINE :SECTORSLINE_CIT_KILL
end
pause
:SECTOR~GOTSECTORDATA
getwordpos $SECTOR~SECTORDATA $SECTOR~BEACONPOS "[0m[35mBeacon  [1;33m:"
if ($SECTOR~BEACONPOS > 0)
  setvar $SECTOR~CONTAINSBEACON TRUE
else
  setvar $SECTOR~CONTAINSBEACON FALSE
end
setvar $PLAYER~CURRENT_SECTOR CURRENTSECTOR
gosub :GETTRADERS
gosub :GETEMPTYSHIPS
gosub :GETFAKETRADERS
return
