:SHIP~LOADSHIPINFO


setvar $SHIP~SHIPCOUNTER 1
:SHIP~COUNT_THE_SHIPS
loadvar $SHIP~CAP_FILE
fileexists $SHIP~EXISTS $SHIP~CAP_FILE
if ($SHIP~EXISTS)
  read $SHIP~CAP_FILE $SHIP~SHIPINF $SHIP~SHIPCOUNTER
  if ($SHIP~SHIPINF <> "EOF")
    add $SHIP~SHIPCOUNTER 1
    goto :COUNT_THE_SHIPS
  end
  setarray $SHIP~SHIPLIST $SHIP~SHIPCOUNTER 9
  setvar $SHIP~SHIPCOUNTER 1
  :SHIP~READSHIPLIST
  read $SHIP~CAP_FILE $SHIP~SHIPINF $SHIP~SHIPCOUNTER
  if ($SHIP~SHIPINF <> "EOF")
    gosub :PROCESS_SHIP_LINE
    setvar $SHIP~SHIP[$SHIP~SHIPNAME] $SHIP~SHIELDS&" "&$SHIP~DEFODD
    setvar $SHIP~SHIPLIST[$SHIP~SHIPCOUNTER] $SHIP~SHIPNAME
    setvar $SHIP~SHIPLIST[$SHIP~SHIPCOUNTER][1] $SHIP~SHIELDS
    setvar $SHIP~SHIPLIST[$SHIP~SHIPCOUNTER][2] $SHIP~DEFODD
    setvar $SHIP~SHIPLIST[$SHIP~SHIPCOUNTER][3] $SHIP~OFF_ODDS
    setvar $SHIP~SHIPLIST[$SHIP~SHIPCOUNTER][4] $SHIP~MAX_HOLDS
    setvar $SHIP~SHIPLIST[$SHIP~SHIPCOUNTER][5] $SHIP~MAX_FIGHTERS
    setvar $SHIP~SHIPLIST[$SHIP~SHIPCOUNTER][6] $SHIP~INIT_HOLDS
    setvar $SHIP~SHIPLIST[$SHIP~SHIPCOUNTER][7] $SHIP~TPW
    setvar $SHIP~SHIPLIST[$SHIP~SHIPCOUNTER][8] $SHIP~ISDEFENDER
    setvar $SHIP~SHIPLIST[$SHIP~SHIPCOUNTER][9] $SHIP~SHIP_COST
    add $SHIP~SHIPCOUNTER 1
    goto :READSHIPLIST
  end
  setvar $SHIP~SHIPSTATS TRUE
end
return
