:BOT~LOADVARS
loadvar $BOT~MODE
loadvar $BOT~COMMAND
loadvar $SWITCHBOARD~BOT_NAME
setvar $BOT~BOT_NAME $SWITCHBOARD~BOT_NAME
loadvar $PLANET~PLANET_FILE
loadvar $SHIP~CAP_FILE
loadvar $BOT~USER_COMMAND_LINE
loadvar $BOT~PARM1
loadvar $BOT~PARM2
loadvar $BOT~PARM3
loadvar $BOT~PARM4
loadvar $BOT~PARM5
loadvar $BOT~PARM6
loadvar $BOT~PARM7
loadvar $BOT~PARM8
loadvar $BOT~BOT_TURN_LIMIT
loadvar $PLAYER~UNLIMITEDGAME
loadvar $MAP~STARDOCK
loadvar $MAP~RYLOS
loadvar $MAP~ALPHA_CENTAURI
loadvar $MAP~HOME_SECTOR
loadvar $MAP~BACKDOOR
loadvar $BOT~SILENT_RUNNING
loadvar $BOT~BOTISDEAF
loadvar $SWITCHBOARD~SELF_COMMAND
loadvar $PLANET~PLANET
loadvar $BOT~PASSWORD
loadvar $BOT~LETTER
loadvar $GAME~PORT_MAX
loadvar $BOT~FOLDER
loadvar $BOT~MOMBOT_DIRECTORY
loadvar $GAME~PHOTON_DURATION
loadvar $SETTINGS~OVERRIDE



setarray $BOT~HELP 60
setvar $BOT~HELP 60
setvar $BOT~TAB "     "

return
