:COMBAT~FASTATTACK
setvar $COMBAT~TARGETSTRING "a"
setvar $PLAYER~ISFOUND FALSE
setvar $COMBAT~TARGETSHOTGUN "a z z y z"&$SHIP~SHIP_MAX_ATTACK&"* * a z z * y z"&$SHIP~SHIP_MAX_ATTACK&"* * a z z * * y z"&$SHIP~SHIP_MAX_ATTACK&"* * "
:COMBAT~CHECKINGFIGS
if ($PLAYER~FIGHTERS <= 0)
  gosub :PLAYER~QUIKSTATS
  if ($PLAYER~FIGHTERS <= 0)
    echo ANSI_12 "*You have no fighters.*" ANSI_7
    goto :STOPPINGPOINT
  end
end
if ($PLAYER~FEDSPACE <> TRUE)
  getwordpos $SECTOR~SECTORDATA $COMBAT~BEACONPOS "[0m[35mBeacon  [1;33m:"
  if ($COMBAT~BEACONPOS > 0)
    setvar $COMBAT~TARGETSTRING $COMBAT~TARGETSTRING&"*"
  end
end
if (($SECTOR~EMPTYSHIPCOUNT + ($SECTOR~FAKETRADERCOUNT + $SECTOR~REALTRADERCOUNT)) > 0)
  setvar $COMBAT~I 0
  while ($COMBAT~I < ($SECTOR~EMPTYSHIPCOUNT + $SECTOR~FAKETRADERCOUNT))
    setvar $COMBAT~TARGETSTRING $COMBAT~TARGETSTRING&"* "
    add $COMBAT~I 1
  end
  setvar $COMBAT~C 1
  if (($COMBAT~C <= $SECTOR~REALTRADERCOUNT) and ($PLAYER~ISFOUND = FALSE))

    if ($PLAYER~TRADERS[$COMBAT~C][1] = $PLAYER~CORP)
      setvar $COMBAT~TARGETSTRING $COMBAT~TARGETSTRING&"* "
    elseif (($PLAYER~FEDSPACE = TRUE) and ($PLAYER~TRADERS[$COMBAT~C][2] = TRUE))
      setvar $COMBAT~TARGETSTRING $COMBAT~TARGETSTRING&"* "
    else
      setvar $PLAYER~ISFOUND TRUE
      setvar $COMBAT~TARGETSTRING $COMBAT~TARGETSTRING&"zy z"
    end
    add $COMBAT~C 1
  end
else
  echo "*You have no targets.*"

  goto :STOPPINGPOINT
end
if ($PLAYER~ISFOUND = TRUE)
  setvar $COMBAT~ATTACKSTRING ""
  while ($PLAYER~FIGHTERS > 0)
    if ($PLAYER~FIGHTERS < $SHIP~SHIP_MAX_ATTACK)
      if ($PLAYER~SHOTGUN)
        setvar $COMBAT~ATTACKSTRING $COMBAT~ATTACKSTRING&$COMBAT~TARGETSHOTGUN&$COMBAT~REFURBSTRING
      else
        if ($PLAYER~DOUBLETAP)
          setvar $COMBAT~ATTACKSTRING $COMBAT~ATTACKSTRING&$COMBAT~TARGETSTRING&$PLAYER~FIGHTERS&"* * "&$COMBAT~TARGETSTRING&$PLAYER~FIGHTERS&"* * "&$COMBAT~REFURBSTRING
        else
          setvar $COMBAT~ATTACKSTRING $COMBAT~ATTACKSTRING&$COMBAT~TARGETSTRING&$PLAYER~FIGHTERS&"* * "&$COMBAT~REFURBSTRING
        end
      end
      setvar $PLAYER~FIGHTERS 0
    else
      if ($PLAYER~SHOTGUN)
        setvar $COMBAT~ATTACKSTRING $COMBAT~ATTACKSTRING&$COMBAT~TARGETSHOTGUN&$COMBAT~REFURBSTRING
      else
        if ($PLAYER~DOUBLETAP)
          setvar $COMBAT~ATTACKSTRING $COMBAT~ATTACKSTRING&$COMBAT~TARGETSTRING&$SHIP~SHIP_MAX_ATTACK&"* * "&$COMBAT~TARGETSTRING&$SHIP~SHIP_MAX_ATTACK&"* * "&$COMBAT~REFURBSTRING
          setvar $PLAYER~FIGHTERS ($PLAYER~FIGHTERS - $SHIP~SHIP_MAX_ATTACK)
        else
          setvar $COMBAT~ATTACKSTRING $COMBAT~ATTACKSTRING&$COMBAT~TARGETSTRING&$SHIP~SHIP_MAX_ATTACK&"* * "&$COMBAT~REFURBSTRING
        end
      end
      setvar $PLAYER~FIGHTERS ($PLAYER~FIGHTERS - $SHIP~SHIP_MAX_ATTACK)
    end
  end
else
  echo "*You have no valid targets.*"

  goto :STOPPINGPOINT
end
send $COMBAT~ATTACKSTRING&"* "
:COMBAT~STOPPINGPOINT

return
