:PLANETINFO~GETPLANETINFO









setvar $PLANETINFO~CURRENT_SECTOR 0
setvar $PLANETINFO~PLANET 0
setvar $PLANETINFO~PLANET_FUEL 0
setvar $PLANETINFO~PLANET_FUEL_MAX 0
setvar $PLANETINFO~PLANET_ORGANICS 0
setvar $PLANETINFO~PLANET_ORGANICS_MAX 0
setvar $PLANETINFO~PLANET_EQUIPMENT 0
setvar $PLANETINFO~PLANET_EQUIPMENT_MAX 0
setvar $PLANETINFO~PLANET_FIGHTERS 0
setvar $PLANETINFO~PLANET_FIGHTERS_MAX 0
setvar $PLANETINFO~CITADEL 0
setvar $PLANETINFO~CITADEL_CREDITS 0
setvar $PLANETINFO~ATMOSPHERE_CANNON 0
setvar $PLANETINFO~SECTOR_CANNON 0



send "*"
settextlinetrigger PLANETINFO2 :PLANETINFO2 "Planet #"
pause
:PLANETINFO~PLANETINFO2

setvar $PLANETINFO~CITADEL 0
setvar $PLANETINFO~SECTOR_CANNON 0
setvar $PLANETINFO~ATMOSPHERE_CANNON 0
setvar $PLANETINFO~CITADEL_CREDITS 0
getword CURRENTLINE $PLANETINFO~PLANET 2
striptext $PLANETINFO~PLANET "#"
getword CURRENTLINE $PLANETINFO~CURRENT_SECTOR 5
striptext $PLANETINFO~CURRENT_SECTOR ":"
waitfor "2 Build 1   Product    Amount     Amount     Maximum"
:PLANETINFO~GETPLANETSTUFF

settextlinetrigger FUELSTART :FUELSTART "Fuel Ore"
settextlinetrigger ORGSTART :ORGSTART "Organics"
settextlinetrigger EQUIPSTART :EQUIPSTART "Equipment"
settextlinetrigger FIGSTART :FIGSTART "Fighters        N/A"
settextlinetrigger CITADELSTART :CITADELSTART "Planet has a level"
settextlinetrigger CANNON :CANNONSTART ", AtmosLvl="
settexttrigger PLANETINFODONE :PLANETINFODONE "Planet command (?=help)"
pause
:PLANETINFO~FUELSTART

getword CURRENTLINE $PLANETINFO~PLANET_FUEL 6
getword CURRENTLINE $PLANETINFO~PLANET_FUEL_MAX 8
striptext $PLANETINFO~PLANET_FUEL ","
striptext $PLANETINFO~PLANET_FUEL_MAX ","
pause
:PLANETINFO~ORGSTART

getword CURRENTLINE $PLANETINFO~PLANET_ORGANICS 5
getword CURRENTLINE $PLANETINFO~PLANET_ORGANICS_MAX 7
striptext $PLANETINFO~PLANET_ORGANICS ","
striptext $PLANETINFO~PLANET_ORGANICS_MAX ","
pause
:PLANETINFO~EQUIPSTART

getword CURRENTLINE $PLANETINFO~PLANET_EQUIPMENT 5
getword CURRENTLINE $PLANETINFO~PLANET_EQUIPMENT_MAX 7
striptext $PLANETINFO~PLANET_EQUIPMENT ","
striptext $PLANETINFO~PLANET_EQUIPMENT_MAX ","
pause
:PLANETINFO~FIGSTART

getword CURRENTLINE $PLANETINFO~PLANET_FIGHTERS 5
getword CURRENTLINE $PLANETINFO~PLANET_FIGHTERS_MAX 7
striptext $PLANETINFO~PLANET_FIGHTERS ","
striptext $PLANETINFO~PLANET_FIGHTERS_MAX ","
pause
:PLANETINFO~CITADELSTART

getword CURRENTLINE $PLANETINFO~CITADEL 5
getword CURRENTLINE $PLANETINFO~CITADEL_CREDITS 9
striptext $PLANETINFO~CITADEL_CREDITS ","
pause
:PLANETINFO~CANNONSTART

getword CURRENTLINE $PLANETINFO~ATMOSPHERE_CANNON 5
getword CURRENTLINE $PLANETINFO~SECTOR_CANNON 6
striptext $PLANETINFO~SECTOR_CANNON "SectLvl="
striptext $PLANETINFO~SECTOR_CANNON "%"
striptext $PLANETINFO~ATMOSPHERE_CANNON "AtmosLvl="
striptext $PLANETINFO~ATMOSPHERE_CANNON "%"
striptext $PLANETINFO~ATMOSPHERE_CANNON ","
pause
:PLANETINFO~PLANETINFODONE
killtrigger CITADELSTART
killtrigger CANNON

setvar $PLANETINFO~CURRENTBOTPLANET $PLANETINFO~PLANET
savevar $PLANETINFO~CURRENTBOTPLANET
return
