:QUIKSTATS~QUIKSTATS









setvar $QUIKSTATS~CURRENT_PROMPT "Undefined"
setvar $QUIKSTATS~PSYCHIC_PROBE "No"
setvar $QUIKSTATS~PLANET_SCANNER "No"
setvar $QUIKSTATS~SCAN_TYPE "None"
setvar $QUIKSTATS~CURRENT_SECTOR 0
setvar $QUIKSTATS~TURNS 0
setvar $QUIKSTATS~CREDITS 0
setvar $QUIKSTATS~FIGHTERS 0
setvar $QUIKSTATS~SHIELDS 0
setvar $QUIKSTATS~TOTAL_HOLDS 0
setvar $QUIKSTATS~ORE_HOLDS 0
setvar $QUIKSTATS~ORGANIC_HOLDS 0
setvar $QUIKSTATS~EQUIPMENT_HOLDS 0
setvar $QUIKSTATS~COLONIST_HOLDS 0
setvar $QUIKSTATS~PHOTONS 0
setvar $QUIKSTATS~ARMIDS 0
setvar $QUIKSTATS~LIMPETS 0
setvar $QUIKSTATS~GENESIS 0
setvar $QUIKSTATS~TWARP_TYPE 0
setvar $QUIKSTATS~CLOAKS 0
setvar $QUIKSTATS~BEACONS 0
setvar $QUIKSTATS~ATOMIC 0
setvar $QUIKSTATS~CORBO 0
setvar $QUIKSTATS~EPROBES 0
setvar $QUIKSTATS~MINE_DISRUPTORS 0
setvar $QUIKSTATS~ALIGNMENT 0
setvar $QUIKSTATS~EXPERIENCE 0
setvar $QUIKSTATS~CORP 0
setvar $QUIKSTATS~SHIP_NUMBER 0
setvar $QUIKSTATS~TURNS_PER_WARP 0
setvar $QUIKSTATS~COMMAND_PROMPT "Command"
setvar $QUIKSTATS~COMPUTER_PROMPT "Computer"
setvar $QUIKSTATS~CITADEL_PROMPT "Citadel"
setvar $QUIKSTATS~PLANET_PROMPT "Planet"
setvar $QUIKSTATS~CORPORATE_PROMPT "Corporate"
setvar $QUIKSTATS~STARDOCK_PROMPT "<Stardock>"
setvar $QUIKSTATS~HARDWARE_PROMPT "<Hardware"
setvar $QUIKSTATS~SHIPYARD_PROMPT "<Shipyard>"
setvar $QUIKSTATS~TERRA_PROMPT "Terra"


setvar $QUIKSTATS~CURRENT_PROMPT "Undefined"
killtrigger NOPROMPT
killtrigger PROMPT1
killtrigger PROMPT2
killtrigger PROMPT3
killtrigger PROMPT4
killtrigger STATLINETRIG
killtrigger GETLINE2
settextlinetrigger PROMPT :ALLPROMPTS #145&#8
settextlinetrigger STATLINETRIG :STATSTART #179
send #145&"/"
pause
:QUIKSTATS~ALLPROMPTS

getword CURRENTLINE $QUIKSTATS~CURRENT_PROMPT 1
striptext $QUIKSTATS~CURRENT_PROMPT #145
striptext $QUIKSTATS~CURRENT_PROMPT #8






settextlinetrigger PROMPT :ALLPROMPTS #145&#8
pause
:QUIKSTATS~STATSTART

killtrigger PROMPT
killtrigger PROMPT2
killtrigger PROMPT3
killtrigger PROMPT4
killtrigger NOPROMPT
setvar $QUIKSTATS~STATS ""
setvar $QUIKSTATS~WORDY ""
:QUIKSTATS~STATSLINE


killtrigger STATLINETRIG
killtrigger GETLINE2
setvar $QUIKSTATS~LINE2 CURRENTLINE
replacetext $QUIKSTATS~LINE2 #179 " "
striptext $QUIKSTATS~LINE2 ","
setvar $QUIKSTATS~STATS $QUIKSTATS~STATS&$QUIKSTATS~LINE2
getwordpos $QUIKSTATS~LINE2 $QUIKSTATS~POS "Ship"
if ($QUIKSTATS~POS > 0)
  goto :GOTSTATS
else
  settextlinetrigger GETLINE2 :STATSLINE
  pause
end
:QUIKSTATS~GOTSTATS

setvar $QUIKSTATS~STATS $QUIKSTATS~STATS&" @@@"

setvar $QUIKSTATS~CURRENT_WORD 0
if ($QUIKSTATS~WORDY <> "@@@")
  if ($QUIKSTATS~WORDY = "Sect")
    getword $QUIKSTATS~STATS $QUIKSTATS~CURRENT_SECTOR ($QUIKSTATS~CURRENT_WORD + 1)
  elseif ($QUIKSTATS~WORDY = "Turns")
    getword $QUIKSTATS~STATS $QUIKSTATS~TURNS ($QUIKSTATS~CURRENT_WORD + 1)
  elseif ($QUIKSTATS~WORDY = "Creds")
    getword $QUIKSTATS~STATS $QUIKSTATS~CREDITS ($QUIKSTATS~CURRENT_WORD + 1)
  elseif ($QUIKSTATS~WORDY = "Figs")
    getword $QUIKSTATS~STATS $QUIKSTATS~FIGHTERS ($QUIKSTATS~CURRENT_WORD + 1)
  elseif ($QUIKSTATS~WORDY = "Shlds")
    getword $QUIKSTATS~STATS $QUIKSTATS~SHIELDS ($QUIKSTATS~CURRENT_WORD + 1)
  elseif ($QUIKSTATS~WORDY = "Hlds")
    getword $QUIKSTATS~STATS $QUIKSTATS~TOTAL_HOLDS ($QUIKSTATS~CURRENT_WORD + 1)
  elseif ($QUIKSTATS~WORDY = "Ore")
    getword $QUIKSTATS~STATS $QUIKSTATS~ORE_HOLDS ($QUIKSTATS~CURRENT_WORD + 1)
  elseif ($QUIKSTATS~WORDY = "Org")
    getword $QUIKSTATS~STATS $QUIKSTATS~ORGANIC_HOLDS ($QUIKSTATS~CURRENT_WORD + 1)
  elseif ($QUIKSTATS~WORDY = "Equ")
    getword $QUIKSTATS~STATS $QUIKSTATS~EQUIPMENT_HOLDS ($QUIKSTATS~CURRENT_WORD + 1)
  elseif ($QUIKSTATS~WORDY = "Col")
    getword $QUIKSTATS~STATS $QUIKSTATS~COLONIST_HOLDS ($QUIKSTATS~CURRENT_WORD + 1)
  elseif ($QUIKSTATS~WORDY = "Phot")
    getword $QUIKSTATS~STATS $QUIKSTATS~PHOTONS ($QUIKSTATS~CURRENT_WORD + 1)
  elseif ($QUIKSTATS~WORDY = "Armd")
    getword $QUIKSTATS~STATS $QUIKSTATS~ARMIDS ($QUIKSTATS~CURRENT_WORD + 1)
  elseif ($QUIKSTATS~WORDY = "Lmpt")
    getword $QUIKSTATS~STATS $QUIKSTATS~LIMPETS ($QUIKSTATS~CURRENT_WORD + 1)
  elseif ($QUIKSTATS~WORDY = "GTorp")
    getword $QUIKSTATS~STATS $QUIKSTATS~GENESIS ($QUIKSTATS~CURRENT_WORD + 1)
  elseif ($QUIKSTATS~WORDY = "TWarp")
    getword $QUIKSTATS~STATS $QUIKSTATS~TWARP_TYPE ($QUIKSTATS~CURRENT_WORD + 1)
  elseif ($QUIKSTATS~WORDY = "Clks")
    getword $QUIKSTATS~STATS $QUIKSTATS~CLOAKS ($QUIKSTATS~CURRENT_WORD + 1)
  elseif ($QUIKSTATS~WORDY = "Beacns")
    getword $QUIKSTATS~STATS $QUIKSTATS~BEACONS ($QUIKSTATS~CURRENT_WORD + 1)
  elseif ($QUIKSTATS~WORDY = "AtmDt")
    getword $QUIKSTATS~STATS $QUIKSTATS~ATOMIC ($QUIKSTATS~CURRENT_WORD + 1)
  elseif ($QUIKSTATS~WORDY = "Corbo")
    getword $QUIKSTATS~STATS $QUIKSTATS~CORBO ($QUIKSTATS~CURRENT_WORD + 1)
  elseif ($QUIKSTATS~WORDY = "EPrb")
    getword $QUIKSTATS~STATS $QUIKSTATS~EPROBES ($QUIKSTATS~CURRENT_WORD + 1)
  elseif ($QUIKSTATS~WORDY = "MDis")
    getword $QUIKSTATS~STATS $QUIKSTATS~MINE_DISRUPTORS ($QUIKSTATS~CURRENT_WORD + 1)
  elseif ($QUIKSTATS~WORDY = "PsPrb")
    getword $QUIKSTATS~STATS $QUIKSTATS~PSYCHIC_PROBE ($QUIKSTATS~CURRENT_WORD + 1)
  elseif ($QUIKSTATS~WORDY = "PlScn")
    getword $QUIKSTATS~STATS $QUIKSTATS~PLANET_SCANNER ($QUIKSTATS~CURRENT_WORD + 1)
  elseif ($QUIKSTATS~WORDY = "LRS")
    getword $QUIKSTATS~STATS $QUIKSTATS~SCAN_TYPE ($QUIKSTATS~CURRENT_WORD + 1)
  elseif ($QUIKSTATS~WORDY = "Aln")
    getword $QUIKSTATS~STATS $QUIKSTATS~ALIGNMENT ($QUIKSTATS~CURRENT_WORD + 1)
  elseif ($QUIKSTATS~WORDY = "Exp")
    getword $QUIKSTATS~STATS $QUIKSTATS~EXPERIENCE ($QUIKSTATS~CURRENT_WORD + 1)
  elseif ($QUIKSTATS~WORDY = "Corp")
    getword $QUIKSTATS~STATS $QUIKSTATS~CORP ($QUIKSTATS~CURRENT_WORD + 1)
  elseif ($QUIKSTATS~WORDY = "Ship")
    getword $QUIKSTATS~STATS $QUIKSTATS~SHIP_NUMBER ($QUIKSTATS~CURRENT_WORD + 1)
  end
  add $QUIKSTATS~CURRENT_WORD 1
  getword $QUIKSTATS~STATS $QUIKSTATS~WORDY $QUIKSTATS~CURRENT_WORD
end
:QUIKSTATS~DONEQUIKSTATS
killtrigger PROMPT1
killtrigger PROMPT2
killtrigger PROMPT3
killtrigger PROMPT4
killtrigger STATLINETRIG
killtrigger GETLINE2

return
:QUIKSTATS~GETINFO




setvar $QUIKSTATS~PHOTONS 0
setvar $QUIKSTATS~SCAN_TYPE "None"
setvar $QUIKSTATS~TWARP_TYPE 0
setvar $QUIKSTATS~CORPSTRING "[0]"
setvar $QUIKSTATS~IGSTAT 0
send "I"
waitfor "<Info>"
:QUIKSTATS~WAITFORINFO
settextlinetrigger GETTRADERNAME :GETTRADERNAME "Trader Name    :"
settextlinetrigger GETEXPANDALIGN :GETEXPANDALIGN "Rank and Exp"
settextlinetrigger GETCORP :GETCORP "Corp           #"
settextlinetrigger GETSHIPTYPE :GETSHIPTYPE "Ship Info      :"
settextlinetrigger GETTPW :GETTPW "Turns to Warp  :"
settextlinetrigger GETSECT :GETSECT "Current Sector :"
settextlinetrigger GETTURNS :GETTURNS "Turns left"
settextlinetrigger GETHOLDS :GETHOLDS "Total Holds"
settextlinetrigger GETFIGHTERS :GETFIGHTERS "Fighters       :"
settextlinetrigger GETSHIELDS :GETSHIELDS "Shield points  :"
settextlinetrigger GETPHOTONS :GETPHOTONS "Photon Missiles:"
settextlinetrigger GETSCANTYPE :GETSCANTYPE "LongRange Scan :"
settextlinetrigger GETTWARPTYPE1 :GETTWARPTYPE1 "  (Type 1 Jump):"
settextlinetrigger GETTWARPTYPE2 :GETTWARPTYPE2 "  (Type 2 Jump):"
settextlinetrigger GETCREDITS :GETCREDITS "Credits"
settextlinetrigger CHECKIG :CHECKIG "Interdictor ON :"
settexttrigger GETINFODONE :GETINFODONE "Command [TL="
settexttrigger GETINFODONE2 :GETINFODONE "Citadel command"
pause
:QUIKSTATS~GETTRADERNAME
setvar $QUIKSTATS~TRADER_NAME CURRENTLINE
striptext $QUIKSTATS~TRADER_NAME "Trader Name    : "
striptext $QUIKSTATS~TRADER_NAME "3rd Class "
striptext $QUIKSTATS~TRADER_NAME "2nd Class "
striptext $QUIKSTATS~TRADER_NAME "1st Class "
striptext $QUIKSTATS~TRADER_NAME "Nuisance "
striptext $QUIKSTATS~TRADER_NAME "Menace "
striptext $QUIKSTATS~TRADER_NAME "Smuggler Savant "
striptext $QUIKSTATS~TRADER_NAME "Smuggler "
striptext $QUIKSTATS~TRADER_NAME "Robber "
striptext $QUIKSTATS~TRADER_NAME "Private "
striptext $QUIKSTATS~TRADER_NAME "Lance Corporal "
striptext $QUIKSTATS~TRADER_NAME "Corporal "
striptext $QUIKSTATS~TRADER_NAME "Staff Sergeant "
striptext $QUIKSTATS~TRADER_NAME "Gunnery Sergeant "
striptext $QUIKSTATS~TRADER_NAME "1st Sergeant "
striptext $QUIKSTATS~TRADER_NAME "Sergeant Major "
striptext $QUIKSTATS~TRADER_NAME "Sergeant "
striptext $QUIKSTATS~TRADER_NAME "Chief Warrant Officer "
striptext $QUIKSTATS~TRADER_NAME "Warrant Officer "
striptext $QUIKSTATS~TRADER_NAME "Terrorist "
striptext $QUIKSTATS~TRADER_NAME "Infamous Pirate "
striptext $QUIKSTATS~TRADER_NAME "Notorious Pirate "
striptext $QUIKSTATS~TRADER_NAME "Dread Pirate "
striptext $QUIKSTATS~TRADER_NAME "Pirate "
striptext $QUIKSTATS~TRADER_NAME "Galactic Scourge "
striptext $QUIKSTATS~TRADER_NAME "Enemy of the State "
striptext $QUIKSTATS~TRADER_NAME "Enemy of the People "
striptext $QUIKSTATS~TRADER_NAME "Enemy of Humankind "
striptext $QUIKSTATS~TRADER_NAME "Heinous Overlord "
striptext $QUIKSTATS~TRADER_NAME "Prime Evil "
striptext $QUIKSTATS~TRADER_NAME "Ensign "
striptext $QUIKSTATS~TRADER_NAME "Lieutenant J.G. "
striptext $QUIKSTATS~TRADER_NAME "Lieutenant Commander "
striptext $QUIKSTATS~TRADER_NAME "Lieutenant "
striptext $QUIKSTATS~TRADER_NAME "Commander "
striptext $QUIKSTATS~TRADER_NAME "Captain "
striptext $QUIKSTATS~TRADER_NAME "Commodore "
striptext $QUIKSTATS~TRADER_NAME "Rear Admiral "
striptext $QUIKSTATS~TRADER_NAME "Vice Admiral "
striptext $QUIKSTATS~TRADER_NAME "Fleet Admiral "
striptext $QUIKSTATS~TRADER_NAME "Admiral "
striptext $QUIKSTATS~TRADER_NAME "Civilian "
striptext $QUIKSTATS~TRADER_NAME "Annoyance "



pause
:QUIKSTATS~GETEXPANDALIGN
getword CURRENTLINE $QUIKSTATS~EXPERIENCE 5
getword CURRENTLINE $QUIKSTATS~ALIGNMENT 7
striptext $QUIKSTATS~EXPERIENCE ","
striptext $QUIKSTATS~ALIGNMENT ","
striptext $QUIKSTATS~ALIGNMENT "Alignment="
pause
:QUIKSTATS~GETCORP
getword CURRENTLINE $QUIKSTATS~CORP 3
striptext $QUIKSTATS~CORP ","
setvar $QUIKSTATS~CORPSTRING "["&$QUIKSTATS~CORP&"]"
pause
:QUIKSTATS~GETSHIPTYPE
getwordpos CURRENTLINE $QUIKSTATS~SHIPTYPEEND "Ported="
subtract $QUIKSTATS~SHIPTYPEEND 18
cuttext CURRENTLINE $QUIKSTATS~SHIP_TYPE 18 $QUIKSTATS~SHIPTYPEEND
pause
:QUIKSTATS~GETTPW
getword CURRENTLINE $QUIKSTATS~TURNS_PER_WARP 5
pause
:QUIKSTATS~GETSECT
getword CURRENTLINE $QUIKSTATS~CURRENT_SECTOR 4
pause
:QUIKSTATS~GETTURNS
getword CURRENTLINE $QUIKSTATS~TURNS 4
if ($QUIKSTATS~TURNS = "Unlimited")
  setvar $QUIKSTATS~TURNS 65000
  setvar $QUIKSTATS~UNLIMITEDGAME TRUE
end
savevar $QUIKSTATS~UNLIMITEDGAME
pause
:QUIKSTATS~GETHOLDS
setvar $QUIKSTATS~LINE CURRENTLINE
getword $QUIKSTATS~LINE $QUIKSTATS~TOTAL_HOLDS 4
getwordpos $QUIKSTATS~LINE $QUIKSTATS~TEXTPOS "Ore="
if ($QUIKSTATS~TEXTPOS <> 0)
  cuttext CURRENTLINE $QUIKSTATS~TEMP $QUIKSTATS~TEXTPOS 100
  getword $QUIKSTATS~TEMP $QUIKSTATS~ORE_HOLDS 1
  striptext $QUIKSTATS~ORE_HOLDS "Ore="
else
  setvar $QUIKSTATS~ORE_HOLDS 0
end
getwordpos $QUIKSTATS~LINE $QUIKSTATS~TEXTPOS "Organics="
if ($QUIKSTATS~TEXTPOS <> 0)
  cuttext CURRENTLINE $QUIKSTATS~TEMP $QUIKSTATS~TEXTPOS 100
  getword $QUIKSTATS~TEMP $QUIKSTATS~ORGANIC_HOLDS 1
  striptext $QUIKSTATS~ORGANIC_HOLDS "Organics="
else
  setvar $QUIKSTATS~ORGANIC_HOLDS 0
end
getwordpos $QUIKSTATS~LINE $QUIKSTATS~TEXTPOS "Equipment="
if ($QUIKSTATS~TEXTPOS <> 0)
  cuttext CURRENTLINE $QUIKSTATS~TEMP $QUIKSTATS~TEXTPOS 100
  getword $QUIKSTATS~TEMP $QUIKSTATS~EQUIPMENT_HOLDS 1
  striptext $QUIKSTATS~EQUIPMENT_HOLDS "Equipment="
else
  setvar $QUIKSTATS~EQUIPMENT_HOLDS 0
end
getwordpos $QUIKSTATS~LINE $QUIKSTATS~TEXTPOS "Colonists="
if ($QUIKSTATS~TEXTPOS <> 0)
  cuttext CURRENTLINE $QUIKSTATS~TEMP $QUIKSTATS~TEXTPOS 100
  getword $QUIKSTATS~TEMP $QUIKSTATS~COLONIST_HOLDS 1
  striptext $QUIKSTATS~COLONIST_HOLDS "Colonists="
else
  setvar $QUIKSTATS~COLONIST_HOLDS 0
end
getwordpos $QUIKSTATS~LINE $QUIKSTATS~TEXTPOS "Empty="
if ($QUIKSTATS~TEXTPOS <> 0)
  cuttext CURRENTLINE $QUIKSTATS~TEMP $QUIKSTATS~TEXTPOS 100
  getword $QUIKSTATS~TEMP $QUIKSTATS~EMPTY_HOLDS 1
  striptext $QUIKSTATS~EMPTY_HOLDS "Empty="
else
  setvar $QUIKSTATS~EMPTY_HOLDS 0
end
pause
:QUIKSTATS~GETFIGHTERS
getword CURRENTLINE $QUIKSTATS~FIGHTERS 3
striptext $QUIKSTATS~FIGHTERS ","
pause
:QUIKSTATS~GETSHIELDS
getword CURRENTLINE $QUIKSTATS~SHIELDS 4
striptext $QUIKSTATS~SHIELDS ","
pause
:QUIKSTATS~GETPHOTONS
getword CURRENTLINE $QUIKSTATS~PHOTONS 3
pause
:QUIKSTATS~GETSCANTYPE
getword CURRENTLINE $QUIKSTATS~SCAN_TYPE 4
pause
:QUIKSTATS~GETTWARPTYPE1
getword CURRENTLINE $QUIKSTATS~TWARP_1_RANGE 4
setvar $QUIKSTATS~TWARP_TYPE 1
pause
:QUIKSTATS~GETTWARPTYPE2
getword CURRENTLINE $QUIKSTATS~TWARP_2_RANGE 4
setvar $QUIKSTATS~TWARP_TYPE 2
pause
:QUIKSTATS~GETCREDITS
getword CURRENTLINE $QUIKSTATS~CREDITS 3
striptext $QUIKSTATS~CREDITS ","
if ($QUIKSTATS~IGSTAT = 0)
  setvar $QUIKSTATS~IGSTAT "NO IG"
end
pause
:QUIKSTATS~CHECKIG
getword CURRENTLINE $QUIKSTATS~IGSTAT 4
pause
:QUIKSTATS~GETINFODONE

killtrigger GETINFODONE
killtrigger GETINFODONE2
killtrigger GETTRADERNAME
killtrigger GETEXPANDALIGN
killtrigger GETCORP
killtrigger GETSHIPTYPE
killtrigger GETTPW
killtrigger GETSECT
killtrigger GETTURNS
killtrigger GETHOLDS
killtrigger GETFIGHTERS
killtrigger GETSHIELDS
killtrigger GETPHOTONS
killtrigger GETSCANTYPE
killtrigger GETTWARPTYPE1
killtrigger GETTWARPTYPE2
killtrigger GETCREDITS
killtrigger CHECKIG
gosub :VALIDATION~VALIDATION

return
