




setvar $SHIPSTATS~SHIP_OFFENSIVE_ODDS 0
setvar $SHIPSTATS~SHIP_FIGHTERS_MAX 0
setvar $SHIPSTATS~SHIP_MAX_ATTACK 0
setvar $SHIPSTATS~SHIP_MINES_MAX 0
:SHIPSTATS~GETSHIPSTATS


send "c;q"
settextlinetrigger GETSHIPOFFENSE :SHIPOFFENSEODDS "Offensive Odds: "
settextlinetrigger GETSHIPFIGHTERS :SHIPMAXFIGSPERATTACK " TransWarp Drive:   "
settextlinetrigger GETSHIPMINES :SHIPMAXMINES " Mine Max:  "
pause
:SHIPSTATS~SHIPOFFENSEODDS

getwordpos CURRENTANSILINE $SHIPSTATS~POS "[0;31m:[1;36m1"
if ($SHIPSTATS~POS > 0)
  gettext CURRENTANSILINE $SHIPSTATS~SHIP_OFFENSIVE_ODDS "Offensive Odds[1;33m:[36m " "[0;31m:[1;36m1"
  striptext $SHIPSTATS~SHIP_OFFENSIVE_ODDS "."
  striptext $SHIPSTATS~SHIP_OFFENSIVE_ODDS " "
  gettext CURRENTANSILINE $SHIPSTATS~SHIP_FIGHTERS_MAX "Max Fighters[1;33m:[36m" "[0;32m Offensive Odds"
  striptext $SHIPSTATS~SHIP_FIGHTERS_MAX ","
  striptext $SHIPSTATS~SHIP_FIGHTERS_MAX " "
end
pause
:SHIPSTATS~SHIPMAXMINES
gettext CURRENTLINE $SHIPSTATS~SHIP_MINES_MAX "Mine Max:" "Beacon Max:"
striptext $SHIPSTATS~SHIP_MINES_MAX " "
pause
:SHIPSTATS~SHIPMAXFIGSPERATTACK

getwordpos CURRENTANSILINE $SHIPSTATS~POS "[0m[32m Max Figs Per Attack[1;33m:[36m"
if ($SHIPSTATS~POS > 0)
  gettext CURRENTANSILINE $SHIPSTATS~SHIP_MAX_ATTACK "[0m[32m Max Figs Per Attack[1;33m:[36m" "[0;32mTransWarp"
  striptext $SHIPSTATS~SHIP_MAX_ATTACK " "
end
return
